import requests
from bs4 import BeautifulSoup
import time
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from typing.io import TextIO

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"}
opts = Options()
opts.headless = False
driver = webdriver.Chrome(r"/home/pradeep/Music/chromedriver_linux64/chromedriver")
l = 0
mylist = [
    # 'https://www.zoro.com/search?q=panduit%20F78-10-M',
    # 'https://www.zoro.com/search?q=panduit%20F80-10-M',
    # 'https://www.zoro.com/search?q=panduit%20F80-12-M',
    # 'https://www.zoro.com/search?q=panduit%20F82-12-M',
    # 'https://www.zoro.com/search?q=panduit%20F82-15-M',
    # 'https://www.zoro.com/search?q=panduit%20F83-12-D',
    # 'https://www.zoro.com/search?q=panduit%20F83-15-D',
    # 'https://www.zoro.com/search?q=panduit%20F84-12-TL',
    # 'https://www.zoro.com/search?q=panduit%20F84-15-TL',
    # 'https://www.zoro.com/search?q=panduit%20F85-18-C',
    # 'https://www.zoro.com/search?q=panduit%20F87-25-C',
    # 'https://www.zoro.com/search?q=panduit%20FSD72-8-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD73-6-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD73-8-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD74-6-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD74-8-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD75-10-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD75-6-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD75-8-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD75-8-DSL10',
    # 'https://www.zoro.com/search?q=panduit%20FSD76-10-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD76-8-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD77-10-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD77-12-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD77-6-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD77-8-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD77-8-DSL2',
    # 'https://www.zoro.com/search?q=panduit%20FSD78-10-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD78-12-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD78-18-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD78-6-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD78-8-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD78-8-DSL0',
    # 'https://www.zoro.com/search?q=panduit%20FSD79-8-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD80-12-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD80-18-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD80-8-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD80-8-DSL6',
    # 'https://www.zoro.com/search?q=panduit%20FSD81-10-D',
    # 'https://www.zoro.com/search?q=panduit%20FSD81-12-C',
    # 'https://www.zoro.com/search?q=panduit%20FSD81-18-C',
    # 'https://www.zoro.com/search?q=panduit%20FSD82-12-C',
    # 'https://www.zoro.com/search?q=panduit%20FSD82-18-C',
    # 'https://www.zoro.com/search?q=panduit%20FSD83-12-C',
    # 'https://www.zoro.com/search?q=panduit%20FSD83-18-C',
    # 'https://www.zoro.com/search?q=panduit%20FSD84-12-C',
    # 'https://www.zoro.com/search?q=panduit%20FSD84-18-C',
    # 'https://www.zoro.com/search?q=panduit%20FSD86-16-L',
    # 'https://www.zoro.com/search?q=panduit%20FTD75-8-D',
    # 'https://www.zoro.com/search?q=panduit%20FTD76-10-D',
    # 'https://www.zoro.com/search?q=panduit%20FTD76-8-D',
    # 'https://www.zoro.com/search?q=panduit%20FTD77-10-D',
    # 'https://www.zoro.com/search?q=panduit%20FTD77-8-D',
    # 'https://www.zoro.com/search?q=panduit%20FTD78-12-D',
    # 'https://www.zoro.com/search?q=panduit%20FTD78-8-D',
    # 'https://www.zoro.com/search?q=panduit%20FTD80-10-TL',
    # 'https://www.zoro.com/search?q=panduit%20FTD80-13-TL',
    # 'https://www.zoro.com/search?q=panduit%20BS10-D',
    # 'https://www.zoro.com/search?q=panduit%20BS10-L',
    # 'https://www.zoro.com/search?q=panduit%20BS14-C',
    # 'https://www.zoro.com/search?q=panduit%20BS14-M',
    # 'https://www.zoro.com/search?q=panduit%20BS18-C',
    # 'https://www.zoro.com/search?q=panduit%20BSH10-E',
    # 'https://www.zoro.com/search?q=panduit%20BSH14-Q',
    # 'https://www.zoro.com/search?q=panduit%20BSH18-Q',
    # 'https://www.zoro.com/search?q=panduit%20BSN10-D',
    # 'https://www.zoro.com/search?q=panduit%20BSN10-L',
    # 'https://www.zoro.com/search?q=panduit%20BSN14-C',
    # 'https://www.zoro.com/search?q=panduit%20BSN14-M',
    # 'https://www.zoro.com/search?q=panduit%20BSN18-C',
    # 'https://www.zoro.com/search?q=panduit%20BSN18-M',
    # 'https://www.zoro.com/search?q=panduit%20BSV10X-D',
    # 'https://www.zoro.com/search?q=panduit%20BSV10X-Q',
    # 'https://www.zoro.com/search?q=panduit%20BSV14X-L',
    # 'https://www.zoro.com/search?q=panduit%20BSV14X-M',
    # 'https://www.zoro.com/search?q=panduit%20BSV18X-LY',
    # 'https://www.zoro.com/search?q=panduit%20BSV18X-MY',
    # 'https://www.zoro.com/search?q=panduit%20D10-250-D',
    # 'https://www.zoro.com/search?q=panduit%20D10-250-L',
    # 'https://www.zoro.com/search?q=panduit%20D14-250-C',
    # 'https://www.zoro.com/search?q=panduit%20D14-250-M',
    # 'https://www.zoro.com/search?q=panduit%20D-250A-C',
    # 'https://www.zoro.com/search?q=panduit%20DNF10-250FIB-D',
    # 'https://www.zoro.com/search?q=panduit%20DNF10-250FIB-L',
    # 'https://www.zoro.com/search?q=panduit%20DNF10-250FI-D',
    # 'https://www.zoro.com/search?q=panduit%20DNF10-250FI-L',
    # 'https://www.zoro.com/search?q=panduit%20DNF10-250FIMB-D',
    # 'https://www.zoro.com/search?q=panduit%20DNF10-250FIMB-Q',
    # 'https://www.zoro.com/search?q=panduit%20DNF10-250M-L',
    # 'https://www.zoro.com/search?q=panduit%20DNF14-250-C',
    # 'https://www.zoro.com/search?q=panduit%20DNF14-250FIB-C',
    # 'https://www.zoro.com/search?q=panduit%20DNF14-250FIB-E',
    # 'https://www.zoro.com/search?q=panduit%20DNF14-250FIB-M',
    # 'https://www.zoro.com/search?q=panduit%20DNF14-250FI-L',
    # 'https://www.zoro.com/search?q=panduit%20DNF14-250FIM-L',
    # 'https://www.zoro.com/search?q=panduit%20DNF14-250FIM-M',
    # 'https://www.zoro.com/search?q=panduit%20DNF14-250-M',
    # 'https://www.zoro.com/search?q=panduit%20DNF14-250M-C',
    # 'https://www.zoro.com/search?q=panduit%20DNF18-250-C',
    # 'https://www.zoro.com/search?q=panduit%20DNF18-250FIB-C',
    # 'https://www.zoro.com/search?q=panduit%20DNF18-250FIB-M',
    # 'https://www.zoro.com/search?q=panduit%20DNF18-250FIM-L',
    # 'https://www.zoro.com/search?q=panduit%20DNF18-250FIM-M',
    # 'https://www.zoro.com/search?q=panduit%20DNF18-250-M',
    # 'https://www.zoro.com/search?q=panduit%20DNF18-250M-C',
    # 'https://www.zoro.com/search?q=panduit%20DNFR14-250FIB-L',
    # 'https://www.zoro.com/search?q=panduit%20DNFR14-250FIB-M',
    # 'https://www.zoro.com/search?q=panduit%20DNFR18-250FIB-L',
    # 'https://www.zoro.com/search?q=panduit%20DNFR18-250FIB-M',
    # 'https://www.zoro.com/search?q=panduit%20DNH14-250FIB-Q',
    # 'https://www.zoro.com/search?q=panduit%20DNH14-250FIM-Q',
    # 'https://www.zoro.com/search?q=panduit%20DR14-250-C',
    # 'https://www.zoro.com/search?q=panduit%20DR14-250-M',
    # 'https://www.zoro.com/search?q=panduit%20DV10-250-D',
    # 'https://www.zoro.com/search?q=panduit%20DV10-250-L',
    # 'https://www.zoro.com/search?q=panduit%20DV10-250M-L',
    # 'https://www.zoro.com/search?q=panduit%20DV14-250B-C',
    # 'https://www.zoro.com/search?q=panduit%20DV14-250B-M',
    # 'https://www.zoro.com/search?q=panduit%20DV14-250MB-C',
    # 'https://www.zoro.com/search?q=panduit%20DV18-250B-CY',
    # 'https://www.zoro.com/search?q=panduit%20DV18-250B-MY',
    # 'https://www.zoro.com/search?q=panduit%20DV18-250MB-CY',
    # 'https://www.zoro.com/search?q=panduit%20DVF14-250-C',
    # 'https://www.zoro.com/search?q=panduit%20JN418-212-C',
    # 'https://www.zoro.com/search?q=panduit%20JN418-212-D',
    # 'https://www.zoro.com/search?q=panduit%20P10-10F-L',
    # 'https://www.zoro.com/search?q=panduit%20P10-10R-D',
    # 'https://www.zoro.com/search?q=panduit%20P10-10R-L',
    # 'https://www.zoro.com/search?q=panduit%20P10-12R-L',
    # 'https://www.zoro.com/search?q=panduit%20P10-14R-D',
    # 'https://www.zoro.com/search?q=panduit%20P10-14R-L',
    # 'https://www.zoro.com/search?q=panduit%20P10-38R-D',
    # 'https://www.zoro.com/search?q=panduit%20P10-38R-L',
    # 'https://www.zoro.com/search?q=panduit%20P10-56R-L',
    # 'https://www.zoro.com/search?q=panduit%20P10-6R-D',
    # 'https://www.zoro.com/search?q=panduit%20P10-8F-L',
    # 'https://www.zoro.com/search?q=panduit%20P10-8R-D',
    # 'https://www.zoro.com/search?q=panduit%20P10-8R-L',
    # 'https://www.zoro.com/search?q=panduit%20P14-10F-C',
    # 'https://www.zoro.com/search?q=panduit%20P14-10R-C',
    # 'https://www.zoro.com/search?q=panduit%20P14-10R-M',
    # 'https://www.zoro.com/search?q=panduit%20P14-14R-C',
    # 'https://www.zoro.com/search?q=panduit%20P14-14R-M',
    # 'https://www.zoro.com/search?q=panduit%20P14-56R-C',
    # 'https://www.zoro.com/search?q=panduit%20P14-6F-C',
    # 'https://www.zoro.com/search?q=panduit%20P14-6R-C',
    # 'https://www.zoro.com/search?q=panduit%20P14-6R-M',
    # 'https://www.zoro.com/search?q=panduit%20P14-8F-C',
    # 'https://www.zoro.com/search?q=panduit%20P14-8F-M',
    # 'https://www.zoro.com/search?q=panduit%20P14-8R-C',
    # 'https://www.zoro.com/search?q=panduit%20P14-8R-M',
    # 'https://www.zoro.com/search?q=panduit%20P18-10R-C',
    # 'https://www.zoro.com/search?q=panduit%20P18-10R-M',
    # 'https://www.zoro.com/search?q=panduit%20P18-6F-M',
    # 'https://www.zoro.com/search?q=panduit%20P18-6R-C',
    # 'https://www.zoro.com/search?q=panduit%20P18-6R-M',
    # 'https://www.zoro.com/search?q=panduit%20P18-8R-C',
    # 'https://www.zoro.com/search?q=panduit%20P18-8R-M',
    # 'https://www.zoro.com/search?q=panduit%20P18-P47-C',
    # 'https://www.zoro.com/search?q=panduit%20P4-14R-E',
    # 'https://www.zoro.com/search?q=panduit%20P4-14R-T',
    # 'https://www.zoro.com/search?q=panduit%20P4-38R-E',
    # 'https://www.zoro.com/search?q=panduit%20P4-38R-T',
    # 'https://www.zoro.com/search?q=panduit%20P4-56R-E',
    # 'https://www.zoro.com/search?q=panduit%20P4-56R-T',
    # 'https://www.zoro.com/search?q=panduit%20P6-10R-E',
    # 'https://www.zoro.com/search?q=panduit%20P6-10R-T',
    # 'https://www.zoro.com/search?q=panduit%20P6-12R-E',
    # 'https://www.zoro.com/search?q=panduit%20P6-14R-E',
    # 'https://www.zoro.com/search?q=panduit%20P6-14R-T',
    # 'https://www.zoro.com/search?q=panduit%20P6-38R-E',
    # 'https://www.zoro.com/search?q=panduit%20P6-38R-T',
    # 'https://www.zoro.com/search?q=panduit%20P6-56R-E',
    # 'https://www.zoro.com/search?q=panduit%20P6-56R-T',
    # 'https://www.zoro.com/search?q=panduit%20P8-10R-Q',
    # 'https://www.zoro.com/search?q=panduit%20P8-10R-T',
    # 'https://www.zoro.com/search?q=panduit%20P8-14R-Q',
    # 'https://www.zoro.com/search?q=panduit%20P8-14R-T',
    # 'https://www.zoro.com/search?q=panduit%20P8-38R-Q',
    # 'https://www.zoro.com/search?q=panduit%20P8-56R-Q',
    # 'https://www.zoro.com/search?q=panduit%20PH10-10R-E',
    # 'https://www.zoro.com/search?q=panduit%20PH14-6R-Q',
    # 'https://www.zoro.com/search?q=panduit%20PN10-10F-L',
    # 'https://www.zoro.com/search?q=panduit%20PN10-10R-D',
    # 'https://www.zoro.com/search?q=panduit%20PN10-10R-L',
    # 'https://www.zoro.com/search?q=panduit%20PN10-12R-Q',
    # 'https://www.zoro.com/search?q=panduit%20PN10-14F-L',
    # 'https://www.zoro.com/search?q=panduit%20PN10-14R-D',
    # 'https://www.zoro.com/search?q=panduit%20PN10-14R-L',
    # 'https://www.zoro.com/search?q=panduit%20PN10-38R-L',
    # 'https://www.zoro.com/search?q=panduit%20PN10-56R-L',
    # 'https://www.zoro.com/search?q=panduit%20PN10-6F-L',
    # 'https://www.zoro.com/search?q=panduit%20PN10-6R-L',
    # 'https://www.zoro.com/search?q=panduit%20PN10-8F-D',
    # 'https://www.zoro.com/search?q=panduit%20PN10-8F-L',
    # 'https://www.zoro.com/search?q=panduit%20PN10-8R-D',
    # 'https://www.zoro.com/search?q=panduit%20PN10-8R-L',
    # 'https://www.zoro.com/search?q=panduit%20PN14-10F-C',
    # 'https://www.zoro.com/search?q=panduit%20PN14-10R-C',
    # 'https://www.zoro.com/search?q=panduit%20PN14-10R-M',
    # 'https://www.zoro.com/search?q=panduit%20PN14-14F-C',
    # 'https://www.zoro.com/search?q=panduit%20PN14-14R-C',
    # 'https://www.zoro.com/search?q=panduit%20PN14-14R-M',
    # 'https://www.zoro.com/search?q=panduit%20PN14-38R-L',
    # 'https://www.zoro.com/search?q=panduit%20PN14-56R-C',
    # 'https://www.zoro.com/search?q=panduit%20PN14-6F-C',
    # 'https://www.zoro.com/search?q=panduit%20PN14-6R-C',
    # 'https://www.zoro.com/search?q=panduit%20PN14-6R-M',
    # 'https://www.zoro.com/search?q=panduit%20PN14-8F-C',
    # 'https://www.zoro.com/search?q=panduit%20PN14-8R-C',
    # 'https://www.zoro.com/search?q=panduit%20PN14-8R-M',
    # 'https://www.zoro.com/search?q=panduit%20PN18-10F-C',
    # 'https://www.zoro.com/search?q=panduit%20PN18-10R-C',
    # 'https://www.zoro.com/search?q=panduit%20PN18-10R-M',
    # 'https://www.zoro.com/search?q=panduit%20PN18-14R-C',
    # 'https://www.zoro.com/search?q=panduit%20PN18-6F-C',
    # 'https://www.zoro.com/search?q=panduit%20PN18-6F-M',
    # 'https://www.zoro.com/search?q=panduit%20PN18-6R-C',
    # 'https://www.zoro.com/search?q=panduit%20PN18-6R-M',
    # 'https://www.zoro.com/search?q=panduit%20PN18-8F-C',
    # 'https://www.zoro.com/search?q=panduit%20PN18-8R-C',
    # 'https://www.zoro.com/search?q=panduit%20PN18-8R-M',
    # 'https://www.zoro.com/search?q=panduit%20PV10-10F-D',
    # 'https://www.zoro.com/search?q=panduit%20PV10-10F-E',
    # 'https://www.zoro.com/search?q=panduit%20PV10-10F-L',
    # 'https://www.zoro.com/search?q=panduit%20PV10-10R-D',
    # 'https://www.zoro.com/search?q=panduit%20PV10-10R-L',
    # 'https://www.zoro.com/search?q=panduit%20PV10-12R-Q',
    # 'https://www.zoro.com/search?q=panduit%20PV10-14F-L',
    # 'https://www.zoro.com/search?q=panduit%20PV10-14R-D',
    # 'https://www.zoro.com/search?q=panduit%20PV10-14R-L',
    # 'https://www.zoro.com/search?q=panduit%20PV10-38R-D',
    # 'https://www.zoro.com/search?q=panduit%20PV10-38R-L',
    # 'https://www.zoro.com/search?q=panduit%20PV10-56R-D',
    # 'https://www.zoro.com/search?q=panduit%20PV10-56R-L',
    # 'https://www.zoro.com/search?q=panduit%20PV10-6F-L',
    # 'https://www.zoro.com/search?q=panduit%20PV10-6R-D',
    # 'https://www.zoro.com/search?q=panduit%20PV10-6R-L',
    # 'https://www.zoro.com/search?q=panduit%20PV10-8F-D',
    # 'https://www.zoro.com/search?q=panduit%20PV10-8F-L',
    # 'https://www.zoro.com/search?q=panduit%20PV10-8R-D',
    # 'https://www.zoro.com/search?q=panduit%20PV10-8R-L',
    # 'https://www.zoro.com/search?q=panduit%20PV10-P55-DY',
    # 'https://www.zoro.com/search?q=panduit%20PV14-10F-C',
    # 'https://www.zoro.com/search?q=panduit%20PV14-10F-M',
    # 'https://www.zoro.com/search?q=panduit%20PV14-10R-C',
    # 'https://www.zoro.com/search?q=panduit%20PV14-10R-M',
    # 'https://www.zoro.com/search?q=panduit%20PV14-12R-L',
    # 'https://www.zoro.com/search?q=panduit%20PV14-14F-C',
    # 'https://www.zoro.com/search?q=panduit%20PV14-14R-C',
    # # 'https://www.zoro.com/search?q=panduit%20PV14-14R-M',
    # 'https://www.zoro.com/search?q=panduit%20PV14-38R-L',
    # 'https://www.zoro.com/search?q=panduit%20PV14-38R-M',
    # 'https://www.zoro.com/search?q=panduit%20PV14-56R-C',
    # 'https://www.zoro.com/search?q=panduit%20PV14-56R-M',
    # 'https://www.zoro.com/search?q=panduit%20PV14-6F-C',
    # 'https://www.zoro.com/search?q=panduit%20PV14-6F-M',
    # 'https://www.zoro.com/search?q=panduit%20PV14-6R-C',
    # 'https://www.zoro.com/search?q=panduit%20PV14-6R-M',
    # 'https://www.zoro.com/search?q=panduit%20PV14-8F-C',
    # 'https://www.zoro.com/search?q=panduit%20PV14-8F-M',
    # 'https://www.zoro.com/search?q=panduit%20PV14-8R-C',
    # 'https://www.zoro.com/search?q=panduit%20PV14-8R-M',
    # 'https://www.zoro.com/search?q=panduit%20PV14-P47-C',
    # 'https://www.zoro.com/search?q=panduit%20PV14-P47-M',
    # 'https://www.zoro.com/search?q=panduit%20PV18-10F-CY',
    # 'https://www.zoro.com/search?q=panduit%20PV18-10R-CY',
    'https://www.zoro.com/search?q=panduit%20PV18-10R-MY',
    'https://www.zoro.com/search?q=panduit%20PV18-14R-CY',
    'https://www.zoro.com/search?q=panduit%20PV18-14R-MY',
    'https://www.zoro.com/search?q=panduit%20PV18-6F-CY',
    'https://www.zoro.com/search?q=panduit%20PV18-6F-MY',
    'https://www.zoro.com/search?q=panduit%20PV18-6R-CY',
    'https://www.zoro.com/search?q=panduit%20PV18-6R-MY',
    'https://www.zoro.com/search?q=panduit%20PV18-8F-CY',
    'https://www.zoro.com/search?q=panduit%20PV18-8F-MY',
    'https://www.zoro.com/search?q=panduit%20PV18-8R-CY',
    'https://www.zoro.com/search?q=panduit%20PV18-8R-MY',
    'https://www.zoro.com/search?q=panduit%20PV18-P47-CY',
    'https://www.zoro.com/search?q=panduit%20PV6-10R-T',
    'https://www.zoro.com/search?q=panduit%20PV6-10R-X',
    'https://www.zoro.com/search?q=panduit%20PV6-14R-T',
    'https://www.zoro.com/search?q=panduit%20PV6-14R-X',
    'https://www.zoro.com/search?q=panduit%20PV8-10R-QY',
    'https://www.zoro.com/search?q=panduit%20PV8-10R-TY',
    'https://www.zoro.com/search?q=panduit%20PV8-12R-XY',
    'https://www.zoro.com/search?q=panduit%20PV8-14R-QY',
    'https://www.zoro.com/search?q=panduit%20PV8-14R-TY',
    'https://www.zoro.com/search?q=panduit%20PV8-38R-QY',
    'https://www.zoro.com/search?q=panduit%20PV8-38R-TY',
    'https://www.zoro.com/search?q=panduit%20PV8-56R-QY',
    'https://www.zoro.com/search?q=panduit%20PV8-56R-TY',
    'https://www.zoro.com/search?q=panduit%20KP-FSD2',
    'https://www.zoro.com/search?q=panduit%20KP-1075Y',
    'https://www.zoro.com/search?q=panduit%20KP-FSD1',
    'https://www.zoro.com/search?q=panduit%20KP-FSD3',
    'https://www.zoro.com/search?q=panduit%20KP-1165Y',
    'https://www.zoro.com/search?q=panduit%20GTS-E',
    'https://www.zoro.com/search?q=panduit%20K1-PNKIT',
    'https://www.zoro.com/search?q=panduit%20GTH-E',


]


for url in mylist:
    try:
        l = l + 1
        r = requests.get(url)
        soup = BeautifulSoup(r.content, "html.parser")
        driver.get(url)
        driver.get(driver.current_url)
        # time.sleep(3)
        get_url = driver.current_url
        print("current = ", get_url)
        print("Products Urls", l, url)
        all_data = []
        all = driver.find_element(By.XPATH, "//ul[@class='product-identifiers pl-0 pb-2 product-specifications__identifiers my-4 pl-4']")
        data = all.find_elements(By.TAG_NAME, "li")
        for da in data:
            all_data.append(da.text)
        try:
            zoro = all_data[0]
        except:
            zoro = "Not Found"
            print("Not Found")
        try:
            mfr = all_data[1]
        except:
            mfr = "Not Found"
            print("Not Found")
        try:
            upc = all_data[2]
        except:
            upc = "Not Found"
            print("Not Found")
        print("zoro = ", zoro)
        print("mfr = ", mfr)
        print("upc = ", upc)
        save_details: TextIO = open("zoro2.xlsx", "a+", encoding="utf-8")
        save_details.write("\n" + url + "\t" + get_url + "\t" + zoro + "\t" + mfr + "\t" + upc)
        save_details.close()
        print("\n ***** Record stored into upc  files. *****")

    except:
        save_details: TextIO = open("remaining_urls2.xlsx", "a+", encoding="utf-8")
        save_details.write("\n" + url)
        save_details.close()
        print("\n ***** Record stored into upc  files. *****")
        print("Not Found")
