import time

import requests
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"}
opts = Options()
opts.headless = False
driver = webdriver.Chrome(r"/home/pradeep/Music/chromedriver_linux64/chromedriver")
driver.maximize_window()
L = 0
Result = [
    # 'https://www.watts.com/products/drainage-solutions',
    # 'https://www.watts.com/products/drainage-solutions/fixture-carriers',
    # 'https://www.watts.com/products/drainage-solutions/floor-drains-channels-trench',
    # 'https://www.watts.com/products/drainage-solutions/floor-drains-channels-trench/cleanouts',
    # 'https://www.watts.com/products/drainage-solutions/floor-drains-channels-trench/floor-area-drains',
    # 'https://www.watts.com/products/drainage-solutions/floor-drains-channels-trench/sanitary-floor-sinks',
    # 'https://www.watts.com/products/drainage-solutions/floor-drains-channels-trench/dead-level-trench-drains',
    # 'https://www.watts.com/products/drainage-solutions/interceptors',
    # 'https://www.watts.com/products/drainage-solutions/roof-drains',
    # 'https://www.watts.com/products/drainage-solutions/roof-drains/balcony-drains',
    # 'https://www.watts.com/products/drainage-solutions/roof-drains/green-roof-drains',
    # 'https://www.watts.com/products/drainage-solutions/roof-drains/roof-drain-accessories',
    # 'https://www.watts.com/products/drainage-solutions/light-commercial',
    # 'https://www.watts.com/products/drainage-solutions/parking-deck-drains',
    # 'https://www.watts.com/products/drainage-solutions/chemical-waste-pipes-and-fittings',
    # 'https://www.watts.com/products/drainage-solutions/chemical-waste-pipes-and-fittings/chemical-waste-tools-accessories',
    # 'https://www.watts.com/products/drainage-solutions/chemical-waste-pipes-and-fittings/chemical-waste-fittings',
    # 'https://www.watts.com/products/drainage-solutions/chemical-waste-pipes-and-fittings/chemical-waste-fittings/adapters-for-chemical-waste',
    # 'https://www.watts.com/products/drainage-solutions/chemical-waste-pipes-and-fittings/chemical-waste-fittings/couplings-for-chemical-waste',
    # 'https://www.watts.com/products/drainage-solutions/chemical-waste-pipes-and-fittings/chemical-waste-fittings/elbows-for-chemical-waste',
    # 'https://www.watts.com/products/drainage-solutions/chemical-waste-pipes-and-fittings/chemical-waste-fittings/plugs-caps-and-bushings-for-chemical-waste',
    # 'https://www.watts.com/products/drainage-solutions/chemical-waste-pipes-and-fittings/chemical-waste-fittings/tees-y-wyes-for-chemical-waste',
    # 'https://www.watts.com/products/drainage-solutions/chemical-waste-pipes-and-fittings/chemical-waste-fittings/traps-for-chemical-waste',
    # 'https://www.watts.com/products/drainage-solutions/chemical-waste-pipes-and-fittings/chemical-waste-floor-drains-cleanouts',
    # 'https://www.watts.com/products/drainage-solutions/chemical-waste-pipes-and-fittings/chemical-waste-piping',
    # 'https://www.watts.com/products/drainage-solutions/drainage-specialties',
    # 'https://www.watts.com/products/drainage-solutions/drainage-specialties/backwater-valves',
    # 'https://www.watts.com/products/drainage-solutions/drainage-specialties/pipe-sleeves',
    # 'https://www.watts.com/products/drainage-solutions/drainage-specialties/shockhammer-arrestors',
    # 'https://www.watts.com/products/drainage-solutions/drainage-specialties/trap-primersadaptors',
    # 'https://www.watts.com/products/drainage-solutions/drainage-tanks-and-monitoring',
    # 'https://www.watts.com/products/drainage-solutions/drainage-tanks-and-monitoring/neutralization-tanks',
    # 'https://www.watts.com/products/drainage-solutions/drainage-tanks-and-monitoring/system-monitoring',
    # 'https://www.watts.com/products/hvac-hot-water-solutions',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/controls',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/controls/boiler-mixing-controls',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/controls/control-accessories',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/controls/heat-pump',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/controls/multi-staging',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/controls/setpoint',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/controls/snow-melting-controls',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/controls/solar',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/controls/thermostats',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/controls/zone-controls',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/floor-heating',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/floor-heating/fittings-for-floor-heating',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/floor-heating/floor-heating-accessories',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/floor-heating/hydronic-controls',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/floor-heating/manifolds-for-floor-heating',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/floor-heating/mechanical-panels',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/floor-heating/tubing-for-floor-heating',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/control-valves',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/actuators',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/air-separators',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/solar-thermal',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/air-vents',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/balancing-valves',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/boiler-drains',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/boiler-feed-water-pressure-regulators',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/boiler-fill-fittings',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/expansion-tanks',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/flow-check-valves',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/flow-control-valves',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/flow-switches',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/heating-valves',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/hydronic-packages',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/isolation-pump-flanges',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/low-water-cut-offs',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/oil-tank-valve',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/process-boiler-water-feeders',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/purge-and-balancing-valves',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/service-check-valves',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/steam-air-vents',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/heating-valves-accessories/steam-traps',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/snow-melting',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/snow-melting/fittings-for-snow-melting',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/snow-melting/manifolds-for-snow-melting',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/snow-melting/mechanical-panels',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/snow-melting/snow-melting-accessories',
    # 'https://www.watts.com/products/hvac-hot-water-solutions/snow-melting/tubing-for-snow-melting',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/leak-detection',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/mixing-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/mixing-valves/digital-mixing-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/mixing-valves/emergency-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/mixing-valves/industrial-mixing-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/mixing-valves/lavatory-mixing-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/mixing-valves/master-mixing-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/mixing-valves/mixing-valve-accessories',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/mixing-valves/mixing-valve-stations',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/mixing-valves/shower-mixing-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/mixing-valves/shower-panel-mixing-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/mixing-valves/supply-fixtures',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/pex-plumbing-radiant-heating-systems',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/pex-plumbing-radiant-heating-systems/fittings-for-pex-plumbing-radiant-heating-systems',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/pex-plumbing-radiant-heating-systems/hydronic-controls',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/pex-plumbing-radiant-heating-systems/manifolds-for-pex-plumbing-radiant-heating-systems',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/pex-plumbing-radiant-heating-systems/mechanical-panels',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/pex-plumbing-radiant-heating-systems/pex-plumbing-radiant-heating-system-accessories',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/pex-plumbing-radiant-heating-systems/tools-for-pex-plumbing-radiant-heating-systems',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/pex-plumbing-radiant-heating-systems/tubing-for-pex-plumbing-and-radiant-heating-systems',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/pex-plumbing-radiant-heating-systems/valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/plumbing-specialties',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/plumbing-specialties/access-panels',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/plumbing-specialties/anti-sweat-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/plumbing-specialties/line-blinds',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/plumbing-specialties/suction-diffusers',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/plumbing-specialties/trap-primers',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/plumbing-specialties/water-hammer-arrestors',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/repair-kits',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/pressure-reducing-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/pressure-reducing-valves/pressure-reducing-valve-kits',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/pressure-reducing-valves/steam-pressure-reducing-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/pressure-reducing-valves/water-pressure-reducing-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/relief-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/relief-valves/asme-safety-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/relief-valves/by-pass-control-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/relief-valves/expansion-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/relief-valves/pressure-only-relief-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/relief-valves/relief-valve-accessories',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/relief-valves/temperature-and-pressure-relief-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/relief-valves/vacuum-relief-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/risers',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/shutoff-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/shutoff-valves/isolation-pump-flanges',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/shutoff-valves/ball-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/shutoff-valves/butterfly-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/shutoff-valves/gate-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/shutoff-valves/commercial-hydrants',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/shutoff-valves/stop-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/shutoff-valves/tankless-water-heater-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/shutoff-valves/residential-hydrants',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/shutoff-valves/washing-machine-shutoffs',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/shutoff-valves/water-meter-angle-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/shutoff-valves/water-supply-control-box',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/strainers',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/strainers/basket-strainers',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/strainers/duplex-strainers',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/strainers/in-line-strainers',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/strainers/tee-strainers',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/strainers/temporary-strainers',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/strainers/turbine-meter-strainers',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/strainers/y-wye-strainers',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/water-heater-accessories',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/water-heater-accessories/drain-tubes',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/water-heater-accessories/expansion-tanks',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/water-heater-accessories/hot-water-recirculating-systems',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/water-heater-accessories/shutoff-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/commercial-markets',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/commercial-markets/altitude-control',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/commercial-markets/basic-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/commercial-markets/check-control',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/commercial-markets/controls-and-accessories',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/commercial-markets/float-control',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/commercial-markets/pre-engineered-valve-stations',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/commercial-markets/pressure-reduction-control',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/commercial-markets/pressure-relief-sustaining-or-backpressure-control',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/commercial-markets/pump-control',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/commercial-markets/rate-of-flow-control',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/commercial-markets/solenoid-control',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/fire-protection',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/waterworks',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/waterworks/pressure-relief-sustaining-or-backpressure-control',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/waterworks/controls-and-accessories',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/waterworks/pump-control',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/waterworks/basic-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/waterworks/rate-of-flow-control',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/waterworks/altitude-control',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/waterworks/pressure-reduction-control',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/waterworks/check-control',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/waterworks/float-control',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/automatic-control-valves/waterworks/solenoid-control',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/backflow-preventers',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/backflow-preventers/backflow-preventer-accessories',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/backflow-preventers/ames-deringer',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/backflow-preventers/double-check-detector-assemblies',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/backflow-preventers/double-check-valve-assemblies',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/backflow-preventers/dual-checksdual-checks-with-atmospheric-vent',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/backflow-preventers/enclosures-for-backflow-preventers',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/backflow-preventers/reduced-pressure-detector-assemblies',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/backflow-preventers/reduced-pressure-zone-assemblies',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/backflow-preventers/test-kits-for-backflow-preventers',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/backflow-preventers/vacuum-breakers',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/check-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/check-valves/control-chek-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/check-valves/backwater-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/check-valves/chexter-check-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/check-valves/silent-check-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/check-valves/sure-check-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/connections',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/connections/triton-pipe-fusion',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/connections/dielectric-unions',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/connections/aqualock-push-to-connect-fittings',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/connections/aqualock-push-to-connect-fittings/aqualock-hoses',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/connections/aqualock-push-to-connect-fittings/aqualock-mini-fittings',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/connections/aqualock-push-to-connect-fittings/aqualock-plastic-fittings',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/connections/aqualock-push-to-connect-fittings/aqualock-brass-fittings',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/float-valves-agricultural-solutions',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/float-valves-agricultural-solutions/accessories-for-agriculture',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/float-valves-agricultural-solutions/check-valve',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/float-valves-agricultural-solutions/couplings',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/float-valves-agricultural-solutions/fittings-for-agriculture',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/float-valves-agricultural-solutions/float-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/float-valves-agricultural-solutions/foot-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/float-valves-agricultural-solutions/hose-nozzlestails',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/float-valves-agricultural-solutions/pipe-unions',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/float-valves-agricultural-solutions/tank-level-indicators',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/gas-water-connection-solutions',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/gas-water-connection-solutions/gas-accessories',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/gas-water-connection-solutions/gas-connector-kits',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/gas-water-connection-solutions/gas-connectors',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/gas-water-connection-solutions/gas-fittings-and-adapters',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/gas-water-connection-solutions/gas-pressure-regulators',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/gas-water-connection-solutions/gas-shutoff-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/gas-water-connection-solutions/steam-water-connectors',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/gauges',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/gauges/pressure-gauges',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/gauges/test-plugs',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/gauges/thermometers',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/high-purity-piping-and-laboratory-accessories',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/high-purity-piping-and-laboratory-accessories/fittings-for-high-purity-piping',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/high-purity-piping-and-laboratory-accessories/high-purity-piping',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/high-purity-piping-and-laboratory-accessories/laboratory-faucets',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/high-purity-piping-and-laboratory-accessories/laboratory-sinks',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating/air-separators',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating/air-vents',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating/balancing-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating/boiler-drains',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating/boiler-feed-water-pressure-regulators',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating/boiler-fill-fittings',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating/expansion-tanks',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating/flow-check-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating/flow-control-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating/flow-switches',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating/heating-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating/hydronic-packages',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating/isolation-pump-flanges',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating/low-water-cut-offs',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating/oil-tank-valve',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating/process-boiler-water-feeders',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating/purge-and-balancing-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating/service-check-valves',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating/steam-air-vents',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating/steam-traps',
    # 'https://www.watts.com/products/plumbing-flow-control-solutions/hydronic-steam-heating/tankless-water-heater-valves',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/conditioning-solutions',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/conditioning-solutions/water-softeners',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/disinfection-solutions',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/filtration-solutions',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/filtration-solutions/backwashing-systems',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/filtration-solutions/drinking-water-systems',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/filtration-solutions/filter-housing-systems',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/filtration-solutions/icerefrigerator-filtration-systems',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/instrumentation-solutions',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/instrumentation-solutions/ballast-water-market',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/instrumentation-solutions/ballast-water-market/total-residual-oxidant-and-chlorine-monitors',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/instrumentation-solutions/ballast-water-market/reagents-and-dispensers',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/instrumentation-solutions/ballast-water-market/online-uv-analyzers',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/instrumentation-solutions/instrumentation-parts-accessories',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/instrumentation-solutions/municipal-market',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/instrumentation-solutions/municipal-market/online-chlorine-monitors',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/instrumentation-solutions/municipal-market/online-uv-analyzers',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/instrumentation-solutions/municipal-market/photometers',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/instrumentation-solutions/municipal-market/reagents-and-dispensers',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/instrumentation-solutions/municipal-market/test-strips',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/instrumentation-solutions/municipal-market/turbidity-and-standards',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/oneflow-scale-prevention-solutions',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/rainwater-harvesting',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/rainwater-harvesting/rainwater-harvesting-systems',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/water-quality-parts-accessories',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/water-quality-parts-accessories/brackets',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/water-quality-parts-accessories/brine-tanks',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/water-quality-parts-accessories/faucets',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/water-quality-parts-accessories/filter-cartridges',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/water-quality-parts-accessories/filter-housings',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/water-quality-parts-accessories/fittings-for-water-quality',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/water-quality-parts-accessories/fittings-for-water-quality/aqualock-plastic-fittings',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/water-quality-parts-accessories/fittings-for-water-quality/aqualock-mini-fittings',
    # 'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/water-quality-parts-accessories/flow-restrictors',
    'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/water-quality-parts-accessories/kits-for-water-quality',
    'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/water-quality-parts-accessories/media',
    'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/water-quality-parts-accessories/o-rings',
    'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/water-quality-parts-accessories/pumps',
    'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/water-quality-parts-accessories/ro-membranes',
    'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/water-quality-parts-accessories/tanks',
    'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/water-quality-parts-accessories/test-kits-for-water-quality',
    'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/water-quality-parts-accessories/valves',
    'https://www.watts.com/products/water-quality-rainwater-harvesting-solutions/water-quality-parts-accessories/wrenches',

]
for url in Result:
    L = L + 1
    r = requests.get(url, headers=headers)
    # print(soup.prettify())
    driver.get(url)
    time.sleep(5)
    print("Products Urls", L,  url)
    try:
        clk = driver.find_element(By.ID, "SelectResultCount").find_elements(By.TAG_NAME, 'option')
        for s in clk:
            # print(s.text)
            if "50" in s.text:
                s.click()
                time.sleep(5)
            else:
                pass

        l = driver.find_element(By.XPATH, "//div[@class='js-pagination-showing-results__container pagination-showing-results__container']")
        c = l.text.replace(',', '').split()[-2]
        print("count = ", c)
        length = round(int(c) / 50)
        # print(length)
        links = driver.find_element(By.XPATH, "//div[@class='js-results-target results-target']").find_elements(By.TAG_NAME, 'a')
        print("Length", len(links))
        for x in links:
            url_links = (x.get_attribute('href'))
            data_urls = ("'" + url_links + "',")
            print(data_urls)
            save_details: url_links = open("watts_urls.xlsx", "a+", encoding="utf-8")
            save_details.write("\n" + data_urls)
            save_details.close()
        print("\n ***** Record stored into urls  files. *****")

        for i in range(1, length):
            driver.find_element(By.XPATH, "//a[normalize-space()='>']").click()
            time.sleep(5)
            print(i)
            links = driver.find_element(By.XPATH, "//div[@class='js-results-target results-target']").find_elements(By.TAG_NAME, 'a')
            print("Length", len(links))
            for x in links:
                url_links = (x.get_attribute('href'))
                data_urls = ("'" + url_links + "',")
                print(data_urls)
                save_details: url_links = open("watts_urls.xlsx", "a+", encoding="utf-8")
                save_details.write("\n" + data_urls)
                save_details.close()
            print("\n ***** Record stored into urls  files. *****")
    except:
        print("Not Found click")

