import time

from selenium import webdriver

from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.maximize_window()
# Step One

"""
url = 'https://www.bodine-electric.com/products/'

driver.get(url)
time.sleep(1)
for u in driver.find_elements(By.XPATH, "//main[@class='mainContentWrapper']//div[@class='container']//div//div//div//ul//li//a"):
    print(u.get_attribute('href'))
 """

# step Two

"""
mylist = [
    'https://www.bodine-electric.com/products/dc-motors/',
    'https://www.bodine-electric.com/products/dc-parallel-shaft-gearmotors/',
    'https://www.bodine-electric.com/products/dc-right-angle-gearmotors/',
    'https://www.bodine-electric.com/products/dc-right-angle-hollow-shaft-gearmotors/',
    'https://www.bodine-electric.com/products/ac-motors/',
    'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/',
    'https://www.bodine-electric.com/products/ac-right-angle-gearmotors/',
    'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/',
    'https://www.bodine-electric.com/products/ac-torque-motors/',
    'https://www.bodine-electric.com/products/brushless-dc-motors/',
    'https://www.bodine-electric.com/products/brushless-dc-parallel-shaft-gearmotors/',
    'https://www.bodine-electric.com/products/brushless-dc-right-angle-gearmotors/',
    'https://www.bodine-electric.com/products/integramotor-bldc-motors-and-gearmotors/',
    'https://www.bodine-electric.com/products/capacitors/',
    'https://www.bodine-electric.com/products/terminal-boxes/',
    'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/',
    'https://www.bodine-electric.com/products/encoder-shaft-kits/',
    'https://www.bodine-electric.com/products/planetary-gearmotor-accessories/',
    'https://www.bodine-electric.com/products/l-brackets/',
    'https://www.bodine-electric.com/products/base-kits-adaptors/',
    'https://www.bodine-electric.com/products/cable-kits/',
    'https://www.bodine-electric.com/products/ip-44-kits-for-pmdc-controls/',
    'https://www.bodine-electric.com/products/accessory-kits-for-speed-controls/',
    'https://www.bodine-electric.com/products/ac-controls/',
    'https://www.bodine-electric.com/products/dc-controls/',
    'https://www.bodine-electric.com/products/brushless-dc-controls/',
    'https://www.bodine-electric.com/products/replacement-parts/',
]

for url in mylist:
    driver.get(url)
    time.sleep(1)
    print('product-url', url)
    length = driver.find_elements(By.XPATH, "//body/main[@class='mainContentWrapper']/div[@class='container']/div[@class='col-xs-12 col-sm-8']//div//a")
    print(len(length))
    for u in driver.find_elements(By.XPATH,"//body/main[@class='mainContentWrapper']/div[@class='container']/div[@class='col-xs-12 col-sm-8']//div//a"):
        url_link = (u.get_attribute('href'))
        print(url_link)
        save = open('bodine-urls-step2.txt', 'a+', encoding='utf-8')
        save.write('\n' + "'" + url_link + "',")
"""

# step Three


mylist = [
    # 'https://www.bodine-electric.com/products/dc-motors/24a-series-permanent-magnet-dc-motor/',
    # 'https://www.bodine-electric.com/products/dc-motors/33a-series-permanent-magnet-dc-motor/',
    # 'https://www.bodine-electric.com/products/dc-motors/metric-33a-series-permanent-magnet-dc-motor/',
    # 'https://www.bodine-electric.com/products/dc-motors/42a-series-permanent-magnet-dc-motor/',
    # 'https://www.bodine-electric.com/products/dc-motors/metric-42a-series-permanent-magnet-dc-motor/',
    # 'https://www.bodine-electric.com/products/dc-parallel-shaft-gearmotors/24a4-60p-series-90-130v-inline-planetary-dc-gearmotor-us/',
    # 'https://www.bodine-electric.com/products/dc-parallel-shaft-gearmotors/24a4-60p-series-12-or-24v-inline-planetary-dc-gearmotor-metric/',
    # 'https://www.bodine-electric.com/products/dc-parallel-shaft-gearmotors/24a-d-series-parallel-shaft-dc-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-parallel-shaft-gearmotors/metric-24a-d-series-parallel-shaft-dc-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-parallel-shaft-gearmotors/24a-z-series-parallel-shaft-dc-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-parallel-shaft-gearmotors/24a-z-series-parallel-shaft-dc-gearmotor-scr-rated/',
    # 'https://www.bodine-electric.com/products/dc-parallel-shaft-gearmotors/metric-24a-z-series-parallel-shaft-dc-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-parallel-shaft-gearmotors/33a-z-series-parallel-shaft-dc-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-parallel-shaft-gearmotors/33a-z-series-dc-parallel-shaft-scr-rated-90v-180v-gearmotors/',
    # 'https://www.bodine-electric.com/products/dc-parallel-shaft-gearmotors/metric-33a-z-series-parallel-shaft-dc-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-parallel-shaft-gearmotors/33a-wx-series-parallel-shaft-dc-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-parallel-shaft-gearmotors/33a-wx-series-parallel-shaft-dc-gearmotor-scr-rated/',
    # 'https://www.bodine-electric.com/products/dc-parallel-shaft-gearmotors/metric-33a-w-series-parallel-shaft-dc-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-parallel-shaft-gearmotors/42a5-fx-parallel-shaft-dc-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-parallel-shaft-gearmotors/42a-fx-series-dc-parallel-shaft-scr-rated-90v-180v-gearmotors/',
    # 'https://www.bodine-electric.com/products/dc-parallel-shaft-gearmotors/metric-42a-e-and-42a-f-series-parallel-shaft-dc-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-parallel-shaft-gearmotors/33a-hg-h-series-offset-parallel-shaft-dc-hollow-shaft-gearmotor247/',
    # 'https://www.bodine-electric.com/products/dc-parallel-shaft-gearmotors/33a-hg-series-parallel-shaft-dc-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-parallel-shaft-gearmotors/42a-cg-series-parallel-shaft-dc-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-gearmotors/hypoid-series-33a7-dc-right-angle-hollow-shaft-130v-24v-12v-gearmotors215/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-gearmotors/hypoid-series-33a7-dc-right-angle-hollow-shaft-scr-rated-90v-180v-gearmotors/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-gearmotors/24a-3f-series-dc-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-gearmotors/24a-3f-h-series-dc-right-angle-hollow-shaft-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-gearmotors/metric-24a-3f-series-dc-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-gearmotors/24a-3rd-series-dc-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-gearmotors/33a-5f-series-dc-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-gearmotors/metric-33a-5f-series-dc-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-gearmotors/33a-5r-and-33a-5l-series-dc-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-gearmotors/33a-gb-series-dc-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-gearmotors/33a-gb-h-series-dc-right-angle-hollow-shaft-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-gearmotors/33a-5l-h-series-dc-right-angle-hollow-shaft-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-gearmotors/33a-5l-h-series-dc-right-angle-hollow-shaft-scr-rated-90v-180v-gearmotors197/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-gearmotors/42a-5l-series-dc-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-gearmotors/42a-5n-series-dc-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-gearmotors/metric-42a-5n-series-dc-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-gearmotors/42a-5h-series-dc-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-gearmotors/metric-42a-5h-series-dc-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-gearmotors/42a-gb-series-dc-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-gearmotors/metric-42a-gb-series-dc-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-hollow-shaft-gearmotors/33a-hg-h-series-offset-parallel-shaft-dc-hollow-shaft-gearmotor248/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-hollow-shaft-gearmotors/hypoid-series-33a7-dc-right-angle-hollow-shaft-130v-24v-12v-gearmotors/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-hollow-shaft-gearmotors/hypoid-series-33a7-dc-right-angle-hollow-shaft-scr-rated-90v-180v-gearmotors217/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-hollow-shaft-gearmotors/24a-3f-h-series-dc-right-angle-hollow-shaft-gearmotor150/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-hollow-shaft-gearmotors/33a-gb-h-series-dc-right-angle-hollow-shaft-gearmotor151/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-hollow-shaft-gearmotors/33a-5l-h-series-dc-right-angle-hollow-shaft-gearmotor152/',
    # 'https://www.bodine-electric.com/products/dc-right-angle-hollow-shaft-gearmotors/33a-5l-h-series-dc-right-angle-hollow-shaft-scr-rated-90v-180v-gearmotors/',
    # 'https://www.bodine-electric.com/products/ac-motors/30r-series-ac-induction-motor/',
    # 'https://www.bodine-electric.com/products/ac-motors/30r-ac-3-phase-inverter-duty-motor/',
    # 'https://www.bodine-electric.com/products/ac-motors/metric-30r-series-ac-motor/',
    # 'https://www.bodine-electric.com/products/ac-motors/34r-series-ac-induction-motor/',
    # 'https://www.bodine-electric.com/products/ac-motors/pacesetter-34r-ac-inverter-duty-motor/',
    # 'https://www.bodine-electric.com/products/ac-motors/34r6-series-ac-3-phase-inverter-duty-motors-class-1-division-1/',
    # 'https://www.bodine-electric.com/products/ac-motors/metric-34r-series-ac-motor/',
    # 'https://www.bodine-electric.com/products/ac-motors/42r-series-ac-induction-motor/',
    # 'https://www.bodine-electric.com/products/ac-motors/pacesetter-42r-ac-inverter-duty-motor/',
    # 'https://www.bodine-electric.com/products/ac-motors/metric-42r-series-ac-motor/',
    # 'https://www.bodine-electric.com/products/ac-motors/48r-series-ac-induction-motor/',
    # 'https://www.bodine-electric.com/products/ac-motors/pacesetter-48r-ac-inverter-duty-motor/',
    # 'https://www.bodine-electric.com/products/ac-motors/k-2-series-ac-induction-motor/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/30r-d-series-parallel-shaft-ac-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/pacesetter-30r-d-parallel-shaft-ac-inverter-duty-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/metric-30r-d-series-parallel-shaft-ac-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/34r-z-series-parallel-shaft-ac-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/pacesetter-34r-z-parallel-shaft-ac-inverter-duty-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/metric-34r-z-series-parallel-shaft-ac-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/34r-wx-series-parallel-shaft-ac-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/34r-wx-series-parallel-shaft-ac-3-phase-inverter-duty-gearmotor201/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/metric-34r-w-series-parallel-shaft-ac-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/pacesetter-34r-fx-parallel-shaft-ac-inverter-duty-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/34r4-fx-series-parallel-shaft-ac-3-phase-inverter-duty-gearmotors-class-1-division-2/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/34r6-fx-series-parallel-shaft-ac-1-phase-psc-gearmotors-class-1-division-2236/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/34r6-fx-series-parallel-shaft-ac-3-phase-inverter-duty-gearmotors-class-1-division-1/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/42r6-fx-series-parallel-shaft-ac-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/42r5-fx-series-split-phase-parallel-shaft-ac-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/pacesetter-42r-fx-parallel-shaft-ac-inverter-duty-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/metric-42r-e-series-parallel-shaft-ac-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/42r-hg-h-series-parallel-shaft-ac-3-phase-inverter-duty-hollow-shaft-gearmotor241/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/42r-hg-series-parallel-shaft-ac-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/pacesetter-42r-hg-parallel-shaft-ac-inverter-duty-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/48r-fx-series-parallel-shaft-ac-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/pacesetter-48r-cg-parallel-shaft-ac-inverter-duty-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/k-2-series-parallel-shaft-ac-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-parallel-shaft-gearmotors/metric-k-2-series-parallel-shaft-ac-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-right-angle-gearmotors/30r-3rd-series-ac-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-right-angle-gearmotors/pacesetter-30r-3rd-right-angle-ac-inverter-duty-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-right-angle-gearmotors/pacesetter-30r-3n-right-angle-ac-inverter-duty-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-right-angle-gearmotors/34r-3f-series-ac-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-right-angle-gearmotors/metric-34r-3f-series-ac-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-right-angle-gearmotors/34r-5f-series-ac-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-right-angle-gearmotors/metric-34r-5f-series-ac-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-right-angle-gearmotors/34r-5r-and-42r-5l-series-ac-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-right-angle-gearmotors/42r-5n-series-ac-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-right-angle-gearmotors/pacesetter-42r-5n-right-angle-ac-inverter-duty-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-right-angle-gearmotors/metric-42r-5n-series-ac-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-right-angle-gearmotors/metric-42r-5f-series-ac-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-right-angle-gearmotors/pacesetter-42r-5l-h-right-angle-hollow-shaft-ac-inverter-duty-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-right-angle-gearmotors/42r-gb-series-ac-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-right-angle-gearmotors/pacesetter-42r-gb-right-angle-ac-inverter-duty-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-right-angle-gearmotors/42r-gb-h-series-ac-right-angle-hollow-shaft-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-right-angle-gearmotors/pacesetter-42r6-gb-h-right-angle-hollow-shaft-ac-inverter-duty-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-right-angle-gearmotors/metric-42r-gb-series-ac-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-right-angle-gearmotors/pacesetter-48r-5h-right-angle-ac-inverter-duty-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/pacesetter-30r-ac-inverter-duty-motor/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/34r-ac-3-phase-inverter-duty-motor/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/34r6-series-ac-3-phase-inverter-duty-motors-class-1-division-1232/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/42r-ac-3-phase-inverter-duty-motor/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/48r-ac-series-3-phase-inverter-duty-motor/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/30r-d-parallel-shaft-ac-series-3-phase-inverter-duty-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/34r-z-parallel-shaft-ac-3-phase-inverter-duty-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/34r-wx-series-parallel-shaft-ac-3-phase-inverter-duty-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/34r-fx-parallel-shaft-ac-3-phase-inverter-duty-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/34r4-fx-series-parallel-shaft-ac-3-phase-inverter-duty-gearmotors-class-1-division-2235/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/34r6-fx-series-parallel-shaft-ac-3-phase-inverter-duty-gearmotors-class-1-division-1228/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/42r-fx-parallel-shaft-ac-3-phase-inverter-duty-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/42r-hg-h-series-parallel-shaft-ac-3-phase-inverter-duty-hollow-shaft-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/42r-hg-parallel-shaft-ac-3-phase-inverter-duty-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/48r-cg-series-parallel-shaft-ac-3-phase-inverter-duty-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/30r-3rd-series-ac-right-angle-gearmotor180/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/30r-3n-series-3-phase-ac-inverter-duty-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/42r-5n-series-3-phase-ac-inverter-duty-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/42r-5l-h-series-3-phase-ac-inverter-duty-right-angle-hollow-shaft-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/42r-gb-series-3-phase-ac-inverter-duty-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/42r-gb-h-series-3-phase-ac-inverter-duty-right-angle-hollow-shaft-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-3-phase-inverter-duty-gearmotors-and-motors/48r-5h-series-3-phase-ac-inverter-duty-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-torque-motors/k-2-series-ac-torque-motor/',
    # 'https://www.bodine-electric.com/products/ac-torque-motors/30r-series-ac-torque-motor/',
    # 'https://www.bodine-electric.com/products/ac-torque-motors/42r-series-ac-torque-motor/',
    # 'https://www.bodine-electric.com/products/ac-torque-motors/48r-series-ac-torque-motor/',
    # 'https://www.bodine-electric.com/products/brushless-dc-motors/22b-series-bldc-motor/',
    # 'https://www.bodine-electric.com/products/brushless-dc-motors/22b-sr-series-integramotor-bldc-motor/',
    # 'https://www.bodine-electric.com/products/brushless-dc-motors/22b-fv-series-integramotor-bldc-motor/',
    # 'https://www.bodine-electric.com/products/brushless-dc-motors/34b-series-bldc-motor/',
    # 'https://www.bodine-electric.com/products/brushless-dc-motors/34b-fv-series-integramotor-bldc-motor/',
    # 'https://www.bodine-electric.com/products/brushless-dc-motors/34b6-series-bldc-motors-class-1-division-1/',
    # 'https://www.bodine-electric.com/products/brushless-dc-parallel-shaft-gearmotors/22b4-60p-series-130v-inline-planetary-bldc-gearmotors-us/',
    # 'https://www.bodine-electric.com/products/brushless-dc-parallel-shaft-gearmotors/22b4-60p-series-24v-inline-planetary-bldc-gearmotors-metric/',
    # 'https://www.bodine-electric.com/products/brushless-dc-parallel-shaft-gearmotors/22b-d-series-parallel-shaft-bldc-gearmotor/',
    # 'https://www.bodine-electric.com/products/brushless-dc-parallel-shaft-gearmotors/22b-z-series-parallel-shaft-bldc-gearmotor/',
    # 'https://www.bodine-electric.com/products/brushless-dc-parallel-shaft-gearmotors/22b-sr-d-and-22b-sr-z-series-integramotor-parallel-shaft-bldc-gearmotor/',
    # 'https://www.bodine-electric.com/products/brushless-dc-parallel-shaft-gearmotors/22b-fv-d-and-22b-fv-z-series-integramotor-parallel-shaft-bldc-gearmotor/',
    # 'https://www.bodine-electric.com/products/brushless-dc-parallel-shaft-gearmotors/34b-e-and-34b-f-series-parallel-shaft-bldc-gearmotor/',
    # 'https://www.bodine-electric.com/products/brushless-dc-parallel-shaft-gearmotors/34b-wx-series-parallel-shaft-bldc-gearmotor/',
    # 'https://www.bodine-electric.com/products/brushless-dc-parallel-shaft-gearmotors/34b4-sr-wx-series-integramotor-bldc-parallel-shaft-gearmotor-class-1-division-2160/',
    # 'https://www.bodine-electric.com/products/brushless-dc-parallel-shaft-gearmotors/34b-fv-f-series-integramotor-bldc-parallel-shaft-gearmotor147/',
    # 'https://www.bodine-electric.com/products/brushless-dc-parallel-shaft-gearmotors/34b6-fx-series-parallel-shaft-bldc-gearmotors-class-1-division-1/',
    # 'https://www.bodine-electric.com/products/brushless-dc-right-angle-gearmotors/22b-3n-series-bldc-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/brushless-dc-right-angle-gearmotors/22b-3rd-series-bldc-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/brushless-dc-right-angle-gearmotors/34b-5n-series-bldc-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/brushless-dc-right-angle-gearmotors/22b-sr-3n-series-integramotor-bldc-right-angle-gearmotor54/',
    # 'https://www.bodine-electric.com/products/brushless-dc-right-angle-gearmotors/22b-fv-3n-series-integramotor-bldc-right-angle-gearmotor100/',
    # 'https://www.bodine-electric.com/products/brushless-dc-right-angle-gearmotors/22b-sr-3f-h-series-integramotor-bldc-right-angle-hollow-shaft-gearmotor143/',
    # 'https://www.bodine-electric.com/products/brushless-dc-right-angle-gearmotors/22b-fv-3f-h-series-integramotor-bldc-right-angle-hollow-shaft-gearmotor144/',
    # 'https://www.bodine-electric.com/products/brushless-dc-right-angle-gearmotors/34b-fv-5n-series-integramotor-bldc-right-angle-gearmotor155/',
    # 'https://www.bodine-electric.com/products/integramotor-bldc-motors-and-gearmotors/34b4-sr-wx-series-integramotor-bldc-parallel-shaft-gearmotor/',
    # 'https://www.bodine-electric.com/products/integramotor-bldc-motors-and-gearmotors/22b-sr-series-integramotor/',
    # 'https://www.bodine-electric.com/products/integramotor-bldc-motors-and-gearmotors/22b-fv-series-integramotor/',
    # 'https://www.bodine-electric.com/products/integramotor-bldc-motors-and-gearmotors/34b-fv-series-integramotor/',
    # 'https://www.bodine-electric.com/products/integramotor-bldc-motors-and-gearmotors/22b-sr-d-and-22b-sr-z-series-integramotor-bldc-parallel-shaft-gearmotor/',
    # 'https://www.bodine-electric.com/products/integramotor-bldc-motors-and-gearmotors/22b-fv-d-and-22b-fv-z-series-integramotor-bldc-parallel-shaft-gearmotor/',
    # 'https://www.bodine-electric.com/products/integramotor-bldc-motors-and-gearmotors/34b-fv-f-series-integramotor-bldc-parallel-shaft-gearmotor/',
    # 'https://www.bodine-electric.com/products/integramotor-bldc-motors-and-gearmotors/22b-sr-3n-series-integramotor-bldc-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/integramotor-bldc-motors-and-gearmotors/22b-fv-3n-series-integramotor-bldc-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/integramotor-bldc-motors-and-gearmotors/22b-sr-3f-h-series-integramotor-bldc-right-angle-hollow-shaft-gearmotor/',
    # 'https://www.bodine-electric.com/products/integramotor-bldc-motors-and-gearmotors/22b-fv-3f-h-series-integramotor-bldc-right-angle-hollow-shaft-gearmotor/',
    # 'https://www.bodine-electric.com/products/integramotor-bldc-motors-and-gearmotors/34b-fv-5n-series-integramotor-bldc-right-angle-gearmotor/',
    # 'https://www.bodine-electric.com/products/ac-controls/pacesetter-chassis-ip-00-series-ac-inverter/',
    # 'https://www.bodine-electric.com/products/ac-controls/pacesetter-nema-1-ip-40-series-ac-motor-speed-control/',
    # 'https://www.bodine-electric.com/products/ac-controls/pacesetter-nema-4x-ip-65-series-ac-motor-speed-control158/',
    # 'https://www.bodine-electric.com/products/dc-controls/filtered-pwm-dc-basic-speed-control/',
    # 'https://www.bodine-electric.com/products/dc-controls/filtered-pwm-dc-speed-and-direction-control/',
    # 'https://www.bodine-electric.com/products/dc-controls/filtered-scr-dc-basic-speed-control/',
    # 'https://www.bodine-electric.com/products/dc-controls/filtered-scr-dc-speed-and-direction-control/',
    # 'https://www.bodine-electric.com/products/dc-controls/filtered-scr-dc-remote-speed-control/',
    # 'https://www.bodine-electric.com/products/dc-controls/unfiltered-scr-dc-basic-speed-control/',
    # 'https://www.bodine-electric.com/products/dc-controls/unfiltered-scr-motor-speed-control/',
    # 'https://www.bodine-electric.com/products/dc-controls/filtered-pwm-dc-basic-speed-control-open-chassis/',
    # 'https://www.bodine-electric.com/products/dc-controls/low-voltage-pwm-dc-motor-speed-control-open-chassis/',
    # 'https://www.bodine-electric.com/products/dc-controls/unfiltered-scr-dc-basic-speed-control-open-chassis/',
    # 'https://www.bodine-electric.com/products/dc-controls/filtered-scr-dc-basic-speed-control-open-chassis/',
    # 'https://www.bodine-electric.com/products/brushless-dc-controls/compact-low-voltage-brushless-dc-controls/',
    # 'https://www.bodine-electric.com/products/brushless-dc-controls/compact-low-voltage-brushless-dc-controls-120-commutation/',
    # 'https://www.bodine-electric.com/products/brushless-dc-controls/low-voltage-pwm-brushless-dc-controls/',
    # 'https://www.bodine-electric.com/products/brushless-dc-controls/low-voltage-brushless-dc-controls-120-commutation-8-pole/',
    # 'https://www.bodine-electric.com/products/brushless-dc-controls/enclosed-filtered-scr-brushless-dc-controls/',
    # 'https://www.bodine-electric.com/products/brushless-dc-controls/filtered-scr-brushless-dc-controls/',
    # 'https://www.bodine-electric.com/products/brushless-dc-controls/unfiltered-scr-brushless-dc-controls/',
    # 'https://www.bodine-electric.com/products/brushless-dc-controls/low-voltage-12v-pwm-brushless-dc-control/',

    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-085-mfd-250v-model-49400045/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-10-mfd-250v-model-49400046/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-12-mfd-250v-model-49400047/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-13-mfd-250v-model-49400048/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-15-mfd-250v-model-49400050/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-16-mfd-250v-model-49400051/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-13-mfd-440v-model-49400091/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-125-mfd-250v-model-49401006/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-50-mfd-250v-model-49401015/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-23-mfd-250v-model-49401047/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-100-mfd-250v-model-49401054/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-200-mfd-350v-model-49401057/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-50-mfd-400v-model-49401068/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-150-mfd-350v-model-49401075/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-30-mfd-250v-model-49401090/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-90-mfd-250v-model-49401106/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-125-mfd-370v-model-49401107/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-275-mfd-250v-model-49401112/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-20-mfd-250v-model-49401113/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-60-mfd-450v-model-49401115/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-375-mfd-370v-model-49401123/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-metal-can-type-25-mfd-400v-model-49401124/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-metal-can-type-45-mfd-250v-model-49401145/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-metal-can-type-40-mfd-250v-model-49401147/',
    # 'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/shaft-kit-3f-h-1-2-inch-single-shaft-model-0910/',
    # 'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/shaft-kit-5l-h-5-8-inch-single-shaft-model-0912/',
    # 'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/shaft-kit-gb-h-3-4-inch-single-shaft-model-0917/',
    # 'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/shaft-kit-3f-h-1-2-inch-double-shaft-model-0920/',
    # 'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/shaft-kit-5l-h-5-8-inch-double-shaft-model-0922/',
    # 'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/shaft-kit-gb-h-3-4-inch-double-shaft-model-0927/',
    # 'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/shaft-kit-5l-h-5-8-inch-single-shaft-model-0928/',
    # 'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/shaft-kit-25h2-1-inch-single-shaft-model-0929/',
    # 'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/shaft-kit-30h3-1-1-8-inch-single-shaft-model-0930/',
    # 'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/shaft-kit-hg-h-3-4-inch-single-shaft-model-0932/',
    # 'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/shaft-kit-hg-h-3-4-inch-double-shaft-model-0933/',
    # 'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/cover-kit-for-3f-h-hollow-shaft-gearmotors-model-0950/',
    # 'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/cover-kit-for-5l-h-amp-gb-h-hollow-shaft-gearmotors-model-0951/',
    # 'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/cover-kit-for-25h2-hollow-shaft-gearmotors-model-0952/',
    # 'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/cover-kit-for-30h3-hollow-shaft-gearmotors-model-0953/',
    # 'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/cover-kit-for-hg-h-hollow-shaft-gearmotors-model-0954/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-metal-can-type-10-mfd-450v-model-49401148/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-04-mfd-440v-model-49401049/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-75mfd-370v-model-49401154/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-125-mfd-250v-model-49401155/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-150-mfd-250v-49401156/',
    # 'https://www.bodine-electric.com/products/capacitors/capacitor-plastic-box-type-40-mfd-250v-model-49426812/',
    # 'https://www.bodine-electric.com/products/capacitors/mounting-clamp-for-capacitor-49401124-model-54701013/',
    # 'https://www.bodine-electric.com/products/capacitors/mounting-clamp-for-42r6-and-42r6-fx-run-capacitors-49401145-47-48-model-54701029/',
    # 'https://www.bodine-electric.com/products/capacitors/mounting-clamp-p-n-54701036/',
    # 'https://www.bodine-electric.com/products/terminal-boxes/die-cast-terminal-box-kit-for-33a-34r-42a-42r-and-48r-motors-and-gearmotors-model-0984/',
    # 'https://www.bodine-electric.com/products/terminal-boxes/large-die-cast-terminal-box-kit-for-34r-42r-48r-42r-fx-33a-42a-stock-motors-and-gearmotors-model-0986/',
    # 'https://www.bodine-electric.com/products/terminal-boxes/die-cast-metric-terminal-box-with-terminal-block-for-30r-motors-and-gearmotors-model-1982/',
    # 'https://www.bodine-electric.com/products/terminal-boxes/die-cast-metric-terminal-box-kit-with-terminal-block-for-33a-34r-42a-42r-and-48r-motors-and-gearmotors-model-1984/',
    # 'https://www.bodine-electric.com/products/terminal-boxes/die-cast-terminal-box-for-30r-motors-and-gearmotors-model-5982/',
    # 'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/flange-mount-kit-for-3f-h-hollow-shaft-gearmotors-model-0955/',
    # 'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/flange-mount-kit-for-5l-h-amp-gb-h-hollow-shaft-gearmotors-model-0956/',
    # 'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/base-mount-kit-for-30h3-hollow-shaft-gearmotors-model-0959/',
    # 'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/base-mount-kit-for-25h2-hollow-shaft-gearmotors-model-0957/',
    # 'https://www.bodine-electric.com/products/hollow-shaft-gearmotor-accessories/base-mount-kit-for-5l-h-hollow-shaft-gearmotors-0958/',
    # 'https://www.bodine-electric.com/products/encoder-shaft-kits/encoder-shaft-kit-for-type-60p-gearmotors-us-metric/',
    # 'https://www.bodine-electric.com/products/planetary-gearmotor-accessories/flange-kit-for-type-60p-gearmotors-us-model-0960107/',
    # 'https://www.bodine-electric.com/products/planetary-gearmotor-accessories/flange-kit-for-type-60p-gearmotors-metric-model-0961/',
    # 'https://www.bodine-electric.com/products/planetary-gearmotor-accessories/flange-ip-66-seal-kit-for-type-60p-gearmotors-us-model-0962/',
    # 'https://www.bodine-electric.com/products/planetary-gearmotor-accessories/flange-ip-66-seal-kit-for-type-60p-gearmotors-metric-model-0963/',
    # 'https://www.bodine-electric.com/products/l-brackets/quotlquot-bracket-kit-for-quotequot-quotfquot-and-quotfxquot-gearmotors-model-0969/',
    # 'https://www.bodine-electric.com/products/l-brackets/quotlquot-bracket-kit-for-quotwquot-and-quotwxquot-gearmotors-model-0970/',
    # 'https://www.bodine-electric.com/products/l-brackets/quotlquot-bracket-kit-for-34b-and-34r-motors-model-0979/',
    # 'https://www.bodine-electric.com/products/l-brackets/quotlquot-bracket-kit-for-34r-z-gearmotors-model-0980/',
    # 'https://www.bodine-electric.com/products/l-brackets/quotlquot-bracket-kit-for-24a-motors-model-0990/',
    # 'https://www.bodine-electric.com/products/l-brackets/quotlquot-bracket-kit-for-metric-type-30r-33a-30r-d-24a-d-24a-z-products-model-1968/',
    # 'https://www.bodine-electric.com/products/l-brackets/quotlquot-bracket-mounting-kit-for-metric-type-quote-fquot-gearmotors-model-1969/',
    # 'https://www.bodine-electric.com/products/l-brackets/quotlquot-bracket-mounting-kit-for-metric-type-quotwquot-gearmotors-model-1970/',
    # 'https://www.bodine-electric.com/products/l-brackets/quotlquot-bracket-kit-for-30r-motors-30r-d-gearmotors-33a-motors-and-22b-d-22b-z-24a-d-24a-z-33a-z-gearmotors-model-5968/',
    # 'https://www.bodine-electric.com/products/base-kits-adaptors/base-mount-kit-for-c1d1-gearmotors-and-motors-model-0931/',
    # 'https://www.bodine-electric.com/products/base-kits-adaptors/base-plate-mounting-kit-for-3f-gearmotors-model-0967/',
    # 'https://www.bodine-electric.com/products/base-kits-adaptors/die-cast-base-kit-for-42a-motors-model-0991/',
    # 'https://www.bodine-electric.com/products/base-kits-adaptors/33a-42a-mounting-adaptor-for-encoders-and-brakes-model-0992/',
    # 'https://www.bodine-electric.com/products/base-kits-adaptors/22-34b-adaptor-plate-kit-model-0993/',
    # 'https://www.bodine-electric.com/products/base-kits-adaptors/adaptor-plate-kit-for-quotequot-quotfquot-quotwquot-quotwxquot-and-quotfxquot-gearheads-model-0995/',
    # 'https://www.bodine-electric.com/products/base-kits-adaptors/base-kit-for-34r-motor-with-extruded-center-ring-model-0996/',
    # 'https://www.bodine-electric.com/products/cable-kits/6-cable-kit-for-stock-34b-fv-integramotors-model-3981/',
    # 'https://www.bodine-electric.com/products/cable-kits/6-cable-encased-model-3982/',
    # 'https://www.bodine-electric.com/products/cable-kits/6-cable-chassis-model-3983/',
    # 'https://www.bodine-electric.com/products/ip-44-kits-for-pmdc-controls/ip-44-kit-for-24a-motors-model-0976/',
    # 'https://www.bodine-electric.com/products/ip-44-kits-for-pmdc-controls/ip-44-kit-for-33a-motors-model-0977/',
    # 'https://www.bodine-electric.com/products/ip-44-kits-for-pmdc-controls/ip-44-kit-for-42a-motors-model-0978/',
    # 'https://www.bodine-electric.com/products/accessory-kits-for-speed-controls/analog-interface-board-model-0888/',
    # 'https://www.bodine-electric.com/products/accessory-kits-for-speed-controls/electronic-direction-and-braking-board-f-b-r-kit-model-0890/',
    # 'https://www.bodine-electric.com/products/accessory-kits-for-speed-controls/ip-44-sealing-kit-model-0895/',
    # 'https://www.bodine-electric.com/products/accessory-kits-for-speed-controls/local-remote-switch-kit-for-fpm-controls-model-0893/',
    # 'https://www.bodine-electric.com/products/accessory-kits-for-speed-controls/analog-interface-and-isolation-module-model-3984/',
    # 'https://www.bodine-electric.com/products/accessory-kits-for-speed-controls/speed-pot-kit-for-fpm-permanent-magnet-dc-controls-chassis-models-only-model-43300260/',
    # 'https://www.bodine-electric.com/products/accessory-kits-for-speed-controls/fuse-and-speed-potentiometer-kit-for-brushless-dc-controls-model-43300270/',
    # 'https://www.bodine-electric.com/products/replacement-parts/brush-s49200032/',
    # 'https://www.bodine-electric.com/products/replacement-parts/spring-s57401001/',
    # 'https://www.bodine-electric.com/products/replacement-parts/brush-and-spring-combo-s49201001/',
    # 'https://www.bodine-electric.com/products/replacement-parts/brush-and-spring-combo-s49201003/',
    # 'https://www.bodine-electric.com/products/replacement-parts/24a-brush-cap-s49300037/',
    # 'https://www.bodine-electric.com/products/replacement-parts/brush-s49201010/',
    # 'https://www.bodine-electric.com/products/replacement-parts/brush-s49200047/',
    # 'https://www.bodine-electric.com/products/replacement-parts/33a-brush-part-number-49201047/',
    # 'https://www.bodine-electric.com/products/replacement-parts/33a-32a-brush-s49201028/',
    # 'https://www.bodine-electric.com/products/replacement-parts/33a-32a-brush-s49201031/',
    # 'https://www.bodine-electric.com/products/replacement-parts/brush-cap-s49300034/',
    # 'https://www.bodine-electric.com/products/replacement-parts/brush-cap-s49301001/',
    # 'https://www.bodine-electric.com/products/replacement-parts/spring-s57400008/',
    # 'https://www.bodine-electric.com/products/replacement-parts/brush-s49200048/',
    # 'https://www.bodine-electric.com/products/replacement-parts/brush-s49201032/',
    # 'https://www.bodine-electric.com/products/replacement-parts/42a-brush-s49201029/',


]
for url in mylist:
    driver.get(url)
    time.sleep(1)
    print('product-url', url)
    driver.find_element(By.XPATH, "//div[@class='accordion']").click()
    time.sleep(1)
    # length = driver.find_elements(By.XPATH, "//div[@class='col-xs-12 product-models no-spacing hidden-xs']//ul[@class='dLocator']//li//a")
    length = driver.find_elements(By.XPATH, "//div[@class='accordion__content']//div//a")
    print(len(length))

    # for url_links in driver.find_elements(By.XPATH, "//div[@class='col-xs-12 product-models no-spacing hidden-xs']//ul[@class='dLocator']//li//a"):
    for url_links in driver.find_elements(By.XPATH, "//div[@class='accordion__content']//div//a"):
        url_link = url_links.get_attribute('href')
        print(url_link)

        save = open('bodine-urls-step3.txt', 'a+', encoding='utf-8')
        save.write('\n' + "'" + url_link + "',")
