import time

import requests
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import undetected_chromedriver as uc

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"}
opts = Options()
opts.headless = False
# driver = webdriver.Chrome(r"/home/pradeep/Music/chromedriver_linux64/chromedriver")
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

# driver = uc.Chrome()

driver.maximize_window()

L = 0
Result = [

    # 'https://cad.timken.com/viewitems/standard-jaw-couplings-l-type/solid-center-spiders-metric?plpver=1013&pcat=lovejoy',
    # 'https://cad.timken.com/viewitems/standard-jaw-couplings-l-type/open-center-spiders-metric?plpver=1013&pcat=lovejoy',
    # 'https://cad.timken.com/viewitems/standard-jaw-couplings-l-type/l-type-coupling-hubs-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    # 'https://cad.timken.com/viewitems/standard-jaw-couplings-l-type/l-type-coupling-hubs-w-keyway-metric?plpver=1013&pcat=lovejoy',
    # 'https://cad.timken.com/viewitems/standard-jaw-couplings-l-type/l-type-coupling-hubs-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    # 'https://cad.timken.com/viewitems/standard-jaw-couplings-l-type/l-type-coupling-hubs-w-o-keyway-metric?plpver=1013&pcat=lovejoy',
    # 'https://cad.timken.com/viewitems/standard-jaw-couplings-l-type/l-type-coupling-hubs-w-rough-stock-bore-imperial?plpver=1013&pcat=lovejoy',
    # 'https://cad.timken.com/viewitems/standard-jaw-couplings-l-type/l-type-solid-hubs?plpver=1013&pcat=lovejoy',
    # 'https://cad.timken.com/viewitems/standard-jaw-couplings-l-type/jaw-type-couplings-spling-hubs?plpver=1013&pcat=lovejoy',
    # 'https://cad.timken.com/viewitems/standard-jaw-couplings-l-type/l-type-hubs-imperial?plpver=1013&pcat=lovejoy',
    # 'https://cad.timken.com/viewitems/aluminum-jaw-couplings-al-type/al-type-coupling-hubs-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    # 'https://cad.timken.com/viewitems/aluminum-jaw-couplings-al-type/al-type-coupling-hubs-w-keyway-metric?plpver=1013&pcat=lovejoy',
    # 'https://cad.timken.com/viewitems/aluminum-jaw-couplings-al-type/al-type-coupling-hubs-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    # 'https://cad.timken.com/viewitems/aluminum-jaw-couplings-al-type/al-type-coupling-hubs-w-o-keyway-metric?plpver=1013&pcat=lovejoy',
    # 'https://cad.timken.com/item/aluminum-jaw-couplings-al-type/al150-type-sox-nbr-rubber-spider-metric/68514418027-2?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/stainless-steel-jaw-couplings-ss-type/ss-type-coupling-hubs-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/stainless-steel-jaw-couplings-ss-type/ss-type-coupling-hubs-w-keyway-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/stainless-steel-jaw-couplings-ss-type/ss-type-coupling-hubs-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/stainless-steel-jaw-couplings-ss-type/ype-coupling-hubs-w-rough-stock-bore-hole-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/w-couplings-w-radially-removable-elastomer-sw-type/snap-wrap-flexible-spiders-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/w-couplings-w-radially-removable-elastomer-lc-type/lc-type-coupling-kits-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/w-couplings-w-radially-removable-elastomer-lc-type/lc-type-collars-w-screws-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/w-couplings-w-radially-removable-elastomer-lc-type/snap-wrap-flexible-spiders-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/w-couplings-w-radially-removable-elastomer-lc-type/lc-type-coupling-hubs-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/w-couplings-w-radially-removable-elastomer-lc-type/lc-type-coupling-hubs-w-keyway-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/w-couplings-w-radially-removable-elastomer-lc-type/lc-type-coupling-hubs-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/w-couplings-w-radially-removable-elastomer-lc-type/lc-type-coupling-hubs-w-o-keyway-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/ially-removable-spacer-jaw-couplings-rrs-rrsc-type/rrs-type-spacer-assembly-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/ially-removable-spacer-jaw-couplings-rrs-rrsc-type/rrs-type-spacer-assembly-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/ially-removable-spacer-jaw-couplings-rrs-rrsc-type/y-removable-spacer-coupling-hubs-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/ially-removable-spacer-jaw-couplings-rrs-rrsc-type/lly-removable-spacer-coupling-hubs-w-keyway-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/ially-removable-spacer-jaw-couplings-rrs-rrsc-type/removable-spacer-coupling-hubs-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/ially-removable-spacer-jaw-couplings-rrs-rrsc-type/y-removable-spacer-coupling-hubs-w-o-keyway-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/ially-removable-spacer-jaw-couplings-rrs-rrsc-type/emovable-spacer-jaw-couplings-rrc-type-hub_unknown/68514452097?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/radially-removable-spacer-jaw-couplings-rrc-type/rrc-type-adapter-hubs-w-rough-stock-inch-bore?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/radially-removable-spacer-jaw-couplings-rrc-type/rrc-type-spacer-assembly-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/higher-torque-jaw-couplings-c-type/c-type-cushion-sets-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/higher-torque-jaw-couplings-c-type/c-type-collars-w-hardware-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/higher-torque-jaw-couplings-c-type/c-type-coupling-hubs-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/higher-torque-jaw-couplings-c-type/c-type-coupling-hubs-w-keyway-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/higher-torque-jaw-couplings-c-type/c-type-coupling-hubs-w-rough-stock-bore-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/higher-torque-jaw-couplings-c-type/c-type-coupling-hubs-w-o-keyway-metric/68514476472?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/higher-torque-jaw-couplings-c-type/jaw-couplings-c-type-hub_unknown/68514476300?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/highest-torque-jaw-couplings-h-type/h-type-couplings-w-rough-stock-bore-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/highest-torque-jaw-couplings-h-type/h-type-coupling-hubs-w-rough-stock-bore-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/highest-torque-jaw-couplings-h-type/h-type-cushion-sets?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/highest-torque-jaw-couplings-h-type/h-type-collars-w-hardware?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/internal-shaft-locking-device-type/edium-high-torque-devices-sld-1500-series-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/internal-shaft-locking-device-type/-medium-high-torque-devices-sld-1500-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/internal-shaft-locking-device-type/cking-high-torque-devices-sld-1850-series-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/internal-shaft-locking-device-type/locking-high-torque-devices-sld-1850-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/internal-shaft-locking-device-type/cking-high-torque-devices-sld-1750-series-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/internal-shaft-locking-device-type/locking-high-torque-devices-sld-1750-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/internal-shaft-locking-device-type/cking-high-torque-devices-sld-1350-series-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/internal-shaft-locking-device-type/locking-high-torque-devices-sld-1350-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/internal-shaft-locking-device-type/cking-high-torque-devices-sld-1450-series-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/internal-shaft-locking-device-type/locking-high-torque-devices-sld-1450-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/internal-shaft-locking-device-type/ocking-heavy-duty-devices-sld-2600-series-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/internal-shaft-locking-device-type/-locking-heavy-duty-devices-sld-2600-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/internal-shaft-locking-device-type/ing-medium-torque-devices-sld-1900-series-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/internal-shaft-locking-device-type/cking-medium-torque-devices-sld-1900-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/internal-shaft-locking-device-type/t-locking-low-torque-devices-sld-350-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/internal-shaft-locking-device-type/locking-low-torque-devices-sld-350-s-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/external-shaft-locking-device-type/cking-self-centering-devices-sld-900-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/jes-jns-type-sleeves-for-s-flex-couplings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/e-n-type-sleeves-for-s-flex-couplings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/h-hs-type-sleeves-for-s-flex-couplings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/s-flex-s-type-flanges-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/s-flex-s-type-flanges-w-keyway-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/s-flex-s-type-flanges-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/s-flex-s-type-flanges-w-o-keyway-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/s-flex-s-type-flanges-w-rough-stock-bore-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/s-flex-j-type-flanges-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/s-flex-j-type-flanges-w-keyway-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/s-flex-j-type-flanges-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/s-flex-j-type-flanges-w-o-keyway-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/j-type-flanges-w-rough-stock-bore-w-hole-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/er-coupling-hubs-w-keyway-standard-length-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/acer-coupling-hubs-w-keyway-standard-length-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/coupling-hubs-w-o-keyway-standard-length-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/g-hubs-w-rough-stock-bore-standard-length-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/pacer-coupling-hubs-w-keyway-short-length-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/cer-coupling-hubs-w-o-keyway-short-length-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/s-flex-couplings/ling-hubs-w-rough-stock-bore-short-length-imperial/68514436755?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/sc-type-spacer-flanges-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/b-type-flanges-for-use-w-bushings-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/ype-flanges-for-use-w-taper-lock-bushings-imperi-2?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/s-flex-couplings/ype-flanges-for-use-w-taper-lock-bushings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/torsional-couplings-lf-series/lf-series-torsional-base-element-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/torsional-couplings-lf-series/eries-torsional-coupling-cylindrical-hubs-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/torsional-couplings-lf-series/lf-series-torsional-coupling-flange-hubs-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/torsional-couplings-lf-series/-of-bolts-for-lf-series-torsional-couplings-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/torsional-couplings-lf-series/-coupling-w-rough-stock-bore-model-2-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/torsional-couplings-lf-series/ling-hubs-w-l-loc-spline-clamping-feature-imperial/68514476411-2?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/torsional-couplings-lf-series/s-torsional-coupling-flange-hubs-w-keyway-imperial/68514476429-2?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/torsional-couplings-lf-series/-torsional-threaded-coupling-hubs-model-2-imperial/68514476211?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/torsional-couplings-lf-series/lf-series-component-of-couplings/68514476412?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/jaw-in-shear-type-couplings/jaw-in-shear-6-pin-kits-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/jaw-in-shear-type-couplings/jaw-in-shear-6-pin-rings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/jaw-in-shear-type-couplings/jaw-in-shear-6-pin-spiders-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/tyle-motion-control-couplings-es-ec-asb-adb-series/luminum-single-beam-clamp-style-couplings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/tyle-motion-control-couplings-es-ec-asb-adb-series/aluminum-single-beam-clamp-style-couplings-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/tyle-motion-control-couplings-es-ec-asb-adb-series/ies-single-beam-set-screw-style-couplings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/tyle-motion-control-couplings-es-ec-asb-adb-series/eries-single-beam-set-screw-style-couplings-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/tyle-motion-control-couplings-es-ec-asb-adb-series/series-single-beam-clamp-style-couplings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/tyle-motion-control-couplings-es-ec-asb-adb-series/ec-series-single-beam-clamp-style-couplings-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/tyle-motion-control-couplings-es-ec-asb-adb-series/luminum-double-beam-clamp-style-couplings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/ows-style-motion-control-couplings-bwc-bwlc-series/bwc-series-bellows-clamp-style-couplings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/ows-style-motion-control-couplings-bwc-bwlc-series/bwc-series-bellows-clamp-style-couplings-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/ows-style-motion-control-couplings-bwc-bwlc-series/bwlc-series-bellows-clamp-style-couplings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/ows-style-motion-control-couplings-bwc-bwlc-series/bwlc-series-bellows-clamp-style-couplings-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/urved-jaw-style-motion-control-couplings-gs-series/curved-jaw-coupling-spiders-gs-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/urved-jaw-style-motion-control-couplings-gs-series/uminum-curved-jaw-coupling-hubs-gs-series-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/urved-jaw-style-motion-control-couplings-gs-series/uminum-curved-jaw-coupling-hubs-gs-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/style-motion-control-couplings-md-mds-mdsd-series/md-series-mini-disc-clamp-style-couplings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/style-motion-control-couplings-md-mds-mdsd-series/es-mini-disc-spacer-clamp-style-couplings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/style-motion-control-couplings-md-mds-mdsd-series/ni-disc-single-disc-clamp-style-couplings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/category/standard-jaw-couplings-l-type?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/ini-soft-style-motion-control-couplings-msf-series/tyle-coupling-center-members-insert-sleeves-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/ini-soft-style-motion-control-couplings-msf-series/set-screw-style-coupling-hubs-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/ini-soft-style-motion-control-couplings-msf-series/ft-set-screw-style-coupling-hubs-w-o-keyway-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/oldham-style-motion-control-couplings-mol-series/ham-style-coupling-center-members-inserts-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/oldham-style-motion-control-couplings-mol-series/set-screw-style-coupling-hubs-w-o-keyway-imperi-2?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/oldham-style-motion-control-couplings-mol-series/am-set-screw-style-coupling-hubs-w-o-keyway-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/oldham-style-motion-control-couplings-mol-series/dham-clamp-style-coupling-hubs-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/oldham-style-motion-control-couplings-mol-series/oldham-clamp-style-coupling-hubs-w-o-keyway-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/deltaflex-couplings/es-flex-link-coupling-delta-hubs-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/deltaflex-couplings/ries-flex-link-coupling-delta-hubs-w-keyway-metric/68514476482?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/deltaflex-couplings/-flex-link-coupling-delta-hubs-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/deltaflex-couplings/es-flex-link-coupling-round-hubs-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/deltaflex-couplings/-flex-link-coupling-round-hubs-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/deltaflex-couplings/deltaflex-series-inner-flange-w-hardware-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/deltaflex-couplings/deltaflex-series-outer-flanges-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/deltaflex-couplings/nk-coupling-delta-hubs-type-3-spacer-type-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/deltaflex-couplings/ing-delta-hubs-type-4-floating-shaft-type-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/deltaflex-couplings/taflex-series-flex-link-coupling-hardware-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/deltaflex-couplings/pling-hardware-type-4-floating-shaft-type-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/deltaflex-couplings/deltaflex?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/uniflex-couplings/ular-version-shaft-to-shaft-configuration-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/uniflex-couplings/egular-version-shaft-to-shaft-configuration-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/uniflex-couplings/hort-version-shaft-to-shaft-configuration-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/uniflex-couplings/-short-version-shaft-to-shaft-configuration-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/uniflex-couplings/ular-version-shaft-to-shaft-configuration-imperi-2?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/uniflex-couplings/hort-version-shaft-to-shaft-configuration-imperi-2?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/uniflex-couplings/lex-coupling-hubs-w-keyway-drop-out-style-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/uniflex-couplings/x-coupling-hubs-w-o-keyway-drop-out-style-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/uniflex-couplings/ng-hubs-w-rough-stock-bore-drop-out-style-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/uniflex-couplings/ckage-of-rru-type-uniflex-coupling-hardware-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/uniflex-couplings/pling-hubs-flange-to-flange-configuration-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/uniflex-couplings/lar-version-flange-to-shaft-configuration-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/uniflex-couplings/ort-version-flange-to-shaft-configuration-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/uniflex-couplings/lar-version-flange-to-shaft-configuration-imperi-2?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/saga-couplings/eral-purpose-couplings-w-rough-stock-bore-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/saga-couplings/-purpose-coupling-hubs-w-rough-stock-bore-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/saga-couplings/eneral-purpose-coupling-donuts-w-hardware-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/saga-couplings/ga-general-purpose-coupling-bolts-washers-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/rigid-sleeve-couplings/rigid-sleeve-couplings-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/rigid-sleeve-couplings/rigid-sleeve-couplings-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/shaft-collars/zinc-plated-steel-shaft-collars-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/shaft-collars/stainless-steel-shaft-collars-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/shaft-collars/one-piece-split-shaft-collars-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/shaft-collars/two-piece-split-shaft-collars-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/econoline-series-variable-speed-drives/ies-variable-speed-drive-pulleys-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/econoline-series-variable-speed-drives/s-variable-speed-drive-pulleys-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/econoline-series-variable-speed-drives/e-series-m-type-manual-pulleys-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/econoline-series-variable-speed-drives/ine-series-m-type-manual-pulleys-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/econoline-series-variable-speed-drives/e-series-mla-type-manual-pulleys-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/econoline-series-variable-speed-drives/series-mla-type-manual-pulleys-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/econoline-series-variable-speed-drives/ble-variable-speed-drive-pulleys-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/econoline-series-variable-speed-drives/econoline-series-variable-speed-drives---pulleys?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/aluminoline-series-variable-speed-drives/model-145-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/aluminoline-series-variable-speed-drives/model-160-hd-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/aluminoline-series-variable-speed-drives/model-170-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/aluminoline-series-variable-speed-drives/model-175-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/aluminoline-series-variable-speed-drives/model-180-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/model-301e-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/model-3030e-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/model-303e-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/model-401e-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/model-402e-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/model-403e-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/model-3050e-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/model-m1-adjustable-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/301c-spring-loaded-driven-pulleys-c-mount-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/301d-spring-loaded-driven-pulleys-z-mount-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/model-m-14-adjustable-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/1401-spring-loaded-driven-pulleys-c-mount-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/model-m-19-adjustable-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/model-1902-spring-loaded-driven-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/1903-spring-loaded-driven-pulleys-c-mount-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/model-m-23-adjustable-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/model-2303-spring-loaded-driven-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/2305-spring-loaded-driven-pulleys-c-mount-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/model-m-3-adjustable-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/030c-spring-loaded-driven-pulleys-c-mount-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/030d-spring-loaded-driven-pulleys-z-mount-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/exact-electric-control-adjustable-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/model-3075b-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/model-3100b-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/model-3150b-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/model-245-spring-loaded-driven-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/model-260-spring-loaded-driven-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/wb-series-variable-speed-drives/model-m-007-adjustable-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hi-ratio-series-variable-speed-drives/model-m-14-adjustable-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hi-ratio-series-variable-speed-drives/model-m-19-adjustable-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hi-ratio-series-variable-speed-drives/model-m-23-adjustable-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hi-ratio-series-variable-speed-drives/1401-spring-loaded-driven-pulleys-c-mount-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hi-ratio-series-variable-speed-drives/model-1902-spring-loaded-driven-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hi-ratio-series-variable-speed-drives/1903-spring-loaded-driven-pulleys-c-mount-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hi-ratio-series-variable-speed-drives/model-2303-spring-loaded-driven-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hi-ratio-series-variable-speed-drives/2305-spring-loaded-driven-pulleys-c-mount-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/adjustable-motor-bases/sliding-cast-iron-motor-bases-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/adjustable-motor-bases/sliding-smb-type-motor-bases-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/adjustable-motor-bases/sliding-dovetail-type-motor-bases-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/adjustable-motor-bases/tilting-type-motor-bases-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/adjustable-motor-bases/model-76-control-stand-imperial/68514420021-2?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/adjustable-motor-bases/motorized-torque-arm-imperial/68514443982-2?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/adjustable-motor-bases/501-torque-arm-bracket-imperial/68514419952-2?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/companion-sheaves/grooved-companion-sheaves-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hexadrive-variable-speed-drives/model-m-007-adjustable-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/horizontal-split-cover-grid-couplings/ents-cover-grid-assembly-horizontal-style-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/horizontal-split-cover-grid-couplings/onents-cover-grid-assembly-horizontal-style-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/horizontal-split-cover-grid-couplings/apered-components-seal-kit-horizontal-style-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/horizontal-split-cover-grid-couplings/ts-hub-pilot-w-puller-hole-horizontal-style-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/horizontal-split-cover-grid-couplings/ents-cover-grid-assembly-horizontal-style-imperi-2?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/horizontal-split-cover-grid-couplings/onents-cover-grid-assembly-horizontal-style-metr-2?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/horizontal-split-cover-grid-couplings/raight-components-seal-kit-horizontal-style-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/horizontal-split-cover-grid-couplings/tapered-components-cover-horizontal-style-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/horizontal-split-cover-grid-couplings/g-tapered-components-cover-horizontal-style-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/horizontal-split-cover-grid-couplings/omponents-cover-hardware-horizontal-style-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/horizontal-split-cover-grid-couplings/-components-cover-hardware-horizontal-style-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/horizontal-split-cover-grid-couplings/traight-components-cover-horizontal-style-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/horizontal-split-cover-grid-couplings/-straight-components-cover-horizontal-style-metric/69790410951?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/horizontal-split-cover-grid-couplings/omponents-cover-hardware-horizontal-style-imperi-2/69790410558?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/horizontal-split-cover-grid-couplings/-components-cover-hardware-horizontal-style-metr-2/69790499271?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/horizontal-split-cover-grid-couplings/grid-coupling-cover-set-horizontal-style-metric/69790410949?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/horizontal-split-cover-grid-couplings/s-inch-bore-keyway-horizontal-vertical-cover-style?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/horizontal-split-cover-grid-couplings/grid-coupling-hubs-metric-bore-keyway?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/horizontal-split-cover-grid-couplings/grid-coupling-taper-lock-bushing-hubs-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/horizontal-split-cover-grid-couplings/grid-coupling-shaft-hubs?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/horizontal-split-cover-grid-couplings/grid-coupling-hubs-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/horizontal-split-cover-grid-couplings/grid-coupling-hubs-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/horizontal-split-cover-grid-couplings/grid-coupling-tapered-components-grid-only-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/horizontal-split-cover-grid-couplings/grid-coupling-straight-components-grid-only-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/horizontal-split-cover-grid-couplings/hub-pilot-w-rough-stock-bore-puller-hole-metric/69790410952?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/horizontal-split-cover-grid-couplings/spacer-hub-hardware-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/vertical-split-cover-grid-couplings/-tapered-components-seal-kit-vertical-style-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/vertical-split-cover-grid-couplings/onents-cover-grid-assembly-vertical-style-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/vertical-split-cover-grid-couplings/mponents-cover-grid-assembly-vertical-style-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/vertical-split-cover-grid-couplings/g-tapered-components-cover-vertical-style-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/vertical-split-cover-grid-couplings/ing-tapered-components-cover-vertical-style-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/vertical-split-cover-grid-couplings/-components-cover-hardware-vertical-style-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/vertical-split-cover-grid-couplings/ed-components-cover-hardware-vertical-style-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/vertical-split-cover-grid-couplings/s-inch-bore-keyway-horizontal-vertical-cover-style?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/vertical-split-cover-grid-couplings/grid-coupling-hubs-metric-bore-keyway?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/vertical-split-cover-grid-couplings/grid-coupling-taper-lock-bushing-hubs-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/vertical-split-cover-grid-couplings/grid-coupling-shaft-hubs?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/vertical-split-cover-grid-couplings/grid-coupling-hubs-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/vertical-split-cover-grid-couplings/grid-coupling-hubs-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/vertical-split-cover-grid-couplings/grid-coupling-tapered-components-grid-only-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/vertical-split-cover-grid-couplings/grid-coupling-straight-components-grid-only-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/vertical-split-cover-grid-couplings/hub-pilot-w-rough-stock-bore-puller-hole-metric/69790410952?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/vertical-split-cover-grid-couplings/spacer-hub-hardware-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-tensioner-devices/runright-tensioners-rt-inch?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-tensioner-devices/runright-tensioners-rt-f?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-tensioner-devices/runright-inch-imperial-sprockets?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-tensioner-devices/runright-metric-tensioners-type-rt-rtn-rth-rtr?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-tensioner-devices/runright-metric-tensioners-rt-ss-stainless-steel?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-tensioner-devices/runright-metric-tensioners-type-rt-f?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-tensioner-devices/runright-tensioners-rt-b?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-tensioner-devices/runright-metric-sprockets?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-tensioner-devices/runright-chain-rider-sets?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-tensioner-devices/runright-chain-riders?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-tensioner-devices/runright-tensioning-rollers?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-tensioner-devices/runright-steel-idler-pulley?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-tensioner-devices/runright-rlb-bracket?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-tensioner-devices/runright-safety-socket?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-tensioner-devices/runright-tensioners-type-rt-t?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-tensioner-devices/runright-tensioners-type-rt-p?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-tensioner-devices/runright-tensioners-type-rt-m?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-motorbases/runright-tensioning-motorbases?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-oscillating-mountings/runright-units-rsc?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-oscillating-mountings/runright-units-rsc50?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-oscillating-mountings/runright-units-rsc-hd?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-oscillating-mountings/runright-units-rsc-d?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-oscillating-mountings/runright-units-rsc-ss?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-oscillating-mountings/runright-units-hs?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-oscillating-mountings/runright-units-rsc-r?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-oscillating-mountings/runright-units-rdh?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-oscillating-mountings/runright-units-rsd-a?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-oscillating-mountings/runright-units-rsc-v?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-oscillating-mountings/runright-units-rsc-uj?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-rubber-suspension-units/runright-units-rss?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-rubber-suspension-units/runright-units-rss-c?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-rubber-suspension-units/runright-units-rss-s?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-rubber-suspension-units/runright-units-rbs-clamp?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-rubber-suspension-units/runright-units-rsr?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-rubber-suspension-units/runright-units-rsr-s?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-rubber-suspension-units/runright-units-rbr-clamp?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-rubber-suspension-units/runright-units-rsf-a?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-rubber-suspension-units/runright-units-rsf-c?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-rubber-suspension-units/runright-units-rsd-a?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-rubber-suspension-units/runright-rlb-bracket?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-anti-vibration-mountings/runright-rav-d-anti-vibrating-mount?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/runright-anti-vibration-mountings/runright-v-anti-vibrating-mount?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/industrial-disc-couplings-su-type/disc-pack-kits-standard?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/industrial-disc-couplings-su-type/high-speed-disc-pack-kits-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/industrial-disc-couplings-su-type/overload-disc-pack-kits?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/industrial-disc-couplings-su-type/e-industrial-couplings-w-rough-stock-bore?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/industrial-disc-couplings-su-type/su-6-type-industrial-couplings-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/industrial-disc-couplings-su-type/su-6-type-industrial-coupling-w-keyway-inch-metric/69790497860?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/industrial-disc-couplings-su-type/su-6-type-industrial-coupling-hubs-w-keyway-metric/69790499337?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/industrial-disc-couplings-sx-type/disc-pack-kits-standard?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/industrial-disc-couplings-sx-type/high-speed-disc-pack-kits-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/industrial-disc-couplings-sx-type/overload-disc-pack-kits?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/industrial-disc-couplings-sx-type/dustrial-coupling-hubs-w-rough-stock-bore-imperi-2?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/industrial-disc-couplings-sx-type/-6-type-industrial-coupling-hubs-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/industrial-disc-couplings-sx-type/ndustrial-coupling-hubs-w-extra-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/industrial-disc-couplings-sx-type/-type-industrial-coupling-hubs-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/industrial-disc-couplings-sx-type/sx-6-type-industrial-coupling-hubs-w-keyway-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/industrial-disc-couplings-sx-type/sx-6-type-industrial-coupling-hubs-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/industrial-disc-couplings-sx-type/sx-6-type-industrial-couplings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/industrial-disc-couplings-sx-type/e-industrial-couplings-w-rough-stock-bore-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/close-coupled-industrial-disc-couplings-sxc-type/dustrial-coupling-hubs-w-rough-stock-bore-imperi-3?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/close-coupled-industrial-disc-couplings-sxc-type/coupled-industrial-coupling-hubs-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/close-coupled-industrial-disc-couplings-sxc-type/d-coupled-industrial-coupling-hubs-w-keyway-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/close-coupled-industrial-disc-couplings-sxc-type/disc-pack-kits-standard?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/close-coupled-industrial-disc-couplings-sxc-type/high-speed-disc-pack-kits-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/close-coupled-industrial-disc-couplings-sxc-type/overload-disc-pack-kits?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/drop-in-spacer-disc-couplings-di-type/-in-center-industrial-coupling-sub-assembly-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/drop-in-spacer-disc-couplings-di-type/dustrial-coupling-hubs-w-rough-stock-bore-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/drop-in-spacer-disc-couplings-di-type/-in-center-industrial-coupling-jumbo-hubs-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/drop-in-spacer-disc-couplings-di-type/-center-industrial-coupling-hubs-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/drop-in-spacer-disc-couplings-di-type/ype-drop-in-center-industrial-coupling-hubs-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/drop-in-spacer-disc-couplings-di-type/r-industrial-couplings-w-rough-stock-bore-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/drop-in-spacer-disc-couplings-di-type/drop-in-center-industrial-jumbo-couplings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/drop-in-spacer-disc-couplings-di-type/-type-drop-in-center-industrial-couplings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/drop-in-spacer-disc-couplings-di-type/i-6-type-drop-in-center-industrial-coupling-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/drop-in-spacer-disc-couplings-di-type/-6-type-drop-in-center-industrial-couplings-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/drop-in-spacer-disc-couplings-di-type/-industrial-coupling-standard-hub-bolt-kits-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/drop-in-spacer-disc-couplings-di-type/ter-industrial-coupling-jumbo-hub-bolt-kits-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/drop-in-spacer-disc-couplings-di-type/disc-pack-kits-standard?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/drop-in-spacer-disc-couplings-di-type/high-speed-disc-pack-kits-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/drop-in-spacer-disc-couplings-di-type/overload-disc-pack-kits?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/sxcs-type-close-coupled-spilt-spacer/sxcs-6-type-hubs-with-keyway-inch-imperial-bores?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/sxcs-type-close-coupled-spilt-spacer/sxcs-6-type-hubs-with-keyway-metric-bores?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/d-type-universal-joints/universal-solid-joints-w-pin-block-design?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/d-type-universal-joints/universal-bored-joints-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/d-type-universal-joints/universal-bored-joints-w-keyway-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/d-type-universal-joints/universal-bored-joints-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/d-type-universal-joints/universal-bored-joints-mixed?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/d-type-universal-joints/repair-kits-for-d-type-universal-joints-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/d-type-universal-joints/set-of-d-hd-type-rivet-pins-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hd-type-universal-joints/hd-type-universal-solid-joints-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hd-type-universal-joints/hd-type-universal-bored-joints-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hd-type-universal-joints/hd-type-universal-bored-joints-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hd-type-universal-joints/hd-type-universal-bored-joints-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hd-type-universal-joints/set-of-d-hd-type-rivet-pins-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/d303-stainless-steel-universal-joints/03-stainless-steel-universal-solid-joints-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/d303-stainless-steel-universal-joints/stainless-steel-universal-joints-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/d303-stainless-steel-universal-joints/ainless-steel-universal-joints-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/needle-bearing-type-universal-joints/eedle-bearing-type-universal-solid-joints-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/needle-bearing-type-universal-joints/ring-type-universal-bored-joints-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/needle-bearing-type-universal-joints/ng-type-universal-bored-joints-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/loj-jr-4-types-universal-joints/jr-4-type-universal-joints-w-o-keyway-imperial/68514417332?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/loj-jr-4-types-universal-joints/loj-type-universal-solid-joints-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/loj-jr-4-types-universal-joints/loj-type-universal-bored-joints-w-keyway-imperial/68514476290?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/loj-jr-4-types-universal-joints/oj-type-universal-bored-joints-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/dd-ddx-types-universal-joints/l-solid-joints-w-double-joint-arrangement-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/dd-ddx-types-universal-joints/nts-w-double-joint-arrangement-w-o-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/dd-ddx-types-universal-joints/dd-universal-joints-special?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/dd-ddx-types-universal-joints/oints-w-double-joint-arrangement-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/dd-ddx-types-universal-joints/al-joints-ddx-no-boots-inch-imperial-bores?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/1-side-movable-flange-variable-speed-pulleys/model-11401-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/1-side-movable-flange-variable-speed-pulleys/model-11407-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/1-side-movable-flange-variable-speed-pulleys/model-11901-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/1-side-movable-flange-variable-speed-pulleys/model-11902-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/1-side-movable-flange-variable-speed-pulleys/model-11903-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/1-side-movable-flange-variable-speed-pulleys/model-12904-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/1-side-movable-flange-variable-speed-pulleys/model-12905-spring-loaded-driver-pulleys?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/1-side-movable-flange-variable-speed-pulleys/model-12907-spring-loaded-driver-pulleys?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/1-side-movable-flange-variable-speed-pulleys/model-12908-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/1-side-movable-flange-variable-speed-pulleys/model-13207-spring-loaded-driver-pulleys?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/1-side-movable-flange-variable-speed-pulleys/model-13210-spring-loaded-driver-pulleys?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/1-side-movable-flange-variable-speed-pulleys/model-13220-spring-loaded-driver-pulleys?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/1-side-movable-flange-variable-speed-pulleys/model-13230-spring-loaded-driver-pulleys?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/1-side-movable-flange-variable-speed-pulleys/model-14407-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/1-side-movable-flange-variable-speed-pulleys/model-14410-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/1-side-movable-flange-variable-speed-pulleys/model-14420-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/1-side-movable-flange-variable-speed-pulleys/model-14430-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/1-side-movable-flange-variable-speed-pulleys/model-14433-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/1-side-movable-flange-variable-speed-pulleys/variable-speed-drives---pulleys---imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-21401-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-21407-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-21901-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-21902-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-21903-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-22904-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-22905-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-22907-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-22908-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-23207-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-23210-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-23220-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-23230-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-24407-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-24410-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-24420-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-24430-spring-loaded-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-24433-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-31901-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-31902-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-31903-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-32904-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-32905-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-32907-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-34407-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-34410-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-34420-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/2-side-movable-flange-variable-speed-pulleys/model-34430-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hexact-electric-control-method/ustable-pulleys-w-electric-control-option-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hexact-electric-control-method/ustable-pulleys-w-electric-control-option-imperi-2?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hexact-electric-control-method/ustable-pulleys-w-electric-control-option-imperi-3?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hexact-linear-actuation-method/-pulleys-w-hexact-linear-actuation-method-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hexact-linear-actuation-method/-pulleys-w-hexact-linear-actuation-method-imperi-2?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hexact-linear-actuation-method/-pulleys-w-hexact-linear-actuation-method-imperi-3?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/manuel-adjustable-driver-pulley/model-hm-3-adjustable-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/manuel-adjustable-driver-pulley/model-hm-30-adjustable-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/manuel-adjustable-driver-pulley/model-hm-7-adjustable-driver-pulleys-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hydraulic-pump-motor-mounts-bellhousings/p-motor-mounts-w-vertical-mounting-option-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hydraulic-pump-motor-mounts-bellhousings/ump-motor-mounts-w-vertical-mounting-option-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hydraulic-pump-motor-mounts-bellhousings/hydraulics-horizontal-pump-motor-mounts-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hydraulic-pump-motor-mounts-bellhousings/hydraulics-horizontal-pump-motor-mounts-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hydraulic-pump-motor-mounts-bellhousings/hydraulics-vertical-pump-motor-mounts-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hydraulic-pump-motor-mounts-bellhousings/hydraulics-vertical-pump-motor-mounts-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hydraulic-pump-motor-mounts-bellhousings/vertical-mount-gaskets-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/bnz-series-water-oil-coolers/1-pass-model-oil-coolers-bnz-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/bnz-series-water-oil-coolers/2-pass-model-oil-coolers-bnz-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/bnz-series-water-oil-coolers/4-pass-model-oil-coolers-bnz-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/reservoirs-accessories/hydraulic-aluminum-reservoirs-w-plug-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/reservoirs-accessories/steel-tank-lids-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/reservoirs-accessories/steel-lid-seal-kits-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/reservoirs-accessories/tank-lid-seals-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/reservoirs-accessories/enviro-seal-kits-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/reservoirs-accessories/enviro-tank-lid-seals-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/reservoirs-accessories/filler-breathers-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/reservoirs-accessories/oil-level-gauges-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/reservoirs-accessories/oil-level-sights-oil-eye-sights-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/reservoirs-accessories/leg-kits-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/reservoirs-accessories/tank-legs-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/reservoirs-accessories/caster-kits-w-2-casters-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/reservoirs-accessories/tank-casters-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/reservoirs-accessories/elastic-bushings-w-imperial-tubing?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/reservoirs-accessories/elastic-bushings-w-imperial-pipe?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/reservoirs-accessories/elastic-bushings-w-metric-tubing?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/standard-curved-jaw-couplings-cj-type/curved-jaw-coupling-spiders-cj-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/standard-curved-jaw-couplings-cj-type/metal-curved-jaw-coupling-hubs-cj-series-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/standard-curved-jaw-couplings-cj-type/er-metal-curved-jaw-coupling-hubs-cj-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/standard-curved-jaw-couplings-cj-type/powder-metal-curved-jaw-couplings-cj-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/standard-curved-jaw-couplings-cj-type/t-iron-curved-jaw-coupling-hubs-cj-series-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/standard-curved-jaw-couplings-cj-type/cast-iron-curved-jaw-couplings-cj-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/standard-curved-jaw-couplings-cj-type/steel-curved-jaw-coupling-hubs-cj-series-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/standard-curved-jaw-couplings-cj-type/steel-curved-jaw-coupling-hubs-cj-series-metric/68514476181?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/standard-curved-jaw-couplings-cj-type/lar-iron-curved-jaw-coupling-hubs-cj-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/standard-curved-jaw-couplings-cj-type/aluminum-curved-jaw-couplings-cj-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/standard-curved-jaw-couplings-cj-type/curved-jaw-couplings-cj-series_unknown?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/standard-curved-jaw-couplings-gs-type/curved-jaw-coupling-spiders-gs-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/standard-curved-jaw-couplings-gs-type/uminum-curved-jaw-coupling-hubs-gs-series-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/standard-curved-jaw-couplings-gs-type/uminum-curved-jaw-coupling-hubs-gs-series-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hercuflex-flanged-style-gear-couplings/hercuflex-standard-hubs-with-keyway-inch-imperial-?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hercuflex-flanged-style-gear-couplings/hercuflex-standard-hubs-with-keyway-metric-bore?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hercuflex-flanged-style-gear-couplings/hercuflex-fx-flange-type-sleeves?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hercuflex-flanged-style-gear-couplings/accessory-kits-for-lovejoy-flanged-hercuflex-gear-?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hercuflex-flanged-style-gear-couplings/hercuflex-fx-rigid-hubs-with-keyway-inch-imperial-?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hercuflex-flanged-style-gear-couplings/hercuflex-fx-rigid-hubs-with-keyway-metric-bore?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hercuflex-flanged-style-gear-couplings/hercuflex-fcxmm-universal-mill-motor-hubs-with-key?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hercuflex-flanged-style-gear-couplings/hercuflex-fxlmm-universal-mill-motor-hubs-with-key?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hercuflex-flanged-style-gear-couplings/hercuflex-fxl-hubs-with-keyway-inch-imperial-bore?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hercuflex-flanged-style-gear-couplings/hercuflex-fxl-hubs-with-keyway-metric-bore?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hercuflex-flanged-style-gear-couplings/hercuflex-fxl-flange-type-sleeves?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hercuflex-continuous-style-gear-couplings/hercuflex-standard-hubs-with-keyway-inch-imperial-?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hercuflex-continuous-style-gear-couplings/hercuflex-standard-hubs-with-keyway-metric-bore?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hercuflex-continuous-style-gear-couplings/hercuflex-cx-continuous-coupling-sleeves-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hercuflex-continuous-style-gear-couplings/accessory-kits-for-lovejoy-continuous-sleeve-hercu?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/hercuflex-continuous-style-gear-couplings/hercuflex-fcxmm-universal-mill-motor-hubs-with-key?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/grease-can-w-material-safety-data-sheet-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/flanged-couplings-accessory-kit-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/alloy-steel-flanged-gaskets-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/f-type-universal-hubs-w-rough-stock-bore-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/f-type-universal-hubs-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/f-type-universal-hubs-w-keyway-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/f-type-sleeves-w-o-ring-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/f-type-o-rings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/f-type-universal-rigid-hubs-w-center-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/f-type-universal-rigid-hubs-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/f-type-universal-rigid-hubs-w-keyway-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/pe-mill-universal-hubs-w-rough-stock-bore-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/fmm-type-mill-motor-universal-hubs-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/flanged-sleeve-gear-type-couplings/fmm-type-mill-universal-hubs-w-keyway-imperial/69790411805?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/fspcr-type-spacer-couplings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/lex-flex-coupling-hubs-w-rough-stock-bore-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/oy-steel-flex-flex-coupling-hubs-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/y-steel-flex-flex-coupling-sleeves-w-seal-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/loy-steel-flex-flex-coupling-molded-seals-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/amm-type-coupling-hubs-w-rough-stock-bore-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/nth-seal-coupling-hubs-w-rough-stock-bore-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/tal-labyrinth-seal-coupling-hubs-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/all-metal-labyrinth-seal-coupling-sleeves-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/ll-motor-coupling-hubs-w-rough-stock-bore-imperi-2?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/-type-flex-rigid-mill-motor-coupling-hubs-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/flanged-sleeve-gear-type-couplings/fshp-shear-pin-set-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/flanged-sleeve-gear-type-couplings/-hub-w-keyway-w-puller-hole-accessory-kit-imperial/69790411683?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/continuous-sleeve-gear-type-couplings/grease-can-w-material-safety-data-sheet-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/continuous-sleeve-gear-type-couplings/c-type-universal-accessory-kits-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/continuous-sleeve-gear-type-couplings/c-type-universal-seals-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/continuous-sleeve-gear-type-couplings/c-type-universal-lock-rings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/continuous-sleeve-gear-type-couplings/c-type-universal-coupling-sleeves-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/continuous-sleeve-gear-type-couplings/c-type-universal-hubs-w-rough-stock-bore-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/continuous-sleeve-gear-type-couplings/c-type-universal-hubs-w-center-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/continuous-sleeve-gear-type-couplings/c-type-universal-hubs-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/continuous-sleeve-gear-type-couplings/c-type-universal-hubs-w-keyway-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/continuous-sleeve-gear-type-couplings/e-universal-rigid-hubs-w-rough-stock-bore-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/continuous-sleeve-gear-type-couplings/c-type-universal-rigid-hubs-w-center-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/continuous-sleeve-gear-type-couplings/c-type-universal-rigid-hubs-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/continuous-sleeve-gear-type-couplings/c-type-universal-rigid-hubs-w-keyway-metric/69790411444?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/continuous-sleeve-gear-type-couplings/c-type-universal-hubs-w-o-keyway-w-lock-imperial/69790411830?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/continuous-sleeve-gear-type-couplings/ll-motor-coupling-hubs-w-rough-stock-bore-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/continuous-sleeve-gear-type-couplings/mm-type-mill-motor-coupling-hubs-w-center-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/continuous-sleeve-gear-type-couplings/type-mill-motor-coupling-hubs-motor-frame-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/continuous-sleeve-gear-type-couplings/mm-type-mill-motor-coupling-hubs-w-keyway-imperial/69790411709?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/continuous-sleeve-gear-type-couplings/ccs-type-cut-out-shifter-coupling-hubs-imperial/69790412062?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/continuous-sleeve-gear-type-couplings/cv-type-hubs-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/continuous-sleeve-gear-type-couplings/cfr-type-flex-rigid-couplings/69790411566?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/nylon-sleeve-gear-type-couplings/mite-type-coupling-hubs-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/nylon-sleeve-gear-type-couplings/nyflex-type-coupling-hubs-w-keyway-metric/69790411575?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/nylon-sleeve-gear-type-couplings/nyflex-type-coupling-hubs-w-keyway-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/nylon-sleeve-gear-type-couplings/ite-type-coupling-hubs-w-rough-stock-bore-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/nylon-sleeve-gear-type-couplings/lex-type-coupling-hubs-w-rough-stock-bore-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/nylon-sleeve-gear-type-couplings/nyflex-type-coupling-sleeves-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/nylon-sleeve-gear-type-couplings/mite-type-coupling-sleeves-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/nylon-sleeve-gear-type-couplings/mite-type-couplings-accessory-kit-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/nylon-sleeve-gear-type-couplings/nyflex-type-couplings-accessory-kit-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/yle-coupling-hubs-w-horizontal-split-covers-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/spacer-hub-hardware-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/s-inch-bore-keyway-horizontal-vertical-cover-style?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/grid-coupling-hubs-metric-bore-keyway?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/grid-coupling-taper-lock-bushing-hubs-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/grid-coupling-shaft-hubs?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/grid-coupling-hubs-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/grid-coupling-hubs-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/apered-components-seal-kit-horizontal-style-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/-tapered-components-seal-kit-vertical-style-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/tapered-components-cover-horizontal-style-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/g-tapered-components-cover-vertical-style-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/g-tapered-components-cover-horizontal-style-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/ing-tapered-components-cover-vertical-style-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/ents-cover-grid-assembly-horizontal-style-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/onents-cover-grid-assembly-vertical-style-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/onents-cover-grid-assembly-horizontal-style-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/mponents-cover-grid-assembly-vertical-style-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/grid-coupling-tapered-components-grid-only-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/omponents-cover-hardware-horizontal-style-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/-components-cover-hardware-vertical-style-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/-components-cover-hardware-horizontal-style-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/ed-components-cover-hardware-vertical-style-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/ts-hub-pilot-w-puller-hole-horizontal-style-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/ents-cover-grid-assembly-horizontal-style-imperi-2?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/onents-cover-grid-assembly-horizontal-style-metr-2?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/traight-components-cover-horizontal-style-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/spacer-style-grid-couplings/-straight-components-cover-horizontal-style-metric/69790410951?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/raight-components-seal-kit-horizontal-style-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/spacer-style-grid-couplings/omponents-cover-hardware-horizontal-style-imperi-2/69790410558?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/spacer-style-grid-couplings/-components-cover-hardware-horizontal-style-metr-2/69790499271?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/spacer-style-grid-couplings/grid-coupling-straight-components-grid-only-metric?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/spacer-style-grid-couplings/grid-coupling-cover-set-horizontal-style-metric/69790410949?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/item/spacer-style-grid-couplings/hub-pilot-w-rough-stock-bore-puller-hole-metric/69790410952?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/mini-disc-style-couplings-md-mds-mdsd-series/md-series-mini-disc-clamp-style-couplings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/mini-disc-style-couplings-md-mds-mdsd-series/es-mini-disc-spacer-clamp-style-couplings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/mini-disc-style-couplings-md-mds-mdsd-series/ni-disc-single-disc-clamp-style-couplings-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/universal-joint-boots/set-of-d-type-upper-boots-ties-imperial?plpver=1013&pcat=lovejoy',
    'https://cad.timken.com/viewitems/universal-joint-boots/set-of-d-type-lower-boots-ties-imperial?plpver=1013&pcat=lovejoy',

    # 'https://cad.timken.com/viewitems/hydraulic-components/lh-type-hydraulic-couplings?plpver=1013&pcat=lovejoy',

]

for url in Result:
    L = L + 1
    r = requests.get(url, headers=headers)
    # print(soup.prettify())?page=
    driver.get(url)
    time.sleep(5)
    print("Products Urls", L, url)
    data_urls = ''
    url_links = ''
    try:
        links = driver.find_element(By.XPATH, "//div[@class='ui-corner-all ui-widget-content plp-table-wrapper']").find_elements(By.TAG_NAME, 'a')
        print("Lenght", len(links))
        for x in links:
            url_links = (x.get_attribute('href'))
            data_urls = url_links
            print(data_urls)
            save_details: url_links = open("LoveJoy_urls.xlsx", "a+", encoding="utf-8")
            save_details.write("\n" + "'" + data_urls + "',")
            save_details.close()
        print("\n ***** Record stored into urls  files. *****")
    except:
        save_details: url_links = open("remaining_urls.xlsx", "a+", encoding="utf-8")
        save_details.write("\n" + "'"+url+"',")
        save_details.close()
    print("\n ***** Record stored into urls  files. *****")

    # clk = driver.find_element(By.CLASS_NAME, "plp-pageRange").find_elements(By.TAG_NAME, "option")
    # for x in clk:
    #     if '200' in x.text:
    #         x.click()
    #         time.sleep(5)
    #     else:
    #         pass
    try:
        l = driver.find_element(By.ID, "pageInfo")
        cnt = l.text.split()[-1]
        print("count..", cnt)
        length = round(int(cnt) / 25)
        print("Loop..", length)

        for i in range(1, length+1):
            driver.find_element(By.XPATH, '//body[1]/div[1]/main[1]/div[1]/div[1]/div[7]/div[1]/div[1]/div[2]/a['+str(i)+']').click()
            time.sleep(5)
            links = driver.find_element(By.XPATH, "//div[@class='ui-corner-all ui-widget-content plp-table-wrapper']").find_elements(By.TAG_NAME, 'a')
            print("links", len(links))
            for x in links:
                url_links = (x.get_attribute('href'))
                print(url_links)
                data_urls = url_links
                print(data_urls)
                save_details: url_links = open("LoveJoy_urls.xlsx", "a+", encoding="utf-8")
                save_details.write("\n" + "'" + data_urls + "',")
                save_details.close()
            print("\n ***** Record stored into urls  files. *****")
            print(i)
    except:
        # save_details: url_links = open("remaining_urls.xlsx", "a+", encoding="utf-8")
        # save_details.write("\n" + "'" + url + "',")
        # save_details.close()
        # print("\n ***** Record stored into urls  files. *****")
        print("Not Found click")
