import requests
from bs4 import BeautifulSoup
from selenium.webdriver.common.by import By
import time
from typing import TextIO
from selenium.webdriver.chrome.options import Options
from selenium import webdriver


opts = Options()
opts.headless = False
opts.add_argument(
    "--user-agent=" + "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.2.8) Gecko/20100722 Firefox/3.6.8 GTB7.1 (.NET CLR 3.5.30729)")
driver = webdriver.Chrome("/home/tajender/Downloads/chromedriver",chrome_options=opts)
l=[
'https://mayhew.com/products/displays/pocket-magnet-inspection-tools-display',
'https://mayhew.com/products/punches-chisels/punches_and_chisels_handguarded__handguarded_cold_chisels',
'https://mayhew.com/products/punches-chisels/punches_and_chisels_punch_sets__punch_mix?body_type=0&size=0&weight_capacity=0&tool_oal=0&cut_width=0&body_width=0&blade_size=0&blade_width=0&blade_length=0&taper_length=0&taper_width=0&pin_width=0&pin_length=0&point_width=0&point_size=0&finish_type=1960&prod_length=2054&prod_width=2595&prod_height=2325&num_products_in_set=3834',
'https://mayhew.com/news/news-full-article/mayhew-extends-hammerless-tools-products-line-with-addition-of-new-2-pc-nail-starter-and-nail-set',
'https://mayhew.com/news/news-full-article/mayhew-steel-products-expands-with-a-new-injection-molding-and-manufacturing-company',
'https://mayhew.com/products/demo-tools',
'https://mayhew.com/products/displays',
'https://mayhew.com/products/displays/12-punch-chisel-rack-carded-displays',
'https://mayhew.com/products/displays/24-punch-chisel-rack-carded-displays',
'https://mayhew.com/products/displays/deck-wrecker-bulk-display',
'https://mayhew.com/products/displays/dominator-r-big-bar-rack',
'https://mayhew.com/products/displays/full-masonry-builders-carded-display',
'https://mayhew.com/products/displays/full-masonry-builders-carded-displays',
'https://mayhew.com/products/displays/inspection-tools-bulk-display',
'https://mayhew.com/products/displays/masonry-display',
'https://mayhew.com/products/displays/pilot-punch-display',
'https://mayhew.com/products/displays/pneumatic-display-block',
'https://mayhew.com/products/displays/pocket-magnet-inspection-tools-display',
'https://mayhew.com/products/displays/pro-punch-chisel-displays',
'https://mayhew.com/products/displays/punch-chisel-displays',
'https://mayhew.com/products/displays/screw-extractor-display',
'https://mayhew.com/products/dual-drives-bits',
'https://mayhew.com/products/handguarded-masonry/brass-scraperers',
'https://mayhew.com/products/handguarded-masonry/dominator-r-angled-scraper-set',
'https://mayhew.com/products/handguarded-masonry/dominator-r-weld-wakker-scraper-set',
'https://mayhew.com/products/handguarded-masonry/progrip-straight-angled-scraper-set',
'https://mayhew.com/products/handguarded-masonry/progrip-wide-stubby-scraper',
'https://mayhew.com/products/handguarded-masonry/progrip-wide-scrapers',
'https://mayhew.com/products/handguarded-masonry/progrip-angled-scrapers',
'https://mayhew.com/products/handguarded-masonry/progrip-carbon-scrapers',
'https://mayhew.com/products/hooks-picks',
'https://mayhew.com/products/hooks-picks/hook-and-pick-sets',
'https://mayhew.com/products/hooks-picks/hose-picks',
'https://mayhew.com/products/hooks-picks/marking-and-hole-making-picks',
'https://mayhew.com/products/hooks-picks/o-ring-picks',
'https://mayhew.com/products/hooks-picks/picks',
'https://mayhew.com/products/hooks-picks/trim-tool-sets',
'https://mayhew.com/products/hooks-picks/trim-tools',
'https://mayhew.com/products/inspection-tools',
'https://mayhew.com/products/inspection-tools/catspaw-r-magnetic-pick-up-tools-colored-handle',
'https://mayhew.com/products/inspection-tools/catspaw-r-magnetic-pick-up-tools',
'https://mayhew.com/products/inspection-tools/inspection-hook-pick-sets',
'https://mayhew.com/products/inspection-tools/inspection-hook-and-picks',
'https://mayhew.com/products/inspection-tools/inspection-hook-and-pick-kits',
'https://mayhew.com/products/inspection-tools/inspection-mirrors',
'https://mayhew.com/products/inspection-tools/lighted-inspection-mirror',
'https://mayhew.com/products/inspection-tools/mirrors-magnifying-tools',
'https://mayhew.com/products/inspection-tools/multi-function-led-utility-knife',
'https://mayhew.com/products/inspection-tools/pick-up-tools',
'https://mayhew.com/products/inspection-tools/rechargeable-led-multi-tool',
'https://mayhew.com/products/inspection-tools/rectangular-inspection-mirrors',
'https://mayhew.com/products/inspection-tools/replacement-mirrors',
'https://mayhew.com/products/inspection-tools/replacement-catspaw-r-mirrors',
'https://mayhew.com/products/pliers',
'https://mayhew.com/products/pliers/cut-n-hold-nippers',
'https://mayhew.com/products/pliers/plumbing-pliers',
'https://mayhew.com/products/pliers/replacement-jaws',
'https://mayhew.com/products/pliers/screw-pliers',
'https://mayhew.com/products/pliers/slip-joint-pliers',
'https://mayhew.com/products/pliers/soft-jaw-pliers',
'https://mayhew.com/products/pneumatics',
'https://mayhew.com/products/pneumatics/long-pneumatic-hammers',
'https://mayhew.com/products/pneumatics/long-pneumatic-scrapers',
'https://mayhew.com/products/pneumatics/non-turning-pneumatics',
'https://mayhew.com/products/pneumatics/pneumatic-bolt-cutter',
'https://mayhew.com/products/pneumatics/pneumatic-cold-chisels',
'https://mayhew.com/products/pneumatics/pneumatic-control-arm-bushing-remover',
'https://mayhew.com/products/pneumatics/pneumatic-double-cut-body-ripper',
'https://mayhew.com/products/pneumatics/pneumatic-flange-nut-drivers',
'https://mayhew.com/products/pneumatics/pneumatic-hammer',
'https://mayhew.com/products/pneumatics/pneumatic-hinge-pin-drivers',
'https://mayhew.com/products/pneumatics/pneumatic-hammers',
'https://mayhew.com/products/pneumatics/pneumatic-inside-muffler-cutter',
'https://mayhew.com/products/pneumatics/pneumatic-muffler-tailpipe-remover',
'https://mayhew.com/products/pneumatics/pneumatic-nut-splitters',
'https://mayhew.com/products/pneumatics/pneumatic-outside-muffler-cutter',
'https://mayhew.com/products/pneumatics/pneumatic-pin-rod-driver',
'https://mayhew.com/products/pneumatics/pneumatic-panel-cutter',
'https://mayhew.com/products/pneumatics/pneumatic-pin-drift-punches',
'https://mayhew.com/products/pneumatics/pneumatic-roll-pin-punches',
'https://mayhew.com/products/pneumatics/pneumatic-retainer-spring',
'https://mayhew.com/products/pneumatics/pneumatic-round-head-riveters',
'https://mayhew.com/products/pneumatics/pneumatic-radius-cutter',
'https://mayhew.com/products/pneumatics/pneumatic-rivet-bolt-cutter',
'https://mayhew.com/products/pneumatics/pneumatic-retainer-chuck',
'https://mayhew.com/products/pneumatics/pneumatic-slotted-panel-cutter',
'https://mayhew.com/products/pneumatics/pneumatic-scrapers',
'https://mayhew.com/products/pneumatics/pneumatic-separating-forks',
'https://mayhew.com/products/pneumatics/pneumatic-sets',
'https://mayhew.com/products/pneumatics/pneumatic-sheet-metal-trimmer',
'https://mayhew.com/products/pneumatics/pneumatic-splitting-tool',
'https://mayhew.com/products/pneumatics/pneumatic-spot-weld-breaker',
'https://mayhew.com/products/pneumatics/pneumatic-taper-punches-sharp-point',
'https://mayhew.com/products/pneumatics/pneumatic-tailpipe-cutoff',
'https://mayhew.com/products/pneumatics/pneumatic-taper-punches',
'https://mayhew.com/products/pneumatics/pneumatic-taper-punches-sharp-point-2',
'https://mayhew.com/products/pneumatics/pneumatic-u-joint-tie-rod-tool',
'https://mayhew.com/products/pneumatics/pneumatic-valve-guide-remover',
'https://mayhew.com/products/pneumatics/replaceable-pneumatic-set-hammers',
'https://mayhew.com/products/pneumatics/replaceable-pneumatic-set-tips',
'https://mayhew.com/products/product-reader',
'https://mayhew.com/products/products-search',
'https://mayhew.com/products/pry-bars',
'https://mayhew.com/products/pry-bars/deck-wrecker',
'https://mayhew.com/products/pry-bars/deck-wrecker-with-indexing-head',
'https://mayhew.com/products/pry-bars/die-separating-bars',
'https://mayhew.com/products/pry-bars/dominator-r-economy-pry-bars',
'https://mayhew.com/products/pry-bars/dominator-r-economy-pry-bar-sets',
'https://mayhew.com/products/pry-bars/dominator-r-pro-pry-bar',
'https://mayhew.com/products/pry-bars/dominator-r-pro-pry-bar-sets',
'https://mayhew.com/products/pry-bars/dominator-r-screwdriver-pry-bar',
'https://mayhew.com/products/pry-bars/gooseneck-wrecking-bars',
'https://mayhew.com/products/pry-bars/ladyfoot-pry-bars',
'https://mayhew.com/products/pry-bars/line-up-pry-bars',
'https://mayhew.com/products/pry-bars/mini-utility-bar',
'https://mayhew.com/products/pry-bars/molding-lift-bar',
'https://mayhew.com/products/pry-bars/nail-pullers',
'https://mayhew.com/products/pry-bars/plated-jimmy-bars',
'https://mayhew.com/products/pry-bars/plated-rolling-head-bar',
'https://mayhew.com/products/pry-bars/pry-bars-sets',
'https://mayhew.com/products/pry-bars/ripping-chisels',
'https://mayhew.com/products/pry-bars/rolling-head-pry-bars',
'https://mayhew.com/products/pry-bars/screwdriver-style-pry-bars',
'https://mayhew.com/products/pry-bars/straight-pinch-bars',
'https://mayhew.com/products/punches-chisels',
'https://mayhew.com/products/punches-chisels/150-line-punches',
'https://mayhew.com/products/punches-chisels/advanced-retractable-centering-punch',
'https://mayhew.com/products/punches-chisels/aligning-punch-sets',
'https://mayhew.com/products/punches-chisels/automatic-center-punch',
'https://mayhew.com/products/punches-chisels/automatic-center-punch-replacement-tip',
'https://mayhew.com/products/punches-chisels/bearing-race-punches',
'https://mayhew.com/products/punches-chisels/brass-pin-punches-metric',
'https://mayhew.com/products/punches-chisels/brass-pin-punches',
'https://mayhew.com/products/punches-chisels/brass-solid-punch',
'https://mayhew.com/products/punches-chisels/brass-pilot-punches-metric',
'https://mayhew.com/products/punches-chisels/brass-chisel',
'https://mayhew.com/products/punches-chisels/brass-line-up-punches',
'https://mayhew.com/products/punches-chisels/brass-drift-punch-sets',
'https://mayhew.com/products/punches-chisels/brass-pilot-punches',
'https://mayhew.com/products/punches-chisels/bull-point-chisel',
'https://mayhew.com/products/punches-chisels/cape-chisels-150-line',
'https://mayhew.com/products/punches-chisels/cape-chisels',
'https://mayhew.com/products/punches-chisels/center-punches',
'https://mayhew.com/products/punches-chisels/center-punch-sets',
'https://mayhew.com/products/punches-chisels/clapboard-chisel',
'https://mayhew.com/products/punches-chisels/cold-chisels-150-line',
'https://mayhew.com/products/punches-chisels/cold-chisel-sets',
'https://mayhew.com/products/punches-chisels/cold-chisels',
'https://mayhew.com/products/punches-chisels/cold-chisels-long-chisels',
'https://mayhew.com/products/punches-chisels/diamond-point-chisels',
'https://mayhew.com/products/punches-chisels/dominator-r-weld-wakker',
'https://mayhew.com/products/punches-chisels/drift-punches',
'https://mayhew.com/products/punches-chisels/extra-long-pin-punches',
'https://mayhew.com/products/punches-chisels/extra-long-pin-punches-metric',
'https://mayhew.com/products/punches-chisels/extra-long-aligning-punches',
'https://mayhew.com/products/punches-chisels/flat-utility-chisel',
'https://mayhew.com/products/punches-chisels/floor-chisels',
'https://mayhew.com/products/punches-chisels/half-round-nose-chisels',
'https://mayhew.com/products/punches-chisels/handguarded',
'https://mayhew.com/products/punches-chisels/hard-cap-pin-punches',
'https://mayhew.com/products/punches-chisels/hard-cap-pin-punch-set',
'https://mayhew.com/products/punches-chisels/hard-cap-prick-punches',
'https://mayhew.com/products/punches-chisels/hard-cap-punch-set',
'https://mayhew.com/products/punches-chisels/hard-cap-starter-punches',
'https://mayhew.com/products/punches-chisels/hard-cap-cold-chisel-set',
'https://mayhew.com/products/punches-chisels/hard-cap-cold-chisels',
'https://mayhew.com/products/punches-chisels/hard-cap-aligning-punches',
'https://mayhew.com/products/punches-chisels/hard-cap-nail-set',
'https://mayhew.com/products/punches-chisels/hollow-punch-handle-mandrill-set',
'https://mayhew.com/products/punches-chisels/hollow-punch-sets-metric',
'https://mayhew.com/products/punches-chisels/hollow-punch-sets-sae',
'https://mayhew.com/products/punches-chisels/hollow-punch-mandrills',
'https://mayhew.com/products/punches-chisels/hollow-punch-handles',
'https://mayhew.com/products/punches-chisels/hollow-punches-sae',
'https://mayhew.com/products/punches-chisels/hollow-punches-metric',
'https://mayhew.com/products/punches-chisels/knurled-pin-punches',
'https://mayhew.com/products/punches-chisels/knurled-alignment-punches',
'https://mayhew.com/products/punches-chisels/knurled-solid-punches',
'https://mayhew.com/products/punches-chisels/knurled-aligning-punch-sets',
'https://mayhew.com/products/punches-chisels/knurled-prick-punch',
'https://mayhew.com/products/punches-chisels/large-pilot-punch-kit',
'https://mayhew.com/products/punches-chisels/line-up-punches',
'https://mayhew.com/products/punches-chisels/mason-chisels',
'https://mayhew.com/products/punches-chisels/metric-punch-and-chisel-sets',
'https://mayhew.com/products/punches-chisels/mini-knurled-pin-punches',
'https://mayhew.com/products/punches-chisels/nail-sets',
'https://mayhew.com/products/punches-chisels/pilot-pin-punches',
'https://mayhew.com/products/punches-chisels/pilot-pin-punches-metric',
'https://mayhew.com/products/punches-chisels/pilot-punch-sets',
'https://mayhew.com/products/punches-chisels/pin-punches',
'https://mayhew.com/products/punches-chisels/pin-punches-metric',
'https://mayhew.com/products/punches-chisels/pin-punch-sets',
'https://mayhew.com/products/punches-chisels/pistol-grip-conversion-handle-set',
'https://mayhew.com/products/punches-chisels/prick-punches',
'https://mayhew.com/products/punches-chisels/pro-center-punches',
'https://mayhew.com/products/punches-chisels/pro-knurled-center-punches',
'https://mayhew.com/products/punches-chisels/punch-sets',
'https://mayhew.com/products/punches-chisels/punch-chisel-sets',
'https://mayhew.com/products/punches-chisels/punch-chisel-set-150-line',
'https://mayhew.com/products/punches-chisels/punches_and_chisels_punch_sets__punch_mix',
'https://mayhew.com/products/punches-chisels/punches_and_chisels_handguarded__handguarded_cold_chisels',
'https://mayhew.com/products/punches-chisels/punches_and_chisels_hollow_punch_sets__metric',
'https://mayhew.com/products/punches-chisels/rivet-buster',
'https://mayhew.com/products/punches-chisels/rivet-set',
'https://mayhew.com/products/punches-chisels/solid-punches',
'https://mayhew.com/products/scrapers',
'https://mayhew.com/products/screwdrivers',
'https://mayhew.com/products/screwdrivers/cushion-grip-11-in-1-screwdriver',
'https://mayhew.com/products/screwdrivers/cushion-grip-11-in-1-screwdriver-display',
'https://mayhew.com/products/screwdrivers/large-screwdriver-no-2-phillips-r-head',
'https://mayhew.com/products/screwdrivers/large-screwdrivers',
'https://mayhew.com/products/screwdrivers/low-profile-screwdrivers',
'https://mayhew.com/products/screwdrivers/Mayhew-USA-Screwdrivers',
'https://mayhew.com/products/screwdrivers/phillips-r-screwdrivers',
'https://mayhew.com/products/screwdrivers/screwdriver-sets',
'https://mayhew.com/products/screwdrivers/slotted-screwdrivers',
'https://mayhew.com/products/screwdrivers/torx-r-fixed-screwdrivers',
'https://mayhew.com/products/screwdrivers/torx-r-tamperproof-fixed-screwdrivers',
'https://mayhew.com/products/specialty',
'https://mayhew.com/products/specialty/aluminum-body-panel-repair-kit',
'https://mayhew.com/products/specialty/belt-molding-removal-tool',
'https://mayhew.com/products/specialty/bolt-extractor-set-sae',
'https://mayhew.com/products/specialty/bolt-extractor-sets-metric',
'https://mayhew.com/products/specialty/brass-hammer',
'https://mayhew.com/products/specialty/complete-flat-pad-kit',
'https://mayhew.com/products/specialty/faceshields',
'https://mayhew.com/products/specialty/hose-clamp-plier-set',
'https://mayhew.com/products/specialty/hose-clamp-pliers',
'https://mayhew.com/products/specialty/nose-caulk-iron',
'https://mayhew.com/products/specialty/nose-caulk-irons',
'https://mayhew.com/products/specialty/pivot-air-blow-gun',
'https://mayhew.com/products/specialty/punch-chisel-holder',
'https://mayhew.com/products/specialty/replacement-parts',
'https://mayhew.com/products/specialty/scratch-awl',
'https://mayhew.com/products/specialty/screw-extractor-spiral',
'https://mayhew.com/products/specialty/screw-extractor-sae',
'https://mayhew.com/products/specialty/screw-extractors-metric',
'https://mayhew.com/products/specialty/screw-extractor-sets',
'https://mayhew.com/products/specialty/screw-extractor-set',
'https://mayhew.com/products/specialty/seal-puller',
'https://mayhew.com/products/specialty/spiral-screw-extractor-sets',
'https://mayhew.com/products/specialty/stud-extractor',
'https://mayhew.com/products/specialty/tie-rod-tool-kits',
'https://mayhew.com/products/specialty/twisted-hex-key-set-sae',
'https://mayhew.com/products/specialty/twisted-hex-key-set-metric',
'https://mayhew.com/products/specialty/welders-chip-hammers',
'https://mayhew.com/products/displays/punches_and_chisels_cold_chisels?body_type=0&cut_width=0&blade_size=0&blade_length=0&taper_length=0&taper_width=0&pin_width=0&pin_length=0&point_width=0&point_size=0&size=2782&length=4097&set_options=0&finish_type=0&unit_of_measurement=0&color=0&blade_style=0&packaing_type=4016&part_number_variance=0',
'https://mayhew.com/products/dual-drives-bits/dual_drives_and_bits_insert_bits__tamper_resistant_torx?body_type=0&size=0&tip_size=3021&tip_diameter=2912&tool_oal=0&rail_color=0&prod_length=0&prod_width=0&prod_height=0&dual_drives_bits_options=3285&num_products_in_set=0&pieces_per_bag=0',
'https://mayhew.com/products/dual-drives-bits/dual_drives_and_bits_insert_bits__metric_hex?body_type=0&size=0&tip_size=1970&tip_diameter=2273&tool_oal=0&rail_color=0&prod_length=0&prod_width=0&prod_height=0&dual_drives_bits_options=3304&num_products_in_set=0&pieces_per_bag=0',
'https://mayhew.com/products/punches-chisels/punches_and_chisels_pilot_pin_punches?body_type=2112&size=0&weight_capacity=0&tool_oal=0&cut_width=0&body_width=0&blade_size=0&blade_width=0&blade_length=0&taper_length=0&taper_width=0&pin_width=2239&pin_length=2133&point_width=0&point_size=0&finish_type=2036&prod_length=0&prod_width=0&prod_height=0&num_products_in_set=0',
'https://mayhew.com/products/punches-chisels/punches_and_chisels_pilot_pin_punches?body_type=2112&size=0&weight_capacity=0&tool_oal=0&cut_width=0&body_width=0&blade_size=0&blade_width=0&blade_length=0&taper_length=0&taper_width=0&pin_width=2263&pin_length=2310&point_width=0&point_size=0&finish_type=2036&prod_length=0&prod_width=0&prod_height=0&num_products_in_set=0',
'https://mayhew.com/products/punches-chisels/punches_and_chisels_pilot_pin_punches?body_type=2112&size=0&weight_capacity=0&tool_oal=0&cut_width=0&body_width=0&blade_size=0&blade_width=0&blade_length=0&taper_length=0&taper_width=0&pin_width=2286&pin_length=2333&point_width=0&point_size=0&finish_type=2036&prod_length=0&prod_width=0&prod_height=0&num_products_in_set=0',
'https://mayhew.com/products/punches-chisels/punches_and_chisels_pilot_pin_punches?body_type=2112&size=0&weight_capacity=0&tool_oal=0&cut_width=0&body_width=0&blade_size=0&blade_width=0&blade_length=0&taper_length=0&taper_width=0&pin_width=2309&pin_length=2162&point_width=0&point_size=0&finish_type=2036&prod_length=0&prod_width=0&prod_height=0&num_products_in_set=0',



]

for j in l:
    # res = requests.get(j)
    # soup = BeautifulSoup(res.content,'html.parser')
    driver.get(j)
    data = driver.page_source
    # driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    # print(data)
    soup = BeautifulSoup(data, 'html.parser')
    # count=soup.find('nav',class_='pagination block').find('p')
    # m=count.text.split('of ')[1]
    # for i in range(1,int(m)+1):
    #     jl=j+"?page_iso29="+str(i)
    #     res = requests.get(jl)
    #     soup = BeautifulSoup(res.content, 'html.parser')
    #     sd=soup.find('div',class_='product_list').find_all('a')
    #     for k in sd:
    #         print("''https://mayhew.com/"+k.get('href')+"',")

    try:
        in_l=soup.find_all('figure',class_='image_container')
        for l in in_l:

            save_detaisl: TextIO=open("may_url_inside.txt","a+",encoding="utf-8")
            save_detaisl.write('\n'+"'https://mayhew.com/"+l.find('a').get('href')+"'',")
            print("'https://mayhew.com/"+l.find('a').get('href'))
    except:
        print("'")
        pass

