from selenium import webdriver
from selenium.webdriver.common.by import By
import time
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
# Set headless mode
chrome_options.add_argument('--headless')

driver = webdriver.Chrome()
driver.maximize_window()
time.sleep(2)

mylist = [

    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/three-hole-widespread-deck-mount-kitchen-sink-faucets/dual-knob-handle-three-hole-widespread-deck-mount-kitchen-sink-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/plumbing-hoses/hose-stations?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/drains-and-drainage/drains/pipe-and-valve-covers?categoryIndex=10',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-and-tubing-accessories/pipe-and-test-plugs?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/flow-control-valves/v-ball-control-valves?categoryIndex=14',
    # 'https://www.grainger.com/category/plumbing/gaskets/sheet-and-ring-gaskets?attrs=Product+Type%7CCompression+Packing+Seal&filters=attrs'# start 3000 urls
    'https://www.grainger.com/category/plumbing/gaskets/sheet-and-ring-gaskets?attrs=Product+Type%7CFlange+Gasket&filters=attrs', # 1800
    
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-and-tubing-accessories/clamps-and-fasteners?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/bathtubs-showers-repair-parts/showers/bathtub-shower-faucet-combinations?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/three-hole-widespread-deck-mount-kitchen-sink-faucets/single-joystick-handle-three-hole-widespread-deck-mount-kitchen-sink-faucets?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/faucets/multipurpose-faucets/two-hole-centerset-deck-mount-multipurpose-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/two-hole-centerset-deck-mount-bathroom-faucets/single-knob-handle-two-hole-centerset-deck-mount-bathroom-faucets?categoryIndex=8',
    # 'https://www.grainger.com/category/plumbing/gaskets/sheet-and-ring-gaskets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/water-filtration-purification-systems/water-strainers/temporary-strainers?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/single-hole-deck-mount-bathroom-faucets/single-lever-handle-single-hole-deck-mount-bathroom-faucets?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/kitchen-bar-sinks/counter-mounted-kitchen-bar-sinks?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/bathtubs-showers-repair-parts/bathtubs/alcove-bathtubs?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/single-hole-deck-mount-bathroom-faucets/single-metering-handle-single-hole-deck-mount-bathroom-faucets?categoryIndex=7',
    # 'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-spouts-spout-extensions/faucet-supply-arms?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/two-hole-centerset-deck-mount-kitchen-sink-faucets/single-joystick-handle-two-hole-centerset-deck-mount-kitchen-sink-faucets?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/two-hole-off-centerset-with-sprayer-deck-mount-kitchen-sink-faucets?categoryIndex=7',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/instrumentation-manifold-valves?categoryIndex=16',
    # 'https://www.grainger.com/category/plumbing/faucets/multipurpose-faucets/two-hole-widespread-wall-mount-multipurpose-faucets?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/three-hole-widespread-deck-mount-bathroom-faucets/dual-wristblade-handle-three-hole-widespread-deck-mount-bathroom-faucets?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/faucets/utility-faucets/laundry-sink-faucets/two-hole-centerset-deck-mount-laundry-sink-faucets/dual-dome-lever-handle-two-hole-centerset-deck-mount-laundry-sink-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/liquid-level-gauges-and-sight-indicators/gauge-cocks?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/bathroom-hardware/shower-curtain-rods-and-tracks?categoryIndex=14',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/two-hole-off-centerset-deck-mount-bathroom-faucets/single-joystick-handle-two-hole-off-centerset-deck-mount-bathroom-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/rotary-swivel-and-expansion-joints/expansion-joints?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/two-hole-centerset-deck-mount-bathroom-faucets/dual-lever-handle-two-hole-centerset-deck-mount-bathroom-faucets?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/pressure-and-temperature-control-valves/steam-separators?categoryIndex=13',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/valve-actuators-enclosures-and-accessories/valve-and-meter-boxes?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/check-valves-and-backflow-preventers/flow-control-check-valves?categoryIndex=7',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/flow-control-valves/balancing-valves?categoryIndex=10',
    # 'https://www.grainger.com/category/plumbing/water-heaters/replacement-parts-accessories-for-water-heaters/storage-tanks-for-water-heaters?categoryIndex=12',
    # 'https://www.grainger.com/category/plumbing/drains-and-drainage/drains/drain-components?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/flow-control-valves/globe-valves?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/float-valves-and-accessories/self-contained-float-valves?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-and-tubing-accessories/pipe-saddles?categoryIndex=9',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories?categoryIndex=12',
    # 'https://www.grainger.com/category/plumbing/faucets/utility-faucets/laundry-sink-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/pressure-and-temperature-control-valves/vent-valves?categoryIndex=16',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-and-tubing-accessories/flange-covers?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/faucets/utility-faucets/service-sink-faucets/two-hole-widespread-deck-mount-service-sink-faucets?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/bathroom-sinks/counter-mounted-bathroom-sinks?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/air-operated-valves?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/drinking-fountains-bottle-fillers-water-dispensers/replacement-parts-for-drinking-fountains-bottle-fillers?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/water-filtration-purification-systems/process-water-filter-systems/loose-filter-media?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/water-filtration-purification-systems/appliance-water-filter-systems/complete-appliance-water-filtration-systems?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/hand-sinks-hand-wash-stations/counter-mounted-hand-sinks-hand-wash-stations?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/laboratory-faucets/single-hole-deck-mount-laboratory-faucets/dual-cross-handle-single-hole-deck-mount-laboratory-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/garbage-disposals-and-accessories/garbage-disposal-accessories?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/bar-sink-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/water-filtration-purification-systems/water-strainers/suction-diffuser-strainers?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/water-heaters/replacement-parts-accessories-for-water-heaters/heating-elements-for-electric-water-heaters?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/boiler-drain-valves?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/bar-sink-faucets/two-hole-centerset-wall-mount-bar-sink-faucet?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/gaskets/sanitary-gaskets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/water-heaters/replacement-parts-accessories-for-water-heaters/relief-valves-for-water-heaters?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/flow-control-valves?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/flow-control-valves/hydrant-and-hose-rack-gate-valves?categoryIndex=11',
    # 'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/kitchen-bar-sinks/freestanding-kitchen-bar-sinks?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/insulation/pipe-insulation-wrap?categoryIndex=12',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-and-tubing-accessories/saddle-clamps?categoryIndex=14',
    # 'https://www.grainger.com/category/plumbing/faucets/utility-faucets/laundry-sink-faucets/two-hole-centerset-wall-mount-laundry-sink-faucets/dual-cross-handle-two-hole-centerset-wall-mount-laundry-sink-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/bathtubs-showers-repair-parts/showers/shower-faucet-panels?categoryIndex=10',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/two-hole-off-centerset-with-sprayer-deck-mount-kitchen-sink-faucets/single-side-joystick-handle-two-hole-off-centerset-with-sprayer-deck-mount-kitchen-sink-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/liquid-level-gauges-and-sight-indicators/gauge-glass-and-rod-kits?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/bathroom-hardware/lighted-makeup-mirrors?categoryIndex=8',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-and-tubing-accessories/pipe-supports?categoryIndex=11',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/single-hole-deck-mount-kitchen-sink-faucets/single-lever-handle-single-hole-deck-mount-kitchen-sink-faucets?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/three-hole-widespread-wall-mount-bathroom-faucets/dual-lever-handle-three-hole-widespread-wall-mount-bathroom-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/insulation/pipe-insulation?categoryIndex=7',
    # 'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-cartridges-stems-valve-parts?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-handles-foot-pedals?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/faucets/outdoor-hose-bibbs-hydrants?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-spouts-spout-extensions/double-jointed-faucet-spouts?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/valve-actuators-enclosures-and-accessories/valve-accessories?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/bathroom-hardware/shower-curtains?categoryIndex=15',
    # 'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-handles-foot-pedals/faucet-foot-pedals-parts?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/drains-and-drainage/drains/dilution-tanks-and-traps?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/urinal-repair-parts-accessories/standard-urinal-repair-parts-accessories?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/check-valves-and-backflow-preventers/foot-valves?categoryIndex=8',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/pressure-and-temperature-control-valves/gas-pressure-regulators?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/toilet-repair-parts-accessories/bedpan-washers-portable-toilet-flushers?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves?categoryIndex=15',
    # 'https://www.grainger.com/category/plumbing/bathtubs-showers-repair-parts/showers/fixed-handheld-showerhead-combinations?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/pressure-and-temperature-control-valves/boiler-feed-valves?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/hand-sinks-hand-wash-stations/freestanding-hand-sinks-hand-wash-stations?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/three-hole-widespread-deck-mount-kitchen-sink-faucets/dual-dome-lever-handle-three-hole-widespread-deck-mount-kitchen-sink-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/three-hole-widespread-deck-mount-kitchen-sink-faucets/dual-lever-handle-three-hole-widespread-deck-mount-kitchen-sink-faucets?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/toilets/prison-toilets-combination-units?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/bathroom-hardware/makeup-mirrors?categoryIndex=9',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/two-hole-centerset-deck-mount-bathroom-faucets/dual-metering-handle-two-hole-centerset-deck-mount-bathroom-faucets?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/faucets/multipurpose-faucets/two-hole-centerset-wall-mount-multipurpose-faucets/dual-lever-handle-two-hole-centerset-wall-mount-multipurpose-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/single-hole-deck-mount-bathroom-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/glass-fillers/single-hole-wall-mount-glass-fillers?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/four-hole-widespread-with-sprayer-deck-mount-kitchen-sink-faucets?categoryIndex=1',
    'https://www.grainger.com/category/plumbing/water-heaters/replacement-parts-accessories-for-water-heaters/insulation-blankets-for-water-heaters?categoryIndex=10',
    'https://www.grainger.com/category/plumbing/water-heaters/replacement-parts-accessories-for-water-heaters?categoryIndex=5',
    'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/flush-valves-retrofit-kits/bedpan-washer-flush-valves?categoryIndex=3',
    'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/sink-wash-fountain-parts-accessories/drainboards?categoryIndex=2',
    'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/flush-valves-retrofit-kits/manual-flush-valves?categoryIndex=4',
    'https://www.grainger.com/category/plumbing/water-softeners-softening-salt?categoryIndex=20',
    'https://www.grainger.com/category/plumbing/bathroom-hardware/mirror-framing-kits?categoryIndex=10',
    'https://www.grainger.com/category/plumbing/plumbing-valves/pressure-and-temperature-control-valves/temperature-and-pressure-relief-valves?categoryIndex=14',
    'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/single-hole-wall-mount-bathroom-faucets/single-metering-handle-single-hole-wall-mount-bathroom-faucets?categoryIndex=3',
    'https://www.grainger.com/category/plumbing/insulation/pipe-insulation-accessories?categoryIndex=8',
    'https://www.grainger.com/category/plumbing/bathroom-hardware/bathroom-hooks?categoryIndex=3',
    'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/two-hole-off-centerset-deck-mount-bathroom-faucets?categoryIndex=6',
    'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/bathroom-sinks?categoryIndex=1',
    'https://www.grainger.com/category/plumbing/plumbing-valves/float-valves-and-accessories/float-rods-adapters-and-nuzzle-assemblies?categoryIndex=2',
    'https://www.grainger.com/category/plumbing/bathroom-hardware/bathroom-stalls-and-partitions/bathroom-partitions?categoryIndex=2',
    'https://www.grainger.com/category/plumbing/liquid-level-gauges-and-sight-indicators/full-view-sight-flow-indicators?categoryIndex=1',
    'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/toilets?categoryIndex=3',
    'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/single-hole-deck-mount-kitchen-sink-faucets?categoryIndex=2',
    'https://www.grainger.com/category/plumbing/plumbing-valves/pressure-and-temperature-control-valves/rupture-discs?categoryIndex=12',
    'https://www.grainger.com/category/plumbing/plumbing-valves/pressure-and-temperature-control-valves/pressure-reducing-automatic-control-valves?categoryIndex=9',
    'https://www.grainger.com/category/plumbing/faucets/utility-faucets/service-sink-faucets/two-hole-centerset-wall-mount-service-sink-faucets/dual-dome-lever-handle-two-hole-centerset-wall-mount-service-sink-faucets?categoryIndex=1',
    'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/truck-valves?categoryIndex=24',
    'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/utility-laundry-sinks/counter-mounted-utility-laundry-sinks?categoryIndex=1',
    'https://www.grainger.com/category/plumbing/drinking-fountains-bottle-fillers-water-dispensers/retrofit-kits-for-drinking-fountains?categoryIndex=6',
    'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/toilet-repair-parts-accessories/prison-toilet-repair-parts?categoryIndex=6',
    'https://www.grainger.com/category/plumbing/faucets/utility-faucets/laundry-sink-faucets/two-hole-centerset-deck-mount-laundry-sink-faucets/dual-lever-handle-two-hole-centerset-deck-mount-laundry-sink-faucets?categoryIndex=2',
    'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/single-hole-deck-mount-bathroom-faucets/sensor-single-hole-deck-mount-bathroom-faucets?categoryIndex=3',
    'https://www.grainger.com/category/plumbing/faucets/utility-faucets?categoryIndex=7',
    'https://www.grainger.com/category/plumbing/water-heaters/replacement-parts-accessories-for-water-heaters/drain-pans-for-water-heaters?categoryIndex=7',
    'https://www.grainger.com/category/plumbing/faucets/laboratory-faucets/single-hole-deck-mount-laboratory-faucets/foot-pedal-single-hole-deck-mount-laboratory-faucets?categoryIndex=4',
    'https://www.grainger.com/category/plumbing/bathroom-hardware/baby-changing-stations?categoryIndex=2',
    'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/urinal-repair-parts-accessories/waterless-urinal-repair-parts-accessories?categoryIndex=3',
    'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/three-hole-widespread-deck-mount-bathroom-faucets/sensor-three-hole-widespread-deck-mount-bathroom-faucets?categoryIndex=7',
    'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/utility-laundry-sinks/freestanding-utility-laundry-sinks?categoryIndex=2',
    'https://www.grainger.com/category/plumbing/plumbing-valves/flow-control-valves/pneumatic-globe-control-valves?categoryIndex=7',
    'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/pneumatically-actuated-diaphragm-valves?categoryIndex=19',
    'https://www.grainger.com/category/plumbing/bathroom-hardware/shower-baskets?categoryIndex=12',
    'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/two-hole-widespread-wall-mount-kitchen-sink-faucets/single-joystick-handle-two-hole-widespread-wall-mount-kitchen-sink-faucets?categoryIndex=3',
    'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-and-tubing-accessories/tools?categoryIndex=17',
    'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/hand-sinks-hand-wash-stations/wall-mounted-hand-sinks-hand-wash-stations?categoryIndex=3',
    'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/sink-wash-fountain-parts-accessories?categoryIndex=7',
    'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/urinal-repair-parts-accessories/urinal-flush-valve-repair-parts-accessories?categoryIndex=2',
    'https://www.grainger.com/category/plumbing/faucets/utility-faucets/service-sink-faucets/single-hole-deck-mount-service-sink-faucets?categoryIndex=1',
    'https://www.grainger.com/category/plumbing/insulation/removable-blanket-insulation?categoryIndex=14',
    'https://www.grainger.com/category/plumbing/fixtures?categoryIndex=6',
    'https://www.grainger.com/category/plumbing/faucets/laboratory-faucets/single-hole-deck-mount-laboratory-faucets?categoryIndex=1',
    'https://www.grainger.com/category/plumbing/plumbing-valves/pressure-and-temperature-control-valves/pressure-regulators?categoryIndex=10',
    'https://www.grainger.com/category/plumbing/water-heaters/electric-water-heaters-with-tank?categoryIndex=3',
    'https://www.grainger.com/category/plumbing/water-heaters/replacement-parts-accessories-for-water-heaters/controls-for-water-heaters?categoryIndex=1',
    'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/urinal-repair-parts-accessories?categoryIndex=5',
    'https://www.grainger.com/category/plumbing/gaskets?categoryIndex=9',
    'https://www.grainger.com/category/plumbing/faucets/outdoor-hose-bibbs-hydrants/hose-bibbs-sillcocks?categoryIndex=1',
    'https://www.grainger.com/category/plumbing/bathroom-hardware?categoryIndex=1',
    'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-spouts-spout-extensions/double-bend-faucet-spouts?categoryIndex=2',
    'https://www.grainger.com/category/plumbing/bathroom-hardware/baby-changing-station-accessories?categoryIndex=1',
    'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/water-supply-stops?categoryIndex=27',
    'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/bathroom-sinks/wall-mounted-bathroom-sinks?categoryIndex=3',
    'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/ball-valve-connection-adapters?categoryIndex=4',
    'https://www.grainger.com/category/plumbing/bathtubs-showers-repair-parts/showers/fixed-showerheads?categoryIndex=3',
    'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-and-tubing-accessories/pipe-hangers-and-clamps?categoryIndex=7',
    'https://www.grainger.com/category/plumbing/bathroom-hardware/towel-warmers?categoryIndex=20',
    'https://www.grainger.com/category/plumbing/water-heaters/replacement-parts-accessories-for-water-heaters/cleaners-descalers-for-water-heaters?categoryIndex=13',
    'https://www.grainger.com/category/plumbing/water-heaters/gas-water-heaters-with-tank?categoryIndex=1',
    'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/hospital-lab-sinks/wall-mounted-hospital-lab-sinks?categoryIndex=2',
    'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/bar-sink-faucets/single-hole-deck-mount-bar-sink-faucets?categoryIndex=1',
    'https://www.grainger.com/category/plumbing/plumbing-hoses/hose-station-accessories?categoryIndex=1',
    'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/four-hole-widespread-with-sprayer-deck-mount-kitchen-sink-faucets/dual-wristblade-handle-four-hole-widespread-with-sprayer-deck-mount-kitchen-sink-faucets?categoryIndex=2',
    'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/pre-rinse-faucets/two-hole-widespread-wall-mount-pre-rinse-faucets?categoryIndex=3',
    'https://www.grainger.com/category/plumbing/gas-and-water-line-connectors/gas-connector-fitting?categoryIndex=1',
    'https://www.grainger.com/category/plumbing/pipe-accessories/rotary-swivel-and-expansion-joints?categoryIndex=5',
    'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/two-hole-centerset-deck-mount-kitchen-sink-faucets/dual-lever-handle-two-hole-centerset-deck-mount-kitchen-sink-faucets?categoryIndex=3',
    'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-spouts-spout-extensions/straight-faucet-spouts?categoryIndex=10',
    'https://www.grainger.com/category/plumbing/fixtures/sink-accessories?categoryIndex=1',
    'https://www.grainger.com/category/plumbing/water-filtration-purification-systems/process-water-filter-systems/filter-bags?categoryIndex=1',
    'https://www.grainger.com/category/plumbing/bathtubs-showers-repair-parts/showers/handheld-showerhead-accessories?categoryIndex=4',
    'https://www.grainger.com/category/plumbing/faucets/utility-faucets/inside-sill-faucets?categoryIndex=1',
    'https://www.grainger.com/category/plumbing/plumbing-valves/valve-actuators-enclosures-and-accessories/electric-valve-actuators?categoryIndex=1',
    'https://www.grainger.com/category/plumbing/water-heaters/replacement-parts-accessories-for-water-heaters/expansion-tanks-for-water-heaters?categoryIndex=9',
    'https://www.grainger.com/category/plumbing/water-softeners-softening-salt/water-softeners?categoryIndex=2',
    'https://www.grainger.com/category/plumbing/bathtubs-showers-repair-parts/showers/shower-bases-pans?categoryIndex=8',
    'https://www.grainger.com/category/plumbing/drains-and-drainage/drains/roof-and-floor-drains?categoryIndex=11',
    'https://www.grainger.com/category/plumbing/plumbing-valves/flow-control-valves/pneumatically-actuated-butterfly-valves?categoryIndex=4',
    'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/ball-valves/electrically-actuated-ball-valves?categoryIndex=2',
    'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/single-hole-deck-mount-bathroom-faucets/single-joystick-handle-single-hole-deck-mount-bathroom-faucets?categoryIndex=5',
    'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-and-tubing-accessories/pipe-hanger-strap?categoryIndex=8',
    'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/toilets/ligature-resistant-toilets-flush-valve-covers?categoryIndex=2',
    'https://www.grainger.com/category/plumbing/plumbing-valves/float-valves-and-accessories/float-valves?categoryIndex=4',
    'https://www.grainger.com/category/plumbing/water-filtration-purification-systems/water-strainers?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/flush-valves-retrofit-kits/automatic-flush-valve-retrofit-kits?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/rotary-swivel-and-expansion-joints/swivel-joints?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/water-heaters/replacement-parts-accessories-for-water-heaters/retrofit-kits-for-water-heaters?categoryIndex=8',
    # 'https://www.grainger.com/category/plumbing/drinking-fountains-bottle-fillers-water-dispensers/on-wall-drinking-fountains-bottle-fillers?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/pressure-and-temperature-control-valves/temperature-regulator-valves?categoryIndex=15',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/toilet-repair-parts-accessories/gravity-tank-repair-parts?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/bathtubs-showers-repair-parts/showers/shower-arms?categoryIndex=7',
    # 'https://www.grainger.com/category/plumbing/faucets/laboratory-faucets/single-hole-deck-mount-laboratory-faucets/dual-lever-handle-single-hole-deck-mount-laboratory-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/flush-valves-retrofit-kits/prison-ligature-resistant-flush-valves?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-spouts-spout-extensions/angled-straight-faucet-spouts?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-repair-clamps-and-couplings/pipe-repair-kits?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/drains-and-drainage?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/flow-control-valves/plug-valves?categoryIndex=8',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/flow-control-valves/sanitary-butterfly-valves?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/water-heaters/replacement-parts-accessories-for-water-heaters/anode-rods-for-water-heaters?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/drinking-fountains-bottle-fillers-water-dispensers/remote-water-chillers?categoryIndex=9',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/single-hole-deck-mount-kitchen-sink-faucets/dual-lever-handle-single-hole-deck-mount-kitchen-sink-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/two-hole-centerset-wall-mount-kitchen-sink-faucets?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/purge-and-fill-valves?categoryIndex=21',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/three-hole-widespread-deck-mount-bathroom-faucets/single-metering-handle-three-hole-widespread-deck-mount-bathroom-faucets?categoryIndex=8',
    # 'https://www.grainger.com/category/plumbing/water-heaters/replacement-parts-accessories-for-water-heaters/water-detectors?categoryIndex=14',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/two-hole-centerset-deck-mount-bathroom-faucets/dual-dome-lever-handle-two-hole-centerset-deck-mount-bathroom-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-spouts-spout-extensions/gooseneck-faucet-spouts?categoryIndex=7',
    # 'https://www.grainger.com/category/plumbing/bathtubs-showers-repair-parts/showers/handheld-showerheads?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/drinking-fountains-bottle-fillers-water-dispensers/in-wall-drinking-fountains-bottle-fillers?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/two-hole-centerset-deck-mount-bathroom-faucets/single-joystick-handle-two-hole-centerset-deck-mount-bathroom-faucets?categoryIndex=7',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/single-hole-deck-mount-bathroom-faucets/single-side-joystick-handle-single-hole-deck-mount-bathroom-faucets?categoryIndex=8',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/single-hole-deck-mount-kitchen-sink-faucets/single-wristblade-handle-single-hole-deck-mount-kitchen-sink-faucets?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/faucets/multipurpose-faucets/two-hole-widespread-wall-mount-multipurpose-faucets/dual-lever-handle-two-hole-widespread-wall-mount-multipurpose-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/two-hole-widespread-wall-mount-kitchen-sink-faucets?categoryIndex=8',
    # 'https://www.grainger.com/category/plumbing/faucets/laboratory-faucets?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-and-tubing-accessories/nipple-caddies?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/insulation/insulation-boards?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-and-tubing-accessories/pipe-straps?categoryIndex=10',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/pressure-and-temperature-control-valves/bypass-valves?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/utility-laundry-sinks/wall-mounted-utility-laundry-sinks?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/water-heaters/gas-tankless-water-heaters?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-spouts-spout-extensions/low-arc-faucet-spouts?categoryIndex=8',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/single-hole-deck-mount-kitchen-sink-faucets/dual-wristblade-handle-single-hole-deck-mount-kitchen-sink-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/water-heaters/replacement-parts-accessories-for-water-heaters/stands-supports-for-water-heaters?categoryIndex=11',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/two-hole-off-centerset-wall-mount-bathroom-faucets/single-joystick-handle-two-hole-off-centerset-wall-mount-bathroom-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/bathroom-hardware/bathroom-stalls-and-partitions?categoryIndex=7',
    # 'https://www.grainger.com/category/plumbing/insulation/insulated-pipe-fitting-covers?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/urinals?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/float-valves-and-accessories?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-and-tubing-accessories/pipe-tube-valve-and-fitting-protection?categoryIndex=12',
    # 'https://www.grainger.com/category/plumbing/drains-and-drainage/drains/sink-drains?categoryIndex=12',
    # 'https://www.grainger.com/category/plumbing/insulation/insulated-pipe-jackets-and-blankets?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/flow-control-valves/plumbing-needle-valves?categoryIndex=9',
    # 'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/portable-hand-sinks-hand-wash-stations?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/faucets/multipurpose-faucets/two-hole-widespread-wall-mount-multipurpose-faucets/dual-wristblade-handle-two-hole-widespread-wall-mount-multipurpose-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-spouts-spout-extensions/faucet-spout-rings?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/faucets/utility-faucets/service-sink-faucets/two-hole-widespread-wall-mount-service-sink-faucets/dual-wristblade-handle-two-hole-widespread-wall-mount-service-sink-faucets?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/flow-control-valves/electrically-actuated-butterfly-valves?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/insulation/pipe-fitting-insulation?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/bathtubs-showers-repair-parts/bathtubs?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/check-valves-and-backflow-preventers/vacuum-breakers?categoryIndex=10',
    # 'https://www.grainger.com/category/plumbing/insulation/pipe-valve-and-fitting-heated-covers?categoryIndex=13',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-fa'
    # 'ucets/four-hole-widespread-with-sprayer-deck-mount-kitchen-sink-faucets/single-joystick-handle-four-hole-widespread-with-sprayer-deck-mount-kitchen-sink-faucets?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/water-heaters/replacement-parts-accessories-for-water-heaters/pilot-assemblies-for-gas-water-heaters?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/three-hole-widespread-deck-mount-bathroom-faucets/dual-cross-handle-three-hole-widespread-deck-mount-bathroom-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/water-softeners-softening-salt/water-softener-chemicals?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/bathroom-hardware/bathroom-shelves?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/check-valves-and-backflow-preventers/sanitary-check-valves?categoryIndex=9',
    # 'https://www.grainger.com/category/plumbing/faucets/utility-faucets/laundry-sink-faucets/two-hole-centerset-wall-mount-laundry-sink-faucets/dual-lever-handle-two-hole-centerset-wall-mount-laundry-sink-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/two-hole-centerset-wall-mount-kitchen-sink-faucets/dual-lever-handle-two-hole-centerset-wall-mount-kitchen-sink-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/bathroom-hardware/towel-bars?categoryIndex=18',
    # 'https://www.grainger.com/category/plumbing/water-filtration-purification-systems/drinking-water-filter-systems/drinking-water-filter-housings?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/two-hole-centerset-deck-mount-kitchen-sink-faucets?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/water-filtration-purification-systems/water-strainers/y-strainers?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/two-hole-widespread-wall-mount-kitchen-sink-faucets/dual-lever-handle-two-hole-widespread-wall-mount-kitchen-sink-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/pressure-and-temperature-control-valves?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/drinking-fountains-bottle-fillers-water-dispensers/outdoor-drinking-fountains-bottle-fillers?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/bathroom-hardware/shower-curtain-systems?categoryIndex=16',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/three-hole-widespread-deck-mount-bathroom-faucets/dual-metering-handle-three-hole-widespread-deck-mount-bathroom-faucets?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/water-filtration-purification-systems/drinking-water-filter-systems?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/bathroom-hardware/retractable-clotheslines?categoryIndex=11',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-and-tubing-accessories/tubing-racks?categoryIndex=19',
    # 'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/kitchen-bar-sinks?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/pressure-and-temperature-control-valves/water-pressure-reducing-valves?categoryIndex=18',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/single-hole-deck-mount-bathroom-faucets/single-cross-handle-single-hole-deck-mount-bathroom-faucets?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/valve-actuators-enclosures-and-accessories/pneumatically-actuated-valve-accessories?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/three-hole-widespread-deck-mount-bathroom-faucets?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/water-filtration-purification-systems/process-water-filter-systems?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/valve-actuators-enclosures-and-accessories/pneumatic-actuators?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-and-tubing-accessories/spray-shields?categoryIndex=15',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/bar-sink-faucets/three-hole-widespread-deck-mount-bar-sink-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/faucets/laboratory-faucets/three-hole-widespread-deck-mount-laboratory-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-escutcheons-cover-plates?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/three-hole-widespread-deck-mount-kitchen-sink-faucets/dual-wristblade-handle-three-hole-widespread-deck-mount-kitchen-sink-faucets?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-and-tubing-accessories/pipe-and-tube-clamps?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/flow-control-valves/liquid-level-control-valves?categoryIndex=12',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/two-hole-centerset-deck-mount-bathroom-faucets/sensor-two-hole-centerset-deck-mount-bathroom-faucets?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/three-hole-widespread-deck-mount-bathroom-faucets/dual-dome-lever-handle-three-hole-widespread-deck-mount-bathroom-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/manifolds/pipe-manifolds?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/ball-valves/manual-ball-valves?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-washers-o-rings-hardware?categoryIndex=9',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/rotary-swivel-and-expansion-joints/rotary-joint-elbows?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/hospital-lab-sinks/counter-mounted-hospital-lab-sinks?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/toilets/tankless-toilets?categoryIndex=7',
    # 'https://www.grainger.com/category/plumbing/faucets/outdoor-hose-bibbs-hydrants/yard-hydrants?categoryIndex=5'
    # , 'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-caps-index-buttons?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-and-tubing-accessories/steel-brackets?categoryIndex=16',
    # 'https://www.grainger.com/category/plumbing/water-softeners-softening-salt/water-softener-salt?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/bathroom-hardware/bathroom-stalls-and-partitions/bathroom-partition-hardware?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/bathtubs-showers-repair-parts/showers/shower-stalls?categoryIndex=12',
    # 'https://www.grainger.com/category/plumbing/faucets/outdoor-hose-bibbs-hydrants/outdoor-faucet-covers?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/water-filtration-purification-systems/water-strainers/inline-strainers?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/portable-hand-sinks-hand-wash-stations/portable-hand-wash-stations?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/water-heaters/replacement-parts-accessories-for-water-heaters/venting-kits-for-water-heaters?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/faucets/utility-faucets/service-sink-faucets/two-hole-centerset-wall-mount-service-sink-faucets/dual-lever-handle-two-hole-centerset-wall-mount-service-sink-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/two-hole-widespread-wall-mount-kitchen-sink-faucets/dual-wristblade-handle-two-hole-widespread-wall-mount-kitchen-sink-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/water-filtration-purification-systems/ultraviolet-water-disinfecting-systems?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/sink-wash-fountain-parts-accessories/portable-hand-sink-hand-wash-station-accessories?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/toilets/pressure-assist-toilets?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/pressure-and-temperature-control-valves/mixing-valve-repair-kits?categoryIndex=7',
    # 'https://www.grainger.com/category/plumbing/faucets/utility-faucets/service-sink-faucets/two-hole-centerset-wall-mount-service-sink-faucets/dual-wristblade-handle-two-hole-centerset-wall-mount-service-sink-faucets?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/faucets/utility-faucets/service-sink-faucets?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-handles-foot-pedals/faucet-handle-adapters-pullers?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-and-tubing-accessories/pneumatic-test-plug-accessories?categoryIndex=13',
    # 'https://www.grainger.com/category/plumbing/bathtubs-showers-repair-parts?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/plumbing-replacement-parts?categoryIndex=14',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/check-valves-and-backflow-preventers/backflow-preventer-test-kits?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/pressure-and-temperature-control-valves/condensate-coolers?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/bathtubs-showers-repair-parts/showers/shower-faucets?categoryIndex=11',
    # 'https://www.grainger.com/category/plumbing/liquid-level-gauges-and-sight-indicators/water-gauges?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts?categoryIndex=16',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts?categoryIndex=17',
    # 'https://www.grainger.com/category/plumbing/plumbing-hoses?categoryIndex=13',
    # 'https://www.grainger.com/category/plumbing/drinking-fountains-bottle-fillers-water-dispensers/replacement-parts-for-water-coolers-dispensers?categoryIndex=8',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/solenoid-valves-and-coils?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/mop-sinks?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-sprayers-sprayer-parts?categoryIndex=8',
    # 'https://www.grainger.com/category/plumbing/drinking-fountains-bottle-fillers-water-dispensers/freestanding-drinking-fountains-bottle-fillers?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/washing-machine-valves?categoryIndex=25',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/ball-valves/pneumatically-actuated-ball-valves?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/insulation/pipe-insulation-tape?categoryIndex=11',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/flow-control-valves/electric-globe-control-valves?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/pressure-and-temperature-control-valves/mixing-valves?categoryIndex=8',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/check-valves-and-backflow-preventers/backflow-preventer-accessories?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/two-hole-centerset-deck-mount-kitchen-sink-faucets/dual-knob-handle-two-hole-centerset-deck-mount-kitchen-sink-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/water-filtration-purification-systems/appliance-water-filter-systems/appliance-water-filter-heads-housings?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/toilets/gravity-tank-toilets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/water-filtration-purification-systems/process-water-filter-systems/process-water-filter-housings?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/float-valves-and-accessories/float-valve-accessories?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/faucets/utility-faucets/service-sink-faucets/two-hole-widespread-wall-mount-service-sink-faucets/dual-cross-handle-two-hole-widespread-wall-mount-service-sink-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/air-cocks?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/multipurpose-faucets?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/faucet-and-supply-stop-adapters?categoryIndex=13',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/gate-valves?categoryIndex=15',
    # 'https://www.grainger.com/category/plumbing/bathroom-hardware/soap-dishes?categoryIndex=17',
    # 'https://www.grainger.com/category/plumbing/bathtubs-showers-repair-parts/bathtubs/bathtub-overflow-plates?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/three-hole-widespread-deck-mount-bathroom-faucets/dual-lever-handle-three-hole-widespread-deck-mount-bathroom-faucets?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/two-hole-off-centerset-deck-mount-kitchen-sink-faucets?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-and-tubing-accessories?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/toilet-repair-parts-accessories/portable-toilet-accessories?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/water-detection-and-shut-off-systems?categoryIndex=26',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/toilet-repair-parts-accessories/macerating-toilet-repair-parts-accessories?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/water-filtration-purification-systems/water-strainers/basket-strainers?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-and-tubing-accessories/tube-clamps?categoryIndex=18',
    # 'https://www.grainger.com/category/plumbing/bathroom-hardware/washroom-accessories?categoryIndex=21',
    # 'https://www.grainger.com/category/plumbing/bathtubs-showers-repair-parts/showers?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/piston-valves?categoryIndex=18',
    # 'https://www.grainger.com/category/plumbing/bathtubs-showers-repair-parts/bathtubs/bathtub-spouts-fillers?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/faucets/outdoor-hose-bibbs-hydrants/wall-yard-hydrant-accessories?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/gas-and-water-line-connectors/supply-valve-outlet-boxes?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/two-hole-off-centerset-deck-mount-kitchen-sink-faucets/single-joystick-handle-two-hole-off-centerset-deck-mount-kitchen-sink-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/manifolds/tube-fitting-manifolds?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/drains-and-drainage/drains/tub-and-shower-drains?categoryIndex=14',
    # 'https://www.grainger.com/category/plumbing/faucets/multipurpose-faucets/three-hole-widespread-deck-mount-multipurpose-faucets/dual-wristblade-handle-three-hole-widespread-deck-mount-multipurpose-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/shut-off-valves?categoryIndex=22',
    # 'https://www.grainger.com/category/plumbing/drains-and-drainage/drains/downspouts-and-extenders?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/toilet-repair-parts-accessories/standard-toilet-repair-parts-accessories?categoryIndex=7',
    # 'https://www.grainger.com/category/plumbing/bathtubs-showers-repair-parts/showers/seated-safety-showers?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/float-valves-and-accessories/float-balls?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/toilet-seats?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/liquid-level-gauges-and-sight-indicators/window-sight-flow-indicators?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/faucets/utility-faucets/service-sink-faucets/two-hole-widespread-wall-mount-service-sink-faucets?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/faucets/laboratory-faucets/two-hole-centerset-wall-mount-laboratory-faucets?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/utility-laundry-sinks?categoryIndex=8',
    # 'https://www.grainger.com/category/plumbing/water-filtration-purification-systems/drinking-water-filter-systems/drinking-water-filters?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/combination-strainer-ball-valves?categoryIndex=8',
    # 'https://www.grainger.com/category/plumbing/bathroom-hardware/bathroom-mirrors-cabinets?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/single-hole-deck-mount-kitchen-sink-faucets/single-joystick-handle-single-hole-deck-mount-kitchen-sink-faucets?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/ball-valves?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/valve-actuators-enclosures-and-accessories/valve-enclosures?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/bathtubs-showers-repair-parts/bathtubs/bathtub-doors?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/drinking-fountains-bottle-fillers-water-dispensers?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/faucets/multipurpose-faucets/three-hole-widespread-deck-mount-multipurpose-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/single-hole-wall-mount-bathroom-faucets/single-cross-handle-single-hole-wall-mount-bathroom-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/pressure-and-temperature-control-valves/air-and-vacuum-release-valves?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/hand-sinks-hand-wash-stations?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/faucets/laboratory-faucets/single-hole-deck-mount-laboratory-faucets/single-wristblade-handle-single-hole-deck-mount-laboratory-faucets?categoryIndex=8',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/toilet-repair-parts-accessories/toilet-flush-valve-repair-parts-accessories?categoryIndex=8',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/two-hole-centerset-deck-mount-kitchen-sink-faucets/dual-dome-lever-handle-two-hole-centerset-deck-mount-kitchen-sink-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-aerators-outlets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/single-hole-deck-mount-kitchen-sink-faucets/single-side-joystick-handle-single-hole-deck-mount-kitchen-sink-faucets?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/water-heaters/electric-tankless-water-heaters?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/flow-control-valves/saddle-valves?categoryIndex=13',
    # 'https://www.grainger.com/category/plumbing/insulation/insulated-valve-jackets?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/cable-controlled-gas-shut-off-valves?categoryIndex=7',
    # 'https://www.grainger.com/category/plumbing/bathtubs-showers-repair-parts/bathtubs/bathtub-faucets?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/drains-and-drainage/drains/drain-openers?categoryIndex=7',
    # 'https://www.grainger.com/category/plumbing/drains-and-drainage/drains/drain-strainers?categoryIndex=9',
    # 'https://www.grainger.com/category/plumbing/bathtubs-showers-repair-parts/bathtub-shower-repair-parts?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/two-hole-off-centerset-wall-mount-bathroom-faucets?categoryIndex=7',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/three-hole-widespread-wall-mount-bathroom-faucets?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/insulation/pipe-insulation-jacketing?categoryIndex=9',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/two-hole-centerset-deck-mount-bathroom-faucets?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/drain-cocks?categoryIndex=9',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/glass-fillers/single-hole-deck-mount-glass-fillers?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/flush-valves-retrofit-kits/automatic-flush-valves?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/drinking-fountains-bottle-fillers-water-dispensers/water-coolers-dispensers?categoryIndex=7',
    # 'https://www.grainger.com/category/plumbing/liquid-level-gauges-and-sight-indicators?categoryIndex=11',
    # 'https://www.grainger.com/category/plumbing/water-filtration-purification-systems?categoryIndex=18',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-repair-clamps-and-couplings/pipe-repair-wrap?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/bar-sink-faucets/two-hole-off-centerset-deck-mount-bar-sink-faucets?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/flow-control-valves/butterfly-valves?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/glass-fillers?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/pre-rinse-faucets/single-hole-deck-mount-pre-rinse-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/pressure-and-temperature-control-valves/relief-valves?categoryIndex=11',
    # 'https://www.grainger.com/category/plumbing/faucets/utility-faucets/laundry-sink-faucets/two-hole-widespread-wall-mount-laundry-sink-faucets?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/toilet-repair-parts-accessories/pressure-assist-tank-repair-parts?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/three-hole-widespread-deck-mount-kitchen-sink-faucets?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/pneumatic-toggle-valves?categoryIndex=20',
    # 'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/portable-hand-sinks-hand-wash-stations/portable-hand-sinks?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/single-hole-deck-mount-bathroom-faucets/dual-wristblade-handle-single-hole-deck-mount-bathroom-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/single-hole-deck-mount-bathroom-faucets/dual-lever-handle-single-hole-deck-mount-bathroom-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/gas-and-water-line-connectors?categoryIndex=8',
    # 'https://www.grainger.com/category/plumbing/plumbing-replacement-parts/plumbing-parts?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/pre-rinse-faucets?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-handles-foot-pedals/replacement-faucet-handles?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/water-filtration-purification-systems/appliance-water-filter-systems?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/drains-and-drainage/drains/trench-drains?categoryIndex=13',
    # 'https://www.grainger.com/category/plumbing/faucets/multipurpose-faucets/two-hole-centerset-deck-mount-multipurpose-faucets/dual-wristblade-handle-two-hole-centerset-deck-mount-multipurpose-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/wash-fountains?categoryIndex=9',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/two-hole-centerset-deck-mount-bathroom-faucets/dual-wristblade-handle-two-hole-centerset-deck-mount-bathroom-faucets?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-sensor-parts?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/kitchen-sink-faucets/four-hole-widespread-with-sprayer-deck-mount-kitchen-sink-faucets/dual-lever-handle-four-hole-widespread-with-sprayer-deck-mount-kitchen-sink-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/two-hole-centerset-deck-mount-bathroom-faucets/single-metering-handle-two-hole-centerset-deck-mount-bathroom-faucets?categoryIndex=9',
    # 'https://www.grainger.com/category/plumbing/faucets/utility-faucets/service-sink-faucets/two-hole-widespread-wall-mount-service-sink-faucets/dual-lever-handle-two-hole-widespread-wall-mount-service-sink-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/insulation/pipe-insulation-sheets?categoryIndex=10',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-repair-clamps-and-couplings/pipe-repair-clamps?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/toilets/portable-toilets-commode-chairs?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/pressure-and-temperature-control-valves/water-hammer-arrestors?categoryIndex=17',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/two-hole-centerset-deck-mount-bathroom-faucets/dual-knob-handle-two-hole-centerset-deck-mount-bathroom-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/single-hole-wall-mount-bathroom-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/flush-valves-retrofit-kits/service-sink-flush-valves?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/faucets/utility-faucets/laundry-sink-faucets/two-hole-centerset-deck-mount-laundry-sink-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/utility-faucets/service-sink-faucets/three-hole-widespread-wall-mount-service-sink-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/faucets/laboratory-faucets/single-hole-deck-mount-laboratory-faucets/dual-wristblade-handle-single-hole-deck-mount-laboratory-faucets?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/hospital-lab-sinks?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/bathtubs-showers-repair-parts/showers/shower-doors?categoryIndex=9',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/stop-and-waste-valves?categoryIndex=23',
    # 'https://www.grainger.com/category/plumbing/faucets?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/water-filtration-purification-systems/process-water-filter-systems/drop-in-filter-cartridges?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/insulation/ceramic-fiber-insulation?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-spouts-spout-extensions?categoryIndex=7',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/gas-cocks?categoryIndex=14',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/ball-valves/flanged-ball-valves?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/utility-faucets/service-sink-faucets/two-hole-centerset-wall-mount-service-sink-faucets?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/pre-rinse-faucets/two-hole-widespread-deck-mount-pre-rinse-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/axial-valves?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/emergency-shut-off-devices?categoryIndex=12',
    # 'https://www.grainger.com/category/plumbing/faucets/laboratory-faucets/single-hole-deck-mount-laboratory-faucets/single-lever-handle-single-hole-deck-mount-laboratory-faucets?categoryIndex=7',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/valve-actuators-enclosures-and-accessories?categoryIndex=7',
    # 'https://www.grainger.com/category/plumbing/faucets/multipurpose-faucets/two-hole-centerset-deck-mount-multipurpose-faucets/dual-lever-handle-two-hole-centerset-deck-mount-multipurpose-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/water-filtration-purification-systems/drinking-water-filter-systems/complete-drinking-water-filtration-systems?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-spouts-spout-extensions/glass-filler-faucet-spouts?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/water-filtration-purification-systems/appliance-water-filter-systems/appliance-water-filters?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/single-hole-wall-mount-bathroom-faucets/sensor-single-hole-wall-mount-bathroom-faucets?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/utility-faucets/laundry-sink-faucets/two-hole-centerset-wall-mount-laundry-sink-faucets?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/check-valves-and-backflow-preventers?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/garbage-disposals-and-accessories/garbage-disposals?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/float-valves-and-accessories/float-valves-with-float?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/sink-wash-fountain-parts-accessories/wash-fountain-parts-accessories?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/toilet-repair-parts-accessories?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/toilets/macerating-toilets?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/faucets/outdoor-hose-bibbs-hydrants/wall-hydrants?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/bathroom-hardware/bathroom-safety-bars-and-chairs?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/drains-and-drainage/drains/drain-interceptors?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/water-heaters?categoryIndex=19',
    # 'https://www.grainger.com/category/plumbing/faucets/kitchen-faucets/bar-sink-faucets/two-hole-centerset-deck-mount-bar-sink-faucets?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/bulkhead-tank-fittings?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/manifolds?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/faucets/laboratory-faucets/single-hole-deck-mount-laboratory-faucets/single-cross-handle-single-hole-deck-mount-laboratory-faucets?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/check-valves-and-backflow-preventers/backflow-preventer-repair-kits?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-repair-clamps-and-couplings/pipe-couplings?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/faucets/laboratory-faucets/single-hole-deck-mount-laboratory-faucets/single-knob-handle-single-hole-deck-mount-laboratory-faucets?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/check-valves-and-backflow-preventers/backwater-valves?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/faucets/multipurpose-faucets/two-hole-centerset-wall-mount-multipurpose-faucets?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/pressure-and-temperature-control-valves/excess-flow-valves?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/bathroom-hardware/shower-curtain-accessories?categoryIndex=13',
    # 'https://www.grainger.com/category/plumbing/garbage-disposals-and-accessories?categoryIndex=7',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/shut-off-valves/manual-diaphragm-valves?categoryIndex=17',
    # 'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/bathroom-sinks/pedestal-bathroom-sinks?categoryIndex=2',
    # 'https://www.grainger.com/category/plumbing/bathroom-hardware/towel-rings?categoryIndex=19',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/rotary-swivel-and-expansion-joints/rotary-joints-and-unions?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/check-valves-and-backflow-preventers/check-valves?categoryIndex=6',
    # 'https://www.grainger.com/category/plumbing/faucets/faucet-parts-accessories/faucet-spouts-spout-extensions/mid-arc-faucet-spouts?categoryIndex=9',
    # 'https://www.grainger.com/category/plumbing/faucets/utility-faucets/inside-sill-faucets/single-hole-wall-mount-inside-sill-faucets/single-blade-handle-single-hole-wall-mount-inside-sill-faucets?categoryIndex=2',
    #
    # 'https://www.grainger.com/category/plumbing/plumbing-valves/check-valves-and-backflow-preventers/backflow-preventers?categoryIndex=3',
    # 'https://www.grainger.com/category/plumbing/toilets-urinals-repair-parts/flush-valves-retrofit-kits?categoryIndex=1',
    # 'https://www.grainger.com/category/plumbing/drains-and-drainage/drains/drain-stoppers?categoryIndex=8',
    # 'https://www.grainger.com/category/plumbing/pipe-accessories/pipe-repair-clamps-and-couplings?categoryIndex=4',
    # 'https://www.grainger.com/category/plumbing/faucets/bathroom-faucets/three-hole-widespread-deck-mount-bathroom-faucets/dual-three-wing-canopy-handle-three-hole-widespread-deck-mount-bathroom-faucets?categoryIndex=5',
    # 'https://www.grainger.com/category/plumbing/sinks-wash-fountains-repair-parts/sink-wash-fountain-parts-accessories/air-gap-covers?categoryIndex=1'

]

c = 0
for url in mylist:
    try:
        c = c + 1
        driver.get(url)
        time.sleep(1)
        print('Product-url', c, url)

        total_height = driver.execute_script("return Math.max( document.body.scrollHeight, document.body.offsetHeight, document.documentElement.clientHeight, document.documentElement.scrollHeight, document.documentElement.offsetHeight );")
        scroll_position = driver.execute_script("return window.pageYOffset || document.documentElement.scrollTop || document.body.scrollTop || 0;")
        t = 0
        for i in range(scroll_position, total_height - 700, 700):
            driver.execute_script("window.scrollBy(0, 10000)", "")
            time.sleep(1)
            # print(i)
            """
            # table = driver.find_elements(By.XPATH, "//div[@class='J5ihJT']//table//td")        
            print(len(table))
            for a in table:
                time.sleep(2)
                link = a.find_elements(By.TAG_NAME, "a")
                for l in link:
                    url_links = l.get_attribute('href')
                    print(url_links)
            #         save = open("Motors.txt", 'a+', encoding="utf-8")
            #         save.write('\n' + url + '\t' + "'" + url_links + "',")
            # print('save urls into text files')
            """

            t +=1
            try:
                driver.execute_script('return document.querySelector("#category-container > section.dNNbs2.category-list-view__wrapper > div > button")').click()
                time.sleep(7)
                print('Try..click', t)
            except AttributeError:
                driver.execute_script('return document.querySelector("#category-container > section.dNNbs2.category-list-view__wrapper > div > button")').click()
                print('Exception...click', t)
        print('exit and get into product for loop')
        try:
            driver.execute_script('return document.querySelector("#category-container > section.dNNbs2.category-list-view__wrapper > div > button")').click()
            time.sleep(2)
        except AttributeError:
            print('N')
        for product in driver.find_elements(By.XPATH, "//section[@aria-label='Category products']//li//a"):
            url_links = product.get_attribute('href')
            print(url_links)
            # save = open("grainger_plumbing_total_urls.txt", 'a+', encoding="utf-8")
            # save.write('\n' + url + '\t' + "'" + url_links + "',")


    except Exception as e:
        save = open("remaining.txt", 'a+', encoding="utf-8")
        save.write('\n' + url)
        print(e)
