import requests
from bs4 import BeautifulSoup
import time
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from typing.io import TextIO

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"}
opts = Options()
opts.headless = False
driver = webdriver.Chrome(r"/home/pradeep/Music/chromedriver_linux64/chromedriver")
l = 0
mylist = [
    # 'https://www.zoro.com/search?q=panduit%20PWT75',
    # 'https://www.zoro.com/search?q=panduit%20FL12X12LG-A',
    # 'https://www.zoro.com/search?q=panduit%20FL25X25LG-A',
    # 'https://www.zoro.com/search?q=panduit%20FL50X50LG-A',
    # 'https://www.zoro.com/search?q=panduit%20H1.5X2LG6',
    # 'https://www.zoro.com/search?q=panduit%20H1.5X2WH6',
    # 'https://www.zoro.com/search?q=panduit%20H1.5X3LG6',
    # 'https://www.zoro.com/search?q=panduit%20H1.5X3WH6',
    # 'https://www.zoro.com/search?q=panduit%20HC1.5LG6',
    # 'https://www.zoro.com/search?q=panduit%20HC1.5WH6',
    # 'https://www.zoro.com/search?q=panduit%20H2X2LG6',
    # 'https://www.zoro.com/search?q=panduit%20H2X2WH6',
    # 'https://www.zoro.com/search?q=panduit%20H2X3LG6',
    # 'https://www.zoro.com/search?q=panduit%20H2X3WH6',
    # 'https://www.zoro.com/search?q=panduit%20H2X4LG6',
    # 'https://www.zoro.com/search?q=panduit%20H2X4WH6',
    # 'https://www.zoro.com/search?q=panduit%20HC2LG6',
    # 'https://www.zoro.com/search?q=panduit%20HC2WH6',
    # 'https://www.zoro.com/search?q=panduit%20H3X3LG6',
    # 'https://www.zoro.com/search?q=panduit%20H3X3WH6',
    # 'https://www.zoro.com/search?q=panduit%20H3X4LG6',
    # 'https://www.zoro.com/search?q=panduit%20H3X4WH6',
    # 'https://www.zoro.com/search?q=panduit%20HC3LG6',
    # 'https://www.zoro.com/search?q=panduit%20HC3WH6',
    # 'https://www.zoro.com/search?q=panduit%20H4X4LG6',
    # 'https://www.zoro.com/search?q=panduit%20H4X4WH6',
    # 'https://www.zoro.com/search?q=panduit%20HC4LG6',
    # 'https://www.zoro.com/search?q=panduit%20HC4WH6',
    # 'https://www.zoro.com/search?q=panduit%20HS1.5X2LG6NM',
    # 'https://www.zoro.com/search?q=panduit%20HS1.5X2WH6NM',
    # 'https://www.zoro.com/search?q=panduit%20HS1.5X3LG6NM',
    # 'https://www.zoro.com/search?q=panduit%20HS1.5X3WH6NM',
    # 'https://www.zoro.com/search?q=panduit%20HS2X2LG6NM',
    # 'https://www.zoro.com/search?q=panduit%20HS2X2WH6NM',
    # 'https://www.zoro.com/search?q=panduit%20HS2X3LG6NM',
    # 'https://www.zoro.com/search?q=panduit%20HS2X3WH6NM',
    # 'https://www.zoro.com/search?q=panduit%20HS2X4WH6NM',
    # 'https://www.zoro.com/search?q=panduit%20HS3X3LG6NM',
    # 'https://www.zoro.com/search?q=panduit%20HS3X3WH6NM',
    # 'https://www.zoro.com/search?q=panduit%20HS3X4LG6NM',
    # 'https://www.zoro.com/search?q=panduit%20HS3X4WH6NM',
    # 'https://www.zoro.com/search?q=panduit%20HS4X4LG6NM',
    # 'https://www.zoro.com/search?q=panduit%20HS4X4WH6NM',
    # 'https://www.zoro.com/search?q=panduit%20SGABM25-A-C',
    # 'https://www.zoro.com/search?q=panduit%20SGABM40-A-L',
    # 'https://www.zoro.com/search?q=panduit%20SGABM50-A-L',
    # 'https://www.zoro.com/search?q=panduit%20SGABM20-A-C',
    # 'https://www.zoro.com/search?q=panduit%20SGMPMS25-C0',
    # 'https://www.zoro.com/search?q=panduit%20SGMPMH38-L0',
    # 'https://www.zoro.com/search?q=panduit%20ACC38-A-C',
    # 'https://www.zoro.com/search?q=panduit%20CCS25-S8-C',
    # 'https://www.zoro.com/search?q=panduit%20CCH38-S10-C',
    # 'https://www.zoro.com/search?q=panduit%20CCS50-S8-C',
    # 'https://www.zoro.com/search?q=panduit%20SG100M-C',
    # 'https://www.zoro.com/search?q=panduit%20SG100M-C0',
    # 'https://www.zoro.com/search?q=panduit%20SG150I-C',
    # 'https://www.zoro.com/search?q=panduit%20SG150I-C0',
    # 'https://www.zoro.com/search?q=panduit%20SG200S-C',
    # 'https://www.zoro.com/search?q=panduit%20SG200S-C0',
    # 'https://www.zoro.com/search?q=panduit%20SG300S-C',
    # 'https://www.zoro.com/search?q=panduit%20SG300S-C0',
    # 'https://www.zoro.com/search?q=panduit%20SG350LHG-Q',
    # 'https://www.zoro.com/search?q=panduit%20SG350LHG-Q0',
    # 'https://www.zoro.com/search?q=panduit%20SG370SG-L',
    # 'https://www.zoro.com/search?q=panduit%20SG370SG-L0',
    # 'https://www.zoro.com/search?q=panduit%20SG450HG-Q',
    # 'https://www.zoro.com/search?q=panduit%20SG450HG-Q0',
    # 'https://www.zoro.com/search?q=panduit%20PWT100',
    # 'https://www.zoro.com/search?q=panduit%20PWT150',
    # 'https://www.zoro.com/search?q=panduit%20PW50F-T20',
    # 'https://www.zoro.com/search?q=panduit%20PW75F-C20',
    # 'https://www.zoro.com/search?q=panduit%20PW100F-C20',
    # 'https://www.zoro.com/search?q=panduit%20PW150F-L20',
    # 'https://www.zoro.com/search?q=panduit%20T25F-C',
    # 'https://www.zoro.com/search?q=panduit%20T38F-C',
    # 'https://www.zoro.com/search?q=panduit%20T50F-C',
    # 'https://www.zoro.com/search?q=panduit%20T75F-C',
    # 'https://www.zoro.com/search?q=panduit%20T100F-C',
    # 'https://www.zoro.com/search?q=panduit%20SE50P-CR0',
    # 'https://www.zoro.com/search?q=panduit%20SE50PFR-CR0',
    # 'https://www.zoro.com/search?q=panduit%20GEE62F-A-C',
    # 'https://www.zoro.com/search?q=panduit%20GES62F-A-C',
    # 'https://www.zoro.com/search?q=panduit%20GEE99F-A-C',
    # 'https://www.zoro.com/search?q=panduit%20GES99F-A-C',
    # 'https://www.zoro.com/search?q=panduit%20JP2W',
    # 'https://www.zoro.com/search?q=panduit%20PLT1.5IG-C',
    # 'https://www.zoro.com/search?q=panduit%20PLT1.5IG-C0',
    # 'https://www.zoro.com/search?q=panduit%20PLT1.5I-M',
    # 'https://www.zoro.com/search?q=panduit%20PLT1.5I-M0',
    # 'https://www.zoro.com/search?q=panduit%20PLT10LHG-L',
    # 'https://www.zoro.com/search?q=panduit%20PLT1MG-C',
    # 'https://www.zoro.com/search?q=panduit%20PLT1MG-C0',
    # 'https://www.zoro.com/search?q=panduit%20PLT1M-M',
    # 'https://www.zoro.com/search?q=panduit%20PLT1M-M0',
    # 'https://www.zoro.com/search?q=panduit%20PLT2IG-C',
    # 'https://www.zoro.com/search?q=panduit%20PLT2IG-C0',
    # 'https://www.zoro.com/search?q=panduit%20PLT2I-M',
    # 'https://www.zoro.com/search?q=panduit%20PLT2I-M0',
    # 'https://www.zoro.com/search?q=panduit%20PLT2MG-C',
    # 'https://www.zoro.com/search?q=panduit%20PLT2MG-C0',
    # 'https://www.zoro.com/search?q=panduit%20PLT2M-M',
    # 'https://www.zoro.com/search?q=panduit%20PLT2M-M0',
    # 'https://www.zoro.com/search?q=panduit%20PLT2SG-C',
    # 'https://www.zoro.com/search?q=panduit%20PLT2SG-C0',
    # 'https://www.zoro.com/search?q=panduit%20PLT2S-M',
    # 'https://www.zoro.com/search?q=panduit%20PLT2S-M0',
    # 'https://www.zoro.com/search?q=panduit%20PLT3IG-C',
    # 'https://www.zoro.com/search?q=panduit%20PLT3IG-C0',
    # 'https://www.zoro.com/search?q=panduit%20PLT3I-M',
    # 'https://www.zoro.com/search?q=panduit%20PLT3I-M0',
    # 'https://www.zoro.com/search?q=panduit%20PLT3SG-C',
    # 'https://www.zoro.com/search?q=panduit%20PLT3SG-C0',
    # 'https://www.zoro.com/search?q=panduit%20PLT3S-M',
    # 'https://www.zoro.com/search?q=panduit%20PLT3S-M0',
    # 'https://www.zoro.com/search?q=panduit%20PLT4IG-C',
    # 'https://www.zoro.com/search?q=panduit%20PLT4IG-C0',
    # 'https://www.zoro.com/search?q=panduit%20PLT4I-M',
    # 'https://www.zoro.com/search?q=panduit%20PLT4I-M0',
    # 'https://www.zoro.com/search?q=panduit%20PLT4SG-C',
    # 'https://www.zoro.com/search?q=panduit%20PLT4S-M',
    # 'https://www.zoro.com/search?q=panduit%20PLT4S-M0',
    # 'https://www.zoro.com/search?q=panduit%20PLT6LHG-L',
    # 'https://www.zoro.com/search?q=panduit%20PLT6LHG-L0',
    # 'https://www.zoro.com/search?q=panduit%20PLT7LHG-L',
    # 'https://www.zoro.com/search?q=panduit%20PLT7LHG-L0',
    # 'https://www.zoro.com/search?q=panduit%20PLT8LHG-L',
    # 'https://www.zoro.com/search?q=panduit%20PLT8LHG-L0',
    # 'https://www.zoro.com/search?q=panduit%20PLT9LHG-L',
    # 'https://www.zoro.com/search?q=panduit%20PLT9LHG-L0',
    # 'https://www.zoro.com/search?q=panduit%20GB2B0306TPI-1',
    # 'https://www.zoro.com/search?q=panduit%20GB4B1028TPI-1',
    # 'https://www.zoro.com/search?q=panduit%20GB4N0016TPI-1',
    # 'https://www.zoro.com/search?q=panduit%20RGRB19Y',
    # 'https://www.zoro.com/search?q=panduit%20MLT1S-CP',
    # 'https://www.zoro.com/search?q=panduit%20MLT2S-CP',
    # 'https://www.zoro.com/search?q=panduit%20MLT4S-CP',
    # 'https://www.zoro.com/search?q=panduit%20MLT6S-CP',
    # 'https://www.zoro.com/search?q=panduit%20MLT2H-LP',
    # 'https://www.zoro.com/search?q=panduit%20MLT4H-LP',
    # 'https://www.zoro.com/search?q=panduit%20MLT6H-LP',
    # 'https://www.zoro.com/search?q=panduit%20MLT1S-CP316',
    # 'https://www.zoro.com/search?q=panduit%20MLT2S-CP316',
    # 'https://www.zoro.com/search?q=panduit%20MLT4S-CP316',
    # 'https://www.zoro.com/search?q=panduit%20MLT6S-CP316',
    # 'https://www.zoro.com/search?q=panduit%20MLT2H-LP316',
    # 'https://www.zoro.com/search?q=panduit%20MLT4H-LP316',
    # 'https://www.zoro.com/search?q=panduit%20MLT6H-LP316',
    # 'https://www.zoro.com/search?q=panduit%20MRT2S-C4',
    # 'https://www.zoro.com/search?q=panduit%20MRT4S-C4',
    # 'https://www.zoro.com/search?q=panduit%20MRT6S-C4',
    # 'https://www.zoro.com/search?q=panduit%20MRT1.5LH-L4',
    # 'https://www.zoro.com/search?q=panduit%20MRT2LH-L4',
    # 'https://www.zoro.com/search?q=panduit%20MRT4LH-L4',
    # 'https://www.zoro.com/search?q=panduit%20MRT6LH-L4',
    # 'https://www.zoro.com/search?q=panduit%20MRS1S-C4',
    # 'https://www.zoro.com/search?q=panduit%20MRS2S-C4',
    # 'https://www.zoro.com/search?q=panduit%20MRS4S-C4',
    # 'https://www.zoro.com/search?q=panduit%20MRS1.5LH-L4',
    # 'https://www.zoro.com/search?q=panduit%20MRS2LH-L4',
    # 'https://www.zoro.com/search?q=panduit%20MRS4LH-L4',
    # 'https://www.zoro.com/search?q=panduit%20GS4MT',
    # 'https://www.zoro.com/search?q=panduit%20ST2MT',
    # 'https://www.zoro.com/search?q=panduit%20MTRTLS',
    # 'https://www.zoro.com/search?q=panduit%20BT1M-C',
    # 'https://www.zoro.com/search?q=panduit%20BT1M-C0',
    # 'https://www.zoro.com/search?q=panduit%20BT1M-M',
    # 'https://www.zoro.com/search?q=panduit%20BT1M-M0',
    # 'https://www.zoro.com/search?q=panduit%20BT1.5M-C',
    # 'https://www.zoro.com/search?q=panduit%20BT1.5M-C0',
    # 'https://www.zoro.com/search?q=panduit%20BT1.5M-M',
    # 'https://www.zoro.com/search?q=panduit%20BT1.5M-M0',
    # 'https://www.zoro.com/search?q=panduit%20BT2M-C',
    # 'https://www.zoro.com/search?q=panduit%20BT2M-C0',
    # 'https://www.zoro.com/search?q=panduit%20BT2M-M',
    # 'https://www.zoro.com/search?q=panduit%20BT2M-M0',
    # 'https://www.zoro.com/search?q=panduit%20BT4M-C',
    # 'https://www.zoro.com/search?q=panduit%20BT4M-C0',
    # 'https://www.zoro.com/search?q=panduit%20BT4M-M',
    # 'https://www.zoro.com/search?q=panduit%20BT4M-M0',
    # 'https://www.zoro.com/search?q=panduit%20BT1.5I-C',
    # 'https://www.zoro.com/search?q=panduit%20BT1.5I-C0',
    # 'https://www.zoro.com/search?q=panduit%20BT1.5I-M',
    # 'https://www.zoro.com/search?q=panduit%20BT1.5I-M0',
    # 'https://www.zoro.com/search?q=panduit%20BT2I-C',
    # 'https://www.zoro.com/search?q=panduit%20BT2I-C0',
    # 'https://www.zoro.com/search?q=panduit%20BT2I-M',
    # 'https://www.zoro.com/search?q=panduit%20BT2I-M0',
    # 'https://www.zoro.com/search?q=panduit%20BT3I-C',
    # 'https://www.zoro.com/search?q=panduit%20BT3I-C0',
    # 'https://www.zoro.com/search?q=panduit%20BT3I-M',
    # 'https://www.zoro.com/search?q=panduit%20BT3I-M0',
    # 'https://www.zoro.com/search?q=panduit%20BT4I-C',
    # 'https://www.zoro.com/search?q=panduit%20BT4I-C0',
    # 'https://www.zoro.com/search?q=panduit%20BT4I-M',
    # 'https://www.zoro.com/search?q=panduit%20BT4I-M0',
    # 'https://www.zoro.com/search?q=panduit%20BT2S-C',
    # 'https://www.zoro.com/search?q=panduit%20BT2S-C0',
    # 'https://www.zoro.com/search?q=panduit%20BT2S-M',
    # 'https://www.zoro.com/search?q=panduit%20BT2S-M0',
    # 'https://www.zoro.com/search?q=panduit%20BT3S-C',
    # 'https://www.zoro.com/search?q=panduit%20BT3S-C0',
    # 'https://www.zoro.com/search?q=panduit%20BT3S-M',
    # 'https://www.zoro.com/search?q=panduit%20BT3S-M0',
    # 'https://www.zoro.com/search?q=panduit%20BT4S-C',
    # 'https://www.zoro.com/search?q=panduit%20BT4S-C0',
    # 'https://www.zoro.com/search?q=panduit%20BT4S-M',
    # 'https://www.zoro.com/search?q=panduit%20BT4S-M0',
    # 'https://www.zoro.com/search?q=panduit%20BT2LH-L',
    # 'https://www.zoro.com/search?q=panduit%20BT2LH-L0',
    # 'https://www.zoro.com/search?q=panduit%20BT2LH-TL',
    # 'https://www.zoro.com/search?q=panduit%20BT2LH-TL0',
    # 'https://www.zoro.com/search?q=panduit%20BT4LH-L',
    # 'https://www.zoro.com/search?q=panduit%20BT4LH-L0',
    # 'https://www.zoro.com/search?q=panduit%20BT4LH-TL',
    # 'https://www.zoro.com/search?q=panduit%20BT4LH-TL0',
    # 'https://www.zoro.com/search?q=panduit%20BT5LH-L',
    # 'https://www.zoro.com/search?q=panduit%20BT5LH-L0',
    # 'https://www.zoro.com/search?q=panduit%20BT6LH-L0',
    # 'https://www.zoro.com/search?q=panduit%20BT7LH-L',
    # 'https://www.zoro.com/search?q=panduit%20BT7LH-L0',
    # 'https://www.zoro.com/search?q=panduit%20BT8LH-L',
    # 'https://www.zoro.com/search?q=panduit%20BT8LH-L0',
    # 'https://www.zoro.com/search?q=panduit%20BT9LH-L',
    # 'https://www.zoro.com/search?q=panduit%20BT9LH-L0',
    # 'https://www.zoro.com/search?q=panduit%20BC2S-S10-C',
    # 'https://www.zoro.com/search?q=panduit%20BC2S-S10-C0',
    # 'https://www.zoro.com/search?q=panduit%20BC4S-S10-C',
    # 'https://www.zoro.com/search?q=panduit%20BC4S-S10-C0',
    # 'https://www.zoro.com/search?q=panduit%20BC4LH-S25-L',
    # 'https://www.zoro.com/search?q=panduit%20BC4LH-S25-L0',
    # 'https://www.zoro.com/search?q=panduit%20PLT2S-C71',
    # 'https://www.zoro.com/search?q=panduit%20PLT1M-C76',
    # 'https://www.zoro.com/search?q=panduit%20PLT2I-C76',
    # 'https://www.zoro.com/search?q=panduit%20PLT2S-C76',
    # 'https://www.zoro.com/search?q=panduit%20PLT3S-C76',
    # 'https://www.zoro.com/search?q=panduit%20PLT4S-C76',
    # 'https://www.zoro.com/search?q=panduit%20PLT3H-L76',
    # 'https://www.zoro.com/search?q=panduit%20PLT4H-L76',
    # 'https://www.zoro.com/search?q=panduit%20HLT2I-X0',
    # 'https://www.zoro.com/search?q=panduit%20HLT3I-X0',
    # 'https://www.zoro.com/search?q=panduit%20HLS1.5S-X0',
    # 'https://www.zoro.com/search?q=panduit%20HLS3S-X0',
    # 'https://www.zoro.com/search?q=panduit%20HLS5S-X0',
    # 'https://www.zoro.com/search?q=panduit%20HLM-15R0',
    # 'https://www.zoro.com/search?q=panduit%20HLS-15R0',
    # 'https://www.zoro.com/search?q=panduit%20HLS-75R0',
    # 'https://www.zoro.com/search?q=panduit%20HLTP2I-X0',
    # 'https://www.zoro.com/search?q=panduit%20HLTP2I-X12',
    # 'https://www.zoro.com/search?q=panduit%20HLTP3I-X0',
    # 'https://www.zoro.com/search?q=panduit%20HLTP3I-X12',
    # 'https://www.zoro.com/search?q=panduit%20HLSP1.5S-X0',
    # 'https://www.zoro.com/search?q=panduit%20HLSP1.5S-X12',
    # 'https://www.zoro.com/search?q=panduit%20HLSP3S-X0',
    # 'https://www.zoro.com/search?q=panduit%20HLSP3S-X12',
    # 'https://www.zoro.com/search?q=panduit%20HLSP5S-X0',
    # 'https://www.zoro.com/search?q=panduit%20TTS-35RX0',
    # 'https://www.zoro.com/search?q=panduit%20UCT3S-X0',
    # 'https://www.zoro.com/search?q=panduit%20UGCTC3S-X0',
    # 'https://www.zoro.com/search?q=panduit%20UGCTE3S-X0',
    # 'https://www.zoro.com/search?q=panduit%20ERT2M-C20',
    # 'https://www.zoro.com/search?q=panduit%20HLB2S-C0',
    # 'https://www.zoro.com/search?q=panduit%20D2H6',
    # 'https://www.zoro.com/search?q=panduit%20D3H6',
    # 'https://www.zoro.com/search?q=panduit%20D4H6',
    # 'https://www.zoro.com/search?q=panduit%20SD2H6',
    # 'https://www.zoro.com/search?q=panduit%20SD3H6',
    # 'https://www.zoro.com/search?q=panduit%20SD4H6',
    # 'https://www.zoro.com/search?q=panduit%20DB-C',
    # 'https://www.zoro.com/search?q=panduit%20DFCT',
    # 'https://www.zoro.com/search?q=panduit%20DCT',
    # 'https://www.zoro.com/search?q=panduit%20DNT-100',
    # 'https://www.zoro.com/search?q=panduit%20HN1.5X2LG6',
    # 'https://www.zoro.com/search?q=panduit%20HN1.5X2WH6',
    # 'https://www.zoro.com/search?q=panduit%20HN1.5X3LG6',
    # 'https://www.zoro.com/search?q=panduit%20HN1.5X3WH6',
    # 'https://www.zoro.com/search?q=panduit%20HN2X2LG6',
    # 'https://www.zoro.com/search?q=panduit%20HN2X2WH6',
    # 'https://www.zoro.com/search?q=panduit%20HN2X3LG6',
    # 'https://www.zoro.com/search?q=panduit%20HN2X4LG6',
    # 'https://www.zoro.com/search?q=panduit%20HN3X3LG6',
    # 'https://www.zoro.com/search?q=panduit%20HN3X4LG6',
    # 'https://www.zoro.com/search?q=panduit%20HN4X4LG6',
    # 'https://www.zoro.com/search?q=panduit%20CBOT24K',
    # 'https://www.zoro.com/search?q=panduit%20G2X2WH6',
    # 'https://www.zoro.com/search?q=panduit%20G2X3LG6',
    # 'https://www.zoro.com/search?q=panduit%20G2X3WH6',
    # 'https://www.zoro.com/search?q=panduit%20G2X4LG6',
    # 'https://www.zoro.com/search?q=panduit%20G2X4WH6',
    # 'https://www.zoro.com/search?q=panduit%20G2X5LG6',
    # 'https://www.zoro.com/search?q=panduit%20G2X5WH6',
    # 'https://www.zoro.com/search?q=panduit%20G3X3LG6',
    # 'https://www.zoro.com/search?q=panduit%20G3X3WH6',
    # 'https://www.zoro.com/search?q=panduit%20G3X4LG6',
    # 'https://www.zoro.com/search?q=panduit%20G3X4WH6',
    # 'https://www.zoro.com/search?q=panduit%20G3X5LG6',
    # 'https://www.zoro.com/search?q=panduit%20G3X5WH6',
    # 'https://www.zoro.com/search?q=panduit%20G4X3LG6',
    # 'https://www.zoro.com/search?q=panduit%20G4X3WH6',
    # 'https://www.zoro.com/search?q=panduit%20G4X4LG6',
    # 'https://www.zoro.com/search?q=panduit%20G4X4WH6',
    # 'https://www.zoro.com/search?q=panduit%20G4X5LG6',
    # 'https://www.zoro.com/search?q=panduit%20G4X5WH6',
    # 'https://www.zoro.com/search?q=panduit%20G1.5X1.5LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20G1.5X2LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20G1.5X3LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20G1.5X4LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20G1X1.5LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20G1X1LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20G1X2LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20G1X3LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20G1X4LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20G2X2LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20G2X3LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20G2X4LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20G3X3LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20G3X4LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20G4X4LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20G4X5LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20F1.5X1.5LG6',
    # 'https://www.zoro.com/search?q=panduit%20F1.5X1.5WH6',
    # 'https://www.zoro.com/search?q=panduit%20F1.5X2LG6',
    # 'https://www.zoro.com/search?q=panduit%20F1.5X2WH6',
    # 'https://www.zoro.com/search?q=panduit%20F1.5X3LG6',
    # 'https://www.zoro.com/search?q=panduit%20F1.5X3WH6',
    # 'https://www.zoro.com/search?q=panduit%20F1.5X4LG6',
    # 'https://www.zoro.com/search?q=panduit%20F1.5X4WH6',
    # 'https://www.zoro.com/search?q=panduit%20F1X1.5LG6',
    # 'https://www.zoro.com/search?q=panduit%20F1X1.5WH6',
    # 'https://www.zoro.com/search?q=panduit%20F1X1LG6',
    # 'https://www.zoro.com/search?q=panduit%20F1X1WH6',
    # 'https://www.zoro.com/search?q=panduit%20F1X2LG6',
    # 'https://www.zoro.com/search?q=panduit%20F1X2WH6',
    # 'https://www.zoro.com/search?q=panduit%20F1X3LG6',
    # 'https://www.zoro.com/search?q=panduit%20F1X3WH6',
    # 'https://www.zoro.com/search?q=panduit%20F1X4LG6',
    # 'https://www.zoro.com/search?q=panduit%20F1X4WH6',
    # 'https://www.zoro.com/search?q=panduit%20F2X2LG6',
    # 'https://www.zoro.com/search?q=panduit%20F2X2WH6',
    # 'https://www.zoro.com/search?q=panduit%20F2X3LG6',
    # 'https://www.zoro.com/search?q=panduit%20F2X3WH6',
    # 'https://www.zoro.com/search?q=panduit%20F2X4LG6',
    # 'https://www.zoro.com/search?q=panduit%20F2X4WH6',
    # 'https://www.zoro.com/search?q=panduit%20F3X3LG6',
    # 'https://www.zoro.com/search?q=panduit%20F3X3WH6',
    # 'https://www.zoro.com/search?q=panduit%20F3X4LG6',
    # 'https://www.zoro.com/search?q=panduit%20F3X4WH6',
    # 'https://www.zoro.com/search?q=panduit%20F3X5LG6',
    # 'https://www.zoro.com/search?q=panduit%20F3X5WH6',
    # 'https://www.zoro.com/search?q=panduit%20F4X3LG6',
    # 'https://www.zoro.com/search?q=panduit%20F4X3WH6',
    # 'https://www.zoro.com/search?q=panduit%20F4X4LG6',
    # 'https://www.zoro.com/search?q=panduit%20F4X4WH6',
    # 'https://www.zoro.com/search?q=panduit%20F4X5LG6',
    # 'https://www.zoro.com/search?q=panduit%20F4X5WH6',
    # 'https://www.zoro.com/search?q=panduit%20F1.5X1.5LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20F1.5X2LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20F1.5X3LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20F1.5X4LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20F1X1.5LG6-A',
    'https://www.zoro.com/search?q=panduit%20F1X1LG6-A',
    'https://www.zoro.com/search?q=panduit%20F1X2LG6-A',
    'https://www.zoro.com/search?q=panduit%20F1X3LG6-A',

]


for url in mylist:
    try:
        l = l + 1
        r = requests.get(url)
        soup = BeautifulSoup(r.content, "html.parser")
        driver.get(url)
        driver.get(driver.current_url)
        # time.sleep(3)
        get_url = driver.current_url
        print("current = ", get_url)
        print("Products Urls", l, url)
        all_data = []
        all = driver.find_element(By.XPATH, "//ul[@class='product-identifiers pl-0 pb-2 product-specifications__identifiers my-4 pl-4']")
        data = all.find_elements(By.TAG_NAME, "li")
        for da in data:
            all_data.append(da.text)
        try:
            zoro = all_data[0]
        except:
            zoro = "Not Found"
            print("Not Found")
        try:
            mfr = all_data[1]
        except:
            mfr = "Not Found"
            print("Not Found")
        try:
            upc = all_data[2]
        except:
            upc = "Not Found"
            print("Not Found")
        print("zoro = ", zoro)
        print("mfr = ", mfr)
        print("upc = ", upc)
        save_details: TextIO = open("zoro.xlsx", "a+", encoding="utf-8")
        save_details.write("\n" + url + "\t" + get_url + "\t" + zoro + "\t" + mfr + "\t" + upc)
        save_details.close()
        print("\n ***** Record stored into upc  files. *****")

    except:
        save_details: TextIO = open("remaining_urls.xlsx", "a+", encoding="utf-8")
        save_details.write("\n" + url)
        save_details.close()
        print("\n ***** Record stored into upc  files. *****")
        print("Not Found")
        print("Not Found")
