import requests
from bs4 import BeautifulSoup
import time
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from typing.io import TextIO

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"}
opts = Options()
opts.headless = False
driver = webdriver.Chrome(r"/home/pradeep/Music/chromedriver_linux64/chromedriver")
l = 0
mylist = [

    # 'https://www.zoro.com/search?q=panduit%20F1X4LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20F2X2LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20F2X3LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20F2X4LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20F3X3LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20F3X4LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20F4X4LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20F4X5LG6-A',
    # 'https://www.zoro.com/search?q=panduit%20C1.5LG6-F',
    # 'https://www.zoro.com/search?q=panduit%20C1.5WH6-F',
    # 'https://www.zoro.com/search?q=panduit%20C1LG6-F',
    # 'https://www.zoro.com/search?q=panduit%20C1WH6-F',
    # 'https://www.zoro.com/search?q=panduit%20C2LG6-F',
    # 'https://www.zoro.com/search?q=panduit%20C2WH6-F',
    # 'https://www.zoro.com/search?q=panduit%20C3LG6-FG',
    # 'https://www.zoro.com/search?q=panduit%20C3WH6-F',
    # 'https://www.zoro.com/search?q=panduit%20C4LG6-F',
    # 'https://www.zoro.com/search?q=panduit%20C4WH6-F',
    # 'https://www.zoro.com/search?q=panduit%20CWD3LG6',
    # 'https://www.zoro.com/search?q=panduit%20CWD4LG6',
    # 'https://www.zoro.com/search?q=panduit%20CWD3WH6',
    # # 'https://www.zoro.com/search?q=panduit%20CWD4WH6',
    # # 'https://www.zoro.com/search?q=panduit%20TNR',
    # # 'https://www.zoro.com/search?q=panduit%20NR1-C',
    # 'https://www.zoro.com/search?q=panduit%20G1.5X1.5LG6',
    # # 'https://www.zoro.com/search?q=panduit%20G1.5X1.5WH6',
    # 'https://www.zoro.com/search?q=panduit%20G1.5X2LG6',
    # # 'https://www.zoro.com/search?q=panduit%20G1.5X2WH6',
    # 'https://www.zoro.com/search?q=panduit%20G1.5X3LG6',
    # # 'https://www.zoro.com/search?q=panduit%20G1.5X3WH6',
    # 'https://www.zoro.com/search?q=panduit%20G1.5X4LG6',
    # # 'https://www.zoro.com/search?q=panduit%20G1.5X4WH6',
    # 'https://www.zoro.com/search?q=panduit%20G1X1.5LG6',
    # 'https://www.zoro.com/search?q=panduit%20G1X1.5WH6',
    # 'https://www.zoro.com/search?q=panduit%20G1X1LG6',
    # # 'https://www.zoro.com/search?q=panduit%20G1X1WH6',
    # 'https://www.zoro.com/search?q=panduit%20G1X2LG6',
    # # 'https://www.zoro.com/search?q=panduit%20G1X2WH6',
    # 'https://www.zoro.com/search?q=panduit%20G1X3LG6',
    # # 'https://www.zoro.com/search?q=panduit%20G1X3WH6',
    # 'https://www.zoro.com/search?q=panduit%20G1X4LG6',
    # 'https://www.zoro.com/search?q=panduit%20G1X4WH6',
    # 'https://www.zoro.com/search?q=panduit%20G2X2LG6',
    # # 'https://www.zoro.com/search?q=panduit%20MMP350-C',
    # # 'https://www.zoro.com/search?q=panduit%20MMP350-C316',
    # # 'https://www.zoro.com/search?q=panduit%20MMP350H-C',
    # # 'https://www.zoro.com/search?q=panduit%20MMP350H-C316',
    # # 'https://www.zoro.com/search?q=panduit%20MT172-C',
    # # 'https://www.zoro.com/search?q=panduit%20MT172-C316',
    # # 'https://www.zoro.com/search?q=panduit%20MMP172W38-C',
    # # 'https://www.zoro.com/search?q=panduit%20MMP172W38-C316',
    # 'https://www.zoro.com/search?q=panduit%20MMP350H-CAL',
    # # 'https://www.zoro.com/search?q=panduit%20MLT2H-LPAL',
    # # 'https://www.zoro.com/search?q=panduit%20MLT4H-LPAL',
    # 'https://www.zoro.com/search?q=panduit%20MIM187',
    # 'https://www.zoro.com/search?q=panduit%20JP75DW-L20',
    # 'https://www.zoro.com/search?q=panduit%20JP75W-L20',
    # # 'https://www.zoro.com/search?q=panduit%20JP131DW-L20',
    # # 'https://www.zoro.com/search?q=panduit%20JP131W-L20',
    # 'https://www.zoro.com/search?q=panduit%20JP4W-X20',
    # 'https://www.zoro.com/search?q=panduit%20JP75DW-L2',
    # # 'https://www.zoro.com/search?q=panduit%20JP75W-L2',
    # # 'https://www.zoro.com/search?q=panduit%20JP2DW-L2',
    # 'https://www.zoro.com/search?q=panduit%20JP2W-L2',
    # 'https://www.zoro.com/search?q=panduit%20JP131W-L6',
    # 'https://www.zoro.com/search?q=panduit%20JP2DW-L6',
    # # 'https://www.zoro.com/search?q=panduit%20JP2W-L6',
    # 'https://www.zoro.com/search?q=panduit%20JP2DW-L',
    # 'https://www.zoro.com/search?q=panduit%20JP4W-X',
    # 'https://www.zoro.com/search?q=panduit%20PES-S1',
    # # 'https://www.zoro.com/search?q=panduit%20PVS0204C178Y',
    # 'https://www.zoro.com/search?q=panduit%20PVS0204C171Y',
    # 'https://www.zoro.com/search?q=panduit%20PVS0503N458Y',
    # 'https://www.zoro.com/search?q=panduit%20PSL-CBWL',
    # 'https://www.zoro.com/search?q=panduit%20HSTT-YK2',
    # 'https://www.zoro.com/search?q=panduit%20KP-HSTT2',
    # 'https://www.zoro.com/search?q=panduit%20PSL-DCJB',
    # 'https://www.zoro.com/search?q=panduit%20PSL-DCJB-BL',
    # 'https://www.zoro.com/search?q=panduit%20PSL-DCJB-BU',
    # 'https://www.zoro.com/search?q=panduit%20PSL-DCJB-GR',
    # 'https://www.zoro.com/search?q=panduit%20PSL-DCJB-IG',
    # 'https://www.zoro.com/search?q=panduit%20PSL-DCJB-IG-C',
    # 'https://www.zoro.com/search?q=panduit%20CJ5E88TBL',
    # 'https://www.zoro.com/search?q=panduit%20CJ5E88TBU',
    # 'https://www.zoro.com/search?q=panduit%20CJ5E88TEI',
    # 'https://www.zoro.com/search?q=panduit%20CJ5E88TWH',
    # 'https://www.zoro.com/search?q=panduit%20CJ5E88TIG',
    # 'https://www.zoro.com/search?q=panduit%20CJ5E88TIW',
    # 'https://www.zoro.com/search?q=panduit%20CJ688TPBL',
    # 'https://www.zoro.com/search?q=panduit%20CJ688TPBU',
    # 'https://www.zoro.com/search?q=panduit%20CJ688TPEI',
    # 'https://www.zoro.com/search?q=panduit%20CJ688TPWH',
    # 'https://www.zoro.com/search?q=panduit%20CJ688TPIG',
    # 'https://www.zoro.com/search?q=panduit%20CJ688TPIW',
    # 'https://www.zoro.com/search?q=panduit%20DP245E88TGY',
    # 'https://www.zoro.com/search?q=panduit%20DP24688TGY',
    # 'https://www.zoro.com/search?q=panduit%20DP485E88TGY',
    # 'https://www.zoro.com/search?q=panduit%20DP48688TGY',
    # 'https://www.zoro.com/search?q=panduit%20CPP24WBLY',
    # 'https://www.zoro.com/search?q=panduit%20CPPL24WBLY',
    # 'https://www.zoro.com/search?q=panduit%20CPP48WBLY',
    # 'https://www.zoro.com/search?q=panduit%20CPPL48WBLY',
    # 'https://www.zoro.com/search?q=panduit%20SRB19BLY',
    # 'https://www.zoro.com/search?q=panduit%20CC688BL',
    # 'https://www.zoro.com/search?q=panduit%20CMFIW',
    # 'https://www.zoro.com/search?q=panduit%20CMFEI',
    # 'https://www.zoro.com/search?q=panduit%20CMFWH',
    # 'https://www.zoro.com/search?q=panduit%20CMBIW-X',
    # 'https://www.zoro.com/search?q=panduit%20CMBEI-X',
    # 'https://www.zoro.com/search?q=panduit%20CMBWH-X',
    # 'https://www.zoro.com/search?q=panduit%20CMBBL-X',
    # 'https://www.zoro.com/search?q=panduit%20CFPE4IWY',
    # 'https://www.zoro.com/search?q=panduit%20CFPE4EIY',
    # 'https://www.zoro.com/search?q=panduit%20CFPE4WHY',
    # 'https://www.zoro.com/search?q=panduit%20CFPE2IWY',
    # 'https://www.zoro.com/search?q=panduit%20CFPE2EIY',
    # 'https://www.zoro.com/search?q=panduit%20CFPE2WHY',
    # 'https://www.zoro.com/search?q=panduit%20CBX2IW-AY',
    # 'https://www.zoro.com/search?q=panduit%20CBX2EI-AY',
    # 'https://www.zoro.com/search?q=panduit%20CBX2WH-AY',
    # 'https://www.zoro.com/search?q=panduit%20CBX4IW-AY',
    # 'https://www.zoro.com/search?q=panduit%20CBX4EI-AY',
    # 'https://www.zoro.com/search?q=panduit%20CBX4WH-AY',
    # 'https://www.zoro.com/search?q=panduit%20CFFPL4BL',
    # 'https://www.zoro.com/search?q=panduit%20CF1062IWY',
    # 'https://www.zoro.com/search?q=panduit%20CF1062EIY',
    # 'https://www.zoro.com/search?q=panduit%20CF1062WHY',
    # 'https://www.zoro.com/search?q=panduit%20CF1064IWY',
    # 'https://www.zoro.com/search?q=panduit%20CF1064EIY',
    # 'https://www.zoro.com/search?q=panduit%20CF1064WHY',
    # 'https://www.zoro.com/search?q=panduit%20CFG2WH',
    # 'https://www.zoro.com/search?q=panduit%20CFG4IW',
    # 'https://www.zoro.com/search?q=panduit%20CFG4WH',
    # 'https://www.zoro.com/search?q=panduit%20CMHDMIIW',
    # 'https://www.zoro.com/search?q=panduit%20CMHDMIEI',
    # 'https://www.zoro.com/search?q=panduit%20CMHDMIWH',
    # 'https://www.zoro.com/search?q=panduit%20FMT1',
    # 'https://www.zoro.com/search?q=panduit%20CFAPPBL1',
    # 'https://www.zoro.com/search?q=panduit%20FOSMF',
    # 'https://www.zoro.com/search?q=panduit%20FSC24',
    # 'https://www.zoro.com/search?q=panduit%20FAPB',
    # 'https://www.zoro.com/search?q=panduit%20FMP6',
    # 'https://www.zoro.com/search?q=panduit%20FMS1',
    # 'https://www.zoro.com/search?q=panduit%20FMS2',
    # 'https://www.zoro.com/search?q=panduit%20FWME2',
    # 'https://www.zoro.com/search?q=panduit%20CMDSAQLCZBL',
    # 'https://www.zoro.com/search?q=panduit%20CMDSLCZBU',
    # 'https://www.zoro.com/search?q=panduit%20CMDBUSCZBU',
    # 'https://www.zoro.com/search?q=panduit%20R2P',
    # 'https://www.zoro.com/search?q=panduit%20WMPV45E',
    # 'https://www.zoro.com/search?q=panduit%20WMPSE',
    # 'https://www.zoro.com/search?q=panduit%20WMP1E',
    # 'https://www.zoro.com/search?q=panduit%20CMPH1',
    # 'https://www.zoro.com/search?q=panduit%20CMPH2',
    # 'https://www.zoro.com/search?q=panduit%20CMPHF1',
    # 'https://www.zoro.com/search?q=panduit%20LDPH5IW8-A',
    # 'https://www.zoro.com/search?q=panduit%20CFX5IW-X',
    # 'https://www.zoro.com/search?q=panduit%20RAFX5IW-X',
    # 'https://www.zoro.com/search?q=panduit%20ICFX5IW-X',
    # 'https://www.zoro.com/search?q=panduit%20OCFC5IW-X',
    # 'https://www.zoro.com/search?q=panduit%20ECFX5IW-X',
    # 'https://www.zoro.com/search?q=panduit%20DCEFXIW-X',
    # 'https://www.zoro.com/search?q=panduit%20TG70IW8',
    # 'https://www.zoro.com/search?q=panduit%20TG70BCIW-X',
    # 'https://www.zoro.com/search?q=panduit%20T70CCIW-X',
    # 'https://www.zoro.com/search?q=panduit%20TGECIW',
    # 'https://www.zoro.com/search?q=panduit%20TG70WR-X',
    # 'https://www.zoro.com/search?q=panduit%20TGEEIW',
    # 'https://www.zoro.com/search?q=panduit%20T70DB-X',
    # 'https://www.zoro.com/search?q=panduit%20T70PIW',
    # 'https://www.zoro.com/search?q=panduit%20T70PGIW',
    # 'https://www.zoro.com/search?q=panduit%20T45BIW8',
    # 'https://www.zoro.com/search?q=panduit%20T45CIW8',
    # 'https://www.zoro.com/search?q=panduit%20T45ICIW',
    # 'https://www.zoro.com/search?q=panduit%20T45OCIW',
    # 'https://www.zoro.com/search?q=panduit%20T45RAIW',
    # 'https://www.zoro.com/search?q=panduit%20T45TIW',
    # 'https://www.zoro.com/search?q=panduit%20T45CCIW-X',
    # 'https://www.zoro.com/search?q=panduit%20T45EEIW',
    # 'https://www.zoro.com/search?q=panduit%20T45ECIW',
    # 'https://www.zoro.com/search?q=panduit%20T45WCIW',
    # 'https://www.zoro.com/search?q=panduit%20T45RLDIW',
    # 'https://www.zoro.com/search?q=panduit%20JBX3510IW-A',
    # 'https://www.zoro.com/search?q=panduit%20JB1FSIW-A',
    # 'https://www.zoro.com/search?q=panduit%20JBP2FSIW',
    # 'https://www.zoro.com/search?q=panduit%20JBP1DIW',
    # 'https://www.zoro.com/search?q=panduit%20JBP2DIW',
    # 'https://www.zoro.com/search?q=panduit%20JBP2SIW',
    # 'https://www.zoro.com/search?q=panduit%20CP106IW-2G',
    # 'https://www.zoro.com/search?q=panduit%20T70BIW8G',
    # 'https://www.zoro.com/search?q=panduit%20T70CIW8',
    # 'https://www.zoro.com/search?q=panduit%20T70ICIW',
    # 'https://www.zoro.com/search?q=panduit%20T70OCIW',
    # 'https://www.zoro.com/search?q=panduit%20T70RAIW',
    # 'https://www.zoro.com/search?q=panduit%20T70TIW',
    # 'https://www.zoro.com/search?q=panduit%20T70TD',
    # 'https://www.zoro.com/search?q=panduit%20T70BCIW-X',
    # 'https://www.zoro.com/search?q=panduit%20T70EEIW',
    # 'https://www.zoro.com/search?q=panduit%20T70ECIW',
    # 'https://www.zoro.com/search?q=panduit%20T70DW8',
    # 'https://www.zoro.com/search?q=panduit%20T70HB3-X',
    # 'https://www.zoro.com/search?q=panduit%20T70WC2IW',
    # 'https://www.zoro.com/search?q=panduit%20T70WR-X',
    # 'https://www.zoro.com/search?q=panduit%20T70TRIW',
    # 'https://www.zoro.com/search?q=panduit%20T70TRCIW',
    # 'https://www.zoro.com/search?q=panduit%20T70BFI',
    # 'https://www.zoro.com/search?q=panduit%20FS3X2LG6NM',
    # 'https://www.zoro.com/search?q=panduit%20FS3X3LG6NM',
    # 'https://www.zoro.com/search?q=panduit%20FS3X4LG6NM',
    # 'https://www.zoro.com/search?q=panduit%20FS2X3LG6NM',
    # 'https://www.zoro.com/search?q=panduit%20LD5IW8-A',
    # 'https://www.zoro.com/search?q=panduit%20CF5IW-E',
    # 'https://www.zoro.com/search?q=panduit%20ICF5IW-E',
    # 'https://www.zoro.com/search?q=panduit%20OCF5IW-E',
    # 'https://www.zoro.com/search?q=panduit%20RAF5IW-E',
    # 'https://www.zoro.com/search?q=panduit%20TF5IW-E',
    # 'https://www.zoro.com/search?q=panduit%20ECF5IW-E',
    # 'https://www.zoro.com/search?q=panduit%20DCF5IW-X',
    # 'https://www.zoro.com/search?q=panduit%20PSL-PL1BLKY',
    # 'https://www.zoro.com/search?q=panduit%20PSL-PL1GRNY',
    # 'https://www.zoro.com/search?q=panduit%20PSL-PL1WHTY',
    # 'https://www.zoro.com/search?q=panduit%20PLT2I-C86',
    # 'https://www.zoro.com/search?q=panduit%20PLT3S-C86',
    # 'https://www.zoro.com/search?q=panduit%20PLT4S-C86',
    # 'https://www.zoro.com/search?q=panduit%20PLT2S-C86',
    # 'https://www.zoro.com/search?q=panduit%20PSL-PL1REDY',
    # 'https://www.zoro.com/search?q=panduit%20PLT1M-C86',
    # 'https://www.zoro.com/search?q=panduit%20CD-930G-1/0',
    # 'https://www.zoro.com/search?q=panduit%20CD-930G-250',
    # 'https://www.zoro.com/search?q=panduit%20CD-930G-500',
    # 'https://www.zoro.com/search?q=panduit%20RGESD2-1',
    # 'https://www.zoro.com/search?q=panduit%20RGESD2B-1',
    # 'https://www.zoro.com/search?q=panduit%20RGESDWS',
    # 'https://www.zoro.com/search?q=panduit%20MEHT187',
    # 'https://www.zoro.com/search?q=panduit%20META-X',
    # 'https://www.zoro.com/search?q=panduit%20METS3-X',
    # 'https://www.zoro.com/search?q=panduit%20METS4-X',
    # 'https://www.zoro.com/search?q=panduit%20MLT2EH-LP',
    # 'https://www.zoro.com/search?q=panduit%20MLT4EH-LP',
    # 'https://www.zoro.com/search?q=panduit%20MLT4SH-LP',
    # 'https://www.zoro.com/search?q=panduit%20MLT6SH-LP',
    # 'https://www.zoro.com/search?q=panduit%20MLTFC2H-LP316',
    # 'https://www.zoro.com/search?q=panduit%20MLTFC2H-LP316RD',
    # 'https://www.zoro.com/search?q=panduit%20MLTFC4H-LP316',
    # 'https://www.zoro.com/search?q=panduit%20MLTFC4H-LP316BU',
    # 'https://www.zoro.com/search?q=panduit%20MLTFC4H-LP316GR',
    # 'https://www.zoro.com/search?q=panduit%20MLTFC4H-LP316RD',
    # 'https://www.zoro.com/search?q=panduit%20MLTFC4H-LP316WH',
    # 'https://www.zoro.com/search?q=panduit%20MLTFC4H-LP316YL',
    # 'https://www.zoro.com/search?q=panduit%20MMP172-C',
    # 'https://www.zoro.com/search?q=panduit%20MMP172-C316',
    # 'https://www.zoro.com/search?q=panduit%20MT150D-Q',
    # 'https://www.zoro.com/search?q=panduit%20MT1D-Q',
    # 'https://www.zoro.com/search?q=panduit%20MT350-C',
    # 'https://www.zoro.com/search?q=panduit%20MT350-C316',
    # 'https://www.zoro.com/search?q=panduit%20MTB150D-Q',
    # 'https://www.zoro.com/search?q=panduit%20MTB1D-Q',
    # 'https://www.zoro.com/search?q=panduit%20PBTMT',
    # 'https://www.zoro.com/search?q=panduit%20RGTBSG-C',
    # 'https://www.zoro.com/search?q=panduit%20GB2B0304TPI-1',
    # 'https://www.zoro.com/search?q=panduit%20GB2B0312TPI-1',
    # 'https://www.zoro.com/search?q=panduit%20GB4B0612TPI-1',
    # 'https://www.zoro.com/search?q=panduit%20GB4B0624TPI-1',
    # 'https://www.zoro.com/search?q=panduit%20RGRB19CN',
    # 'https://www.zoro.com/search?q=panduit%20RGRB19U',
    # 'https://www.zoro.com/search?q=panduit%20GACB-1',
    # 'https://www.zoro.com/search?q=panduit%20GPQC07-1/0',
    # 'https://www.zoro.com/search?q=panduit%20GPQC10-1/0',
    # 'https://www.zoro.com/search?q=panduit%20GPQC12-1/0',
    # 'https://www.zoro.com/search?q=panduit%20GPQC15-1/0',
    # 'https://www.zoro.com/search?q=panduit%20GCC6X6250-1/0',
    # 'https://www.zoro.com/search?q=panduit%20GCC6X6500-250',
    # 'https://www.zoro.com/search?q=panduit%20GCE1/0-1/0',
    # 'https://www.zoro.com/search?q=panduit%20GCE250-1/0',
    # 'https://www.zoro.com/search?q=panduit%20GCE250-250',
    # 'https://www.zoro.com/search?q=panduit%20GCE500-250',
    # 'https://www.zoro.com/search?q=panduit%20CGK630U',
    # 'https://www.zoro.com/search?q=panduit%20CGK630UA',
    # 'https://www.zoro.com/search?q=panduit%20ACG24K',
    # 'https://www.zoro.com/search?q=panduit%20CGR630U',
    # 'https://www.zoro.com/search?q=panduit%20RGS134-10-1Y',
    # 'https://www.zoro.com/search?q=panduit%20RGS134-1Y',
    # 'https://www.zoro.com/search?q=panduit%20RGS134B-1',
    # 'https://www.zoro.com/search?q=panduit%20HTCT2-2-1',
    # 'https://www.zoro.com/search?q=panduit%20HTWC2-2-1',
    # 'https://www.zoro.com/search?q=panduit%20RGCBNJ660P22',
    # 'https://www.zoro.com/search?q=panduit%20RGCBNJ660PY',
    # 'https://www.zoro.com/search?q=panduit%20RGEJ657PFY',
    # 'https://www.zoro.com/search?q=panduit%20RGREJ696Y',
    # 'https://www.zoro.com/search?q=panduit%20RGRKCBNJY',
    # 'https://www.zoro.com/search?q=panduit%20CNB4K',
    # 'https://www.zoro.com/search?q=panduit%20CNBK',
    # 'https://www.zoro.com/search?q=panduit%20CT-1550',
    # 'https://www.zoro.com/search?q=panduit%20CT-1525',
    # 'https://www.zoro.com/search?q=panduit%20CT-1570',
    # 'https://www.zoro.com/search?q=panduit%20CT-1700',
    # 'https://www.zoro.com/search?q=panduit%20CT-1002',
    # 'https://www.zoro.com/search?q=panduit%20CT-1003',
    # 'https://www.zoro.com/search?q=panduit%20CT-1123',
    'https://www.zoro.com/search?q=panduit%20CT-1000',



]


for url in mylist:
    try:
        l = l + 1
        r = requests.get(url)
        soup = BeautifulSoup(r.content, "html.parser")
        driver.get(url)
        driver.get(driver.current_url)
        # time.sleep(3)
        get_url = driver.current_url
        print("current = ", get_url)
        print("Products Urls", l, url)
        all_data = []
        all = driver.find_element(By.XPATH, "//ul[@class='product-identifiers pl-0 pb-2 product-specifications__identifiers my-4 pl-4']")
        data = all.find_elements(By.TAG_NAME, "li")
        for da in data:
            all_data.append(da.text)
        try:
            zoro = all_data[0]
        except:
            zoro = "Not Found"
            print("Not Found")
        try:
            mfr = all_data[1]
        except:
            mfr = "Not Found"
            print("Not Found")
        try:
            upc = all_data[2]
        except:
            upc = "Not Found"
            print("Not Found")
        print("zoro = ", zoro)
        print("mfr = ", mfr)
        print("upc = ", upc)
        save_details: TextIO = open("zoro1.xlsx", "a+", encoding="utf-8")
        save_details.write("\n" + url + "\t" + get_url + "\t" + zoro + "\t" + mfr + "\t" + upc)
        save_details.close()
        print("\n ***** Record stored into upc  files. *****")

    except:
        save_details: TextIO = open("remaining_urls1.xlsx", "a+", encoding="utf-8")
        save_details.write("\n" + url)
        save_details.close()
        print("\n ***** Record stored into upc  files. *****")
        print("Not Found")
