import time
from typing import TextIO
from selenium.webdriver.chrome.options import Options
import requests
from selenium import webdriver
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"}
opts = Options()
opts.headless = True
browser = webdriver.Chrome()
browser.maximize_window()
# time.sleep(9)
myl = [
    # 'https://www.se.com/us/en/search/9001SKR25RH13',
    # 'https://www.se.com/us/en/search/9001SKT38LL',
    # 'https://www.se.com/us/en/search/9001SKT38LRR9',
    # 'https://www.se.com/us/en/search/9001SKT38LW',
    # 'https://www.se.com/us/en/search/9001SKT38LYA31',
    # 'https://www.se.com/us/en/search/9001SKR9W',
    # 'https://www.se.com/us/en/search/9001SKT35R31',
    # 'https://www.se.com/us/en/search/9001SKT38LG',
    # 'https://www.se.com/us/en/search/ZB4BW7A37417',
    # 'https://www.se.com/us/en/search/ZB4BW7A9',
    # 'https://www.se.com/us/en/search/ZB4BG0310',
    # 'https://www.se.com/us/en/search/ZB4BD205',
    # 'https://www.se.com/us/en/search/ZB4BD305',
    # 'https://www.se.com/us/en/search/ZB4BD303',
    # 'https://www.se.com/us/en/search/ZB4BD201',
    # 'https://www.se.com/us/en/search/ZB4BD704',
    # 'https://www.se.com/us/en/search/ZB4BD504',
    # 'https://www.se.com/us/en/search/ZB4BG03',
    # 'https://www.se.com/us/en/search/ZB4BD39',
    # 'https://www.se.com/us/en/search/ZB4BT3',
    # 'https://www.se.com/us/en/search/ZB5AG05',
    # 'https://www.se.com/us/en/search/ZB5AG714',
    # 'https://www.se.com/us/en/search/ZB4BG05',
    # 'https://www.se.com/us/en/search/ZB4BL73417',
    # 'https://www.se.com/us/en/search/ZB4BA73407',
    # 'https://www.se.com/us/en/search/ZB4BS94410',
    # 'https://www.se.com/us/en/search/ZB4BS94412',
    # 'https://www.se.com/us/en/search/ZB5AG710',
    # 'https://www.se.com/us/en/search/ZB4BG920',
    # 'https://www.se.com/us/en/search/ZB4BG310',
    # 'https://www.se.com/us/en/search/ZB4BA72124',
    # 'https://www.se.com/us/en/search/ZB4BA73134',
    # 'https://www.se.com/us/en/search/ZB4BA71115',
    # 'https://www.se.com/us/en/search/ZB4BA791',
    # 'https://www.se.com/us/en/search/ZB4BC54',
    # 'https://www.se.com/us/en/search/ZB4BR3',
    # 'https://www.se.com/us/en/search/ZB4BS864',
    # 'https://www.se.com/us/en/search/ZB4BG0820',
    # 'https://www.se.com/us/en/search/ZB5AV043S',
    # 'https://www.se.com/us/en/search/ZB5AW7A9',
    # 'https://www.se.com/us/en/search/ZB5AW753',
    # 'https://www.se.com/us/en/search/ZB5AD505',
    # 'https://www.se.com/us/en/search/ZB5AS94412',
    # 'https://www.se.com/us/en/search/ZB5AS94410',
    # 'https://www.se.com/us/en/search/ZB5AS94420',
    # 'https://www.se.com/us/en/search/ZB5AS94414',
    # 'https://www.se.com/us/en/search/ZB5AG712',
    # 'https://www.se.com/us/en/search/ZB5AG010',
    # 'https://www.se.com/us/en/search/ZB5AG012',
    # 'https://www.se.com/us/en/search/ZB5AA72124',
    # 'https://www.se.com/us/en/search/ZB5AA73134',
    # 'https://www.se.com/us/en/search/ZB5AA71124',
    # 'https://www.se.com/us/en/search/ZB5AA791',
    # 'https://www.se.com/us/en/search/ZB5AA79',
    # 'https://www.se.com/us/en/search/ZB5AG610',
    # 'https://www.se.com/us/en/search/ZB5AG612',
    # 'https://www.se.com/us/en/search/NSYTRV42SF5LA',
    # 'https://www.se.com/us/en/search/NSYTRV42SF6LA',
    # 'https://www.se.com/us/en/search/9001KP38R31',
    # 'https://www.se.com/us/en/search/ZB6AF4',
    # 'https://www.se.com/us/en/search/ZB6AV1',
    # 'https://www.se.com/us/en/search/ZB6AW1',
    # 'https://www.se.com/us/en/search/ZB6AW3',
    # 'https://www.se.com/us/en/search/ZB6CD23',
    # 'https://www.se.com/us/en/search/ZB6CV9',
    # 'https://www.se.com/us/en/search/ZB6DA3',
    # 'https://www.se.com/us/en/search/ZB6DA4',
    # 'https://www.se.com/us/en/search/ZB6DF3',
    # 'https://www.se.com/us/en/search/ZB6DF4',
    # 'https://www.se.com/us/en/search/VW3A9204',
    # 'https://www.se.com/us/en/search/VW3A9207',
    # 'https://www.se.com/us/en/search/VW3A9208',
    # 'https://www.se.com/us/en/search/LU2B12B',
    # 'https://www.se.com/us/en/search/LU2B12FU',
    # 'https://www.se.com/us/en/search/LU2B32B',
    # 'https://www.se.com/us/en/search/LUCBX6B',
    # 'https://www.se.com/us/en/search/LUCBX6FU',
    # 'https://www.se.com/us/en/search/LUCB1XB',
    # 'https://www.se.com/us/en/search/LUCB05B',
    # 'https://www.se.com/us/en/search/LUCB18B',
    # 'https://www.se.com/us/en/search/LUCCX6B',
    # 'https://www.se.com/us/en/search/LUCC1XB',
    # 'https://www.se.com/us/en/search/LUCC1XFU',
    # 'https://www.se.com/us/en/search/LUCC05B',
    # 'https://www.se.com/us/en/search/LUCC12B',
    # 'https://www.se.com/us/en/search/LUFW10',
    # 'https://www.se.com/us/en/search/LUFN02',
    # 'https://www.se.com/us/en/search/LU9C1',
    # 'https://www.se.com/us/en/search/LU9C2',
    # 'https://www.se.com/us/en/search/9001KP7',
    # 'https://www.se.com/us/en/search/9001KP5',
    # 'https://www.se.com/us/en/search/9001SKS43',
    # 'https://www.se.com/us/en/search/9001SKR4R',
    # 'https://www.se.com/us/en/search/9001SK1L1',
    # 'https://www.se.com/us/en/search/9001R7',
    # 'https://www.se.com/us/en/search/9001L6',
    # 'https://www.se.com/us/en/search/9001KT38',
    # 'https://www.se.com/us/en/search/9001KT35',
    # 'https://www.se.com/us/en/search/9001KT1',
    # 'https://www.se.com/us/en/search/9001KS56',
    # 'https://www.se.com/us/en/search/9001KS42',
    # 'https://www.se.com/us/en/search/9001KR3U',
    # 'https://www.se.com/us/en/search/9001KP35',
    # 'https://www.se.com/us/en/search/9001KP32',
    # 'https://www.se.com/us/en/search/9001KN262',
    # 'https://www.se.com/us/en/search/9001K85',
    # 'https://www.se.com/us/en/search/XVC4B3',
    # 'https://www.se.com/us/en/search/XVC4B4',
    # 'https://www.se.com/us/en/search/XVC4B1K',
    # 'https://www.se.com/us/en/search/XVC4B5K',
    # 'https://www.se.com/us/en/search/XVC6B5',
    # 'https://www.se.com/us/en/search/XVC6B25S',
    # 'https://www.se.com/us/en/search/XVC6B55S',
    # 'https://www.se.com/us/en/search/XVC6B5K',
    # 'https://www.se.com/us/en/search/XVC6B25SK',
    # 'https://www.se.com/us/en/search/9001KR25GH6',
    # 'https://www.se.com/us/en/search/9001KR2GH13',
    # 'https://www.se.com/us/en/search/9001KR2UH5',
    # 'https://www.se.com/us/en/search/9001SKR2BH13',
    # 'https://www.se.com/us/en/search/9001SKR2RH13',
    # 'https://www.se.com/us/en/search/9001SKR2UH13',
    # 'https://www.se.com/us/en/search/9001SKR3GH13',
    # 'https://www.se.com/us/en/search/9001SKR3GH6',
    # 'https://www.se.com/us/en/search/9001SKR3RH13',
    # 'https://www.se.com/us/en/search/9001SKR3UH5',
    # 'https://www.se.com/us/en/search/9001SKR3UH6',
    # 'https://www.se.com/us/en/search/XVBL8B7',
    # 'https://www.se.com/us/en/search/XVBL8B8',
    # 'https://www.se.com/us/en/search/9001KYG1Y',
    # 'https://www.se.com/us/en/search/9001KT32LRR31',
    # 'https://www.se.com/us/en/search/9001KT35LLL31',
    # 'https://www.se.com/us/en/search/9001KT38LGG31',
    # 'https://www.se.com/us/en/search/9001KT38LLL31',
    # 'https://www.se.com/us/en/search/9001SKT35LLL31',
    # 'https://www.se.com/us/en/search/9001SKT35LRR31',
    # 'https://www.se.com/us/en/search/9001K2L1AH13',
    # 'https://www.se.com/us/en/search/9001K2L35AH13',
    # 'https://www.se.com/us/en/search/9001K2L35LRRH13',
    # 'https://www.se.com/us/en/search/9001K2L35LWWH13',
    # 'https://www.se.com/us/en/search/9001K2L35RH13',
    # 'https://www.se.com/us/en/search/9001K3L1RH13',
    # 'https://www.se.com/us/en/search/9001K3L35RH13',
    # 'https://www.se.com/us/en/search/9001SK2L35GH13',
    # 'https://www.se.com/us/en/search/LC1D50AU7',
    # 'https://www.se.com/us/en/search/LC1D65AT7',
    # 'https://www.se.com/us/en/search/ATV12H037M3',
    # 'https://www.se.com/us/en/search/VW3A4416',
    # 'https://www.se.com/us/en/search/VW3A4419',
    # 'https://www.se.com/us/en/search/LR2K0302',
    # 'https://www.se.com/us/en/search/LR2K0303',
    # 'https://www.se.com/us/en/search/9001SKR24R',
    # 'https://www.se.com/us/en/search/9001SKP7',
    # 'https://www.se.com/us/en/search/9001SKP5',
    # 'https://www.se.com/us/en/search/9001SKP1',
    # 'https://www.se.com/us/en/search/9001SK1L35',
    # 'https://www.se.com/us/en/search/9001K2L38',
    # 'https://www.se.com/us/en/search/ATV312H037M3',
    # 'https://www.se.com/us/en/search/ATV312HU11M2',
    # 'https://www.se.com/us/en/search/ATV312HU15M3',
    # 'https://www.se.com/us/en/search/ATV312HU55N4',
    # 'https://www.se.com/us/en/search/XALD164H29H7',
    # 'https://www.se.com/us/en/search/ZB4BV03',
    # 'https://www.se.com/us/en/search/ZB4BV033',
    # 'https://www.se.com/us/en/search/XB4BV35',
    # 'https://www.se.com/us/en/search/XB4BV61',
    # 'https://www.se.com/us/en/search/XB4BVB1',
    # 'https://www.se.com/us/en/search/XB4BW31B5',
    # 'https://www.se.com/us/en/search/XB4BW31G5',
    # 'https://www.se.com/us/en/search/XB4BW3465',
    # 'https://www.se.com/us/en/search/XB5AV65',
    # 'https://www.se.com/us/en/search/XB5AW3335',
    # 'https://www.se.com/us/en/search/XB5DSB',
    # 'https://www.se.com/us/en/search/XD4PA12',
    # 'https://www.se.com/us/en/search/XVBC4B6',
    # 'https://www.se.com/us/en/search/XVBC4M5',
    # 'https://www.se.com/us/en/search/XVBC8G3',
    # 'https://www.se.com/us/en/search/XVBL33',
    # 'https://www.se.com/us/en/search/ZALVB5',
    # 'https://www.se.com/us/en/search/ZB4BA26',
    # 'https://www.se.com/us/en/search/ZB4BA331',
    # 'https://www.se.com/us/en/search/ZB4BA432',
    # 'https://www.se.com/us/en/search/ZB4BG1',
    # 'https://www.se.com/us/en/search/ZB4BH043',
    # 'https://www.se.com/us/en/search/ZB4BK1453',
    # 'https://www.se.com/us/en/search/ZB4BK1853',
    # 'https://www.se.com/us/en/search/ZB4BL4',
    # 'https://www.se.com/us/en/search/ZB4BVB1',
    # 'https://www.se.com/us/en/search/ZB4BVB5',
    # 'https://www.se.com/us/en/search/ZB4BVG1',
    # 'https://www.se.com/us/en/search/ZB4BVG3',
    # 'https://www.se.com/us/en/search/ZB4BVG5',
    # 'https://www.se.com/us/en/search/ZB4BW113',
    # 'https://www.se.com/us/en/search/ZB4BW16',
    # 'https://www.se.com/us/en/search/ZB4BW533',
    # 'https://www.se.com/us/en/search/ZB4BW543',
    # 'https://www.se.com/us/en/search/ZB4BZ009',
    # 'https://www.se.com/us/en/search/ZB4BZ104',
    # 'https://www.se.com/us/en/search/ZB5AD48',
    # 'https://www.se.com/us/en/search/ZB5AG3',
    # 'https://www.se.com/us/en/search/ZB5AH043',
    # 'https://www.se.com/us/en/search/ZB5AH05',
    # 'https://www.se.com/us/en/search/ZB5AH053',
    # 'https://www.se.com/us/en/search/ZB5AH3',
    # 'https://www.se.com/us/en/search/ZB5AH43',
    # 'https://www.se.com/us/en/search/ZB5AH63',
    # 'https://www.se.com/us/en/search/ZB5AJ8',
    # 'https://www.se.com/us/en/search/ZB5AK1243',
    # 'https://www.se.com/us/en/search/ZB5AK1343',
    # 'https://www.se.com/us/en/search/ZB5AK1543',
    # 'https://www.se.com/us/en/search/ZB5AK1553',
    # 'https://www.se.com/us/en/search/ZB5AS42',
    # 'https://www.se.com/us/en/search/ZB5AS62',
    # 'https://www.se.com/us/en/search/ZB5AV4',
    # 'https://www.se.com/us/en/search/ZB5AVB3',
    # 'https://www.se.com/us/en/search/ZB5AVG5',
    # 'https://www.se.com/us/en/search/ZB5AW11',
    # 'https://www.se.com/us/en/search/ZB5AW143',
    # 'https://www.se.com/us/en/search/ZB5AW31',
    # 'https://www.se.com/us/en/search/ZB5AW513',
    # 'https://www.se.com/us/en/search/ZBVB6',
    # 'https://www.se.com/us/en/search/ZBVM3',
    # 'https://www.se.com/us/en/search/ZBY02322',
    # 'https://www.se.com/us/en/search/ZBY02330',
    # 'https://www.se.com/us/en/search/ZBY02306',
    # 'https://www.se.com/us/en/search/ZBY02308',
    # 'https://www.se.com/us/en/search/ZBY02367',
    # 'https://www.se.com/us/en/search/ZBY02387',
    # 'https://www.se.com/us/en/search/ZBY2304',
    # 'https://www.se.com/us/en/search/ZBY2309',
    # 'https://www.se.com/us/en/search/ZBY2327',
    # 'https://www.se.com/us/en/search/ZBY2328',
    # 'https://www.se.com/us/en/search/ZBY2330',
    # 'https://www.se.com/us/en/search/ZBY2387',
    # 'https://www.se.com/us/en/search/LRD332L',
    # 'https://www.se.com/us/en/search/ATV212H075M3X',
    # 'https://www.se.com/us/en/search/REG96PUN1RLU',
    # 'https://www.se.com/us/en/search/XPSAC3421P',
    # 'https://www.se.com/us/en/search/XPSAC5121P',
    # 'https://www.se.com/us/en/search/XPSAFL5130P',
    # 'https://www.se.com/us/en/search/XPSAK351144P',
    # 'https://www.se.com/us/en/search/XPSAR351144P',
    # 'https://www.se.com/us/en/search/XPSAV11113P',
    # 'https://www.se.com/us/en/search/XPSDMB1132P',
    # 'https://www.se.com/us/en/search/XPSDME1132P',
    # 'https://www.se.com/us/en/search/XPSVNE1142P',
    # 'https://www.se.com/us/en/search/XPSVNE3442P',
    # 'https://www.se.com/us/en/search/VW3A8106',
    # 'https://www.se.com/us/en/search/?q=XPSMC16Z&submit=Search',
    # 'https://www.se.com/us/en/search/ATS48D17Y',
    # 'https://www.se.com/us/en/search/ZBV011',
    # 'https://www.se.com/us/en/search/ZBVB17',
    # 'https://www.se.com/us/en/search/LXD3T7',
    # 'https://www.se.com/us/en/search/ZB4RZA0',
    # 'https://www.se.com/us/en/search/ZBRP1',
    # 'https://www.se.com/us/en/search/HMIZRA1',
    # 'https://www.se.com/us/en/search/XSDA405539H7',
    # 'https://www.se.com/us/en/search/9001SKYP6',
    # 'https://www.se.com/us/en/search/SR3XT61B',
    # 'https://www.se.com/us/en/search/SR3XT101B',
    # 'https://www.se.com/us/en/search/SR3XT141BD',
    # 'https://www.se.com/us/en/search/SR3XT141B',
    # 'https://www.se.com/us/en/search/SR2MEM02',
    # 'https://www.se.com/us/en/search/GV2P22',
    # 'https://www.se.com/us/en/search/GV3P13',
    # 'https://www.se.com/us/en/search/GV7RS40',
    # 'https://www.se.com/us/en/search/XB5AD33',
    # 'https://www.se.com/us/en/search/CA2SK20T7',
    # 'https://www.se.com/us/en/search/CAD50T7',
    # 'https://www.se.com/us/en/search/XVR12B05',
    # 'https://www.se.com/us/en/search/XVR12B05S',
    # 'https://www.se.com/us/en/search/XVR12B06',
    # 'https://www.se.com/us/en/search/XVR12J04',
    # 'https://www.se.com/us/en/search/XVR12J04S',
    # 'https://www.se.com/us/en/search/XVR13B04',
    # 'https://www.se.com/us/en/search/XVR13B05',
    # 'https://www.se.com/us/en/search/XVR13J05',
    # 'https://www.se.com/us/en/search/XVRZR3',
    # 'https://www.se.com/us/en/search/750XBXRC-120A',
    # 'https://www.se.com/us/en/search/750XBXRC-12D',
    # 'https://www.se.com/us/en/search/750XBXRC-240A',
    # 'https://www.se.com/us/en/search/750XBXRC-24A',
    # 'https://www.se.com/us/en/search/750XBXRC-24D',
    # 'https://www.se.com/us/en/search/750XBXRM4L-120A',
    # 'https://www.se.com/us/en/search/750XBXRM4L-12D',
    # 'https://www.se.com/us/en/search/750XBXRM4L-240A',
    # 'https://www.se.com/us/en/search/750XBXRM4L-24A',
    # 'https://www.se.com/us/en/search/750XBXRM4L-24D',
    # 'https://www.se.com/us/en/search/750XCXRC-120A',
    # 'https://www.se.com/us/en/search/750XCXRC-12D',
    # 'https://www.se.com/us/en/search/750XCXRC-240A',
    # 'https://www.se.com/us/en/search/750XCXRC-24A',
    # 'https://www.se.com/us/en/search/750XCXRC-24D',
    # 'https://www.se.com/us/en/search/750XCXRM4L-120A',
    # 'https://www.se.com/us/en/search/750XCXRM4L-12D',
    # 'https://www.se.com/us/en/search/750XCXRM4L-240A',
    # 'https://www.se.com/us/en/search/750XCXRM4L-24A',
    # 'https://www.se.com/us/en/search/750XCXRM4L-24D',
    # 'https://www.se.com/us/en/search/788XBXRC-120A',
    # 'https://www.se.com/us/en/search/788XBXRC-12D',
    # 'https://www.se.com/us/en/search/788XBXRC-240A',
    # 'https://www.se.com/us/en/search/788XBXRC-24A',
    # 'https://www.se.com/us/en/search/788XBXRC-24D',
    # 'https://www.se.com/us/en/search/788XBXRC1-24A',
    # 'https://www.se.com/us/en/search/788XBXRC1-24D',
    # 'https://www.se.com/us/en/search/788XBXRC1-120A',
    # 'https://www.se.com/us/en/search/788XBXRC1-12D',
    # 'https://www.se.com/us/en/search/788XBXRC1-240A',
    # 'https://www.se.com/us/en/search/788XBXRM4L-120A',
    # 'https://www.se.com/us/en/search/788XBXRM4L-12D',
    # 'https://www.se.com/us/en/search/788XBXRM4L-240A',
    # 'https://www.se.com/us/en/search/788XBXRM4L-24A',
    # 'https://www.se.com/us/en/search/788XBXRM4L-24D',
    # 'https://www.se.com/us/en/search/788XCXRC-120A',
    # 'https://www.se.com/us/en/search/788XCXRC-12D',
    # 'https://www.se.com/us/en/search/788XCXRC-240A',
    # 'https://www.se.com/us/en/search/788XCXRC-24A',
    # 'https://www.se.com/us/en/search/788XCXRC-24D',
    # 'https://www.se.com/us/en/search/788XCXRC1-120A',
    # 'https://www.se.com/us/en/search/788XCXRC1-12D',
    # 'https://www.se.com/us/en/search/788XCXRC1-240A',
    # 'https://www.se.com/us/en/search/788XCXRC1-24A',
    # 'https://www.se.com/us/en/search/788XCXRC1-24D',
    # 'https://www.se.com/us/en/search/788XCXRM4L-120A',
    # 'https://www.se.com/us/en/search/788XCXRM4L-12D',
    # 'https://www.se.com/us/en/search/788XCXRM4L-240A',
    # 'https://www.se.com/us/en/search/788XCXRM4L-24A',
    # 'https://www.se.com/us/en/search/788XCXRM4L-24D',
    # 'https://www.se.com/us/en/search/MA-418-500',
    # 'https://www.se.com/us/en/search/AG13A020',
    # 'https://www.se.com/us/en/search/TM221CE24T',
    # 'https://www.se.com/us/en/search/TM221CE40T',
    # 'https://www.se.com/us/en/search/TM221ME32TK',
    # 'https://www.se.com/us/en/search/TM3DI8',
    # 'https://www.se.com/us/en/search/TMACBL1',
    # 'https://www.se.com/us/en/search/TMAM2',
    # 'https://www.se.com/us/en/search/792XDX3M4L-24A',
    # 'https://www.se.com/us/en/search/792XDX3M4L-120A',
    # 'https://www.se.com/us/en/search/792XDX3M4L-240A',
    # 'https://www.se.com/us/en/search/792XDX3M4L-12D',
    # 'https://www.se.com/us/en/search/792XDX3M4L-24D',
    # 'https://www.se.com/us/en/search/792XDXM4L-24A',
    # 'https://www.se.com/us/en/search/792XDXM4L-120A',
    # 'https://www.se.com/us/en/search/792XDXM4L-240A',
    # 'https://www.se.com/us/en/search/792XDXM4L-12D',
    # 'https://www.se.com/us/en/search/792XDXM4L-24D',
    # 'https://www.se.com/us/en/search/792XDXC-120A',
    # 'https://www.se.com/us/en/search/792XDXC-24A',
    # 'https://www.se.com/us/en/search/792XDXC-12D',
    # 'https://www.se.com/us/en/search/792XDXC-24D',
    # 'https://www.se.com/us/en/search/792XDX3C-240A',
    # 'https://www.se.com/us/en/search/792XDXC-240A',
    # 'https://www.se.com/us/en/search/792XBXM4L-120A',
    # 'https://www.se.com/us/en/search/792XBXM4L-12D',
    # 'https://www.se.com/us/en/search/792XBXM4L-240A',
    # 'https://www.se.com/us/en/search/792XBXC-24D',
    # 'https://www.se.com/us/en/search/792XBXC-24A',
    # 'https://www.se.com/us/en/search/792XBXC-120A',
    # 'https://www.se.com/us/en/search/792XBXC-240A',
    # 'https://www.se.com/us/en/search/792XBXC-12D',
    # 'https://www.se.com/us/en/search/792XBXM4L-24D',
    # 'https://www.se.com/us/en/search/792XBXM4L-24A',
    # 'https://www.se.com/us/en/search/792XDX3C-120A',
    # 'https://www.se.com/us/en/search/792XDX3C-24A',
    # 'https://www.se.com/us/en/search/792XDX3C-24D',
    # 'https://www.se.com/us/en/search/792XDX3C-12D',
    # 'https://www.se.com/us/en/search/781XAXRM4L-120A',
    # 'https://www.se.com/us/en/search/781XAXRM4L-12D',
    # 'https://www.se.com/us/en/search/781XAXRM4L-240A',
    # 'https://www.se.com/us/en/search/781XAXRM4L-24A',
    # 'https://www.se.com/us/en/search/781XAXRM4L-24D',
    # 'https://www.se.com/us/en/search/781XAXRC-120A',
    # 'https://www.se.com/us/en/search/781XAXRC-12D',
    # 'https://www.se.com/us/en/search/781XAXRC-240A',
    # 'https://www.se.com/us/en/search/781XAXRC-24A',
    # 'https://www.se.com/us/en/search/781XAXRC-24D',
    # 'https://www.se.com/us/en/search/GV2ME03',
    # 'https://www.se.com/us/en/search/GV2ME16',
    # 'https://www.se.com/us/en/search/LX1D6U7',
    # 'https://www.se.com/us/en/search/CAD32B7',
    # 'https://www.se.com/us/en/search/9001SKS49BH2',
    # 'https://www.se.com/us/en/search/CAD50F7',
    # 'https://www.se.com/us/en/search/LP1K0601BD3',
    # 'https://www.se.com/us/en/search/LC1D50AF7',
    # 'https://www.se.com/us/en/search/TCSESU053FN0',
    # 'https://www.se.com/us/en/search/XPSAK311144',
    # 'https://www.se.com/us/en/search/DL1BEG',
    # 'https://www.se.com/us/en/search/XVCZ02',
    # 'https://www.se.com/us/en/search/XVR08B03',
    # 'https://www.se.com/us/en/search/XVR10J04',
    # 'https://www.se.com/us/en/search/XVR10J06',
    # 'https://www.se.com/us/en/search/XVR10B05',
    # 'https://www.se.com/us/en/search/XVR10B06',
    # 'https://www.se.com/us/en/search/9001SKS63FBH1',
    # 'https://www.se.com/us/en/search/9001KS25FBH13',
    # 'https://www.se.com/us/en/search/9001KS42FBH1',
    # 'https://www.se.com/us/en/search/9001KS44BH1',
    # 'https://www.se.com/us/en/search/9001KS73BH1',
    # 'https://www.se.com/us/en/search/9001KS73FBH1',
    # 'https://www.se.com/us/en/search/XB4BG03',
    # 'https://www.se.com/us/en/search/XB4BG33',
    # 'https://www.se.com/us/en/search/ZB4BW0G35',
    # 'https://www.se.com/us/en/search/XVBL4B3',
    # 'https://www.se.com/us/en/search/XVBL4B5',
    # 'https://www.se.com/us/en/search/XVBL4B6',
    # 'https://www.se.com/us/en/search/XVBL8G7',
    # 'https://www.se.com/us/en/search/XPSMCTS16',
    # 'https://www.se.com/us/en/search/TSXCUSB485',
    # 'https://www.se.com/us/en/search/LTMR08MBD',
    # 'https://www.se.com/us/en/search/LTMR27MBD',
    # 'https://www.se.com/us/en/search/LTMR100MBD',
    # 'https://www.se.com/us/en/search/LTMR08MFM',
    # 'https://www.se.com/us/en/search/LTMR27MFM',
    # 'https://www.se.com/us/en/search/LTMR100MFM',
    # 'https://www.se.com/us/en/search/LTMR08PBD',
    # 'https://www.se.com/us/en/search/LTMR27PBD',
    # 'https://www.se.com/us/en/search/LTMR08PFM',
    # 'https://www.se.com/us/en/search/LTMR100PFM',
    # 'https://www.se.com/us/en/search/LTMR100EBD',
    # 'https://www.se.com/us/en/search/LTMR27EFM',
    # 'https://www.se.com/us/en/search/LTMR08CBD',
    # 'https://www.se.com/us/en/search/LTMR100CBD',
    # 'https://www.se.com/us/en/search/LTMR100CFM',
    # 'https://www.se.com/us/en/search/LTMR08DBD',
    # 'https://www.se.com/us/en/search/LTMR27DBD',
    # 'https://www.se.com/us/en/search/LTMR100DBD',
    # 'https://www.se.com/us/en/search/LTMR27DFM',
    # 'https://www.se.com/us/en/search/LTMR100DFM',
    # 'https://www.se.com/us/en/search/9001KP7G31',
    # 'https://www.se.com/us/en/search/9001KP7R31',
    # 'https://www.se.com/us/en/search/9001KR24BH13',
    # 'https://www.se.com/us/en/search/9001KR24RH13',
    # 'https://www.se.com/us/en/search/9001K3L38LR',
    # 'https://www.se.com/us/en/search/9001KP35G31',
    # 'https://www.se.com/us/en/search/9001KP35G9',
    # 'https://www.se.com/us/en/search/9001KP35LRR31',
    # 'https://www.se.com/us/en/search/9001KP35R31',
    # 'https://www.se.com/us/en/search/9001KP35W31',
    # 'https://www.se.com/us/en/search/9001KP38A9',
    # 'https://www.se.com/us/en/search/9001KP38LGG31',
    # 'https://www.se.com/us/en/search/9001KP38LW',
    # 'https://www.se.com/us/en/search/9001KP38LWC9',
    # 'https://www.se.com/us/en/search/9001KP38LY',
    # 'https://www.se.com/us/en/search/LC1D32G7',
    # 'https://www.se.com/us/en/search/LC2D18B7V',
    # 'https://www.se.com/us/en/search/LC2D25U7V',
    # 'https://www.se.com/us/en/search/LC1F115G6',
    # 'https://www.se.com/us/en/search/9001KP1A9',
    # 'https://www.se.com/us/en/search/9001KP1Y31',
    # 'https://www.se.com/us/en/search/LADR2',
    # 'https://www.se.com/us/en/search/LADN02',
    # 'https://www.se.com/us/en/search/LAD8N11',
    'https://www.se.com/us/en/search/SSP3A250BDRT',
    'https://www.se.com/us/en/search/SSP3A250F7RT',
    'https://www.se.com/us/en/search/SSP3A250P7RT',
    'https://www.se.com/us/en/search/SSRHP10',
    'https://www.se.com/us/en/search/ABL1REM12050',
    'https://www.se.com/us/en/search/ABL1REM24062',
    'https://www.se.com/us/en/product-substitution/ABL1RPM24062',
    'https://www.se.com/us/en/search/ABL1RPM24100',
    'https://www.se.com/us/en/product-substitution/XVC4M25S',
    'https://www.se.com/us/en/product-substitution/XVC6M4K',
    'https://www.se.com/us/en/product-substitution/XVC6M45SK',
    'https://www.se.com/us/en/product-substitution/XPSABV11330C',
    'https://www.se.com/us/en/product-substitution/XPSABV11330P',
    'https://www.se.com/us/en/product-substitution/XPSABV1133C',
    'https://www.se.com/us/en/product-substitution/XPSABV1133P',
    'https://www.se.com/us/en/product-substitution/XPSATR1153C',
    'https://www.se.com/us/en/product-substitution/XPSATR39530P',
    'https://www.se.com/us/en/product-substitution/XPSAXE5120C',
    'https://www.se.com/us/en/product-substitution/XPSAXE5120P',
    'https://www.se.com/us/en/product-substitution/XPSBCE3410C',
    'https://www.se.com/us/en/search/XPSBCE3410PXPSECME5131PXPSECPE3910C',
    'https://www.se.com/us/en/product-substitution/XPSECPE3910P',
    'https://www.se.com/us/en/product-substitution/XPSECME5131P',
    'https://www.se.com/us/en/product-substitution/XPSECPE3910C',
    'https://www.se.com/us/en/product-substitution/XPSECPE5131C',
    'https://www.se.com/us/en/product-substitution/LR9F5367',
    'https://www.se.com/us/en/product-substitution/LR9F5371',
    'https://www.se.com/us/en/product-substitution/LR9F7379',

]
for url in myl:
    try:
        browser.get(url)
        time.sleep(3)

        # click url link and make urls
        try:
            browser.execute_script('return document.querySelector("#global-search-tab").shadowRoot.querySelector("div  div  div  div:nth-child(2)  div  uiaas-search-result-product-v2").shadowRoot.querySelector("host  div  a  div  div  section.result-card__text-content-section")').click()
            time.sleep(2)
        except:
            pass
        get_url = browser.current_url
        print("current = ", get_url)

        # clear dialog box
        try:
            browser.execute_script(
                'return document.querySelector("#svelteSearchTag").shadowRoot.querySelector("subs-tnc-dialog").shadowRoot.querySelector("#dialog-simple-notitle > se-dialog-content > div.TermsandConditions > div")').click()
            print('clear')
        except:
            pass
        # save data  here
        save_data: TextIO = open('mannn.txt', 'a+', encoding='utf-8')
        save_data.write('\n' + get_url)
        print("\n", 'data store in text file')
    except:
        save_data: TextIO = open('remain-mannn.txt', 'a+', encoding='utf-8')
        save_data.write('\n' + url)
        print("\n", 'data store in text file')

