import requests
from bs4 import BeautifulSoup
from typing import  TextIO

l=[
'https://www.southwire.com//wire-cable/600-volt-secondary-distribution/600vud-triplex-3e/p/AL600V83',
'https://www.southwire.com//wire-cable/600-volt-secondary-distribution/al-600v-ud-duplex/p/AL600V79',
'https://www.southwire.com//wire-cable/600-volt-secondary-distribution/al-600v-ud-hiscore-duplex/p/AL600V86',
'https://www.southwire.com//wire-cable/600-volt-secondary-distribution/al-600v-ud-hiscore-quadruplex/p/AL600V88',
'https://www.southwire.com//wire-cable/600-volt-secondary-distribution/al-600v-ud-hiscore-single-conductor/p/AL600V85',
'https://www.southwire.com//wire-cable/600-volt-secondary-distribution/al-600v-ud-hiscore-triplex/p/AL600V87',
'https://www.southwire.com//wire-cable/600-volt-secondary-distribution/al-600v-ud-quadruplex/p/AL600V81',
'https://www.southwire.com//wire-cable/600-volt-secondary-distribution/al-600v-ud-single-conductor/p/AL600V78',
'https://www.southwire.com//wire-cable/600-volt-secondary-distribution/al-600v-ud-triplex/p/AL600V80',
'https://www.southwire.com//wire-cable/600-volt-secondary-distribution/al-poly-duplex-service-drop/p/AL600V60',
'https://www.southwire.com//wire-cable/600-volt-secondary-distribution/al-xlp-duplex-service-drop/p/AL600V65',
'https://www.southwire.com//wire-cable/600-volt-secondary-distribution/al-xlp-quadruplex-service-drop/p/AL600V67',
'https://www.southwire.com//wire-cable/600-volt-secondary-distribution/al-xlp-triplex-service-drop/p/AL600V66',
'https://www.southwire.com//wire-cable/600-volt-secondary-distribution/cu-xlp-service-drop-other/p/OCC5',
'https://www.southwire.com//wire-cable/600-volt-secondary-distribution/electrical-al-600v-ud/p/AL600V82',
'https://www.southwire.com//wire-cable/600-volt-secondary-distribution/electrical-al-600v-ud-3e/p/AL600V84',
'https://www.southwire.com//wire-cable/armored-power-cable/2-c-3-c-or-4-c-cu-600v-xlpe-xhhw-2-aluminum-interlocked-armor-pvc-control-cable-with-ground/p/APC40',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-600-or-1000-volt-cu-fr-xlpe-xhhw-2-cpe-jacket-power-cable-halo-flex-type-tc-er-hl/p/APC44',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-al-15kv-220-nlepr-133-aia-pvc-mv-105/p/APC10',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-al-15kv-220-nlepr-133-aia-pvc-mv-105-50-ground-silicone-free/p/APC9',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-al-35kv-420-nlepr-133-armor-x-pvc-mv-105/p/APC12',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-al-5kv-115-nlepr-133-aia-pvc-mv-105/p/APC11',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-al-600v-or-1000-v-xlpe-xhhw-2-pvc-power-cable-with-ground-silicone-free-/p/APC14',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-al-600v-xlpe-xhhw-2-aia-pvc-power-cable-with-50-ground-silicone-free/p/APC8',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-al-600v-xlpe-xhhw-2-aia-pvc-power-cable-with-ground-at-50-silicone-free/p/APC6',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-cu-15kv-175-nlepr-100-aia-pvc-mv-105/p/APC22',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-cu-15kv-220-nlepr-133-aia-cpe-mv-105/p/APC25',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-cu-15kv-220-nlepr-133-aia-lszh-mv-105/p/APC24',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-cu-15kv-220-nlepr-133-aia-pvc-mv-105/p/APC21',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-cu-15kv-220-nlepr-133-aia-pvc-mv-105-50-ground-silicone-free/p/APC23',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-cu-15kv-220-nlepr-133-armor-x-pvc-mv-105/p/APC38',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-cu-15kv-220-nlepr-133-gsia-pvc-mv-105/p/APC20',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-cu-2-4kv-115-epr-aia-pvc-mv-105/p/APC16',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-cu-2-4kv-90-epr-armor-x-pvc-mv-105-vfd-type-mc-hl/p/APC28',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-cu-5kv-115-nlepr-133-aia-cpe-mv-105/p/APC19',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-cu-5kv-115-nlepr-133-aia-lszh-mv-105/p/APC18',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-cu-5kv-115-nlepr-133-aia-pvc-mv-105/p/APC17',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-cu-5kv-115-nlepr-133-armor-x-mc-hl-pvc-mv-105-vfd/p/APC37',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-cu-5kv-115-nlepr-133-gsia-pvc-mv-105/p/APC15',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-cu-600v-xlpe-xhhw-2-aia-pvc-power-cable-with-ground-at-50-silicone-free-/p/APC43',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-cu-600v-xlpe-xhhw-2-aia-pvc-power-cable-with-ground-silicone-free-/p/APC39',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-cu-600v-xlpe-xhhw-2-armor-x-pvc-power-cable-with-ground-vfd/p/APC34',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-or-4-c-600-or-1000-volt-cu-fr-xlpe-xhhw-2-cpe-jacket-control-cable-halo-flex-type-tc-er-hl/p/APC26',
'https://www.southwire.com//wire-cable/armored-power-cable/3-c-or-4-c-cu-600v-xlpe-xhhw-2-armor-x-pvc-cable-with-three-grounds-vfd-cable/p/APC33',
'https://www.southwire.com//wire-cable/armored-power-cable/4-c-al-600v-xlpe-xhhw-2-aia-pvc-power-cable-with-50-ground-silicone-free/p/APC7',
'https://www.southwire.com//wire-cable/armored-power-cable/4-c-cu-600v-xlpe-xhhw-2-aia-pvc-power-cable-with-50-ground-silicone-free/p/APC42',
'https://www.southwire.com//wire-cable/armored-power-cable/4-c-cu-600v-xlpe-xhhw-2-aia-pvc-power-cable-with-ground-silicone-free/p/APC41',
'https://www.southwire.com//wire-cable/armored-power-cable/4-c-cu-600v-xlpe-xhhw-2-armor-x-pvc-power-cable-with-ground/p/APC36',
'https://www.southwire.com//wire-cable/armored-power-cable/600v-cu-pvc-pairs-armor-x-pvc-spos-instrumentation/p/APC31',
'https://www.southwire.com//wire-cable/armored-power-cable/600v-cu-pvc-triads-armor-x-pvc-stos-instrumentation/p/APC32',
'https://www.southwire.com//wire-cable/armored-power-cable/600v-pvc-nylon-shielded-pairs-cpe-jacket-spos-halo-flex-type-tc-er-hl/p/APC29',
'https://www.southwire.com//wire-cable/armored-power-cable/600v-pvc-nylon-shielded-triads-cpe-jacket-stos-halo-flex-type-tc-er-hl/p/APC30',
'https://www.southwire.com//wire-cable/armored-power-cable/cu-600v-xlpe-xhhw-2-armor-x-pvc-control-cable-with-ground/p/APC35',
'https://www.southwire.com//wire-cable/armored-power-cable/hvteck-al-3-c-175nlepr-ts-pvc-aia-pvc-15kv-100-csa/p/APC13',
'https://www.southwire.com//wire-cable/armored-power-cable/multi-conductor-600-or-1000-volt-cu-xlpe-xhhw-2-cpe-control-cable-halo-flex-type-tc-er-hl/p/APC27',
'https://www.southwire.com//wire-cable/bare-aluminum-overhead-transmission-distribution/aac/p/ALBARE2',
'https://www.southwire.com//wire-cable/bare-aluminum-overhead-transmission-distribution/-accs-tw-c7-ts-/p/ALBARE23',
'https://www.southwire.com//wire-cable/bare-aluminum-overhead-transmission-distribution/acsr/p/ALBARE6',
'https://www.southwire.com//wire-cable/bare-aluminum-overhead-transmission-distribution/acsr-aw/p/ALBARE8',
'https://www.southwire.com//wire-cable/bare-aluminum-overhead-transmission-distribution/acsr-tw/p/ALBARE9',
'https://www.southwire.com//wire-cable/bare-aluminum-overhead-transmission-distribution/acss/p/ALBARE7',
'https://www.southwire.com//wire-cable/bare-aluminum-overhead-transmission-distribution/acss-tw/p/ALBARE10',
'https://www.southwire.com//wire-cable/bare-aluminum-overhead-transmission-distribution/hs285-ultra-high-strength-acss-conductor/p/ALBARE13',
'https://www.southwire.com//wire-cable/bare-aluminum-overhead-transmission-distribution/hs285-ultra-high-strength-acss-tw-conductor/p/ALBARE14',
'https://www.southwire.com//wire-cable/bare-aluminum-overhead-transmission-distribution/vr2-acsr-vibration-resistant/p/ALBARE12',
'https://www.southwire.com//wire-cable/bare-aluminum-overhead-transmission-distribution/ztaccr-tw-c7-ts-/p/ALBARE24',
'https://www.southwire.com//wire-cable/building-wire/simpull-thhn-copper-wire/p/BW1',
'https://www.southwire.com//wire-cable/building-wire/simpull-coilpak-wire-payoff/p/BW27',
'https://www.southwire.com//wire-cable/building-wire/simpull-barrel-cable-drum/p/BW28',
'https://www.southwire.com//wire-cable/building-wire/simpull-thhn-wire-with-alumaflex-brand-conductors/p/BW15',
'https://www.southwire.com//wire-cable/building-wire/simpull-xhhw-2-copper-wire/p/BW4',
'https://www.southwire.com//wire-cable/building-wire/simpull-xhhw-2-wire-with-alumaflex-brand-conductors/p/BW16',
'https://www.southwire.com//wire-cable/building-wire/copper-rhh-rhw-2-use-2/p/BW5',
'https://www.southwire.com//wire-cable/building-wire/aluminum-rhh-rhw-2-use-2-with-alumaflex-brand-conductors/p/BW17',
'https://www.southwire.com//wire-cable/building-wire/copper-tffn-tfn-tewn/p/BW3',
'https://www.southwire.com//wire-cable/building-wire/romex-brand-simpull-type-nm-b-cable/p/BW7',
'https://www.southwire.com//wire-cable/building-wire/romex-brand-simpull-type-nm-b-pcs-duo-cable/p/BW23',
'https://www.southwire.com//wire-cable/building-wire/romex-brand-simpull-control-signal-cable/p/BW24',
'https://www.southwire.com//wire-cable/building-wire/copper-uf-b/p/BW8',
'https://www.southwire.com//wire-cable/building-wire/copper-service-entrance-ser-cable/p/BW6',
'https://www.southwire.com//wire-cable/building-wire/aluminum-service-entrance-ser-cable-with-alumaflex-brand-conductors/p/BW18',
'https://www.southwire.com//wire-cable/building-wire/copper-service-entrance-seu-cable/p/BW26',
'https://www.southwire.com//wire-cable/building-wire/aluminum-service-entrance-seu-cable-with-alumaflex-brand-conductors/p/BW25',
'https://www.southwire.com//wire-cable/building-wire/mobile-home-feeder-cable-with-alumaflex-brand-conductors/p/BW19',
'https://www.southwire.com//wire-cable/building-wire/nmd90-romex-simpull-aluminum/p/BW22',
'https://www.southwire.com//wire-cable/building-wire/nmd90-romex-simpull-copper/p/BW12',
'https://www.southwire.com//wire-cable/building-wire/nmwu-copper/p/BW13',
'https://www.southwire.com//wire-cable/building-wire/rw90-simpull-aluminum/p/BW20',
'https://www.southwire.com//wire-cable/building-wire/rw90-simpull-copper/p/BW10',
'https://www.southwire.com//wire-cable/building-wire/rwu90-aluminum/p/BW21',
'https://www.southwire.com//wire-cable/copper-bare-covered/bare-copper-wire-and-cable/p/CUBARE7',
'https://www.southwire.com//wire-cable/covered-aerial-mv-camv-systems/15kv-aaac-camv-tree-wire/p/AL600V73',
'https://www.southwire.com//wire-cable/covered-aerial-mv-camv-systems/15kv-aac-camv-spacer-cable/p/AL600V71',
'https://www.southwire.com//wire-cable/covered-aerial-mv-camv-systems/15kv-acsr-camv-tree-wire/p/AL600V72',
'https://www.southwire.com//wire-cable/covered-aerial-mv-camv-systems/25kv-aac-camv-spacer-cable/p/AL600V74',
'https://www.southwire.com//wire-cable/covered-aerial-mv-camv-systems/25kv-acsr-camv-tree-wire/p/AL600V75',
'https://www.southwire.com//wire-cable/covered-aerial-mv-camv-systems/35kv-aac-camv-spacer-cable/p/AL600V76',
'https://www.southwire.com//wire-cable/covered-aerial-mv-camv-systems/35kv-acsr-camv-tree-wire/p/AL600V77',
'https://www.southwire.com//wire-cable/flexible-conduit/alflex-type-rwa-reduced-wall-aluminum-flexible-metal-conduit/p/FC11',
'https://www.southwire.com//wire-cable/flexible-conduit/alflex-type-swa-standard-wall-aluminum-flexible-metal-conduit/p/FC16',
'https://www.southwire.com//wire-cable/flexible-conduit/data-flex-flexible-metal-conduit/p/FC13',
'https://www.southwire.com//wire-cable/flexible-conduit/galflex-type-rws-reduced-wall-steel-flexible-metal-conduit/p/FC15',
'https://www.southwire.com//wire-cable/flexible-conduit/titan-2-type-cb-liquidtight-flexible-metal-conduit/p/FC12',
'https://www.southwire.com//wire-cable/flexible-conduit/titan-2-type-ef-extra-flexible-liquidtight-metal-conduit/p/FC14',
'https://www.southwire.com//wire-cable/flexible-conduit/titan-2-type-hc-liquidtight-flexible-metal-conduit/p/FC20',
'https://www.southwire.com//wire-cable/flexible-conduit/titan-2-type-ul-liquidtight-flexible-metal-conduit/p/FC19',
'https://www.southwire.com//wire-cable/flexible-conduit/ultratite-type-nm/p/FC17',
'https://www.southwire.com//wire-cable/flexible-cord/300v-american-mustang-sjoow-cord-with-yellow-jacket-105-c/p/PCORD13',
'https://www.southwire.com//wire-cable/flexible-cord/300v-seoprene-plus-sjeoow-cord-with-yellow-jacket-105-c/p/PCORD14',
'https://www.southwire.com//wire-cable/flexible-cord/300v-seoprene-sjeoow-cord-with-black-jacket-105-c/p/PCORD15',
'https://www.southwire.com//wire-cable/flexible-cord/600v-american-mustang-soow-cord-with-yellow-jacket-105-c/p/PCORD16',
'https://www.southwire.com//wire-cable/flexible-cord/600v-royal-soow-cord-control-with-black-jacket-90-c/p/PCORD17',
'https://www.southwire.com//wire-cable/flexible-cord/600v-royal-soow-cord-with-black-jacket-90-c/p/PCORD18',
'https://www.southwire.com//wire-cable/flexible-cord/600v-royal-soow-power-cord-non-ul-csa-with-black-jacket-90-c/p/PCORD19',
'https://www.southwire.com//wire-cable/flexible-cord/600v-seoprene-plus-seoow-cord-with-yellow-jacket-105-c/p/PCORD20',
'https://www.southwire.com//wire-cable/flexible-cord/600v-seoprene-plus-seoow-power-cord-non-ul-csa-with-yellow-jacket-105-c/p/PCORD21',
'https://www.southwire.com//wire-cable/flexible-cord/600v-seoprene-seoow-cord-control-with-black-jacket-105-c/p/PCORD22',
'https://www.southwire.com//wire-cable/flexible-cord/600v-seoprene-seoow-cord-with-black-jacket-105-c/p/PCORD23',
'https://www.southwire.com//wire-cable/flexible-cord/600v-seoprene-seoow-power-cord-non-ul-csa-with-black-jacket-105-c/p/PCORD24',
'https://www.southwire.com//wire-cable/flexible-cord/600v-seoprene-seoow-power-cord-with-black-jacket-105-c/p/PCORD25',
'https://www.southwire.com//wire-cable/high-voltage-underground-69kv-and-up-/al-cable-clamps/p/HVUD9',
'https://www.southwire.com//wire-cable/high-voltage-underground-69kv-and-up-/arrester/p/HVUD7',
'https://www.southwire.com//wire-cable/high-voltage-underground-69kv-and-up-/high-voltage-al-345kv-400kv-power-cable/p/HVUD6',
'https://www.southwire.com//wire-cable/high-voltage-underground-69kv-and-up-/high-voltage-bonding-cable/p/HVUD13',
'https://www.southwire.com//wire-cable/high-voltage-underground-69kv-and-up-/high-voltage-cu-115kv-power-cable/p/HVUD2',
'https://www.southwire.com//wire-cable/high-voltage-underground-69kv-and-up-/high-voltage-cu-138kv-power-cable/p/HVUD3',
'https://www.southwire.com//wire-cable/high-voltage-underground-69kv-and-up-/high-voltage-cu-230kv-power-cable/p/HVUD4',
'https://www.southwire.com//wire-cable/high-voltage-underground-69kv-and-up-/high-voltage-cu-345kv-400kv-power-cable/p/HVUD5',
'https://www.southwire.com//wire-cable/high-voltage-underground-69kv-and-up-/high-voltage-cu-69kv-power-cable/p/HVUD1',
'https://www.southwire.com//wire-cable/high-voltage-underground-69kv-and-up-/high-voltage-joint/p/HVUD10',
'https://www.southwire.com//wire-cable/high-voltage-underground-69kv-and-up-/link-box/p/HVUD8',
'https://www.southwire.com//wire-cable/high-voltage-underground-69kv-and-up-/outdoor-termination/p/HVUD11',
'https://www.southwire.com//wire-cable/high-voltage-underground-69kv-and-up-/switchgear-and-transformer-terminations/p/HVUD12',
'https://www.southwire.com//power-management/extension-cords/16-3-spt-3-straight-3-replacement-cord/p/9733SW8809',
'https://www.southwire.com//power-management/extension-cords/16-3-spt-3-straight-6-replacement-cord/p/9736SW8809',
'https://www.southwire.com//wire-cable/hvac/baron-tstat-wire/p/HVAC1',
'https://www.southwire.com//wire-cable/building-wire/romex-brand-simpull-type-nm-b-cable/p/BW7',
'https://www.southwire.com//wire-cable/building-wire/simpull-thhn-copper-wire/p/BW1',
'https://www.southwire.com//wire-cable/flexible-conduit/ultratite-type-nm/p/FC17',
'https://www.southwire.com//wire-cable/industrial-flexible/1-c-cu-2000v-epdm-cpe-type-w-rhh-rhw-2-industrial-grade-cable-90-c/p/RCORD10',
'https://www.southwire.com//wire-cable/industrial-flexible/1-c-cu-2000v-epr-rhh-rhw-2-cpe-power-cable-hdfpc-dlo-rw90/p/RCORD11',
'https://www.southwire.com//wire-cable/industrial-flexible/2-c-cu-2000v-epdm-cpe-type-w-industrial-grade-cable-90-c/p/RCORD12',
'https://www.southwire.com//wire-cable/industrial-flexible/3-c-cu-2000v-epdm-cpe-type-g-gc-industrial-grade-cable-90-c/p/RCORD13',
'https://www.southwire.com//wire-cable/industrial-flexible/3-c-cu-2000v-epdm-cpe-type-w-industrial-grade-cable-90-c/p/RCORD14',
'https://www.southwire.com//wire-cable/industrial-flexible/4-c-cu-2000v-epdm-cpe-type-g-industrial-grade-cable-90-c/p/RCORD15',
'https://www.southwire.com//wire-cable/industrial-flexible/4-c-cu-2000v-epdm-cpe-type-w-industrial-grade-cable-90-c/p/RCORD16',
'https://www.southwire.com//wire-cable/industrial-flexible/5-c-cu-2000v-epdm-cpe-type-w-industrial-grade-cable-90-c/p/RCORD17',
'https://www.southwire.com//wire-cable/leadwire/3173-sis/p/LW2',
'https://www.southwire.com//wire-cable/leadwire/amw-1015/p/LW65',
'https://www.southwire.com//wire-cable/leadwire/amw-1056-1275/p/LW66',
'https://www.southwire.com//wire-cable/leadwire/awm-1007-1569/p/LW67',
'https://www.southwire.com//wire-cable/leadwire/awm-1011/p/LW68',
'https://www.southwire.com//wire-cable/leadwire/awm-1061-1731/p/LW69',
'https://www.southwire.com//wire-cable/leadwire/awm-1232/p/LW70',
'https://www.southwire.com//wire-cable/leadwire/awm-1283/p/LW71',
'https://www.southwire.com//wire-cable/leadwire/awm-2474/p/LW29',
'https://www.southwire.com//wire-cable/leadwire/awm-3173/p/LW97',
'https://www.southwire.com//wire-cable/leadwire/awm-3191/p/LW117',
'https://www.southwire.com//wire-cable/leadwire/awm-3192/p/LW118',
'https://www.southwire.com//wire-cable/leadwire/awm-3193/p/LW119',
'https://www.southwire.com//wire-cable/leadwire/awm-3195/p/LW98',
'https://www.southwire.com//wire-cable/leadwire/awm-3196/p/LW99',
'https://www.southwire.com//wire-cable/leadwire/awm-3199/p/LW100',
'https://www.southwire.com//wire-cable/leadwire/awm-3237/p/LW101',
'https://www.southwire.com//wire-cable/leadwire/awm-3271/p/LW102',
'https://www.southwire.com//wire-cable/leadwire/awm-3272/p/LW103',
'https://www.southwire.com//wire-cable/leadwire/awm-3273/p/LW104',
'https://www.southwire.com//wire-cable/leadwire/awm-3284/p/LW105',
'https://www.southwire.com//wire-cable/leadwire/awm-3289/p/LW106',
'https://www.southwire.com//wire-cable/leadwire/awm-3290/p/LW107',
'https://www.southwire.com//wire-cable/leadwire/awm-3300/p/LW108',
'https://www.southwire.com//wire-cable/leadwire/awm-3321/p/LW109',
'https://www.southwire.com//wire-cable/leadwire/awm-3340-3374/p/LW110',
'https://www.southwire.com//wire-cable/leadwire/awm-3485/p/LW111',
'https://www.southwire.com//wire-cable/leadwire/awm-3499/p/LW112',
'https://www.southwire.com//wire-cable/leadwire/awm-3538/p/LW113',
'https://www.southwire.com//wire-cable/leadwire/awm-3556/p/LW114',
'https://www.southwire.com//wire-cable/leadwire/awm-3591/p/LW115',
'https://www.southwire.com//wire-cable/leadwire/awm-3666/p/LW116',
'https://www.southwire.com//wire-cable/leadwire/booster-cable/p/LW120',
'https://www.southwire.com//wire-cable/leadwire/brake-cable/p/LW17',
'https://www.southwire.com//wire-cable/leadwire/fl2x-a/p/LW76',
'https://www.southwire.com//wire-cable/leadwire/fl2x-b/p/LW77',
'https://www.southwire.com//wire-cable/leadwire/flr2x-a/p/LW80',
'https://www.southwire.com//wire-cable/leadwire/flr2x-a-ebeam/p/LW81',
'https://www.southwire.com//wire-cable/leadwire/flr2x-b/p/LW82',
'https://www.southwire.com//wire-cable/leadwire/flr2x-c/p/LW84',
'https://www.southwire.com//wire-cable/leadwire/flr2x-c-ebeam/p/LW85',
'https://www.southwire.com//wire-cable/leadwire/flry-b/p/LW50',
'https://www.southwire.com//wire-cable/leadwire/gpt/p/LW62',
'https://www.southwire.com//wire-cable/leadwire/gpt-bonded/p/LW33',
'https://www.southwire.com//wire-cable/leadwire/gpt-rip-cord/p/LW34',
'https://www.southwire.com//wire-cable/leadwire/gptm/p/LW63',
'https://www.southwire.com//wire-cable/leadwire/gptm-bonded/p/LW35',
'https://www.southwire.com//wire-cable/leadwire/gptm-rip-cord/p/LW36',
'https://www.southwire.com//wire-cable/low-voltage-cable/fire-alarm-fplp/p/ELC24',
'https://www.southwire.com//wire-cable/low-voltage-cable/fire-alarm-fplr/p/ELC47',
'https://www.southwire.com//wire-cable/low-voltage-cable/circuit-defender-2-hour-rated/p/ELC53',
'https://www.southwire.com//wire-cable/low-voltage-cable/access-control-cable/p/ELC32',
'https://www.southwire.com//wire-cable/low-voltage-cable/burglar-wire/p/ELC31',
'https://www.southwire.com//wire-cable/low-voltage-cable/multi-conductor-security-plenum-shielded/p/ELC54',
'https://www.southwire.com//wire-cable/low-voltage-cable/multi-conductor-security-plenum-unshielded/p/ELC23',
'https://www.southwire.com//wire-cable/low-voltage-cable/multi-conductor-security-riser-shielded/p/ELC56',
'https://www.southwire.com//wire-cable/low-voltage-cable/multi-conductor-security-riser-unshielded/p/ELC55',
'https://www.southwire.com//wire-cable/low-voltage-cable/cat6a-cmr/p/ELC36',
'https://www.southwire.com//wire-cable/low-voltage-cable/cat6e-cmp-poe-ul-lp/p/ELC38',
'https://www.southwire.com//wire-cable/low-voltage-cable/cat6e-cmr/p/ELC39',
'https://www.southwire.com//wire-cable/low-voltage-cable/cat6-cmr/p/ELC37',
'https://www.southwire.com//wire-cable/low-voltage-cable/cat5e-cm/p/ELC40',
'https://www.southwire.com//wire-cable/low-voltage-cable/cat5e-direct-burial/p/ELC42',
'https://www.southwire.com//wire-cable/low-voltage-cable/cat6-cmp-poe-ul-lp/p/ELC43',
'https://www.southwire.com//wire-cable/low-voltage-cable/cat5e-cmr/p/ELC44',
'https://www.southwire.com//wire-cable/low-voltage-cable/select-cables-for-control-systems/p/ELC29',
'https://www.southwire.com//wire-cable/low-voltage-cable/low-voltage-dimming-or-luminaire-cable/p/ELC26',
'https://www.southwire.com//wire-cable/low-voltage-cable/instrumentation-and-building-management-control-cable/p/ELC28',
'https://www.southwire.com//wire-cable/low-voltage-cable/low-voltage-landscape-lighting/p/ELC45',
'https://www.southwire.com//wire-cable/low-voltage-cable/combo-cctv-siamese/p/ELC35',
'https://www.southwire.com//wire-cable/low-voltage-cable/rg59-cctv/p/ELC34',
'https://www.southwire.com//wire-cable/low-voltage-cable/rg6-catv-/p/ELC33',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-al-15kv-220-nlepr-133-simpull-pvc-mv-105/p/MV7',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-al-15kv-220-nlepr-133-simpull-pvc-mv-105-2x5-mils-tape-shield/p/MV12',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-al-35kv-345-nlepr-100-simpull-pvc-mv-105/p/MV10',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-al-35kv-420-nlepr-133-simpull-pvc-mv-105/p/MV9',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-al-5kv-115-nlepr-133-simpull-pvc-mv-105/p/MV8',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-al-5kv-115-nlepr-133-simpull-pvc-mv-105/p/MV6',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-compact-cu-15kv-175-nlepr-100-simpull-pvc-mv-105/p/MV35',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-compact-cu-15kv-220-nlepr-133-simpull-pvc-mv-105/p/MV42',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-compact-cu-5kv-115-nlepr-133-simpull-pvc-mv-105/p/MV28',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-15kv-175-nlepr-100-cpe-mv-105/p/MV36',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-15kv-175-nlepr-100-simpull-pvc-mv-105/p/MV33',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-15kv-220-nlepr-133-cpe-mv-105-silicone-free/p/MV40',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-15kv-220-nlepr-133-lszh-mv-105/p/MV18',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-15kv-220-nlepr-133-simpull-pvc-mv-105/p/MV43',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-15kv-220-nlepr-133-simpull-pvc-mv-105-2x5-mils-tape-shield/p/MV29',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-2-4kv-epr-simpull-pvc-mv-90-ct-rated/p/MV16',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-2-4kv-epr-thermoset-xl-lszh-mv-90-silicone-free/p/MV49',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-2-4kv-xlpe-silicone-free/p/MV48',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-25kv-260-nlepr-100-simpull-pvc-mv-105/p/MV44',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-25kv-320-nlepr-133-simpull-pvc-mv-105/p/MV46',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-35kv-345-nlepr-100-simpull-pvc-mv-105/p/MV45',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-35kv-420-nlepr-133-cpe-mv-105/p/MV51',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-35kv-420-nlepr-133-simpull-pvc-mv-105/p/MV52',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-5-8-kv-133-100-115-nlepr-simpull-pvc-mv-105/p/MV24',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-5kv-115-nlepr-133-cpe-mv-105/p/MV25',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-5kv-115-nlepr-133-lszh-mv-105/p/MV17',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-5kv-220-nlepr-133-pvc-mv-105/p/MV23',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-5kv-90-nlepr-100-pvc-mv-105/p/MV20',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-5kv-xlpe-airport-lighting-silicone-free-/p/MV14',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-8kv-140-nlepr-133-cpe-mv-105/p/MV22',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-8kv-140-nlepr-133-lszh-mv-105/p/MV50',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-epr-cpe-medium-voltage-non-shielded-jumper-switchgear-cable/p/MV53',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/1-c-cu-epr-medium-voltage-non-shielded-jumper-switchgear-cable/p/MV47',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/3-c-al-15kv-220-nlepr-133-pvc-mv-105/p/MV13',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/3-c-al-5kv-115-nlepr-133-pvc-mv-105/p/MV11',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/3-c-cu-15kv-175-nlepr-100-cpe-mv-105/p/MV38',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/3-c-cu-15kv-220-nlepr-133-cpe-mv-105/p/MV34',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/3-c-cu-15kv-220-nlepr-133-cpe-mv-105-silicone-free/p/MV41',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/3-c-cu-15kv-220-nlepr-133-pvc-mv-105-silicone-free/p/MV39',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/3-c-cu-2-4kv-90-mils-nlepr-pvc-mv-105/p/MV15',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/3-c-cu-25kv-320-nlepr-133-pvc-mv-105/p/MV37',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/3-c-cu-35kv-420-nlepr-133-pvc-mv-105/p/MV32',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/3-c-cu-5kv-115-nlepr-133-cpe-mv-105/p/MV30',
'https://www.southwire.com//wire-cable/medium-voltage-power-cable/3-c-cu-5kv-115-nlepr-133-pvc-mv-105/p/MV21',
'https://www.southwire.com//wire-cable/medium-voltage-primary-underground-distribution/15kv-aluminum-epr-mv-lldpe-jacket/p/MVDIST17',
'https://www.southwire.com//wire-cable/medium-voltage-primary-underground-distribution/15kv-aluminum-xlp-mv-lldpe-jacket/p/MVDIST1',
'https://www.southwire.com//wire-cable/medium-voltage-primary-underground-distribution/15kv-aluminum-xlp-mv-powerglide-jacket/p/MVDIST9',
'https://www.southwire.com//wire-cable/medium-voltage-primary-underground-distribution/15kv-copper-epr-mv-lldpe-jacket/p/MVDIST49',
'https://www.southwire.com//wire-cable/medium-voltage-primary-underground-distribution/15kv-copper-xlp-mv-lldpe-jacket/p/MVDIST33',
'https://www.southwire.com//wire-cable/medium-voltage-primary-underground-distribution/15kv-copper-xlp-mv-powerglide-jacket/p/MVDIST41',
'https://www.southwire.com//wire-cable/medium-voltage-primary-underground-distribution/25kv-aluminum-epr-mv-lldpe-jacket/p/MVDIST18',
'https://www.southwire.com//wire-cable/medium-voltage-primary-underground-distribution/25kv-aluminum-xlp-mv-lldpe-jacket/p/MVDIST2',
'https://www.southwire.com//wire-cable/medium-voltage-primary-underground-distribution/25kv-aluminum-xlp-mv-powerglide-jacket/p/MVDIST10',
'https://www.southwire.com//wire-cable/medium-voltage-primary-underground-distribution/25kv-copper-epr-mv-lldpe-jacket/p/MVDIST50',
'https://www.southwire.com//wire-cable/medium-voltage-primary-underground-distribution/25kv-copper-xlp-mv-lldpe-jacket/p/MVDIST34',
'https://www.southwire.com//wire-cable/medium-voltage-primary-underground-distribution/28kv-aluminum-xlp-mv-lldpe-jacket/p/MVDIST3',
'https://www.southwire.com//wire-cable/medium-voltage-primary-underground-distribution/28kv-copper-xlp-mv-lldpe-jacket/p/MVDIST35',
'https://www.southwire.com//wire-cable/medium-voltage-primary-underground-distribution/35kv-aluminum-epr-mv-lldpe-jacket/p/MVDIST20',
'https://www.southwire.com//wire-cable/medium-voltage-primary-underground-distribution/35kv-aluminum-xlp-mv-lldpe-jacket/p/MVDIST4',
'https://www.southwire.com//wire-cable/medium-voltage-primary-underground-distribution/35kv-copper-epr-mv-lldpe-jacket/p/MVDIST52',
'https://www.southwire.com//wire-cable/medium-voltage-primary-underground-distribution/35kv-copper-xlp-mv-lldpe-jacket/p/MVDIST36',
'https://www.southwire.com//wire-cable/medium-voltage-primary-underground-distribution/46kv-copper-epr-mv-lldpe-jacket/p/MVDIST71',
'https://www.southwire.com//wire-cable/medium-voltage-primary-underground-distribution/600vud-triplex-3e-/p/MVDIST70',
'https://www.southwire.com//wire-cable/metal-clad-cable/armorlite-type-mc/p/MC43',
'https://www.southwire.com//wire-cable/metal-clad-cable/armorlite-type-mc-circuit-pvc-jacketed/p/MC34',
'https://www.southwire.com//wire-cable/metal-clad-cable/armorlite-type-mc-pvc-jacketed/p/MC41',
'https://www.southwire.com//wire-cable/metal-clad-cable/mcap-type-mc-all-purpose/p/MC58',
'https://www.southwire.com//wire-cable/metal-clad-cable/hcf-mcap-type-mc-all-purpose-hospital-care-facility/p/MC60',
'https://www.southwire.com//wire-cable/metal-clad-cable/pvc-jacketed-hcf-mcap-type-mc-all-purpose-hospital-care-facility/p/MC62',
'https://www.southwire.com//wire-cable/metal-clad-cable/armorlite-type-mc-neutral-per-phase/p/MC36',
'https://www.southwire.com//wire-cable/metal-clad-cable/armorlite-type-mc-isolated-ground/p/MC40',
'https://www.southwire.com//wire-cable/metal-clad-cable/armorlite-type-mc-multi-circuit/p/MC35',
'https://www.southwire.com//wire-cable/metal-clad-cable/armorlite-type-mc-oversized-neutral/p/MC63',
'https://www.southwire.com//wire-cable/metal-clad-cable/armorlite-type-mc-blue-armor/p/MC55',
'https://www.southwire.com//wire-cable/metal-clad-cable/armorlite-type-ac/p/MC53',
'https://www.southwire.com//wire-cable/metal-clad-cable/mc-pcs-duo-power-control-signal-cable/p/MC46',
'https://www.southwire.com//wire-cable/metal-clad-cable/mc-pcs-duo-pvc-jacketed-power-control-signal-cable/p/MC47',
'https://www.southwire.com//wire-cable/metal-clad-cable/mcap-pcs-duo-power-control-signal-cable-type-mc-all-purpose/p/MC45',
'https://www.southwire.com//wire-cable/metal-clad-cable/mc-pcs-hcf-duo-power-control-signal-cable-for-healthcare-facilities/p/MC44',
'https://www.southwire.com//wire-cable/metal-clad-cable/mc-pcs-hcf-duo-power-control-signal-cable-for-healthcare-facilities-with-pvc-jacket/p/MC50',
'https://www.southwire.com//wire-cable/metal-clad-cable/red-alert-type-mc-fplp-fire-alarm-and-control/p/MC39',
'https://www.southwire.com//wire-cable/metal-clad-cable/duraclad-type-mc/p/MC56',
'https://www.southwire.com//wire-cable/metal-clad-cable/duraclad-type-mc-blue-armor/p/MC57',
'https://www.southwire.com//wire-cable/metal-clad-cable/armorlite-feeder-metal-clad-cable-with-copper-thhn-conductors/p/MC68',
'https://www.southwire.com//wire-cable/metal-clad-cable/pvc-jacketed-alumaflex-riser-mc-feeder-with-aluminum-thhn-conductors/p/MC31',
'https://www.southwire.com//wire-cable/metal-clad-cable/duraclad-hcf-mcap-type-mc-all-purpose-health-care-facility/p/MC61',
'https://www.southwire.com//wire-cable/metal-clad-cable/duraclad-type-ac/p/MC38',
'https://www.southwire.com//wire-cable/mining-cable/3-c-cu-15kv-100-epr-cpe-rhinopower-type-mp-gc/p/MG9',
'https://www.southwire.com//wire-cable/mining-cable/3-c-cu-15kv-100-xlp-pvc-rhinopower-type-mp-gc/p/MG12',
'https://www.southwire.com//wire-cable/mining-cable/3-c-cu-15kv-type-shd-gc-rhinoshield-cpe-mining-cable-90-c/p/MG10',
'https://www.southwire.com//wire-cable/mining-cable/3-c-cu-2000v-type-g-gc-rhinoflex-cpe-mining-cable-90-c/p/MG6',
'https://www.southwire.com//wire-cable/mining-cable/3-c-cu-5kv-100-133-epr-cpe-rhinopower-type-mp-gc/p/MG15',
'https://www.southwire.com//wire-cable/mining-cable/3-c-cu-5kv-100-133-xlp-pvc-rhinopower-type-mp-gc/p/MG13',
'https://www.southwire.com//wire-cable/mining-cable/3-c-cu-5kv-type-shd-gc-rhinoshield-cpe-mining-cable-90-c/p/MG8',
'https://www.southwire.com//wire-cable/mining-cable/3-c-cu-8kv-100-xlp-pvc-rhinopower-type-mp-gc/p/MG11',
'https://www.southwire.com//wire-cable/mining-cable/3-c-cu-8kv-133-epr-cpe-rhinopower-type-mp-gc/p/MG14',
'https://www.southwire.com//wire-cable/mining-cable/4-c-cu-2000v-type-g-rhinoflex-cpe-mining-cable-90-c/p/MG7',
'https://www.southwire.com//wire-cable/mining-cable/cu-600v-remote-power-drill-cord-cable-90-c/p/MG16',
'https://www.southwire.com//wire-cable/overhead-covered-conductor/copper-transformer-riser-wire/p/OCC3',
'https://www.southwire.com//wire-cable/overhead-covered-conductor/cu-poly-overhead/p/OCC1',
'https://www.southwire.com//wire-cable/overhead-covered-conductor/cu-poly-quadruplex-service-drop/p/OCC8',
'https://www.southwire.com//wire-cable/overhead-covered-conductor/cu-pvc-overhead/p/OCC4',
'https://www.southwire.com//wire-cable/overhead-covered-conductor/cu-solid-poly-linewire/p/OCC7',
'https://www.southwire.com//wire-cable/overhead-covered-conductor/cu-str-poly-linewire/p/OCC6',
'https://www.southwire.com//wire-cable/overhead-covered-conductor/cu-vip-overhead/p/OCC2',
'https://www.southwire.com//wire-cable/overhead-covered-conductor/cu-xlp-duplex-service-drop/p/OCC9',
'https://www.southwire.com//wire-cable/overhead-covered-conductor/cu-xlp-quadruplex-service-drop/p/OCC11',
'https://www.southwire.com//wire-cable/overhead-covered-conductor/cu-xlp-triplex-service-drop/p/OCC10',
'https://www.southwire.com//wire-cable/power-control/instrumentation-300v-600v/p/TC7',
'https://www.southwire.com//wire-cable/power-control/multiconductor-600v-2000v/p/TC2',
'https://www.southwire.com//wire-cable/power-control/shielded-multiconductor-600v-2000v/p/TC6',
'https://www.southwire.com//wire-cable/power-control/single-conductor-2000v/p/TC1',
'https://www.southwire.com//wire-cable/power-control/single-conductor-600v-2000v/p/TC3',
'https://www.southwire.com//wire-cable/power-control/unshielded-multiconductor-600v-2000v/p/TC5',
'https://www.southwire.com//wire-cable/pump-irrigation/flat-jacketed-heavy-duty-type-thw/p/PI2',
'https://www.southwire.com//wire-cable/pump-irrigation/flat-parallel-type-thw/p/PI1',
'https://www.southwire.com//wire-cable/pump-irrigation/hi-lo-supreme-twisted-pump-cable-type-thw-with-ground/p/PI3',
'https://www.southwire.com//wire-cable/pump-irrigation/round-twisted-jacketed-type-thw/p/PI5',
'https://www.southwire.com//wire-cable/pump-irrigation/twisted-pump-cable-type-thw/p/PI4',
'https://www.southwire.com//wire-cable/simpull-cable-in-conduit/schedule-40-empty-duct/p/CIC43',
'https://www.southwire.com//wire-cable/simpull-cable-in-conduit/schedule-40-empty-duct-with-pull-rope/p/CIC46',
'https://www.southwire.com//wire-cable/simpull-cable-in-conduit/schedule-80-empty-duct/p/CIC42',
'https://www.southwire.com//wire-cable/simpull-cable-in-conduit/schedule-80-empty-duct-with-pull-rope/p/CIC47',
'https://www.southwire.com//wire-cable/simpull-cable-in-conduit/sdr-11-empty-duct/p/CIC44',
'https://www.southwire.com//wire-cable/simpull-cable-in-conduit/sdr-11-empty-duct-with-pull-rope/p/CIC48',
'https://www.southwire.com//wire-cable/simpull-cable-in-conduit/sdr-13-5-empty-duct/p/CIC45',
'https://www.southwire.com//wire-cable/simpull-cable-in-conduit/sdr-13-5-empty-duct-with-pull-rope/p/CIC49',
'https://www.southwire.com//wire-cable/substation/cu-frxlpe-cpe-tp-control-cable/p/SUBSTN26',
'https://www.southwire.com//wire-cable/substation/cu-frxlpe-cpe-tp-shielded-control-cable/p/SUBSTN24',
'https://www.southwire.com//wire-cable/substation/cu-frxlpe-cpe-ts-control-cable/p/SUBSTN30',
'https://www.southwire.com//wire-cable/substation/cu-frxlpe-lszh-tp-control-cable/p/SUBSTN31',
'https://www.southwire.com//wire-cable/substation/cu-frxlpe-lszh-tp-shielded-control-cable/p/SUBSTN33',
'https://www.southwire.com//wire-cable/substation/cu-frxlpe-pvc-control-cable/p/SUBSTN27',
'https://www.southwire.com//wire-cable/substation/cu-frxlpe-pvc-shielded-control-cable/p/SUBSTN25',
'https://www.southwire.com//wire-cable/substation/cu-pe-pvc-control-cable/p/SUBSTN29',
'https://www.southwire.com//wire-cable/substation/cu-pe-pvc-shielded-control-cable/p/SUBSTN28',
'https://www.southwire.com//wire-cable/substation/cu-thhn-control-cable/p/SUBSTN34',
'https://www.southwire.com//wire-cable/telecom-power/telcoflex-l2-telecom-power-wire-and-cable/p/TCP3',
'https://www.southwire.com//wire-cable/telecom-power/telcoflex-l3-telecom-power-wire-and-cable/p/TCP4',
'https://www.southwire.com//wire-cable/telecom-power/telcoflex-l4-telecom-power-wire-and-cable/p/TCP5',
'https://www.southwire.com//wire-cable/telecom-power/telcoflex-g-l6-telecom-grounding-cable-green/p/TCP7',
'https://www.southwire.com//wire-cable/transit-cable/cu-2000v-epr-rhh-rhw-2-lszh-traction-power-cable/p/TRC6',
'https://www.southwire.com//wire-cable/transit-cable/cu-hard-drawn-overhead-catenary-systems-messenger-wire/p/TRC3',
'https://www.southwire.com//wire-cable/transit-cable/cu-overhead-catenary-wire/p/TRC4',
'https://www.southwire.com//wire-cable/transit-cable/overhead-catenary-wire/p/TRC5',


]
w=0
for j in l:
    # print(j)
    w+=1
    # print(w)
    r=requests.get(j)
    soup=BeautifulSoup(r.text,'html.parser')
    try:
        ex_link=soup.find_all('td',class_='specifications__table-cta')
        # for ex in ex_link:
        #     save_details: TextIO = open("southwire_link_wire_cable.txt", "a+", encoding="utf-8")
        #     save_details.write("\n" + "'https://www.southwire.com/"+ex.find('a').get('href')+"'," )
        #     print("End")
        #     save_details.close()
        #     print("'https://www.southwire.com/"+ex.find('a').get('href')+"',")

    except:
        print("'"+j+"',")
        pass

    # link=soup.find_all('div',class_='product-tile__name-wrap')
    # count=soup.find('h1',class_='view-options__name h5')
    # try:
    #     c=count.text.split('(')
    #     c1=round(int(c[1].split(')')[0])/24,0)
    #     print(c1)
    # except:
    #
    #     c1 = round(int(c[2].split(')')[0]) / 24, 0)
    #     print(c1)
    #     pass
    #
    # for li in link:
    #     # li_a=li.find_all('a')
    #     # for a in li_a:
    #     save_details: TextIO = open("southwire_link.txt", "a+", encoding="utf-8")
    #     save_details.write("\n" + "'https://www.southwire.com/" + li.find('a').get('href') + "',")
    #     print("End")
    #     save_details.close()
    #     print("'https://www.southwire.com/" + li.find('a').get('href') + "',")
    # if int(c1)>1:
    #     for j1 in range (1,int(c1)):
    #         r = requests.get(j+"?q=%3Ab2c-name-asc&page="+str(j1)+"&pageSize=24&sort=b2c-name-asc")
    #         soup = BeautifulSoup(r.text, 'html.parser')
    #         link = soup.find_all('div', class_='product-tile__name-wrap')
    #         for li in link:
    #             # li_a=li.find_all('a')
    #             # for a in li_a:
    #             save_details: TextIO = open("southwire_link_wire_cable.txt", "a+", encoding="utf-8")
    #             save_details.write("\n" + "'https://www.southwire.com/"+li.find('a').get('href')+"'," )
    #             print("End")
    #             save_details.close()
    #             print("'https://www.southwire.com/"+li.find('a').get('href')+"',")
    #         break