import time
from typing import TextIO

import requests
# from selenium import webdriver
# from selenium.webdriver.chrome.options import Options
# from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup

# import time

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"}
# opts = Options()
# opts.headless = False
# driver = webdriver.Chrome()
# driver.maximize_window()


mylst = [

    # 'https://www.cmtindustrial.com/catalogue/product/846104',
    # 'https://www.cmtindustrial.com/catalogue/product/846105',
    # 'https://www.cmtindustrial.com/catalogue/product/846106',
    # 'https://www.cmtindustrial.com/catalogue/product/846107',
    # 'https://www.cmtindustrial.com/catalogue/product/846108',
    # 'https://www.cmtindustrial.com/catalogue/product/846109',
    # 'https://www.cmtindustrial.com/catalogue/product/846110',
    # 'https://www.cmtindustrial.com/catalogue/product/846111',
    # 'https://www.cmtindustrial.com/catalogue/product/846112',
    # 'https://www.cmtindustrial.com/catalogue/product/846113',
    # 'https://www.cmtindustrial.com/catalogue/product/846114',
    # 'https://www.cmtindustrial.com/catalogue/product/846115',
    # 'https://www.cmtindustrial.com/catalogue/product/846116',
    # 'https://www.cmtindustrial.com/catalogue/product/846117',
    # 'https://www.cmtindustrial.com/catalogue/product/846118',
    # 'https://www.cmtindustrial.com/catalogue/product/846119',
    # 'https://www.cmtindustrial.com/catalogue/product/846120',
    # 'https://www.cmtindustrial.com/catalogue/product/846121',
    # 'https://www.cmtindustrial.com/catalogue/product/846122',
    # 'https://www.cmtindustrial.com/catalogue/product/846123',
    # 'https://www.cmtindustrial.com/catalogue/product/846124',
    # 'https://www.cmtindustrial.com/catalogue/product/846125',
    # 'https://www.cmtindustrial.com/catalogue/product/846126',
    # 'https://www.cmtindustrial.com/catalogue/product/846127',
    # 'https://www.cmtindustrial.com/catalogue/product/846128',
    # 'https://www.cmtindustrial.com/catalogue/product/846129',
    # 'https://www.cmtindustrial.com/catalogue/product/846130',
    # 'https://www.cmtindustrial.com/catalogue/product/846131',
    # 'https://www.cmtindustrial.com/catalogue/product/846132',
    # 'https://www.cmtindustrial.com/catalogue/product/846133',
    # 'https://www.cmtindustrial.com/catalogue/product/846134',
    # 'https://www.cmtindustrial.com/catalogue/product/846135',
    # 'https://www.cmtindustrial.com/catalogue/product/846136',
    # 'https://www.cmtindustrial.com/catalogue/product/846137',
    # 'https://www.cmtindustrial.com/catalogue/product/846138',
    # 'https://www.cmtindustrial.com/catalogue/product/846139',
    # 'https://www.cmtindustrial.com/catalogue/product/846140',
    # 'https://www.cmtindustrial.com/catalogue/product/846141',
    # 'https://www.cmtindustrial.com/catalogue/product/846142',
    # 'https://www.cmtindustrial.com/catalogue/product/846143',
    # 'https://www.cmtindustrial.com/catalogue/product/846144',
    # 'https://www.cmtindustrial.com/catalogue/product/846145',
    # 'https://www.cmtindustrial.com/catalogue/product/846146',
    # 'https://www.cmtindustrial.com/catalogue/product/846147',
    # 'https://www.cmtindustrial.com/catalogue/product/846148',
    # 'https://www.cmtindustrial.com/catalogue/product/846149',
    # 'https://www.cmtindustrial.com/catalogue/product/846150',
    # 'https://www.cmtindustrial.com/catalogue/product/846151',
    # 'https://www.cmtindustrial.com/catalogue/product/846152',
    # 'https://www.cmtindustrial.com/catalogue/product/846153',
    # 'https://www.cmtindustrial.com/catalogue/product/846154',
    # 'https://www.cmtindustrial.com/catalogue/product/846155',
    # 'https://www.cmtindustrial.com/catalogue/product/846156',
    # 'https://www.cmtindustrial.com/catalogue/product/846157',
    # 'https://www.cmtindustrial.com/catalogue/product/846158',
    # 'https://www.cmtindustrial.com/catalogue/product/846159',
    # 'https://www.cmtindustrial.com/catalogue/product/846160',
    # 'https://www.cmtindustrial.com/catalogue/product/846161',
    # 'https://www.cmtindustrial.com/catalogue/product/846162',
    # 'https://www.cmtindustrial.com/catalogue/product/846163',
    # 'https://www.cmtindustrial.com/catalogue/product/846164',
    # 'https://www.cmtindustrial.com/catalogue/product/846165',
    # 'https://www.cmtindustrial.com/catalogue/product/846166',
    # 'https://www.cmtindustrial.com/catalogue/product/846167',
    # 'https://www.cmtindustrial.com/catalogue/product/846168',
    # 'https://www.cmtindustrial.com/catalogue/product/846169',
    # 'https://www.cmtindustrial.com/catalogue/product/846170',
    # 'https://www.cmtindustrial.com/catalogue/product/846171',
    # 'https://www.cmtindustrial.com/catalogue/product/846172',
    # 'https://www.cmtindustrial.com/catalogue/product/846173',
    # 'https://www.cmtindustrial.com/catalogue/product/846174',
    # 'https://www.cmtindustrial.com/catalogue/product/846175',
    # 'https://www.cmtindustrial.com/catalogue/product/846176',
    # 'https://www.cmtindustrial.com/catalogue/product/846177',
    # 'https://www.cmtindustrial.com/catalogue/product/846178',
    # 'https://www.cmtindustrial.com/catalogue/product/846179',
    # 'https://www.cmtindustrial.com/catalogue/product/846180',
    # 'https://www.cmtindustrial.com/catalogue/product/846181',
    # 'https://www.cmtindustrial.com/catalogue/product/846182',
    # 'https://www.cmtindustrial.com/catalogue/product/846183',
    # 'https://www.cmtindustrial.com/catalogue/product/846184',

    'https://www.cmtindustrial.com/catalogue/product/846185',
    'https://www.cmtindustrial.com/catalogue/product/846186',
    'https://www.cmtindustrial.com/catalogue/product/846187',
    'https://www.cmtindustrial.com/catalogue/product/846188',
    # 'https://www.cmtindustrial.com/catalogue/product/846189',
    # 'https://www.cmtindustrial.com/catalogue/product/846190',
    # 'https://www.cmtindustrial.com/catalogue/product/846191',
    # 'https://www.cmtindustrial.com/catalogue/product/846192',
    # 'https://www.cmtindustrial.com/catalogue/product/846193',
    # 'https://www.cmtindustrial.com/catalogue/product/846194',
    # 'https://www.cmtindustrial.com/catalogue/product/846195',
    # 'https://www.cmtindustrial.com/catalogue/product/846196',
    # 'https://www.cmtindustrial.com/catalogue/product/846197',
    # 'https://www.cmtindustrial.com/catalogue/product/846198',
    # 'https://www.cmtindustrial.com/catalogue/product/846199',
    # 'https://www.cmtindustrial.com/catalogue/product/846200',
    # 'https://www.cmtindustrial.com/catalogue/product/846201',
    # 'https://www.cmtindustrial.com/catalogue/product/846202',
    # 'https://www.cmtindustrial.com/catalogue/product/846203',
    # 'https://www.cmtindustrial.com/catalogue/product/846204',
    # 'https://www.cmtindustrial.com/catalogue/product/846205',
    # 'https://www.cmtindustrial.com/catalogue/product/846206',
    # 'https://www.cmtindustrial.com/catalogue/product/846207',
    # 'https://www.cmtindustrial.com/catalogue/product/846208',
    # 'https://www.cmtindustrial.com/catalogue/product/846209',
    # 'https://www.cmtindustrial.com/catalogue/product/846210',
    # 'https://www.cmtindustrial.com/catalogue/product/846211',
    # 'https://www.cmtindustrial.com/catalogue/product/846212',
    # 'https://www.cmtindustrial.com/catalogue/product/846213',
    # 'https://www.cmtindustrial.com/catalogue/product/846214',
    # 'https://www.cmtindustrial.com/catalogue/product/846215',
    # 'https://www.cmtindustrial.com/catalogue/product/846216',
    # 'https://www.cmtindustrial.com/catalogue/product/846217',
    # 'https://www.cmtindustrial.com/catalogue/product/846218',
    # 'https://www.cmtindustrial.com/catalogue/product/846219',
    # 'https://www.cmtindustrial.com/catalogue/product/846220',
    # 'https://www.cmtindustrial.com/catalogue/product/846221',
    # 'https://www.cmtindustrial.com/catalogue/product/846222',
    # 'https://www.cmtindustrial.com/catalogue/product/846223',
    # 'https://www.cmtindustrial.com/catalogue/product/846224',
    # 'https://www.cmtindustrial.com/catalogue/product/846225',
    # 'https://www.cmtindustrial.com/catalogue/product/846226',
    # 'https://www.cmtindustrial.com/catalogue/product/846227',
    # 'https://www.cmtindustrial.com/catalogue/product/846228',
    # 'https://www.cmtindustrial.com/catalogue/product/846229',
    # 'https://www.cmtindustrial.com/catalogue/product/846230',
    # 'https://www.cmtindustrial.com/catalogue/product/846231',
    # 'https://www.cmtindustrial.com/catalogue/product/846232',
    # 'https://www.cmtindustrial.com/catalogue/product/846233',
    # 'https://www.cmtindustrial.com/catalogue/product/846234',
    # 'https://www.cmtindustrial.com/catalogue/product/846235',
    # 'https://www.cmtindustrial.com/catalogue/product/846236',
    # 'https://www.cmtindustrial.com/catalogue/product/846237',
    # 'https://www.cmtindustrial.com/catalogue/product/846238',
    # 'https://www.cmtindustrial.com/catalogue/product/846239',
    # 'https://www.cmtindustrial.com/catalogue/product/846240',
    # 'https://www.cmtindustrial.com/catalogue/product/846241',
    # 'https://www.cmtindustrial.com/catalogue/product/846242',
    # 'https://www.cmtindustrial.com/catalogue/product/846243',
    # 'https://www.cmtindustrial.com/catalogue/product/846244',
    # 'https://www.cmtindustrial.com/catalogue/product/846245',
    # 'https://www.cmtindustrial.com/catalogue/product/846246',
    # 'https://www.cmtindustrial.com/catalogue/product/846247',
    # 'https://www.cmtindustrial.com/catalogue/product/846248',
    # 'https://www.cmtindustrial.com/catalogue/product/846249',
    # 'https://www.cmtindustrial.com/catalogue/product/846250',
    # 'https://www.cmtindustrial.com/catalogue/product/846251',
    # 'https://www.cmtindustrial.com/catalogue/product/846252',
    # 'https://www.cmtindustrial.com/catalogue/product/846253',
    # 'https://www.cmtindustrial.com/catalogue/product/846254',
    # 'https://www.cmtindustrial.com/catalogue/product/846255',
    # 'https://www.cmtindustrial.com/catalogue/product/846256',
    # 'https://www.cmtindustrial.com/catalogue/product/846257',
    # 'https://www.cmtindustrial.com/catalogue/product/846258',
    # 'https://www.cmtindustrial.com/catalogue/product/846259',
    # 'https://www.cmtindustrial.com/catalogue/product/846260',
    # 'https://www.cmtindustrial.com/catalogue/product/846261',
    # 'https://www.cmtindustrial.com/catalogue/product/846262',
    # 'https://www.cmtindustrial.com/catalogue/product/846263',
    # 'https://www.cmtindustrial.com/catalogue/product/846264',
    # 'https://www.cmtindustrial.com/catalogue/product/846265',
    # 'https://www.cmtindustrial.com/catalogue/product/846266',
    # 'https://www.cmtindustrial.com/catalogue/product/846267',
    # 'https://www.cmtindustrial.com/catalogue/product/846268',
    # 'https://www.cmtindustrial.com/catalogue/product/846269',
    # 'https://www.cmtindustrial.com/catalogue/product/846270',
    # 'https://www.cmtindustrial.com/catalogue/product/846271',
    # 'https://www.cmtindustrial.com/catalogue/product/846272',
    # 'https://www.cmtindustrial.com/catalogue/product/846273',
    # 'https://www.cmtindustrial.com/catalogue/product/846274',
    # 'https://www.cmtindustrial.com/catalogue/product/846275',
    # 'https://www.cmtindustrial.com/catalogue/product/846276',
    # 'https://www.cmtindustrial.com/catalogue/product/846277',
    # 'https://www.cmtindustrial.com/catalogue/product/846278',
    # 'https://www.cmtindustrial.com/catalogue/product/846279',
    # 'https://www.cmtindustrial.com/catalogue/product/846280',
    # 'https://www.cmtindustrial.com/catalogue/product/846281',
    # 'https://www.cmtindustrial.com/catalogue/product/846282',
    # 'https://www.cmtindustrial.com/catalogue/product/846283',
    # 'https://www.cmtindustrial.com/catalogue/product/846284',
    # 'https://www.cmtindustrial.com/catalogue/product/846285',
    # 'https://www.cmtindustrial.com/catalogue/product/846286',
    # 'https://www.cmtindustrial.com/catalogue/product/846287',
    # 'https://www.cmtindustrial.com/catalogue/product/846288',
    # 'https://www.cmtindustrial.com/catalogue/product/846289',
    # 'https://www.cmtindustrial.com/catalogue/product/846290',
    # 'https://www.cmtindustrial.com/catalogue/product/846291',
    # 'https://www.cmtindustrial.com/catalogue/product/846292',
    # 'https://www.cmtindustrial.com/catalogue/product/846293',
    # 'https://www.cmtindustrial.com/catalogue/product/846294',
    # 'https://www.cmtindustrial.com/catalogue/product/846295',
    # 'https://www.cmtindustrial.com/catalogue/product/846296',
    # 'https://www.cmtindustrial.com/catalogue/product/846297',
    # 'https://www.cmtindustrial.com/catalogue/product/846298',
    # 'https://www.cmtindustrial.com/catalogue/product/846299',
    # 'https://www.cmtindustrial.com/catalogue/product/846300',
    # 'https://www.cmtindustrial.com/catalogue/product/846301',
    # 'https://www.cmtindustrial.com/catalogue/product/846302',
    # 'https://www.cmtindustrial.com/catalogue/product/846303',
    # 'https://www.cmtindustrial.com/catalogue/product/846304',
    # 'https://www.cmtindustrial.com/catalogue/product/846305',
    # 'https://www.cmtindustrial.com/catalogue/product/846306',
    # 'https://www.cmtindustrial.com/catalogue/product/846307',
    # 'https://www.cmtindustrial.com/catalogue/product/846308',
    # 'https://www.cmtindustrial.com/catalogue/product/846309',
    # 'https://www.cmtindustrial.com/catalogue/product/846310',
    # 'https://www.cmtindustrial.com/catalogue/product/846311',
    # 'https://www.cmtindustrial.com/catalogue/product/846312',
    # 'https://www.cmtindustrial.com/catalogue/product/846313',
    # 'https://www.cmtindustrial.com/catalogue/product/846314',
    # 'https://www.cmtindustrial.com/catalogue/product/846315',
    # 'https://www.cmtindustrial.com/catalogue/product/846316',
    # 'https://www.cmtindustrial.com/catalogue/product/846317',
    # 'https://www.cmtindustrial.com/catalogue/product/846318',
    # 'https://www.cmtindustrial.com/catalogue/product/846319',
    # 'https://www.cmtindustrial.com/catalogue/product/846320',
    # 'https://www.cmtindustrial.com/catalogue/product/846321',
    # 'https://www.cmtindustrial.com/catalogue/product/846322',
    # 'https://www.cmtindustrial.com/catalogue/product/846323',
    # 'https://www.cmtindustrial.com/catalogue/product/846324',
    # 'https://www.cmtindustrial.com/catalogue/product/846325',
    # 'https://www.cmtindustrial.com/catalogue/product/846326',
    # 'https://www.cmtindustrial.com/catalogue/product/846327',
    # 'https://www.cmtindustrial.com/catalogue/product/846328',
    # 'https://www.cmtindustrial.com/catalogue/product/846329',
    # 'https://www.cmtindustrial.com/catalogue/product/846330',
    # 'https://www.cmtindustrial.com/catalogue/product/846331',
    # 'https://www.cmtindustrial.com/catalogue/product/846332',
    # 'https://www.cmtindustrial.com/catalogue/product/846333',
    # 'https://www.cmtindustrial.com/catalogue/product/846334',
    'https://www.cmtindustrial.com/catalogue/product/846335',
    'https://www.cmtindustrial.com/catalogue/product/846336',
    # 'https://www.cmtindustrial.com/catalogue/product/846337',
    # 'https://www.cmtindustrial.com/catalogue/product/846338',
    # 'https://www.cmtindustrial.com/catalogue/product/846339',
    # 'https://www.cmtindustrial.com/catalogue/product/846340',
    # 'https://www.cmtindustrial.com/catalogue/product/846341',
    # 'https://www.cmtindustrial.com/catalogue/product/846342',
    # 'https://www.cmtindustrial.com/catalogue/product/846343',
    # 'https://www.cmtindustrial.com/catalogue/product/846344',
    # 'https://www.cmtindustrial.com/catalogue/product/846345',
    # 'https://www.cmtindustrial.com/catalogue/product/846346',
    # 'https://www.cmtindustrial.com/catalogue/product/846347',
    'https://www.cmtindustrial.com/catalogue/product/846348',
    'https://www.cmtindustrial.com/catalogue/product/846349',
    'https://www.cmtindustrial.com/catalogue/product/846350',
    'https://www.cmtindustrial.com/catalogue/product/846351',
    'https://www.cmtindustrial.com/catalogue/product/846352',
    'https://www.cmtindustrial.com/catalogue/product/846353',
    'https://www.cmtindustrial.com/catalogue/product/846354',
    'https://www.cmtindustrial.com/catalogue/product/846355',
    'https://www.cmtindustrial.com/catalogue/product/846356',
    'https://www.cmtindustrial.com/catalogue/product/846357',
    'https://www.cmtindustrial.com/catalogue/product/846358',
    'https://www.cmtindustrial.com/catalogue/product/846359',
    'https://www.cmtindustrial.com/catalogue/product/846360',
    'https://www.cmtindustrial.com/catalogue/product/846361',
    'https://www.cmtindustrial.com/catalogue/product/846362',
    'https://www.cmtindustrial.com/catalogue/product/846363',
    'https://www.cmtindustrial.com/catalogue/product/846364',
    'https://www.cmtindustrial.com/catalogue/product/847084',
    'https://www.cmtindustrial.com/catalogue/product/847085',
    'https://www.cmtindustrial.com/catalogue/product/847086',
    'https://www.cmtindustrial.com/catalogue/product/847087',
    'https://www.cmtindustrial.com/catalogue/product/847088',
    'https://www.cmtindustrial.com/catalogue/product/847089',
    'https://www.cmtindustrial.com/catalogue/product/847090',
    'https://www.cmtindustrial.com/catalogue/product/847091',
    'https://www.cmtindustrial.com/catalogue/product/847092',
    'https://www.cmtindustrial.com/catalogue/product/847093',
    'https://www.cmtindustrial.com/catalogue/product/847094',
    'https://www.cmtindustrial.com/catalogue/product/847095',
    'https://www.cmtindustrial.com/catalogue/product/847096',
    'https://www.cmtindustrial.com/catalogue/product/847097',
    'https://www.cmtindustrial.com/catalogue/product/847098',
    'https://www.cmtindustrial.com/catalogue/product/847099',
    'https://www.cmtindustrial.com/catalogue/product/847100',
    'https://www.cmtindustrial.com/catalogue/product/847101',
    'https://www.cmtindustrial.com/catalogue/product/847102',
    'https://www.cmtindustrial.com/catalogue/product/847103',
    'https://www.cmtindustrial.com/catalogue/product/847104',
    'https://www.cmtindustrial.com/catalogue/product/847105',
    'https://www.cmtindustrial.com/catalogue/product/847106',
    'https://www.cmtindustrial.com/catalogue/product/847107',
    'https://www.cmtindustrial.com/catalogue/product/847108',
    'https://www.cmtindustrial.com/catalogue/product/847612',
    'https://www.cmtindustrial.com/catalogue/product/847613',
    'https://www.cmtindustrial.com/catalogue/product/847614',
    'https://www.cmtindustrial.com/catalogue/product/847615',
    'https://www.cmtindustrial.com/catalogue/product/847616',
    'https://www.cmtindustrial.com/catalogue/product/847617',
    'https://www.cmtindustrial.com/catalogue/product/847618',
    'https://www.cmtindustrial.com/catalogue/product/847619',
    'https://www.cmtindustrial.com/catalogue/product/847620',
    'https://www.cmtindustrial.com/catalogue/product/847621',
    'https://www.cmtindustrial.com/catalogue/product/847622',
    'https://www.cmtindustrial.com/catalogue/product/847623',
    'https://www.cmtindustrial.com/catalogue/product/847624',
    'https://www.cmtindustrial.com/catalogue/product/847625',
    'https://www.cmtindustrial.com/catalogue/product/847626',
    'https://www.cmtindustrial.com/catalogue/product/847627',
    'https://www.cmtindustrial.com/catalogue/product/847628',
    'https://www.cmtindustrial.com/catalogue/product/847629',
    'https://www.cmtindustrial.com/catalogue/product/847630',
    'https://www.cmtindustrial.com/catalogue/product/847631',
    'https://www.cmtindustrial.com/catalogue/product/847632',
    'https://www.cmtindustrial.com/catalogue/product/847633',
    'https://www.cmtindustrial.com/catalogue/product/847634',
    'https://www.cmtindustrial.com/catalogue/product/847635',
    'https://www.cmtindustrial.com/catalogue/product/847636',
    'https://www.cmtindustrial.com/catalogue/product/847637',
    'https://www.cmtindustrial.com/catalogue/product/847638',
    'https://www.cmtindustrial.com/catalogue/product/847639',
    'https://www.cmtindustrial.com/catalogue/product/847640',
    'https://www.cmtindustrial.com/catalogue/product/847641',
    'https://www.cmtindustrial.com/catalogue/product/847642',
    'https://www.cmtindustrial.com/catalogue/product/847643',
    'https://www.cmtindustrial.com/catalogue/product/847644',
    'https://www.cmtindustrial.com/catalogue/product/847645',
    'https://www.cmtindustrial.com/catalogue/product/847646',
    'https://www.cmtindustrial.com/catalogue/product/847647',
    'https://www.cmtindustrial.com/catalogue/product/847648',
    'https://www.cmtindustrial.com/catalogue/product/847649',
    'https://www.cmtindustrial.com/catalogue/product/847650',
    'https://www.cmtindustrial.com/catalogue/product/847651',
    'https://www.cmtindustrial.com/catalogue/product/847652',
    'https://www.cmtindustrial.com/catalogue/product/847653',
    'https://www.cmtindustrial.com/catalogue/product/847654',
    'https://www.cmtindustrial.com/catalogue/product/847655',
    'https://www.cmtindustrial.com/catalogue/product/847656',
    'https://www.cmtindustrial.com/catalogue/product/847657',
    'https://www.cmtindustrial.com/catalogue/product/847658',
    'https://www.cmtindustrial.com/catalogue/product/847659',
    'https://www.cmtindustrial.com/catalogue/product/847660',
    'https://www.cmtindustrial.com/catalogue/product/847661',
    'https://www.cmtindustrial.com/catalogue/product/847662',
    'https://www.cmtindustrial.com/catalogue/product/847663',
    'https://www.cmtindustrial.com/catalogue/product/847664',
    'https://www.cmtindustrial.com/catalogue/product/847665',
    'https://www.cmtindustrial.com/catalogue/product/847666',
    'https://www.cmtindustrial.com/catalogue/product/847667',
    'https://www.cmtindustrial.com/catalogue/product/847668',
    'https://www.cmtindustrial.com/catalogue/product/847669',
    'https://www.cmtindustrial.com/catalogue/product/847670',
    'https://www.cmtindustrial.com/catalogue/product/847671',
    'https://www.cmtindustrial.com/catalogue/product/847672',
    'https://www.cmtindustrial.com/catalogue/product/847673',
    'https://www.cmtindustrial.com/catalogue/product/847674',
    'https://www.cmtindustrial.com/catalogue/product/847675',
    'https://www.cmtindustrial.com/catalogue/product/847676',
    'https://www.cmtindustrial.com/catalogue/product/847677',
    'https://www.cmtindustrial.com/catalogue/product/847678',
    'https://www.cmtindustrial.com/catalogue/product/847679',
    'https://www.cmtindustrial.com/catalogue/product/847680',
    'https://www.cmtindustrial.com/catalogue/product/841668',
    'https://www.cmtindustrial.com/catalogue/product/841669',
    'https://www.cmtindustrial.com/catalogue/product/841670',
    'https://www.cmtindustrial.com/catalogue/product/841671',
    'https://www.cmtindustrial.com/catalogue/product/841672',
    'https://www.cmtindustrial.com/catalogue/product/841673',
    'https://www.cmtindustrial.com/catalogue/product/841674',
    'https://www.cmtindustrial.com/catalogue/product/841675',
    'https://www.cmtindustrial.com/catalogue/product/841676',
    'https://www.cmtindustrial.com/catalogue/product/841677',
    'https://www.cmtindustrial.com/catalogue/product/841678',
    'https://www.cmtindustrial.com/catalogue/product/841679',
    'https://www.cmtindustrial.com/catalogue/product/841680',
    'https://www.cmtindustrial.com/catalogue/product/841681',
    'https://www.cmtindustrial.com/catalogue/product/841682',
    'https://www.cmtindustrial.com/catalogue/product/841683',
    'https://www.cmtindustrial.com/catalogue/product/841684',
    'https://www.cmtindustrial.com/catalogue/product/841685',
    'https://www.cmtindustrial.com/catalogue/product/841686',
    'https://www.cmtindustrial.com/catalogue/product/841687',
    'https://www.cmtindustrial.com/catalogue/product/841688',
    'https://www.cmtindustrial.com/catalogue/product/841689',
    'https://www.cmtindustrial.com/catalogue/product/841690',
    'https://www.cmtindustrial.com/catalogue/product/841691',
    'https://www.cmtindustrial.com/catalogue/product/841692',
    'https://www.cmtindustrial.com/catalogue/product/841693',
    'https://www.cmtindustrial.com/catalogue/product/841694',
    'https://www.cmtindustrial.com/catalogue/product/841695',
    'https://www.cmtindustrial.com/catalogue/product/841696',
    'https://www.cmtindustrial.com/catalogue/product/841697',
    'https://www.cmtindustrial.com/catalogue/product/841698',
    'https://www.cmtindustrial.com/catalogue/product/841699',
    'https://www.cmtindustrial.com/catalogue/product/841700',
    'https://www.cmtindustrial.com/catalogue/product/841701',
    'https://www.cmtindustrial.com/catalogue/product/841702',
    'https://www.cmtindustrial.com/catalogue/product/841703',
    'https://www.cmtindustrial.com/catalogue/product/841704',
    'https://www.cmtindustrial.com/catalogue/product/841705',
    'https://www.cmtindustrial.com/catalogue/product/841706',
    'https://www.cmtindustrial.com/catalogue/product/841707',
    'https://www.cmtindustrial.com/catalogue/product/841708',
    'https://www.cmtindustrial.com/catalogue/product/841709',
    'https://www.cmtindustrial.com/catalogue/product/841710',
    'https://www.cmtindustrial.com/catalogue/product/841711',
    'https://www.cmtindustrial.com/catalogue/product/841712',
    'https://www.cmtindustrial.com/catalogue/product/841713',
    'https://www.cmtindustrial.com/catalogue/product/841714',
    'https://www.cmtindustrial.com/catalogue/product/841715',
    'https://www.cmtindustrial.com/catalogue/product/841716',
    'https://www.cmtindustrial.com/catalogue/product/841717',
    'https://www.cmtindustrial.com/catalogue/product/841718',
    'https://www.cmtindustrial.com/catalogue/product/841719',
    'https://www.cmtindustrial.com/catalogue/product/841720',
    'https://www.cmtindustrial.com/catalogue/product/841721',
    'https://www.cmtindustrial.com/catalogue/product/841722',
    'https://www.cmtindustrial.com/catalogue/product/841723',
    'https://www.cmtindustrial.com/catalogue/product/841724',
    'https://www.cmtindustrial.com/catalogue/product/841725',
    'https://www.cmtindustrial.com/catalogue/product/841726',
    'https://www.cmtindustrial.com/catalogue/product/841727',
    'https://www.cmtindustrial.com/catalogue/product/841728',
    'https://www.cmtindustrial.com/catalogue/product/841729',
    'https://www.cmtindustrial.com/catalogue/product/841730',
    'https://www.cmtindustrial.com/catalogue/product/841731',
    'https://www.cmtindustrial.com/catalogue/product/841732',
    'https://www.cmtindustrial.com/catalogue/product/841733',
    'https://www.cmtindustrial.com/catalogue/product/841734',
    'https://www.cmtindustrial.com/catalogue/product/841735',
    'https://www.cmtindustrial.com/catalogue/product/841736',
    'https://www.cmtindustrial.com/catalogue/product/841737',
    'https://www.cmtindustrial.com/catalogue/product/841738',
    'https://www.cmtindustrial.com/catalogue/product/841739',
    'https://www.cmtindustrial.com/catalogue/product/841740',
    'https://www.cmtindustrial.com/catalogue/product/841741',
    'https://www.cmtindustrial.com/catalogue/product/841742',
    'https://www.cmtindustrial.com/catalogue/product/841743',
    'https://www.cmtindustrial.com/catalogue/product/841744',
    'https://www.cmtindustrial.com/catalogue/product/841745',
    'https://www.cmtindustrial.com/catalogue/product/841746',
    'https://www.cmtindustrial.com/catalogue/product/841747',
    'https://www.cmtindustrial.com/catalogue/product/841748',
    'https://www.cmtindustrial.com/catalogue/product/841749',
    'https://www.cmtindustrial.com/catalogue/product/841750',
    'https://www.cmtindustrial.com/catalogue/product/841751',
    'https://www.cmtindustrial.com/catalogue/product/841752',
    'https://www.cmtindustrial.com/catalogue/product/841753',
    'https://www.cmtindustrial.com/catalogue/product/841754',
    'https://www.cmtindustrial.com/catalogue/product/841755',
    'https://www.cmtindustrial.com/catalogue/product/841756',
    'https://www.cmtindustrial.com/catalogue/product/841757',
    'https://www.cmtindustrial.com/catalogue/product/841758',
    'https://www.cmtindustrial.com/catalogue/product/841759',
    'https://www.cmtindustrial.com/catalogue/product/841760',
    'https://www.cmtindustrial.com/catalogue/product/841761',
    'https://www.cmtindustrial.com/catalogue/product/841762',
    'https://www.cmtindustrial.com/catalogue/product/841763',
    'https://www.cmtindustrial.com/catalogue/product/841764',
    'https://www.cmtindustrial.com/catalogue/product/841765',
    'https://www.cmtindustrial.com/catalogue/product/841766',
    'https://www.cmtindustrial.com/catalogue/product/841767',
    'https://www.cmtindustrial.com/catalogue/product/841768',
    'https://www.cmtindustrial.com/catalogue/product/841769',
    'https://www.cmtindustrial.com/catalogue/product/841770',
    'https://www.cmtindustrial.com/catalogue/product/841771',
    'https://www.cmtindustrial.com/catalogue/product/841772',
    'https://www.cmtindustrial.com/catalogue/product/841773',
    'https://www.cmtindustrial.com/catalogue/product/841774',
    'https://www.cmtindustrial.com/catalogue/product/841775',
    'https://www.cmtindustrial.com/catalogue/product/841776',
    'https://www.cmtindustrial.com/catalogue/product/841777',
    'https://www.cmtindustrial.com/catalogue/product/841778',
    'https://www.cmtindustrial.com/catalogue/product/841779',
    'https://www.cmtindustrial.com/catalogue/product/841780',
    'https://www.cmtindustrial.com/catalogue/product/841781',
    'https://www.cmtindustrial.com/catalogue/product/841782',
    'https://www.cmtindustrial.com/catalogue/product/841783',
    'https://www.cmtindustrial.com/catalogue/product/841784',
    'https://www.cmtindustrial.com/catalogue/product/841785',
    'https://www.cmtindustrial.com/catalogue/product/841786',
    'https://www.cmtindustrial.com/catalogue/product/841787',
    'https://www.cmtindustrial.com/catalogue/product/841788',
    'https://www.cmtindustrial.com/catalogue/product/841789',
    'https://www.cmtindustrial.com/catalogue/product/841790',
    'https://www.cmtindustrial.com/catalogue/product/841791',
    'https://www.cmtindustrial.com/catalogue/product/841792',
    'https://www.cmtindustrial.com/catalogue/product/841793',
    'https://www.cmtindustrial.com/catalogue/product/841794',
    'https://www.cmtindustrial.com/catalogue/product/841795',
    'https://www.cmtindustrial.com/catalogue/product/841796',
    'https://www.cmtindustrial.com/catalogue/product/841797',
    'https://www.cmtindustrial.com/catalogue/product/841798',
    'https://www.cmtindustrial.com/catalogue/product/841799',
    'https://www.cmtindustrial.com/catalogue/product/841800',
    'https://www.cmtindustrial.com/catalogue/product/841801',
    'https://www.cmtindustrial.com/catalogue/product/841802',
    'https://www.cmtindustrial.com/catalogue/product/841803',
    'https://www.cmtindustrial.com/catalogue/product/841804',
    'https://www.cmtindustrial.com/catalogue/product/841805',
    'https://www.cmtindustrial.com/catalogue/product/841806',
    'https://www.cmtindustrial.com/catalogue/product/841807',
    'https://www.cmtindustrial.com/catalogue/product/841808',
    'https://www.cmtindustrial.com/catalogue/product/841809',
    'https://www.cmtindustrial.com/catalogue/product/841810',
    'https://www.cmtindustrial.com/catalogue/product/841811',
    'https://www.cmtindustrial.com/catalogue/product/841812',
    'https://www.cmtindustrial.com/catalogue/product/841813',
    'https://www.cmtindustrial.com/catalogue/product/841814',
    'https://www.cmtindustrial.com/catalogue/product/841815',
    'https://www.cmtindustrial.com/catalogue/product/841816',
    'https://www.cmtindustrial.com/catalogue/product/841817',
    'https://www.cmtindustrial.com/catalogue/product/841818',
    'https://www.cmtindustrial.com/catalogue/product/841819',
    'https://www.cmtindustrial.com/catalogue/product/841820',
    'https://www.cmtindustrial.com/catalogue/product/841821',
    'https://www.cmtindustrial.com/catalogue/product/841822',
    'https://www.cmtindustrial.com/catalogue/product/841823',
    'https://www.cmtindustrial.com/catalogue/product/841824',
    'https://www.cmtindustrial.com/catalogue/product/841825',
    'https://www.cmtindustrial.com/catalogue/product/841826',
    'https://www.cmtindustrial.com/catalogue/product/841827',
    'https://www.cmtindustrial.com/catalogue/product/841828',
    'https://www.cmtindustrial.com/catalogue/product/841829',
    'https://www.cmtindustrial.com/catalogue/product/841830',
    'https://www.cmtindustrial.com/catalogue/product/841831',
    'https://www.cmtindustrial.com/catalogue/product/841832',
    'https://www.cmtindustrial.com/catalogue/product/841833',
    'https://www.cmtindustrial.com/catalogue/product/841834',
    'https://www.cmtindustrial.com/catalogue/product/841835',
    'https://www.cmtindustrial.com/catalogue/product/841836',
    'https://www.cmtindustrial.com/catalogue/product/841837',
    'https://www.cmtindustrial.com/catalogue/product/841838',
    'https://www.cmtindustrial.com/catalogue/product/841839',
    'https://www.cmtindustrial.com/catalogue/product/841840',
    'https://www.cmtindustrial.com/catalogue/product/841841',
    'https://www.cmtindustrial.com/catalogue/product/841842',
    'https://www.cmtindustrial.com/catalogue/product/841843',
    'https://www.cmtindustrial.com/catalogue/product/841844',
    'https://www.cmtindustrial.com/catalogue/product/841845',
    'https://www.cmtindustrial.com/catalogue/product/841846',
    'https://www.cmtindustrial.com/catalogue/product/841847',
    'https://www.cmtindustrial.com/catalogue/product/841848',
    'https://www.cmtindustrial.com/catalogue/product/841849',
    'https://www.cmtindustrial.com/catalogue/product/841850',
    'https://www.cmtindustrial.com/catalogue/product/841851',
    'https://www.cmtindustrial.com/catalogue/product/841852',
    'https://www.cmtindustrial.com/catalogue/product/841853',
    'https://www.cmtindustrial.com/catalogue/product/841854',
    'https://www.cmtindustrial.com/catalogue/product/841855',
    'https://www.cmtindustrial.com/catalogue/product/841856',
    'https://www.cmtindustrial.com/catalogue/product/841857',
    'https://www.cmtindustrial.com/catalogue/product/841858',
    'https://www.cmtindustrial.com/catalogue/product/841859',
    'https://www.cmtindustrial.com/catalogue/product/841860',
    'https://www.cmtindustrial.com/catalogue/product/841861',
    'https://www.cmtindustrial.com/catalogue/product/841862',
    'https://www.cmtindustrial.com/catalogue/product/841863',
    'https://www.cmtindustrial.com/catalogue/product/841864',
    'https://www.cmtindustrial.com/catalogue/product/841865',
    'https://www.cmtindustrial.com/catalogue/product/841866',
    'https://www.cmtindustrial.com/catalogue/product/841867',
    'https://www.cmtindustrial.com/catalogue/product/841868',
    'https://www.cmtindustrial.com/catalogue/product/841869',
    'https://www.cmtindustrial.com/catalogue/product/841870',
    'https://www.cmtindustrial.com/catalogue/product/841871',
    'https://www.cmtindustrial.com/catalogue/product/841872',
    'https://www.cmtindustrial.com/catalogue/product/841873',
    'https://www.cmtindustrial.com/catalogue/product/841874',
    'https://www.cmtindustrial.com/catalogue/product/841875',
    'https://www.cmtindustrial.com/catalogue/product/841876',
    'https://www.cmtindustrial.com/catalogue/product/841877',
    'https://www.cmtindustrial.com/catalogue/product/841878',
    'https://www.cmtindustrial.com/catalogue/product/841879',
    'https://www.cmtindustrial.com/catalogue/product/841880',
    'https://www.cmtindustrial.com/catalogue/product/841881',
    'https://www.cmtindustrial.com/catalogue/product/841882',
    'https://www.cmtindustrial.com/catalogue/product/841883',
    'https://www.cmtindustrial.com/catalogue/product/841884',
    'https://www.cmtindustrial.com/catalogue/product/841885',
    'https://www.cmtindustrial.com/catalogue/product/841886',
    'https://www.cmtindustrial.com/catalogue/product/841887',
    'https://www.cmtindustrial.com/catalogue/product/841888',
    'https://www.cmtindustrial.com/catalogue/product/841889',
    'https://www.cmtindustrial.com/catalogue/product/841890',
    'https://www.cmtindustrial.com/catalogue/product/841891',
    'https://www.cmtindustrial.com/catalogue/product/841892',
    'https://www.cmtindustrial.com/catalogue/product/841893',
    'https://www.cmtindustrial.com/catalogue/product/841894',
    'https://www.cmtindustrial.com/catalogue/product/841895',
    'https://www.cmtindustrial.com/catalogue/product/841896',
    'https://www.cmtindustrial.com/catalogue/product/841897',
    'https://www.cmtindustrial.com/catalogue/product/841898',
    'https://www.cmtindustrial.com/catalogue/product/841899',
    'https://www.cmtindustrial.com/catalogue/product/841900',
    'https://www.cmtindustrial.com/catalogue/product/841901',
    'https://www.cmtindustrial.com/catalogue/product/841902',
    'https://www.cmtindustrial.com/catalogue/product/841903',
    'https://www.cmtindustrial.com/catalogue/product/841904',
    'https://www.cmtindustrial.com/catalogue/product/841905',
    'https://www.cmtindustrial.com/catalogue/product/841906',
    'https://www.cmtindustrial.com/catalogue/product/841907',
    'https://www.cmtindustrial.com/catalogue/product/841908',
    'https://www.cmtindustrial.com/catalogue/product/841909',
    'https://www.cmtindustrial.com/catalogue/product/841910',
    'https://www.cmtindustrial.com/catalogue/product/841911',
    'https://www.cmtindustrial.com/catalogue/product/841912',
    'https://www.cmtindustrial.com/catalogue/product/841913',
    'https://www.cmtindustrial.com/catalogue/product/841914',
    'https://www.cmtindustrial.com/catalogue/product/841915',
    'https://www.cmtindustrial.com/catalogue/product/841916',
    'https://www.cmtindustrial.com/catalogue/product/841917',
    'https://www.cmtindustrial.com/catalogue/product/841918',
    'https://www.cmtindustrial.com/catalogue/product/841919',
    'https://www.cmtindustrial.com/catalogue/product/841920',
    'https://www.cmtindustrial.com/catalogue/product/841921',
    'https://www.cmtindustrial.com/catalogue/product/841922',
    'https://www.cmtindustrial.com/catalogue/product/841923',
    'https://www.cmtindustrial.com/catalogue/product/841924',
    'https://www.cmtindustrial.com/catalogue/product/841925',
    'https://www.cmtindustrial.com/catalogue/product/841926',
    'https://www.cmtindustrial.com/catalogue/product/841927',
    'https://www.cmtindustrial.com/catalogue/product/841928',
    'https://www.cmtindustrial.com/catalogue/product/841929',
    'https://www.cmtindustrial.com/catalogue/product/841930',
    'https://www.cmtindustrial.com/catalogue/product/841931',
    'https://www.cmtindustrial.com/catalogue/product/841932',
    'https://www.cmtindustrial.com/catalogue/product/841933',
    'https://www.cmtindustrial.com/catalogue/product/841934',
    'https://www.cmtindustrial.com/catalogue/product/841935',
    'https://www.cmtindustrial.com/catalogue/product/841936',
    'https://www.cmtindustrial.com/catalogue/product/841937',
    'https://www.cmtindustrial.com/catalogue/product/841938',
    'https://www.cmtindustrial.com/catalogue/product/841939',
    'https://www.cmtindustrial.com/catalogue/product/841940',
    'https://www.cmtindustrial.com/catalogue/product/841941',
    'https://www.cmtindustrial.com/catalogue/product/841942',
    'https://www.cmtindustrial.com/catalogue/product/841943',
    'https://www.cmtindustrial.com/catalogue/product/841944',
    'https://www.cmtindustrial.com/catalogue/product/841945',
    'https://www.cmtindustrial.com/catalogue/product/841946',
    'https://www.cmtindustrial.com/catalogue/product/841947',
    'https://www.cmtindustrial.com/catalogue/product/841948',
    'https://www.cmtindustrial.com/catalogue/product/841949',
    'https://www.cmtindustrial.com/catalogue/product/841950',
    'https://www.cmtindustrial.com/catalogue/product/841951',
    'https://www.cmtindustrial.com/catalogue/product/841952',
    'https://www.cmtindustrial.com/catalogue/product/841953',
    'https://www.cmtindustrial.com/catalogue/product/841954',
    'https://www.cmtindustrial.com/catalogue/product/841955',
    'https://www.cmtindustrial.com/catalogue/product/841956',
    'https://www.cmtindustrial.com/catalogue/product/841957',
    'https://www.cmtindustrial.com/catalogue/product/841958',
    'https://www.cmtindustrial.com/catalogue/product/841959',
    'https://www.cmtindustrial.com/catalogue/product/841960',
    'https://www.cmtindustrial.com/catalogue/product/841961',
    'https://www.cmtindustrial.com/catalogue/product/841962',
    'https://www.cmtindustrial.com/catalogue/product/841963',
    'https://www.cmtindustrial.com/catalogue/product/841964',
    'https://www.cmtindustrial.com/catalogue/product/841965',
    'https://www.cmtindustrial.com/catalogue/product/841966',
    'https://www.cmtindustrial.com/catalogue/product/841967',
    'https://www.cmtindustrial.com/catalogue/product/841968',
    'https://www.cmtindustrial.com/catalogue/product/841969',
    'https://www.cmtindustrial.com/catalogue/product/841970',
    'https://www.cmtindustrial.com/catalogue/product/841971',
    'https://www.cmtindustrial.com/catalogue/product/841972',
    'https://www.cmtindustrial.com/catalogue/product/841973',
    'https://www.cmtindustrial.com/catalogue/product/841974',
    'https://www.cmtindustrial.com/catalogue/product/841975',
    'https://www.cmtindustrial.com/catalogue/product/841976',
    'https://www.cmtindustrial.com/catalogue/product/841977',
    'https://www.cmtindustrial.com/catalogue/product/841978',
    'https://www.cmtindustrial.com/catalogue/product/841979',
    'https://www.cmtindustrial.com/catalogue/product/841980',
    'https://www.cmtindustrial.com/catalogue/product/841981',
    'https://www.cmtindustrial.com/catalogue/product/841982',
    'https://www.cmtindustrial.com/catalogue/product/841983',
    'https://www.cmtindustrial.com/catalogue/product/841984',
    'https://www.cmtindustrial.com/catalogue/product/841985',
    'https://www.cmtindustrial.com/catalogue/product/841986',
    'https://www.cmtindustrial.com/catalogue/product/841987',
    'https://www.cmtindustrial.com/catalogue/product/841988',
    'https://www.cmtindustrial.com/catalogue/product/841989',
    'https://www.cmtindustrial.com/catalogue/product/841990',
    'https://www.cmtindustrial.com/catalogue/product/841991',
    'https://www.cmtindustrial.com/catalogue/product/841992',
    'https://www.cmtindustrial.com/catalogue/product/841993',
    'https://www.cmtindustrial.com/catalogue/product/841994',
    'https://www.cmtindustrial.com/catalogue/product/841995',
    'https://www.cmtindustrial.com/catalogue/product/841996',
    'https://www.cmtindustrial.com/catalogue/product/841997',
    'https://www.cmtindustrial.com/catalogue/product/841998',
    'https://www.cmtindustrial.com/catalogue/product/841999',
    'https://www.cmtindustrial.com/catalogue/product/842000',
    'https://www.cmtindustrial.com/catalogue/product/842001',
    'https://www.cmtindustrial.com/catalogue/product/842002',
    'https://www.cmtindustrial.com/catalogue/product/842003',
    'https://www.cmtindustrial.com/catalogue/product/842004',
    'https://www.cmtindustrial.com/catalogue/product/842005',
    'https://www.cmtindustrial.com/catalogue/product/842006',
    'https://www.cmtindustrial.com/catalogue/product/842007',
    'https://www.cmtindustrial.com/catalogue/product/842008',
    'https://www.cmtindustrial.com/catalogue/product/842009',
    'https://www.cmtindustrial.com/catalogue/product/842010',
    'https://www.cmtindustrial.com/catalogue/product/842011',
    'https://www.cmtindustrial.com/catalogue/product/842012',
    'https://www.cmtindustrial.com/catalogue/product/842013',
    'https://www.cmtindustrial.com/catalogue/product/842014',
    'https://www.cmtindustrial.com/catalogue/product/842015',
    'https://www.cmtindustrial.com/catalogue/product/842016',
    'https://www.cmtindustrial.com/catalogue/product/842017',
    'https://www.cmtindustrial.com/catalogue/product/842018',
    'https://www.cmtindustrial.com/catalogue/product/842019',
    'https://www.cmtindustrial.com/catalogue/product/842020',
    'https://www.cmtindustrial.com/catalogue/product/842021',
    'https://www.cmtindustrial.com/catalogue/product/842022',
    'https://www.cmtindustrial.com/catalogue/product/842023',
    'https://www.cmtindustrial.com/catalogue/product/842024',
    'https://www.cmtindustrial.com/catalogue/product/842025',
    'https://www.cmtindustrial.com/catalogue/product/842026',
    'https://www.cmtindustrial.com/catalogue/product/842027',
    'https://www.cmtindustrial.com/catalogue/product/842028',
    'https://www.cmtindustrial.com/catalogue/product/842029',
    'https://www.cmtindustrial.com/catalogue/product/842030',
    'https://www.cmtindustrial.com/catalogue/product/842031',
    'https://www.cmtindustrial.com/catalogue/product/842032',
    'https://www.cmtindustrial.com/catalogue/product/842033',
    'https://www.cmtindustrial.com/catalogue/product/842034',
    'https://www.cmtindustrial.com/catalogue/product/842035',
    'https://www.cmtindustrial.com/catalogue/product/842036',
    'https://www.cmtindustrial.com/catalogue/product/842037',
    'https://www.cmtindustrial.com/catalogue/product/842038',
    'https://www.cmtindustrial.com/catalogue/product/842039',
    'https://www.cmtindustrial.com/catalogue/product/842040',
    'https://www.cmtindustrial.com/catalogue/product/842041',
    'https://www.cmtindustrial.com/catalogue/product/842042',
    'https://www.cmtindustrial.com/catalogue/product/842043',
    'https://www.cmtindustrial.com/catalogue/product/842044',
    'https://www.cmtindustrial.com/catalogue/product/842045',
    'https://www.cmtindustrial.com/catalogue/product/842046',
    'https://www.cmtindustrial.com/catalogue/product/842047',
    'https://www.cmtindustrial.com/catalogue/product/842048',
    'https://www.cmtindustrial.com/catalogue/product/842049',
    'https://www.cmtindustrial.com/catalogue/product/842050',
    'https://www.cmtindustrial.com/catalogue/product/842051',
    'https://www.cmtindustrial.com/catalogue/product/842052',
    'https://www.cmtindustrial.com/catalogue/product/842053',
    'https://www.cmtindustrial.com/catalogue/product/842054',
    'https://www.cmtindustrial.com/catalogue/product/842055',
    'https://www.cmtindustrial.com/catalogue/product/842056',
    'https://www.cmtindustrial.com/catalogue/product/842057',
    'https://www.cmtindustrial.com/catalogue/product/842058',
    'https://www.cmtindustrial.com/catalogue/product/842059',
    'https://www.cmtindustrial.com/catalogue/product/842060',
    'https://www.cmtindustrial.com/catalogue/product/842061',
    'https://www.cmtindustrial.com/catalogue/product/842062',
    'https://www.cmtindustrial.com/catalogue/product/842063',
    'https://www.cmtindustrial.com/catalogue/product/842064',
    'https://www.cmtindustrial.com/catalogue/product/842065',
    'https://www.cmtindustrial.com/catalogue/product/842066',
    'https://www.cmtindustrial.com/catalogue/product/842067',
    'https://www.cmtindustrial.com/catalogue/product/842068',
    'https://www.cmtindustrial.com/catalogue/product/842069',
    'https://www.cmtindustrial.com/catalogue/product/842070',
    'https://www.cmtindustrial.com/catalogue/product/842071',
    'https://www.cmtindustrial.com/catalogue/product/842072',
    'https://www.cmtindustrial.com/catalogue/product/842073',
    'https://www.cmtindustrial.com/catalogue/product/842074',
    'https://www.cmtindustrial.com/catalogue/product/842075',
    'https://www.cmtindustrial.com/catalogue/product/842076',
    'https://www.cmtindustrial.com/catalogue/product/842077',
    'https://www.cmtindustrial.com/catalogue/product/842078',
    'https://www.cmtindustrial.com/catalogue/product/842079',
    'https://www.cmtindustrial.com/catalogue/product/842080',
    'https://www.cmtindustrial.com/catalogue/product/842081',
    'https://www.cmtindustrial.com/catalogue/product/842082',
    'https://www.cmtindustrial.com/catalogue/product/842083',
    'https://www.cmtindustrial.com/catalogue/product/842084',
    'https://www.cmtindustrial.com/catalogue/product/842085',
    'https://www.cmtindustrial.com/catalogue/product/842086',
    'https://www.cmtindustrial.com/catalogue/product/842087',
    'https://www.cmtindustrial.com/catalogue/product/842088',
    'https://www.cmtindustrial.com/catalogue/product/842089',
    'https://www.cmtindustrial.com/catalogue/product/842090',
    'https://www.cmtindustrial.com/catalogue/product/842091',
    'https://www.cmtindustrial.com/catalogue/product/842092',
    'https://www.cmtindustrial.com/catalogue/product/842093',
    'https://www.cmtindustrial.com/catalogue/product/842094',
    'https://www.cmtindustrial.com/catalogue/product/842095',
    'https://www.cmtindustrial.com/catalogue/product/842096',
    'https://www.cmtindustrial.com/catalogue/product/842097',
    'https://www.cmtindustrial.com/catalogue/product/842098',
    'https://www.cmtindustrial.com/catalogue/product/842099',
    'https://www.cmtindustrial.com/catalogue/product/842100',
    'https://www.cmtindustrial.com/catalogue/product/842101',
    'https://www.cmtindustrial.com/catalogue/product/842102',
    'https://www.cmtindustrial.com/catalogue/product/842103',
    'https://www.cmtindustrial.com/catalogue/product/842104',
    'https://www.cmtindustrial.com/catalogue/product/842105',
    'https://www.cmtindustrial.com/catalogue/product/842106',
    'https://www.cmtindustrial.com/catalogue/product/842107',
    'https://www.cmtindustrial.com/catalogue/product/842108',
    'https://www.cmtindustrial.com/catalogue/product/842109',
    'https://www.cmtindustrial.com/catalogue/product/842110',
    'https://www.cmtindustrial.com/catalogue/product/842111',
    'https://www.cmtindustrial.com/catalogue/product/842112',
    'https://www.cmtindustrial.com/catalogue/product/842113',
    'https://www.cmtindustrial.com/catalogue/product/842114',
    'https://www.cmtindustrial.com/catalogue/product/842115',
    'https://www.cmtindustrial.com/catalogue/product/842116',
    'https://www.cmtindustrial.com/catalogue/product/842117',
    'https://www.cmtindustrial.com/catalogue/product/842118',
    'https://www.cmtindustrial.com/catalogue/product/842119',
    'https://www.cmtindustrial.com/catalogue/product/842120',
    'https://www.cmtindustrial.com/catalogue/product/842121',
    'https://www.cmtindustrial.com/catalogue/product/842122',
    'https://www.cmtindustrial.com/catalogue/product/842123',
    'https://www.cmtindustrial.com/catalogue/product/842124',
    'https://www.cmtindustrial.com/catalogue/product/842125',
    'https://www.cmtindustrial.com/catalogue/product/842126',
    'https://www.cmtindustrial.com/catalogue/product/842127',
    'https://www.cmtindustrial.com/catalogue/product/842128',
    'https://www.cmtindustrial.com/catalogue/product/842129',
    'https://www.cmtindustrial.com/catalogue/product/842130',
    'https://www.cmtindustrial.com/catalogue/product/842131',
    'https://www.cmtindustrial.com/catalogue/product/842132',
    'https://www.cmtindustrial.com/catalogue/product/842133',
    'https://www.cmtindustrial.com/catalogue/product/842134',
    'https://www.cmtindustrial.com/catalogue/product/842135',
    'https://www.cmtindustrial.com/catalogue/product/842136',
    'https://www.cmtindustrial.com/catalogue/product/842137',
    'https://www.cmtindustrial.com/catalogue/product/842138',
    'https://www.cmtindustrial.com/catalogue/product/842139',
    'https://www.cmtindustrial.com/catalogue/product/842140',
    'https://www.cmtindustrial.com/catalogue/product/842141',
    'https://www.cmtindustrial.com/catalogue/product/842142',
    'https://www.cmtindustrial.com/catalogue/product/842143',
    'https://www.cmtindustrial.com/catalogue/product/842144',
    'https://www.cmtindustrial.com/catalogue/product/842145',
    'https://www.cmtindustrial.com/catalogue/product/842146',
    'https://www.cmtindustrial.com/catalogue/product/842147',
    'https://www.cmtindustrial.com/catalogue/product/842148',
    'https://www.cmtindustrial.com/catalogue/product/842149',
    'https://www.cmtindustrial.com/catalogue/product/842150',
    'https://www.cmtindustrial.com/catalogue/product/842151',
    'https://www.cmtindustrial.com/catalogue/product/842152',
    'https://www.cmtindustrial.com/catalogue/product/842153',
    'https://www.cmtindustrial.com/catalogue/product/842154',
    'https://www.cmtindustrial.com/catalogue/product/842155',
    'https://www.cmtindustrial.com/catalogue/product/842156',
    'https://www.cmtindustrial.com/catalogue/product/842157',
    'https://www.cmtindustrial.com/catalogue/product/842158',
    'https://www.cmtindustrial.com/catalogue/product/842159',
    'https://www.cmtindustrial.com/catalogue/product/842160',
    'https://www.cmtindustrial.com/catalogue/product/842161',
    'https://www.cmtindustrial.com/catalogue/product/842162',
    'https://www.cmtindustrial.com/catalogue/product/842163',
    'https://www.cmtindustrial.com/catalogue/product/842164',
    'https://www.cmtindustrial.com/catalogue/product/842165',
    'https://www.cmtindustrial.com/catalogue/product/842166',
    'https://www.cmtindustrial.com/catalogue/product/842167',
    'https://www.cmtindustrial.com/catalogue/product/842168',
    'https://www.cmtindustrial.com/catalogue/product/842169',
    'https://www.cmtindustrial.com/catalogue/product/842170',
    'https://www.cmtindustrial.com/catalogue/product/842171',
    'https://www.cmtindustrial.com/catalogue/product/842172',
    'https://www.cmtindustrial.com/catalogue/product/842173',
    'https://www.cmtindustrial.com/catalogue/product/842174',
    'https://www.cmtindustrial.com/catalogue/product/842175',
    'https://www.cmtindustrial.com/catalogue/product/842176',
    'https://www.cmtindustrial.com/catalogue/product/842177',
    'https://www.cmtindustrial.com/catalogue/product/842178',
    'https://www.cmtindustrial.com/catalogue/product/842179',
    'https://www.cmtindustrial.com/catalogue/product/842180',
    'https://www.cmtindustrial.com/catalogue/product/842181',
    'https://www.cmtindustrial.com/catalogue/product/842182',
    'https://www.cmtindustrial.com/catalogue/product/842183',
    'https://www.cmtindustrial.com/catalogue/product/842184',
    'https://www.cmtindustrial.com/catalogue/product/842185',
    'https://www.cmtindustrial.com/catalogue/product/842186',
    'https://www.cmtindustrial.com/catalogue/product/842187',
    'https://www.cmtindustrial.com/catalogue/product/842188',
    'https://www.cmtindustrial.com/catalogue/product/842189',
    'https://www.cmtindustrial.com/catalogue/product/842190',
    'https://www.cmtindustrial.com/catalogue/product/842191',
    'https://www.cmtindustrial.com/catalogue/product/842192',
    'https://www.cmtindustrial.com/catalogue/product/842193',
    'https://www.cmtindustrial.com/catalogue/product/842194',
    'https://www.cmtindustrial.com/catalogue/product/842195',
    'https://www.cmtindustrial.com/catalogue/product/842196',
    'https://www.cmtindustrial.com/catalogue/product/842197',
    'https://www.cmtindustrial.com/catalogue/product/842198',
    'https://www.cmtindustrial.com/catalogue/product/842199',
    'https://www.cmtindustrial.com/catalogue/product/842200',
    'https://www.cmtindustrial.com/catalogue/product/842201',
    'https://www.cmtindustrial.com/catalogue/product/842202',
    'https://www.cmtindustrial.com/catalogue/product/842203',
    'https://www.cmtindustrial.com/catalogue/product/842204',
    'https://www.cmtindustrial.com/catalogue/product/842205',
    'https://www.cmtindustrial.com/catalogue/product/842206',
    'https://www.cmtindustrial.com/catalogue/product/842207',
    'https://www.cmtindustrial.com/catalogue/product/842208',
    'https://www.cmtindustrial.com/catalogue/product/842209',
    'https://www.cmtindustrial.com/catalogue/product/842210',
    'https://www.cmtindustrial.com/catalogue/product/842211',
    'https://www.cmtindustrial.com/catalogue/product/842212',
    'https://www.cmtindustrial.com/catalogue/product/842213',
    'https://www.cmtindustrial.com/catalogue/product/842214',
    'https://www.cmtindustrial.com/catalogue/product/842215',
    'https://www.cmtindustrial.com/catalogue/product/842216',
    'https://www.cmtindustrial.com/catalogue/product/842217',
    'https://www.cmtindustrial.com/catalogue/product/842218',
    'https://www.cmtindustrial.com/catalogue/product/842219',
    'https://www.cmtindustrial.com/catalogue/product/842220',
    'https://www.cmtindustrial.com/catalogue/product/842221',
    'https://www.cmtindustrial.com/catalogue/product/842222',
    'https://www.cmtindustrial.com/catalogue/product/842223',
    'https://www.cmtindustrial.com/catalogue/product/842224',
    'https://www.cmtindustrial.com/catalogue/product/842225',
    'https://www.cmtindustrial.com/catalogue/product/842226',
    'https://www.cmtindustrial.com/catalogue/product/842227',
    'https://www.cmtindustrial.com/catalogue/product/842228',
    'https://www.cmtindustrial.com/catalogue/product/842229',
    'https://www.cmtindustrial.com/catalogue/product/842230',
    'https://www.cmtindustrial.com/catalogue/product/842231',
    'https://www.cmtindustrial.com/catalogue/product/842232',
    'https://www.cmtindustrial.com/catalogue/product/842233',
    'https://www.cmtindustrial.com/catalogue/product/842234',
    'https://www.cmtindustrial.com/catalogue/product/842235',
    'https://www.cmtindustrial.com/catalogue/product/842236',
    'https://www.cmtindustrial.com/catalogue/product/842237',
    'https://www.cmtindustrial.com/catalogue/product/842238',
    'https://www.cmtindustrial.com/catalogue/product/842239',
    'https://www.cmtindustrial.com/catalogue/product/842240',
    'https://www.cmtindustrial.com/catalogue/product/842241',
    'https://www.cmtindustrial.com/catalogue/product/842242',
    'https://www.cmtindustrial.com/catalogue/product/842243',
    'https://www.cmtindustrial.com/catalogue/product/842244',
    'https://www.cmtindustrial.com/catalogue/product/842245',
    'https://www.cmtindustrial.com/catalogue/product/842246',
    'https://www.cmtindustrial.com/catalogue/product/842247',
    'https://www.cmtindustrial.com/catalogue/product/842248',
    'https://www.cmtindustrial.com/catalogue/product/842249',
    'https://www.cmtindustrial.com/catalogue/product/842250',
    'https://www.cmtindustrial.com/catalogue/product/842251',
    'https://www.cmtindustrial.com/catalogue/product/842252',
    'https://www.cmtindustrial.com/catalogue/product/842253',
    'https://www.cmtindustrial.com/catalogue/product/842254',
    'https://www.cmtindustrial.com/catalogue/product/842255',
    'https://www.cmtindustrial.com/catalogue/product/842256',
    'https://www.cmtindustrial.com/catalogue/product/842257',
    'https://www.cmtindustrial.com/catalogue/product/842258',
    'https://www.cmtindustrial.com/catalogue/product/842259',
    'https://www.cmtindustrial.com/catalogue/product/842260',
    'https://www.cmtindustrial.com/catalogue/product/842261',
    'https://www.cmtindustrial.com/catalogue/product/842262',
    'https://www.cmtindustrial.com/catalogue/product/842263',
    'https://www.cmtindustrial.com/catalogue/product/842264',
    'https://www.cmtindustrial.com/catalogue/product/842265',
    'https://www.cmtindustrial.com/catalogue/product/842266',
    'https://www.cmtindustrial.com/catalogue/product/842267',
    'https://www.cmtindustrial.com/catalogue/product/842268',
    'https://www.cmtindustrial.com/catalogue/product/842269',
    'https://www.cmtindustrial.com/catalogue/product/842270',
    'https://www.cmtindustrial.com/catalogue/product/842271',
    'https://www.cmtindustrial.com/catalogue/product/842272',
    'https://www.cmtindustrial.com/catalogue/product/842273',
    'https://www.cmtindustrial.com/catalogue/product/842274',
    'https://www.cmtindustrial.com/catalogue/product/842275',
    'https://www.cmtindustrial.com/catalogue/product/842276',
    'https://www.cmtindustrial.com/catalogue/product/842277',
    'https://www.cmtindustrial.com/catalogue/product/842278',
    'https://www.cmtindustrial.com/catalogue/product/842279',
    'https://www.cmtindustrial.com/catalogue/product/842280',
    'https://www.cmtindustrial.com/catalogue/product/842281',
    'https://www.cmtindustrial.com/catalogue/product/842282',
    'https://www.cmtindustrial.com/catalogue/product/842283',
    'https://www.cmtindustrial.com/catalogue/product/842284',
    'https://www.cmtindustrial.com/catalogue/product/842285',
    'https://www.cmtindustrial.com/catalogue/product/842286',
    'https://www.cmtindustrial.com/catalogue/product/842287',
    'https://www.cmtindustrial.com/catalogue/product/842288',
    'https://www.cmtindustrial.com/catalogue/product/842289',
    'https://www.cmtindustrial.com/catalogue/product/842290',
    'https://www.cmtindustrial.com/catalogue/product/842291',
    'https://www.cmtindustrial.com/catalogue/product/842292',
    'https://www.cmtindustrial.com/catalogue/product/842293',
    'https://www.cmtindustrial.com/catalogue/product/842294',
    'https://www.cmtindustrial.com/catalogue/product/842295',
    'https://www.cmtindustrial.com/catalogue/product/842296',
    'https://www.cmtindustrial.com/catalogue/product/842297',
    'https://www.cmtindustrial.com/catalogue/product/842298',
    'https://www.cmtindustrial.com/catalogue/product/842299',
    'https://www.cmtindustrial.com/catalogue/product/842300',
    'https://www.cmtindustrial.com/catalogue/product/842301',
    'https://www.cmtindustrial.com/catalogue/product/842302',
    'https://www.cmtindustrial.com/catalogue/product/842303',
    'https://www.cmtindustrial.com/catalogue/product/842304',
    'https://www.cmtindustrial.com/catalogue/product/842305',
    'https://www.cmtindustrial.com/catalogue/product/842306',
    'https://www.cmtindustrial.com/catalogue/product/842307',
    'https://www.cmtindustrial.com/catalogue/product/842308',
    'https://www.cmtindustrial.com/catalogue/product/842309',
    'https://www.cmtindustrial.com/catalogue/product/842310',
    'https://www.cmtindustrial.com/catalogue/product/842311',
    'https://www.cmtindustrial.com/catalogue/product/842312',
    'https://www.cmtindustrial.com/catalogue/product/842313',
    'https://www.cmtindustrial.com/catalogue/product/842314',
    'https://www.cmtindustrial.com/catalogue/product/842315',
    'https://www.cmtindustrial.com/catalogue/product/842316',
    'https://www.cmtindustrial.com/catalogue/product/842317',
    'https://www.cmtindustrial.com/catalogue/product/842318',
    'https://www.cmtindustrial.com/catalogue/product/842319',
    'https://www.cmtindustrial.com/catalogue/product/842320',
    'https://www.cmtindustrial.com/catalogue/product/842321',
    'https://www.cmtindustrial.com/catalogue/product/842322',
    'https://www.cmtindustrial.com/catalogue/product/842323',
    'https://www.cmtindustrial.com/catalogue/product/842324',
    'https://www.cmtindustrial.com/catalogue/product/842325',
    'https://www.cmtindustrial.com/catalogue/product/842326',
    'https://www.cmtindustrial.com/catalogue/product/842327',
    'https://www.cmtindustrial.com/catalogue/product/842328',
    'https://www.cmtindustrial.com/catalogue/product/842329',
    'https://www.cmtindustrial.com/catalogue/product/842330',
    'https://www.cmtindustrial.com/catalogue/product/842331',
    'https://www.cmtindustrial.com/catalogue/product/842332',
    'https://www.cmtindustrial.com/catalogue/product/842333',
    'https://www.cmtindustrial.com/catalogue/product/842334',
    'https://www.cmtindustrial.com/catalogue/product/842335',
    'https://www.cmtindustrial.com/catalogue/product/842336',
    'https://www.cmtindustrial.com/catalogue/product/842337',
    'https://www.cmtindustrial.com/catalogue/product/842338',
    'https://www.cmtindustrial.com/catalogue/product/842339',
    'https://www.cmtindustrial.com/catalogue/product/842340',
    'https://www.cmtindustrial.com/catalogue/product/842341',
    'https://www.cmtindustrial.com/catalogue/product/842342',
    'https://www.cmtindustrial.com/catalogue/product/842343',
    'https://www.cmtindustrial.com/catalogue/product/842344',
    'https://www.cmtindustrial.com/catalogue/product/842345',
    'https://www.cmtindustrial.com/catalogue/product/842346',
    'https://www.cmtindustrial.com/catalogue/product/842347',
    'https://www.cmtindustrial.com/catalogue/product/842348',
    'https://www.cmtindustrial.com/catalogue/product/842349',
    'https://www.cmtindustrial.com/catalogue/product/842350',
    'https://www.cmtindustrial.com/catalogue/product/842351',
    'https://www.cmtindustrial.com/catalogue/product/842352',
    'https://www.cmtindustrial.com/catalogue/product/842353',
    'https://www.cmtindustrial.com/catalogue/product/842354',
    'https://www.cmtindustrial.com/catalogue/product/842355',
    'https://www.cmtindustrial.com/catalogue/product/842356',
    'https://www.cmtindustrial.com/catalogue/product/842357',
    'https://www.cmtindustrial.com/catalogue/product/842358',
    'https://www.cmtindustrial.com/catalogue/product/842359',
    'https://www.cmtindustrial.com/catalogue/product/842360',
    'https://www.cmtindustrial.com/catalogue/product/842361',
    'https://www.cmtindustrial.com/catalogue/product/842362',
    'https://www.cmtindustrial.com/catalogue/product/842363',
    'https://www.cmtindustrial.com/catalogue/product/842364',
    'https://www.cmtindustrial.com/catalogue/product/842365',
    'https://www.cmtindustrial.com/catalogue/product/842366',
    'https://www.cmtindustrial.com/catalogue/product/842367',
    'https://www.cmtindustrial.com/catalogue/product/842368',
    'https://www.cmtindustrial.com/catalogue/product/842369',
    'https://www.cmtindustrial.com/catalogue/product/842370',
    'https://www.cmtindustrial.com/catalogue/product/842371',
    'https://www.cmtindustrial.com/catalogue/product/842372',
    'https://www.cmtindustrial.com/catalogue/product/842373',
    'https://www.cmtindustrial.com/catalogue/product/842374',
    'https://www.cmtindustrial.com/catalogue/product/842375',
    'https://www.cmtindustrial.com/catalogue/product/842376',
    'https://www.cmtindustrial.com/catalogue/product/842377',
    'https://www.cmtindustrial.com/catalogue/product/842378',
    'https://www.cmtindustrial.com/catalogue/product/842379',
    'https://www.cmtindustrial.com/catalogue/product/842380',
    'https://www.cmtindustrial.com/catalogue/product/842381',
    'https://www.cmtindustrial.com/catalogue/product/842382',
    'https://www.cmtindustrial.com/catalogue/product/842383',
    'https://www.cmtindustrial.com/catalogue/product/842384',
    'https://www.cmtindustrial.com/catalogue/product/842385',
    'https://www.cmtindustrial.com/catalogue/product/842386',
    'https://www.cmtindustrial.com/catalogue/product/842387',
    'https://www.cmtindustrial.com/catalogue/product/842388',
    'https://www.cmtindustrial.com/catalogue/product/842389',
    'https://www.cmtindustrial.com/catalogue/product/842390',
    'https://www.cmtindustrial.com/catalogue/product/842391',
    'https://www.cmtindustrial.com/catalogue/product/842392',
    'https://www.cmtindustrial.com/catalogue/product/842393',
    'https://www.cmtindustrial.com/catalogue/product/842394',
    'https://www.cmtindustrial.com/catalogue/product/842395',
    'https://www.cmtindustrial.com/catalogue/product/842396',
    'https://www.cmtindustrial.com/catalogue/product/842397',
    'https://www.cmtindustrial.com/catalogue/product/842398',
    'https://www.cmtindustrial.com/catalogue/product/842399',
    'https://www.cmtindustrial.com/catalogue/product/842400',
    'https://www.cmtindustrial.com/catalogue/product/842401',
    'https://www.cmtindustrial.com/catalogue/product/842402',
    'https://www.cmtindustrial.com/catalogue/product/842403',
    'https://www.cmtindustrial.com/catalogue/product/842404',
    'https://www.cmtindustrial.com/catalogue/product/842405',
    'https://www.cmtindustrial.com/catalogue/product/842406',
    'https://www.cmtindustrial.com/catalogue/product/842407',
    'https://www.cmtindustrial.com/catalogue/product/842408',
    'https://www.cmtindustrial.com/catalogue/product/842409',
    'https://www.cmtindustrial.com/catalogue/product/842410',
    'https://www.cmtindustrial.com/catalogue/product/842411',
    'https://www.cmtindustrial.com/catalogue/product/842412',
    'https://www.cmtindustrial.com/catalogue/product/842413',
    'https://www.cmtindustrial.com/catalogue/product/842414',
    'https://www.cmtindustrial.com/catalogue/product/842415',
    'https://www.cmtindustrial.com/catalogue/product/842416',
    'https://www.cmtindustrial.com/catalogue/product/842417',
    'https://www.cmtindustrial.com/catalogue/product/842418',
    'https://www.cmtindustrial.com/catalogue/product/842419',
    'https://www.cmtindustrial.com/catalogue/product/842420',
    'https://www.cmtindustrial.com/catalogue/product/842421',
    'https://www.cmtindustrial.com/catalogue/product/842422',
    'https://www.cmtindustrial.com/catalogue/product/842423',
    'https://www.cmtindustrial.com/catalogue/product/842424',
    'https://www.cmtindustrial.com/catalogue/product/842425',
    'https://www.cmtindustrial.com/catalogue/product/842426',
    'https://www.cmtindustrial.com/catalogue/product/842427',
    'https://www.cmtindustrial.com/catalogue/product/842428',
    'https://www.cmtindustrial.com/catalogue/product/842429',
    'https://www.cmtindustrial.com/catalogue/product/842430',
    'https://www.cmtindustrial.com/catalogue/product/842431',
    'https://www.cmtindustrial.com/catalogue/product/842432',
    'https://www.cmtindustrial.com/catalogue/product/842433',
    'https://www.cmtindustrial.com/catalogue/product/842434',
    'https://www.cmtindustrial.com/catalogue/product/842435',
    'https://www.cmtindustrial.com/catalogue/product/842436',
    'https://www.cmtindustrial.com/catalogue/product/842437',
    'https://www.cmtindustrial.com/catalogue/product/842438',
    'https://www.cmtindustrial.com/catalogue/product/842439',
    'https://www.cmtindustrial.com/catalogue/product/842440',
    'https://www.cmtindustrial.com/catalogue/product/842441',
    'https://www.cmtindustrial.com/catalogue/product/842442',
    'https://www.cmtindustrial.com/catalogue/product/842443',
    'https://www.cmtindustrial.com/catalogue/product/842444',
    'https://www.cmtindustrial.com/catalogue/product/842445',
    'https://www.cmtindustrial.com/catalogue/product/842446',
    'https://www.cmtindustrial.com/catalogue/product/842447',
    'https://www.cmtindustrial.com/catalogue/product/842448',
    'https://www.cmtindustrial.com/catalogue/product/842449',
    'https://www.cmtindustrial.com/catalogue/product/842450',
    'https://www.cmtindustrial.com/catalogue/product/842451',
    'https://www.cmtindustrial.com/catalogue/product/842452',
    'https://www.cmtindustrial.com/catalogue/product/842453',
    'https://www.cmtindustrial.com/catalogue/product/842454',
    'https://www.cmtindustrial.com/catalogue/product/842455',
    'https://www.cmtindustrial.com/catalogue/product/842456',
    'https://www.cmtindustrial.com/catalogue/product/842457',
    'https://www.cmtindustrial.com/catalogue/product/842458',
    'https://www.cmtindustrial.com/catalogue/product/842459',
    'https://www.cmtindustrial.com/catalogue/product/842460',
    'https://www.cmtindustrial.com/catalogue/product/842461',
    'https://www.cmtindustrial.com/catalogue/product/842462',
    'https://www.cmtindustrial.com/catalogue/product/842463',
    'https://www.cmtindustrial.com/catalogue/product/842464',
    'https://www.cmtindustrial.com/catalogue/product/842465',
    'https://www.cmtindustrial.com/catalogue/product/842466',
    'https://www.cmtindustrial.com/catalogue/product/842467',
    'https://www.cmtindustrial.com/catalogue/product/842468',
    'https://www.cmtindustrial.com/catalogue/product/842469',
    'https://www.cmtindustrial.com/catalogue/product/842470',
    'https://www.cmtindustrial.com/catalogue/product/842471',
    'https://www.cmtindustrial.com/catalogue/product/842472',
    'https://www.cmtindustrial.com/catalogue/product/842473',
    'https://www.cmtindustrial.com/catalogue/product/842474',
    'https://www.cmtindustrial.com/catalogue/product/842475',
    'https://www.cmtindustrial.com/catalogue/product/842476',
    'https://www.cmtindustrial.com/catalogue/product/842477',
    'https://www.cmtindustrial.com/catalogue/product/842478',
    'https://www.cmtindustrial.com/catalogue/product/842479',
    'https://www.cmtindustrial.com/catalogue/product/842480',
    'https://www.cmtindustrial.com/catalogue/product/842481',
    'https://www.cmtindustrial.com/catalogue/product/842482',
    'https://www.cmtindustrial.com/catalogue/product/842483',
    'https://www.cmtindustrial.com/catalogue/product/842484',
    'https://www.cmtindustrial.com/catalogue/product/842485',
    'https://www.cmtindustrial.com/catalogue/product/842486',
    'https://www.cmtindustrial.com/catalogue/product/842487',

]


def extract_data(url):
    l = 0
    try:
        l = l + 1
        r = requests.get(url)
        soup = BeautifulSoup(r.content, 'html.parser')
        # driver.get(url)
        time.sleep(3)
        # print(soup)
        item = ''
        brand = ''
        upc = ''
        unspsc = ''
        mftn = ''
        print("Product-urls", l, url)
        try:
            print("********** Meta-Description : **********")
            meta_description = soup.find("meta", attrs={"name": "description"}).get("content").strip()
            print("Meta_description......", meta_description)
        except:
            meta_description = "Not Found"
            print("Not Found")

        try:
            print('** ** ** ** ** Meta-Title : ** ** ** ** **')
            meta_title = soup.find('title').string.strip()
            print("Meta_title .....", meta_title)
        except:
            meta_title = "Not Found"
            print("Not Found")

        try:
            print('** ** ** ** ** BreadCrumb: ** ** ** ** **')
            Bread = soup.find("ul", {"class": "uk-breadcrumb uk-visible@s"}).text.strip().replace('\n', ">>")
            print('Bread...', Bread)
        except:
            Bread = "Not Found"
            print("Not Found")

        try:
            print('** ** ** ** ** Title : ** ** ** ** **')
            title = soup.find('h1').text.strip()
            print('title...', title)
        except:
            title = "Not Found"
            print("Not Found")

        try:
            print('** ** ** ** ** Images : ** ** ** ** **')
            image = soup.find("div", {"class": "product_image_wrap"}).find('img')
            images = "https://www.cmtindustrial.com" + image.get('src')
            print('images...', images)
        except:
            images = "Not Found"
            print("Not Found")

        try:
            print('** ** ** ** ** Country : ** ** ** ** **')
            country = soup.find('div', class_="field_data rightside").text.strip()
            print('country...', country)
        except:
            country = "Not Found"
            print("Not Found")

        try:
            print('** ** ** ** ** Weight : ** ** ** ** **')
            weight = soup.find('div', class_="row PackageWeight").text.strip().replace('\n', '').split('.')[1]
            print('weight...', weight)
        except:
            weight = "Not Found"
            print("Not Found")

        try:
            print('** ** ** ** ** Details-of-unic-number : ** ** ** ** **')
            for data in soup.find_all('div', {"class": "product_constant_fields"}):
                unic = data.text.strip().replace('\n', '--').split('------')
                # print(unic)
                item = unic[0]
                print('item...', item)
                brand = unic[1]
                print('brand...', brand)
                upc = unic[2]
                print('upc...', upc)
                unspsc = unic[3]
                print('upscale...', unspsc)
                mftn = unic[4]
                print('mftn...', mftn)
                save_details: TextIO = open("cle-forces.txt", "a+", encoding="utf-8")
                save_details.write(
                    "\n" + url + "\t" + meta_description + "\t" + meta_title + "\t" + Bread + "\t" + title + "\t" + images + "\t" + country + "\t" + "rp_" + weight + "\t" + item + "\t" + brand + "\t" + upc + "\t" + unspsc + "\t" + mftn.strip())
            print("\n ***** Record stored into files. *****")

        except:
            save_details: TextIO = open("cle-forces.txt", "a+", encoding="utf-8")
            save_details.write(
                "\n" + url + "\t" + meta_description + "\t" + meta_title + "\t" + Bread + "\t" + title + "\t" + images + "\t" + country + "\t" + "rp_" + weight + "\t" + item + "\t" + brand + "\t" + upc + "\t" + unspsc + "\t" + mftn.strip())
            print("\n ***** Record stored into Except files. *****")
            print("Not Found")

        # ===================================  table function here ===========================

        print('** ** ** ** ** Tables : ** ** ** ** **')
        i = 0
        attr_name = []
        attr_value = []
        table = soup.find('div', {'id': 'product_specs'})
        td = table.find_all('td')
        for t in td:
            i += 1
            if i % 2 != 0:
                attr_name.append(t.text.strip().replace('\n', ''))
            else:
                attr_value.append(t.text.strip().replace('\n', ''))
        attr_name.remove('')
        attr_value.remove('')
        for a, b, in zip(attr_name, attr_value):
            print(a, "........", b)
            save_details: TextIO = open("cle-forces.txt", "a+", encoding="utf-8")
            save_details.write(
                "\n" + url + "\t" + meta_description + "\t" + meta_title + "\t" + Bread + "\t" + title + "\t" + images + "\t" + country + "\t" + "rp_" + weight + "\t" + item + "\t" + brand + "\t" + upc + "\t" + unspsc + "\t" + mftn + "\t" + a + "\t" + b)
        print("\n ***** Record stored into table  files. *****")

    except Exception as e:
        save_details: TextIO = open("remaining.txt", "a+", encoding="utf-8")
        save_details.write("\n" + url)
        print("\n ***** Record stored into table  files. *****")
        print("Error", e)


#   here is the function for calling url and extract_data
for url in mylst:
    extract_data(url)
