import pandas as pd
import time
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By

chrome_options = Options()
# chrome_options.add_argument('--headless')
chrome_options.add_argument('--disable-gpu')
chrome_options.add_argument('--window-size=1920,1200')
chrome_options.add_argument('--ignore-certificate-errors')
chrome_options.add_argument('--disable-extensions')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome()
driver.maximize_window()

url_links = [


    'https://www.ridgid.com/us/en/test-and-measurement',
    'https://www.ridgid.com/us/en/pressing-technology',
    'https://www.ridgid.com/us/en/pressing-technology',
    'https://www.ridgid.com/us/en/press-tools',
    'https://www.ridgid.com/us/en/press-jaws',
    'https://www.ridgid.com/us/en/press-rings',
    'https://www.ridgid.com/us/en/megapress',
    'https://www.ridgid.com/us/en/press-snap-soil-pipe-cutters',
    'https://www.ridgid.com/us/en/strutslayr-strut-shear-head',
    'https://www.ridgid.com/us/en/advanced-lithium-batteries-and-chargers',
    'https://www.ridgid.com/us/en/drain-cleaning',
    'https://www.ridgid.com/us/en/drain-cleaning',
    'https://www.ridgid.com/us/en/drain-cleaning-tools',
    'https://www.ridgid.com/us/en/sink-drain-cleaning',
    'https://www.ridgid.com/us/en/drain-machine',
    'https://www.ridgid.com/us/en/drain-cleaners',
    'https://www.ridgid.com/us/en/sewer-rodding',
    'https://www.ridgid.com/us/en/sewer-jetter',
    'https://www.ridgid.com/us/en/flexshaft-machines',
    'https://www.ridgid.com/us/en/drain-cable',
    'https://www.ridgid.com/us/en/pipe-patching',
    'https://www.ridgid.com/us/en/threading-pipe-fabrication',
    'https://www.ridgid.com/us/en/threading-pipe-fabrication',
    'https://www.ridgid.com/us/en/pipe-bevelling',
    'https://www.ridgid.com/us/en/pipe-threading',
    'https://www.ridgid.com/us/en/roll-grooving',
    'https://www.ridgid.com/us/en/bending-hole-cutting',
    'https://www.ridgid.com/us/en/pipe-vises-and-supports',
    'https://www.ridgid.com/us/en/pipe-cutting-and-fabrication',
    'https://www.ridgid.com/us/en/wrenches-and-tubing-tools',
    'https://www.ridgid.com/us/en/wrenches-and-tubing-tools',
    'https://www.ridgid.com/us/en/wrenches',
    'https://www.ridgid.com/us/en/bending-and-forming',
    'https://www.ridgid.com/us/en/tube-repair-and-joining',
    'https://www.ridgid.com/us/en/tube-cutting-and-preparation',
    'https://www.ridgid.com/us/en/software',
    'https://www.ridgid.com/us/en/electrical-tools',
    'https://www.ridgid.com/us/en/electrical-tools',
    'https://www.ridgid.com/us/en/manual-hydraulic-crimping',
    'https://www.ridgid.com/us/en/knockout-sets',
    'https://www.ridgid.com/us/en/cable-cutters',
    'https://www.ridgid.com/us/en/cable-trimmers',
    'https://www.ridgid.com/us/en/conduit-benders',
    'https://www.ridgid.com/us/en/sizing-tools',
    'https://www.ridgid.com/us/en/hand-tools',
    'https://www.ridgid.com/us/en/hand-tools',
    'https://www.ridgid.com/us/en/water-pumps',
    'https://www.ridgid.com/us/en/tile-tools',
    'https://www.ridgid.com/us/en/concrete-tools',
    'https://www.ridgid.com/us/en/straplock',
    'https://www.ridgid.com/us/en/vises',
    'https://www.ridgid.com/us/en/anvils',
    'https://www.ridgid.com/us/en/levels',
    'https://www.ridgid.com/us/en/bolt-cutter',
    'https://www.ridgid.com/us/en/folding-rules',
    'https://www.ridgid.com/us/en/on-site-storage',
    'https://www.ridgid.com/us/en/ridgid-pliers',
    'https://www.ridgid.com/us/en/saws',
    'https://www.ridgid.com/us/en/screw-extractor',
    'https://www.ridgid.com/us/en/replacement-drill-guide',
    'https://www.ridgid.com/us/en/twist-drill',
    'https://www.ridgid.com/us/en/ridgid-shovels',
    'https://www.ridgid.com/us/en/ridgid-snips',
    'https://www.ridgid.com/us/en/tape-measure',
    'https://www.ridgid.com/us/en/tool-boxes',
    'https://www.ridgid.com/us/en/wet-dry-vacuum',
    'https://www.ridgid.com/us/en/wet-dry-vacuum',
    'https://www.ridgid.com/us/en/wet-dry-vac',
    'https://www.ridgid.com/us/en/dry-vacs',
    'https://www.ridgid.com/us/en/pro-vacs',
    'https://www.ridgid.com/us/en/vacuum-filters',
    'https://www.ridgid.com/us/en/air-movers',
    'https://www.ridgid.com/us/en/power-tools',
    'https://www.ridgid.com/us/en/power-tools',
    'https://www.ridgid.com/us/en/cordless-power-tools',
    'https://www.ridgid.com/us/en/outdoor-power-equipment',
    'https://www.ridgid.com/us/en/bench-and-stationary',
    'https://www.ridgid.com/us/en/air-tools',
    'https://www.ridgid.com/us/en/corded-power-tools',
    'https://www.ridgid.com/us/en/tile-saws',
    'https://www.ridgid.com/us/en/welding',
    'https://www.ridgid.com/us/en/welding',
    'https://www.ridgid.com/us/en/welding-machine',
    'https://www.ridgid.com/us/en/welding-tools',
    'https://www.ridgid.com/us/en/welding-consumables',
    'https://www.ridgid.com/us/en/welding-parts',
    'https://www.ridgid.com/us/en/ridgid-promotions',
    'https://www.ridgid.com/us/en/ridgid-tools#',
    'https://www.ridgid.com/us/en/ridgid-tools',
    'https://www.ridgid.com/us/en/diagnostic-tools',
    'https://www.ridgid.com/us/en/diagnostic-tools',
    'https://www.ridgid.com/us/en/inspection-cameras',
    'https://www.ridgid.com/us/en/video-inspection',
    'https://www.ridgid.com/us/en/video-inspection',
    'https://www.ridgid.com/us/en/inspection-monitor',
    'https://www.ridgid.com/us/en/reels-and-cameras',
    'https://www.ridgid.com/us/en/line-locator',
    'https://www.ridgid.com/us/en/utility-locating',
    'https://www.ridgid.com/us/en/test-and-measurement',
    'https://www.ridgid.com/us/en/pressing-technology',
    'https://www.ridgid.com/us/en/pressing-technology',
    'https://www.ridgid.com/us/en/press-tools',
    'https://www.ridgid.com/us/en/press-jaws',
    'https://www.ridgid.com/us/en/press-jaws',
    'https://www.ridgid.com/us/en/press-jaws-mini-series',
    'https://www.ridgid.com/us/en/compact-series-press-jaws',
    'https://www.ridgid.com/us/en/standard-series-press-jaws',
    'https://www.ridgid.com/us/en/press-rings',
    'https://www.ridgid.com/us/en/megapress',
    'https://www.ridgid.com/us/en/press-snap-soil-pipe-cutters',
    'https://www.ridgid.com/us/en/strutslayr-strut-shear-head',
    'https://www.ridgid.com/us/en/advanced-lithium-batteries-and-chargers',
    'https://www.ridgid.com/us/en/drain-cleaning',
    'https://www.ridgid.com/us/en/drain-cleaning',
    'https://www.ridgid.com/us/en/drain-cleaning-tools',
    'https://www.ridgid.com/us/en/drain-cleaning-tools',
    'https://www.ridgid.com/us/en/closet-augers',
    'https://www.ridgid.com/us/en/grappler-hooks',
    'https://www.ridgid.com/us/en/hand-spinners',
    'https://www.ridgid.com/us/en/sewer-tapes',
    'https://www.ridgid.com/us/en/sink-drain-cleaning',
    'https://www.ridgid.com/us/en/drain-machine',
    'https://www.ridgid.com/us/en/drain-cleaners',
    'https://www.ridgid.com/us/en/sewer-rodding',
    'https://www.ridgid.com/us/en/sewer-jetter',
    'https://www.ridgid.com/us/en/flexshaft-machines',
    'https://www.ridgid.com/us/en/drain-cable',
    'https://www.ridgid.com/us/en/pipe-patching',
    'https://www.ridgid.com/us/en/threading-pipe-fabrication',
    'https://www.ridgid.com/us/en/threading-pipe-fabrication',
    'https://www.ridgid.com/us/en/pipe-bevelling',
    'https://www.ridgid.com/us/en/pipe-threading',
    'https://www.ridgid.com/us/en/pipe-threading',
    'https://www.ridgid.com/us/en/power-threading-machines',
    'https://www.ridgid.com/us/en/hand-held-power-drives',
    'https://www.ridgid.com/us/en/manual-threading',
    'https://www.ridgid.com/us/en/manual-threading',
    'https://www.ridgid.com/us/en/manual-threading-die-heads',
    'https://www.ridgid.com/us/en/manual-ratchet-threaders',
    'https://www.ridgid.com/us/en/manual-receding-threaders',
    'https://www.ridgid.com/us/en/manual-threading-pipe-and-bolt-dies',
    'https://www.ridgid.com/us/en/nipple-chucks-adapters',
    'https://www.ridgid.com/us/en/pipe-threading-accessories',
    'https://www.ridgid.com/us/en/roll-grooving',
    'https://www.ridgid.com/us/en/bending-hole-cutting',
    'https://www.ridgid.com/us/en/bending-hole-cutting',
    'https://www.ridgid.com/us/en/hole-cutting-tools',
    'https://www.ridgid.com/us/en/blades-for-reciprocating-saw',
    'https://www.ridgid.com/us/en/core-drill-bit',
    'https://www.ridgid.com/us/en/tapping-tools',
    'https://www.ridgid.com/us/en/hydraulic-benders',
    'https://www.ridgid.com/us/en/pipe-vises-and-supports',
    'https://www.ridgid.com/us/en/pipe-vises-and-supports',
    'https://www.ridgid.com/us/en/pipe-vises',
    'https://www.ridgid.com/us/en/pipe-supports',
    'https://www.ridgid.com/us/en/pipe-cutting-and-fabrication',
    'https://www.ridgid.com/us/en/pipe-cutting-and-fabrication',
    'https://www.ridgid.com/us/en/pipe-reamers-extractors-taps',
    'https://www.ridgid.com/us/en/dry-cut-saws',
    'https://www.ridgid.com/us/en/soil-pipe-cutter',
    'https://www.ridgid.com/us/en/power-pipe-cutters',
    'https://www.ridgid.com/us/en/pipe-cutter',
    'https://www.ridgid.com/us/en/pipe-cutter',
    'https://www.ridgid.com/us/en/four-wheel-pipe-cutter',
    'https://www.ridgid.com/us/en/heavy-duty-pipe-cutter',
    'https://www.ridgid.com/us/en/hinged-pipe-cutter',
    'https://www.ridgid.com/us/en/wide-roll-pipe-cutters',
    'https://www.ridgid.com/us/en/wrenches-and-tubing-tools',
    'https://www.ridgid.com/us/en/wrenches-and-tubing-tools',
    'https://www.ridgid.com/us/en/wrenches',
    'https://www.ridgid.com/us/en/wrenches',
    'https://www.ridgid.com/us/en/heavy-duty-wrenches',
    'https://www.ridgid.com/us/en/inner-tube-core-barrel-wrenches',
    'https://www.ridgid.com/us/en/rapidgrip',
    'https://www.ridgid.com/us/en/end-pipe-wrenches',
    'https://www.ridgid.com/us/en/raprench',
    'https://www.ridgid.com/us/en/offset-wrenches',
    'https://www.ridgid.com/us/en/hex-wrench',
    'https://www.ridgid.com/us/en/spud-wrenches',
    'https://www.ridgid.com/us/en/chain-wrench',
    'https://www.ridgid.com/us/en/compound-leverage-wrenches',
    'https://www.ridgid.com/us/en/chain-tong',
    'https://www.ridgid.com/us/en/strap-wrench',
    'https://www.ridgid.com/us/en/ridgid-adjustable-wrenches',
    'https://www.ridgid.com/us/en/pipe-wrenches',
    'https://www.ridgid.com/us/en/ridgid-wrench-parts',
    'https://www.ridgid.com/us/en/bending-and-forming',
    'https://www.ridgid.com/us/en/bending-and-forming',
    'https://www.ridgid.com/us/en/bending-tools',
    'https://www.ridgid.com/us/en/flaring-tools',
    'https://www.ridgid.com/us/en/tube-expanders',
    'https://www.ridgid.com/us/en/swaging-tool',
    'https://www.ridgid.com/us/en/tube-repair-and-joining',
    'https://www.ridgid.com/us/en/tube-repair-and-joining',
    'https://www.ridgid.com/us/en/pipe-freezers',
    'https://www.ridgid.com/us/en/pipe-thawer',
    'https://www.ridgid.com/us/en/pressure-test-pumps',
    'https://www.ridgid.com/us/en/soldering-guns',
    'https://www.ridgid.com/us/en/tube-cutting-and-preparation',
    'https://www.ridgid.com/us/en/tube-cutting-and-preparation',
    'https://www.ridgid.com/us/en/tubing-cutters',
    'https://www.ridgid.com/US/en/power-tubing-cutters',
    'https://www.ridgid.com/us/en/plastic-pipe-cutters',
    'https://www.ridgid.com/us/en/copper-cleaning-brushes',
    'https://www.ridgid.com/us/en/copper-cutting-prep-machines',
    'https://www.ridgid.com/us/en/reamers-deburring-tools',
    'https://www.ridgid.com/us/en/software',
    'https://www.ridgid.com/us/en/electrical-tools',
    'https://www.ridgid.com/us/en/electrical-tools',
    'https://www.ridgid.com/us/en/manual-hydraulic-crimping',
    'https://www.ridgid.com/us/en/knockout-sets',
    'https://www.ridgid.com/us/en/cable-cutters',
    'https://www.ridgid.com/us/en/cable-trimmers',
    'https://www.ridgid.com/us/en/conduit-benders',
    'https://www.ridgid.com/us/en/sizing-tools',
    'https://www.ridgid.com/us/en/hand-tools',
    'https://www.ridgid.com/us/en/hand-tools',
    'https://www.ridgid.com/us/en/water-pumps',
    'https://www.ridgid.com/us/en/water-pumps',
    'https://www.ridgid.com/us/en/sump-pump',
    'https://www.ridgid.com/us/en/sewage-pump',
    'https://www.ridgid.com/us/en/utility-pump',
    'https://www.ridgid.com/us/en/tile-tools',
    'https://www.ridgid.com/us/en/concrete-tools',
    'https://www.ridgid.com/us/en/straplock',
    'https://www.ridgid.com/us/en/vises',
    'https://www.ridgid.com/us/en/anvils',
    'https://www.ridgid.com/us/en/levels',
    'https://www.ridgid.com/us/en/bolt-cutter',
    'https://www.ridgid.com/us/en/folding-rules',
    'https://www.ridgid.com/us/en/on-site-storage',
    'https://www.ridgid.com/us/en/ridgid-pliers',
    'https://www.ridgid.com/us/en/saws',
    'https://www.ridgid.com/us/en/screw-extractor',
    'https://www.ridgid.com/us/en/replacement-drill-guide',
    'https://www.ridgid.com/us/en/twist-drill',
    'https://www.ridgid.com/us/en/ridgid-shovels',
    'https://www.ridgid.com/us/en/ridgid-snips',
    'https://www.ridgid.com/us/en/tape-measure',
    'https://www.ridgid.com/us/en/tool-boxes',
    'https://www.ridgid.com/us/en/tool-boxes',
    'https://www.ridgid.com/us/en/tool-boxes-heavy-duty',
    'https://www.ridgid.com/us/en/tool-boxes-general-purpose',
    'https://www.ridgid.com/us/en/wet-dry-vacuum',
    'https://www.ridgid.com/us/en/wet-dry-vacuum',
    'https://www.ridgid.com/us/en/wet-dry-vac',
    'https://www.ridgid.com/us/en/dry-vacs',
    'https://www.ridgid.com/us/en/pro-vacs',
    'https://www.ridgid.com/us/en/vacuum-filters',
    'https://www.ridgid.com/us/en/air-movers',
    'https://www.ridgid.com/us/en/power-tools',
    'https://www.ridgid.com/us/en/power-tools',
    'https://www.ridgid.com/us/en/cordless-power-tools',
    'https://www.ridgid.com/us/en/cordless-power-tools',
    'https://www.ridgid.com/us/en/cordless-combo-kits',
    'https://www.ridgid.com/us/en/cordless-drills',
    'https://www.ridgid.com/us/en/bare-tools',
    'https://www.ridgid.com/us/en/cordless-lights',
    'https://www.ridgid.com/us/en/batteries-and-chargers',
    'https://www.ridgid.com/us/en/outdoor-power-equipment',
    'https://www.ridgid.com/us/en/bench-and-stationary',
    'https://www.ridgid.com/us/en/bench-and-stationary',
    'https://www.ridgid.com/us/en/miter-saws',
    'https://www.ridgid.com/us/en/table-saws',
    'https://www.ridgid.com/us/en/cut-off-machines',
    'https://www.ridgid.com/us/en/drill-presses',
    'https://www.ridgid.com/us/en/planers',
    'https://www.ridgid.com/us/en/spindle-sanders',
    'https://www.ridgid.com/us/en/stands-for-bench-and-stationary',
    'https://www.ridgid.com/us/en/air-tools',
    'https://www.ridgid.com/us/en/air-tools',
    'https://www.ridgid.com/us/en/nailers',
    'https://www.ridgid.com/us/en/pneumatic-combo-kits',
    'https://www.ridgid.com/us/en/air-compressors',
    'https://www.ridgid.com/us/en/corded-power-tools',
    'https://www.ridgid.com/us/en/corded-power-tools',
    'https://www.ridgid.com/us/en/drills-and-wrenches',
    'https://www.ridgid.com/us/en/circular-saws',
    'https://www.ridgid.com/us/en/reciprocating-saws',
    'https://www.ridgid.com/us/en/angle-grinders',
    'https://www.ridgid.com/us/en/hands-sanders',
    'https://www.ridgid.com/us/en/routers',
    'https://www.ridgid.com/us/en/jig-saws',
    'https://www.ridgid.com/us/en/collated-screwdriver',
    'https://www.ridgid.com/us/en/tile-saws',
    'https://www.ridgid.com/us/en/welding',
    'https://www.ridgid.com/us/en/welding',
    'https://www.ridgid.com/us/en/welding-machine',
    'https://www.ridgid.com/us/en/welding-tools',
    'https://www.ridgid.com/us/en/welding-consumables',
    'https://www.ridgid.com/us/en/welding-parts',
    'https://www.ridgid.com/us/en/new-tools',
    'https://www.ridgid.com/us/en/ridgid-promotions',



]


def UrlLink():
    start_url = 0
    product_urls = []
    for url_count, url in enumerate(url_links[start_url:], start=start_url):
        print('product_url.....', url_count, url)
        driver.get(url)
        time.sleep(3)

        for href_tag in driver.find_elements(By.CSS_SELECTOR, "ul.grid a"):
            product_url = href_tag.get_attribute('href')
            # print(product_url)
            product_urls.append(product_url)


        #
        # while True:
        #     try:
        #         next_button = driver.find_element(By.CSS_SELECTOR, ".inline-block.leading-4.align-top.rounded-r-md svg")
        #         next_button.click()
        #         time.sleep(3)
        #         for href_tag in driver.find_elements(By.CSS_SELECTOR, "a[data-testid='itemLink']"):
        #             product_url = href_tag.get_attribute('href')
        #             print(product_url)
        #             product_urls.append(product_url)
        #     except Exception as e:
        #         print("No more pages or error occurred:", e)
        #         break

        for url_tag in driver.find_elements(By.CSS_SELECTOR, "ul.grid a[itemprop='url']"):
            product_url = url_tag.get_attribute('href')
            product_urls.append(product_url)

        df = pd.DataFrame(product_urls, columns=['URL'])
        df.to_csv('product_url_ridgid.csv', mode='a', header=not pd.io.common.file_exists('product_url_ridgid.csv'), index=False)
        print('save data in dataframe')
    driver.quit()


UrlLink()


"""
'https://www.ridgid.com/us/en/bending-tools',
'https://www.ridgid.com/us/en/flaring-tools',
'https://www.ridgid.com/us/en/tube-expanders',
'https://www.ridgid.com/us/en/swaging-tool',
'https://www.ridgid.com/us/en/wrenches',
'https://www.ridgid.com/us/en/bending-and-forming',
'https://www.ridgid.com/us/en/tube-repair-and-joining',
'https://www.ridgid.com/us/en/tube-cutting-and-preparation',
'https://www.ridgid.com/us/en/wrenches',
'https://www.ridgid.com/us/en/bending-and-forming',
'https://www.ridgid.com/us/en/tube-repair-and-joining',
'https://www.ridgid.com/us/en/tube-cutting-and-preparation',
'https://www.ridgid.com/us/en/pipe-reamers-extractors-taps',
'https://www.ridgid.com/us/en/dry-cut-saws',
'https://www.ridgid.com/us/en/soil-pipe-cutter',
'https://www.ridgid.com/us/en/power-pipe-cutters',
'https://www.ridgid.com/us/en/pipe-cutter',
'https://www.ridgid.com/us/en/pipe-vises',
'https://www.ridgid.com/us/en/pipe-supports',
'https://www.ridgid.com/us/en/hole-cutting-tools',
'https://www.ridgid.com/us/en/blades-for-reciprocating-saw',
'https://www.ridgid.com/us/en/core-drill-bit',
'https://www.ridgid.com/us/en/tapping-tools',
'https://www.ridgid.com/us/en/hydraulic-benders',
'https://www.ridgid.com/us/en/power-threading-machines',
'https://www.ridgid.com/us/en/hand-held-power-drives',
'https://www.ridgid.com/us/en/manual-threading',
'https://www.ridgid.com/us/en/nipple-chucks-adapters',
'https://www.ridgid.com/us/en/pipe-threading-accessories',
'https://www.ridgid.com/us/en/pipe-patching-starter-systems',
'https://www.ridgid.com/us/en/pipe-patch-kits',
'https://www.ridgid.com/us/en/pipe-patching-containment-kits',
'https://www.ridgid.com/us/en/pipe-patching-air-push-rods',
'https://www.ridgid.com/us/en/pipe-patching-packers',
'https://www.ridgid.com/us/en/pipe-patching-accessories',
'https://www.ridgid.com/us/en/pipe-bevelling',
'https://www.ridgid.com/us/en/pipe-threading',
'https://www.ridgid.com/us/en/roll-grooving',
'https://www.ridgid.com/us/en/bending-hole-cutting',
'https://www.ridgid.com/us/en/pipe-vises-and-supports',
'https://www.ridgid.com/us/en/pipe-cutting-and-fabrication',
"""