import time
import pyautogui as gui
from selenium.webdriver.common.by import By
from selenium import webdriver

mylist = [

    # 'https://handle-it.com/collections/cages-and-stillages/products/platform-truck-with-4-mesh-sides',
    # 'https://handle-it.com/collections/dollies/products/stack_and_nest_box_dolly',
    # 'https://handle-it.com/collections/dollies/products/aluminium-dolly-for-plastic-boxes',
    # 'https://handle-it.com/collections/dollies/products/steel-box-dolly',
    # 'https://handle-it.com/collections/dollies/products/tote-pan-dolly',
    # 'https://handle-it.com/collections/dollies/products/grocery-box-dolly',
    # 'https://handle-it.com/collections/dollies/products/food-delivery-dolly',
    # 'https://handle-it.com/collections/dollies/products/210-litre-or-55-gallon-drum-dolly',
    # 'https://handle-it.com/collections/dollies/products/pallet-dolly-to-suit-gkn-or-euro-pallets',
    # 'https://handle-it.com/collections/dollies/products/industrial-barrel-dolly',
    # 'https://handle-it.com/collections/dollies/products/keg-skate-dolly',
    # 'https://handle-it.com/collections/dollies/products/pharmaceutical-drum-dolly',
    # 'https://handle-it.com/collections/dollies/products/euro-stacker-box-dolly-hi9999-eu',
    # 'https://handle-it.com/collections/dollies/products/bakery_dolly',
    # 'https://handle-it.com/collections/dollies/products/tote-pan-lifting-trolley',
    # 'https://handle-it.com/collections/dollies/products/reel-bogie-or-carpet-dolly',
    # 'https://handle-it.com/collections/dollies/products/dolly-with-retention-frame-and-handle',
    # 'https://handle-it.com/collections/dollies/products/tote-pan-and-stacking-box-dolly',
    # 'https://handle-it.com/collections/dollies/products/stainless-steel-platform-dolly',
    # 'https://handle-it.com/collections/dollies/products/tubular-steel-dolly',
    # 'https://handle-it.com/collections/dollies/products/heavy-duty-corner-skates',
    # 'https://handle-it.com/collections/dollies/products/heavy-duty-tri-skates',
    # 'https://handle-it.com/collections/dollies/products/low-loading-bogie',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/electric-powered-flatbed-trolley',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/powered-platform-truck-with-removable-sides-hi-pow-range',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/motorised-platform-truck-with-boarded-sides',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/powered-2-tier-trolley',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/powered-trolley-with-3-shelves',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/powered-shelf-trolley-with-sides',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/power-assisted-locking-cage-trolley',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/electric-security-cage-trolley',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/powered-full-security-storage-trolley',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/motorised-secure-records-trolley',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/power-assisted-cage-trolley',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/motorised-adjustable-lift-table-trolley',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/powered-service-trolley',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/powered-security-trolley-with-panic-alarm-system',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/electric-turntable-trailer',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/powered-turntable-truck-with-steel-sides',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/powered-turntable-trolley-with-mesh-sides',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/1-ton-electric-powered-turntable-trolley',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/motorised-airport-trolley-stack-pusher',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/weigh-scale-trolley',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/weight-scale-trolley-for-drums',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/stair-climbing-sack-truck',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/folding-powered-stair-climbing-sack-truck',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/heavy-duty-stair-climbing-sack-truck-with-tilt-back-support',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/electric-stair-climbing-water-bottle-carrier',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/powered-stair-climbing-sack-truck-for-cylinders-and-gas-bottles',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/electric-lifter-sack-truck',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/extra-heavy-duty-stair-climbing-sack-truck',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/folding-motorised-stair-climbing-sack-truck',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/heavy-duty-powered-stair-climbing-sack-truck',
    # 'https://handle-it.com/collections/electric-motorised-and-powered-trolleys-and-platform-trucks/products/three-position-powered-stair-climbing-sack-truck',
    # 'https://handle-it.com/collections/cages-and-stillages/products/security-platform-truck-with-locking-lid',
    # 'https://handle-it.com/collections/cages-and-stillages/products/secure-mail-and-parcel-cage-trolley',
    # 'https://handle-it.com/collections/cages-and-stillages/products/mesh-sided-platform-truck-or-cage-trolley-with-4-sides',
    # 'https://handle-it.com/collections/cages-and-stillages/products/4-sided-roll-cage-full-security-galvanised',
    # 'https://handle-it.com/collections/cages-and-stillages/products/heavy-duty-shelf-trolley',
    # 'https://handle-it.com/collections/cages-and-stillages/products/heavy-duty-distribution-trolley',
    # 'https://handle-it.com/collections/cages-and-stillages/products/bulk-storage-cage-trolley',
    # 'https://handle-it.com/collections/cages-and-stillages/products/parcel-cage-trolley',
    # 'https://handle-it.com/collections/cages-and-stillages/products/full-security-parcel-cage',
    # 'https://handle-it.com/collections/cages-and-stillages/products/porters-trolley',
    # 'https://handle-it.com/collections/cages-and-stillages/products/powered-platform-truck-with-removable-sides-hi-pow-range',
    # 'https://handle-it.com/collections/cages-and-stillages/products/power-assisted-locking-cage-trolley',
    # 'https://handle-it.com/collections/cages-and-stillages/products/electric-security-cage-trolley',
    # 'https://handle-it.com/collections/cages-and-stillages/products/gas-bottle-storage-cages',
    # 'https://handle-it.com/collections/cages-and-stillages/products/mesh-fronted-stillages',
    # 'https://handle-it.com/collections/cages-and-stillages/products/stacking-stillage',
    # 'https://handle-it.com/collections/cages-and-stillages/products/gas-bottle-storage-rack',
    # 'https://handle-it.com/collections/cages-and-stillages/products/gated-access-cage',
    # 'https://handle-it.com/collections/sack-truck-and-barrow-wheels/products/10-inch-sack-truck-pneumatic-wheels-20mm-axle',
    # 'https://handle-it.com/collections/sack-truck-and-barrow-wheels/products/10-inch-sack-truck-puncture-proof-wheels-20mm-axle',
    # 'https://handle-it.com/collections/sack-truck-and-barrow-wheels/products/10-inch-sack-truck-pneumatic-wheels',
    # 'https://handle-it.com/collections/sack-truck-and-barrow-wheels/products/10-inch-sack-truck-puncture-proof-wheels',
    # 'https://handle-it.com/collections/sack-truck-and-barrow-wheels/products/400mm-pneumatic-wheel-for-turntable-trolley-or-sack-truck-20mm-axle',
    # 'https://handle-it.com/collections/sack-truck-and-barrow-wheels/products/400mm-puncture-proof-trolley-wheel-20mm-axle',
    # 'https://handle-it.com/collections/sack-truck-and-barrow-wheels/products/8-inch-solid-sack-truck-wheel-20mm-axle',
    # 'https://handle-it.com/collections/sack-truck-and-barrow-wheels/products/8-inch-solid-sack-truck-wheel-1-inch-25-4mm-axle',
    # 'https://handle-it.com/collections/sack-truck-and-barrow-wheels/products/13-inch-garden-cart-pneumatic-wheels-16mm-axle',
    # 'https://handle-it.com/collections/sack-truck-and-barrow-wheels/products/magliner-pneumatic-wheel',
    # 'https://handle-it.com/collections/sack-truck-and-barrow-wheels/products/magliner-puncture-proof-wheel',
    # 'https://handle-it.com/collections/sack-truck-and-barrow-wheels/products/sack-truck-ratchet-strap',
    # 'https://handle-it.com/collections/castors/products/polyprop-centre-castor-with-black-rubber-tyre',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/school-tray-storage-trolley',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/school-tray-rack-trolley',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/classroom-storage-trolley',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/school-storage-tray-small',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/school-storage-tray-medium',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/school-storage-tray-large',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/school-storage-tray-huge',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/school-tray-storage-trolley-antibac',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/classroom-antibacterial-tray-rack-trolley',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/school-storage-trolley-antibac',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/eduk8-classroom-storage-tray-trolley-3-columns-no-trays',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/chair-moving-sack-truck',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/double-sided-trestle-table-trolley',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/gym-mat-trolley-with-deadman-brake',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/adjustable-double-sided-trolley-jailbar-sides',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/library_and_book_trolley',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/trolley-for-moving-a4-size-files',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/powered-platform-truck-with-removable-sides-hi-pow-range',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/platform-truck-with-4-mesh-sides',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/bad-boy-all-purpose-trolley',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/heavy-duty-turntable-trolley',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/industrial-turntable-trolley',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/turntable-trolley-1575',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/water-bottle-sack-truck-for-6-bottles',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/power-assisted-stair-climbing-sack-truck',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/sack-truck-and-barrow-for-rough-terrain',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/long-toe-sack-barrow-heavy-duty',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/folding-toe-sack-truck',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/folding-portable-van-sack-truck',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/trolley-ratchet-strap',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/turntable-trolley-with-steel-sides',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/turntable-trailer',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/motorised-platform-truck-with-boarded-sides',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/turntable-trailer-with-400mm-sides-500kg-capacity',
    # 'https://handle-it.com/collections/handling-equipment-for-schools/products/copy-of-turntable-truck-with-400m-sides-1000kg-capacity',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/stacking-mail-room-box-trolley',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/suspended-mail-bag-trolleys',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/mail-room-shelf-trolley',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/mesh-sided-platform-truck-or-cage-trolley-with-4-sides',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/platform-truck-clad-with-4-plastic-sides',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/4-sided-platform-truck-with-ply-board-sides',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/small-mail-room-trolleys',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/mail-room-trolley',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/large-mailroom-trolleys',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/mail-distribution-trolley',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/platform-truck-with-4-mesh-sides',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/folding-portable-van-sack-truck',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/porters-trolley',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/bulk-storage-cage-trolley',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/electric-powered-flatbed-trolley',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/powered-platform-truck-with-removable-sides-hi-pow-range',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/motorised-secure-records-trolley',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/powered-2-tier-trolley',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/powered-trolley-with-3-shelves',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/powered-full-security-storage-trolley',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/power-assisted-locking-cage-trolley',
    # 'https://handle-it.com/collections/mailroom-trolleys/products/electric-security-cage-trolley',
    # 'https://handle-it.com/collections/food-service-handling-equipment/products/sandwich-trolley',
    # 'https://handle-it.com/collections/food-service-handling-equipment/products/water-bottle-sack-truck-for-6-bottles',
    # 'https://handle-it.com/collections/food-service-handling-equipment/products/grocery-box-dolly',
    # 'https://handle-it.com/collections/food-service-handling-equipment/products/food-delivery-dolly',
    # 'https://handle-it.com/collections/food-service-handling-equipment/products/service-trolley-with-2-or-3-tiers',
    # 'https://handle-it.com/collections/food-service-handling-equipment/products/4-sided-roll-cage-full-security-galvanised',
    # 'https://handle-it.com/collections/food-service-handling-equipment/products/long-toe-sack-barrow-heavy-duty',
    # 'https://handle-it.com/collections/food-service-handling-equipment/products/heavy-duty-keg-sack-truck',
    # 'https://handle-it.com/collections/food-service-handling-equipment/products/heavy-duty-keg-and-case-sack-truck',
    # 'https://handle-it.com/collections/food-service-handling-equipment/products/aluminium-sack-trucks-bottled-water-trolley',
    # 'https://handle-it.com/collections/food-service-handling-equipment/products/aluminium-sack-trucks-bottled-water-trolley-5-bottle',
    # 'https://handle-it.com/collections/food-service-handling-equipment/products/aluminium-sack-trucks-traditional-sack-barrow',
    # 'https://handle-it.com/collections/food-service-handling-equipment/products/magliner-aluminium-keg-sack-truck',
    # 'https://handle-it.com/collections/food-service-handling-equipment/products/drop-mat-600mm-x-600mm',
    # 'https://handle-it.com/collections/food-service-handling-equipment/products/cellar-pad-for-kegs-casks-barrels',
    # 'https://handle-it.com/collections/food-service-handling-equipment/products/vita-bumper-pad-for-cellars',
    # 'https://handle-it.com/collections/food-service-handling-equipment/products/sack-truck-ratchet-strap',
    # 'https://handle-it.com/collections/food-service-handling-equipment/products/trolley-ratchet-strap',
    # 'https://handle-it.com/collections/parcel-and-courier-service-handling-equipment/products/security-platform-truck-with-locking-lid',
    # 'https://handle-it.com/collections/parcel-and-courier-service-handling-equipment/products/secure-mail-and-parcel-cage-trolley',
    # 'https://handle-it.com/collections/parcel-and-courier-service-handling-equipment/products/full-security-parcel-cage',
    # 'https://handle-it.com/collections/parcel-and-courier-service-handling-equipment/products/parcel-cage-trolley',
    # 'https://handle-it.com/collections/parcel-and-courier-service-handling-equipment/products/heavy-duty-shelf-trolley',
    # 'https://handle-it.com/collections/parcel-and-courier-service-handling-equipment/products/heavy-duty-distribution-trolley',
    # 'https://handle-it.com/collections/parcel-and-courier-service-handling-equipment/products/10-tread-mobile-safety-steps-with-lever-brake',
    # 'https://handle-it.com/collections/parcel-and-courier-service-handling-equipment/products/folding-portable-van-sack-truck',
    # 'https://handle-it.com/collections/parcel-and-courier-service-handling-equipment/products/professional-aluminium-sack-truck',
    # 'https://handle-it.com/collections/parcel-and-courier-service-handling-equipment/products/mail-room-trolley',
    # 'https://handle-it.com/collections/parcel-and-courier-service-handling-equipment/products/stacking-mail-room-box-trolley',
    # 'https://handle-it.com/collections/retail-handling-solutions-and-shopping-trolleys/products/professional-aluminium-sack-truck',
    # 'https://handle-it.com/collections/retail-handling-solutions-and-shopping-trolleys/products/shopping-trolley-80l',
    # 'https://handle-it.com/collections/retail-handling-solutions-and-shopping-trolleys/products/service-trolley-with-2-or-3-tiers',
    # 'https://handle-it.com/collections/retail-handling-solutions-and-shopping-trolleys/products/traditional-sack-barrow',
    # 'https://handle-it.com/collections/retail-handling-solutions-and-shopping-trolleys/products/two-or-three-shelf-trolley-with-pneumatic-castors',
    # 'https://handle-it.com/collections/retail-handling-solutions-and-shopping-trolleys/products/4-sided-roll-cage-full-security-galvanised',
    # 'https://handle-it.com/collections/retail-handling-solutions-and-shopping-trolleys/products/heavy-duty-distribution-trolley',
    # 'https://handle-it.com/collections/retail-handling-solutions-and-shopping-trolleys/products/heavy-duty-pallet-truck',
    # 'https://handle-it.com/collections/retail-handling-solutions-and-shopping-trolleys/products/shopping-trolley-120l',
    # 'https://handle-it.com/collections/retail-handling-solutions-and-shopping-trolleys/products/shopping-trolley-60l',
    # 'https://handle-it.com/collections/retail-handling-solutions-and-shopping-trolleys/products/water-bottle-sack-truck-for-6-bottles',
    # 'https://handle-it.com/collections/retail-handling-solutions-and-shopping-trolleys/products/shopping-trolley-180l',
    # 'https://handle-it.com/collections/retail-handling-solutions-and-shopping-trolleys/products/wheelchair-friendly-shopping-trolley',
    # 'https://handle-it.com/collections/removal-service-handling-equipment/products/folding-flatbed-trolley',
    # 'https://handle-it.com/collections/removal-service-handling-equipment/products/sack-barrow-with-folding-toeplate-heavy-duty',
    # 'https://handle-it.com/collections/removal-service-handling-equipment/products/euro-stacker-box-dolly-hi9999-eu',
    # 'https://handle-it.com/collections/removal-service-handling-equipment/products/bakery_dolly',
    # 'https://handle-it.com/collections/removal-service-handling-equipment/products/pallet-dolly-to-suit-gkn-or-euro-pallets',
    # 'https://handle-it.com/collections/removal-service-handling-equipment/products/reel-bogie-or-carpet-dolly',
    # 'https://handle-it.com/collections/removal-service-handling-equipment/products/folding-toe-sack-truck',
    # 'https://handle-it.com/collections/removal-service-handling-equipment/products/professional-aluminium-sack-truck',
    # 'https://handle-it.com/collections/removal-service-handling-equipment/products/folding-portable-van-sack-truck',
    # 'https://handle-it.com/collections/removal-service-handling-equipment/products/sack-truck-ratchet-strap',
    # 'https://handle-it.com/collections/removal-service-handling-equipment/products/trolley-ratchet-strap',
    # 'https://handle-it.com/collections/self-storage-handling-equipment/products/adjustable-double-sided-trolley-jailbar-sides',
    # 'https://handle-it.com/collections/self-storage-handling-equipment/products/double-sided-trestle-table-trolley',
    # 'https://handle-it.com/collections/self-storage-handling-equipment/products/economy-flatbed-trolley',
    # 'https://handle-it.com/collections/self-storage-handling-equipment/products/heavy-duty-flatbed-trolley-with-single-mesh-end',
    # 'https://handle-it.com/collections/self-storage-handling-equipment/products/mesh-sided-platform-truck-or-cage-trolley-with-4-sides',
    # 'https://handle-it.com/collections/self-storage-handling-equipment/products/platform-truck-with-4-mesh-sides',
    # 'https://handle-it.com/collections/self-storage-handling-equipment/products/sack-barrow-with-folding-toeplate-heavy-duty',
    # 'https://handle-it.com/collections/self-storage-handling-equipment/products/folding-toe-sack-truck',
    # 'https://handle-it.com/collections/self-storage-handling-equipment/products/professional-aluminium-sack-truck',
    # 'https://handle-it.com/collections/self-storage-handling-equipment/products/folding-portable-van-sack-truck',
    # 'https://handle-it.com/collections/self-storage-handling-equipment/products/sack-truck-ratchet-strap',
    # 'https://handle-it.com/collections/self-storage-handling-equipment/products/trolley-ratchet-strap',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/economy-flatbed-trolley',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/flatbed-trolley',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/industrial-flatbed-trolley',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/folding-flatbed-trolley',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/cash-and-carry-trolley',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/eco-friendly-trolley',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/heavy-duty-flatbed-trolley-with-single-mesh-end',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/heavy-duty-flatbed-trolley-with-ply-wood-end',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/heavy-duty-flatbed-trolley-with-single-plastic-end',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/rough-terrain-flatbed-trolley',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/heavy-duty-platform-truck-with-deadman-brake',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/stainless-steel-heavy-duty-platform-trolley',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/gavanized-heavy-duty-platform-trucks-hi-36-gfbt',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/chair-moving-trolley',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/weigh-scale-trolley',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/electric-powered-flatbed-trolley',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/motorised-adjustable-lift-table-trolley',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/containment-bund-trolley-200-litre-capacity',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/stainless-steel-bund-trolley',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/trolley-ratchet-strap',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/containment-bund-trolley-25-litre-capacity',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/containment-bund-trolley-50-litre-capacity',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/containment-bund-trolley-75-litre-capacity',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/containment-bund-trolley-100-litre-capacity',
    # 'https://handle-it.com/collections/flatbed-trolleys/products/containment-bund-trolley-150-litre-capacity',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/industrial-flatbed-trolley',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/platform-truck-with-4-mesh-sides',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/flatbed-trolley',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/folding-flatbed-trolley',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/cash-and-carry-trolley',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/heavy-duty-flatbed-trolley-with-single-mesh-end',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/double-ended-mesh-platform-truck',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/platform-truck-with-3-removable-mesh-sides',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/mesh-sided-platform-truck-or-cage-trolley-with-4-sides',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/heavy-duty-flatbed-trolley-with-ply-wood-end',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/double-ended-ply-platform-truck',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/platform-truck-or-box-trolley-with-3-wooden-sides',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/4-sided-platform-truck-with-ply-board-sides',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/heavy-duty-flatbed-trolley-with-single-plastic-end',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/double-ended-plastic-platform-truck',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/platform-truck-with-3-plastic-sides',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/platform-truck-clad-with-4-plastic-sides',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/heavy-duty-platform-truck-with-deadman-brake',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/platform-truck-or-cage-trolley-with-deadman-brake-and-4-sides',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/rough-terrain-flatbed-trolley',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/chair-moving-trolley',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/security-platform-truck-with-locking-lid',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/secure-mail-and-parcel-cage-trolley',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/weigh-scale-trolley',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/weight-scale-trolley-for-drums',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/electric-powered-flatbed-trolley',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/powered-platform-truck-with-removable-sides-hi-pow-range',
    # 'https://handle-it.com/collections/platform-trucks-and-trolleys/products/trolley-ratchet-strap',
    # 'https://handle-it.com/collections/turntable-trolleys/products/heavy-duty-turntable-trolley',
    # 'https://handle-it.com/collections/turntable-trolleys/products/industrial-turntable-trolley',
    # 'https://handle-it.com/collections/turntable-trolleys/products/turntable-trailer',
    # 'https://handle-it.com/collections/turntable-trolleys/products/turntable-trolley-with-steel-sides',
    # 'https://handle-it.com/collections/turntable-trolleys/products/bad-boy-all-purpose-trolley',
    # 'https://handle-it.com/collections/turntable-trolleys/products/turntable-trolley-1260',
    # 'https://handle-it.com/collections/turntable-trolleys/products/turntable-trolley-1575',
    # 'https://handle-it.com/collections/turntable-trolleys/products/turntable-trolley-2010',
    # 'https://handle-it.com/collections/turntable-trolleys/products/small-turntable-trolley-with-brake',
    # 'https://handle-it.com/collections/turntable-trolleys/products/turntable-trolley-with-brake',
    # 'https://handle-it.com/collections/turntable-trolleys/products/large-turntable-trolley-with-parking-brake',
    # 'https://handle-it.com/collections/turntable-trolleys/products/galvanised-turntable-trolley',
    # 'https://handle-it.com/collections/turntable-trolleys/products/extra_heavy_duty_turntable_trolley',
    # 'https://handle-it.com/collections/turntable-trolleys/products/electric-turntable-trailer',
    # 'https://handle-it.com/collections/turntable-trolleys/products/powered-turntable-trolley-with-mesh-sides',
    # 'https://handle-it.com/collections/turntable-trolleys/products/3-ton-turntable-trolley',
    # 'https://handle-it.com/collections/turntable-trolleys/products/facilities-bulk-cylinder-or-gas-bottle-trailer',
    # 'https://handle-it.com/collections/turntable-trolleys/products/turntable-trolley-complete-side-pannel-kit',
    # 'https://handle-it.com/collections/turntable-trolleys/products/trolley-ratchet-strap',
    # 'https://handle-it.com/collections/turntable-trolleys/products/low-load-gooseneck-turntable-trolley',
    # 'https://handle-it.com/collections/turntable-trolleys/products/1-ton-electric-powered-turntable-trolley',
    # 'https://handle-it.com/collections/turntable-trolleys/products/powered-turntable-truck-with-steel-sides',
    # 'https://handle-it.com/collections/turntable-trolleys/products/turntable-trailer-with-400mm-sides-500kg-capacity',
    # 'https://handle-it.com/collections/turntable-trolleys/products/copy-of-turntable-truck-with-400m-sides-1000kg-capacity',
    # 'https://handle-it.com/collections/double-sided-trolleys/products/double-sided-trolley',
    # 'https://handle-it.com/collections/panel-board-and-long-load-trolleys/products/diy-store-trolley',
    # 'https://handle-it.com/collections/panel-board-and-long-load-trolleys/products/economy-a-frame-trolley',
    # 'https://handle-it.com/collections/panel-board-and-long-load-trolleys/products/window-panel-or-sheet-trolley',
    # 'https://handle-it.com/collections/panel-board-and-long-load-trolleys/products/double-sided-a-frame-window-trolley',
    # 'https://handle-it.com/collections/panel-board-and-long-load-trolleys/products/double-sided-trolley',
    # 'https://handle-it.com/collections/panel-board-and-long-load-trolleys/products/double-sided-trestle-table-trolley',
    # 'https://handle-it.com/collections/panel-board-and-long-load-trolleys/products/adjustable-double-sided-trolley-jailbar-sides',
    # 'https://handle-it.com/collections/panel-board-and-long-load-trolleys/products/sheet-buggy',
    # 'https://handle-it.com/collections/panel-board-and-long-load-trolleys/products/carpet-trolley',
    # 'https://handle-it.com/collections/panel-board-and-long-load-trolleys/products/reel-bogie-or-carpet-dolly',
    # 'https://handle-it.com/collections/panel-board-and-long-load-trolleys/products/pipe-and-bar-truck',
    # 'https://handle-it.com/collections/panel-board-and-long-load-trolleys/products/adjustable-double-sided-trolley-open-sides',
    # 'https://handle-it.com/collections/panel-board-and-long-load-trolleys/products/adjustable-double-sided-trolley-plastic-sides',
    # 'https://handle-it.com/collections/panel-board-and-long-load-trolleys/products/adjustable-double-sided-trolley-with-board',
    # 'https://handle-it.com/collections/panel-board-and-long-load-trolleys/products/adjustable-double-sided-trolley-w-steel-sides-hi-jd-adst-st',
    # 'https://handle-it.com/collections/panel-board-and-long-load-trolleys/products/trolley-ratchet-strap',
    # 'https://handle-it.com/collections/panel-board-and-long-load-trolleys/products/heavy-duty-double-sided-platform-trolley-with-deadman-brake',
    # 'https://handle-it.com/collections/deadman-brake-trolleys/products/heavy-duty-platform-truck-with-deadman-brake',
    # 'https://handle-it.com/collections/deadman-brake-trolleys/products/platform-truck-or-cage-trolley-with-deadman-brake-and-4-sides',
    # 'https://handle-it.com/collections/deadman-brake-trolleys/products/heavy-duty-double-sided-platform-trolley-with-deadman-brake',
    # 'https://handle-it.com/collections/deadman-brake-trolleys/products/porters-trolley',
    # 'https://handle-it.com/collections/deadman-brake-trolleys/products/4-wheeled-airport-luggage-trolley',
    # 'https://handle-it.com/collections/deadman-brake-trolleys/products/3-wheeled-baggage-trolley',
    # 'https://handle-it.com/collections/deadman-brake-trolleys/products/stainless-steel-passenger-baggage-trolley',
    # 'https://handle-it.com/collections/deadman-brake-trolleys/products/electric-powered-flatbed-trolley',
    # 'https://handle-it.com/collections/deadman-brake-trolleys/products/powered-platform-truck-with-removable-sides-hi-pow-range',
    # 'https://handle-it.com/collections/deadman-brake-trolleys/products/powered-2-tier-trolley',
    # 'https://handle-it.com/collections/deadman-brake-trolleys/products/containment-bund-trolley-25-litre-capacity',
    # 'https://handle-it.com/collections/deadman-brake-trolleys/products/containment-bund-trolley-50-litre-capacity',
    # 'https://handle-it.com/collections/deadman-brake-trolleys/products/containment-bund-trolley-75-litre-capacity',
    # 'https://handle-it.com/collections/deadman-brake-trolleys/products/containment-bund-trolley-100-litre-capacity',
    # 'https://handle-it.com/collections/deadman-brake-trolleys/products/containment-bund-trolley-150-litre-capacity',
    # 'https://handle-it.com/collections/deadman-brake-trolleys/products/containment-bund-trolley-200-litre-capacity',
    # 'https://handle-it.com/collections/deadman-brake-trolleys/products/stainless-steel-bund-trolley',
    # 'https://handle-it.com/collections/airport-trolleys-carts/products/aluminium-airport-trolley',
    # 'https://handle-it.com/collections/stacking-trolleys/products/cash-and-carry-trolley',
    # 'https://handle-it.com/collections/balance-trolleys/products/heavy-duty-balance-trolley',
    # 'https://handle-it.com/collections/aluminium-sack-trucks/products/aluminium-sack-truck',
    # 'https://handle-it.com/collections/sack-barrows/products/traditional-sack-barrow',
    # 'https://handle-it.com/collections/sack-barrows/products/long-toe-sack-barrow-heavy-duty',
    # 'https://handle-it.com/collections/sack-barrows/products/sack-barrow-with-folding-toeplate-heavy-duty',
    # 'https://handle-it.com/collections/sack-barrows/products/sack-barrow-heavy-duty',
    # 'https://handle-it.com/collections/sack-barrows/products/sack-barrow-with-curved-back-heavy-duty',
    # 'https://handle-it.com/collections/sack-barrows/products/sack-barrow-with-high-back-heavy-duty',
    # 'https://handle-it.com/collections/sack-barrows/products/sack-barrow-with-p-handle-heavy-duty',
    # 'https://handle-it.com/collections/sack-barrows/products/10-inch-sack-truck-pneumatic-wheels-20mm-axle',
    # 'https://handle-it.com/collections/sack-barrows/products/10-inch-sack-truck-puncture-proof-wheels-20mm-axle',
    # 'https://handle-it.com/collections/sack-barrows/products/trolley-mounted-document-holder-pick-note-bag',
    # 'https://handle-it.com/collections/sack-barrows/products/black-retention-strap',
    # 'https://handle-it.com/collections/sack-trucks/products/sack-truck-with-flat-back-heavy-duty',
    # 'https://handle-it.com/collections/hand-trucks/products/hand-truck-with-mesh-back',
    # 'https://handle-it.com/collections/light-weight-sack-trucks/products/folding-portable-van-sack-truck',
    # 'https://handle-it.com/collections/sack-trucks-for-keg-water-bottle-and-service-industry-handling/products/heavy-duty-keg-sack-truck',
    # 'https://handle-it.com/collections/sack-trucks-for-keg-water-bottle-and-service-industry-handling/products/heavy-duty-keg-and-case-sack-truck',
    # 'https://handle-it.com/collections/sack-trucks-for-keg-water-bottle-and-service-industry-handling/products/double-keg-sack-truck',
    # 'https://handle-it.com/collections/sack-trucks-for-keg-water-bottle-and-service-industry-handling/products/aluminium-keg-moving-sack-truck',
    # 'https://handle-it.com/collections/sack-trucks-for-keg-water-bottle-and-service-industry-handling/products/aluminium-keg-truck',
    # 'https://handle-it.com/collections/sack-trucks-for-keg-water-bottle-and-service-industry-handling/products/aluminium-high-back-keg-barrow',
    # 'https://handle-it.com/collections/sack-trucks-for-keg-water-bottle-and-service-industry-handling/products/magliner-aluminium-keg-sack-truck',
    # 'https://handle-it.com/collections/sack-trucks-for-keg-water-bottle-and-service-industry-handling/products/heavy-duty-beer-barrel-trolley',
    # 'https://handle-it.com/collections/sack-trucks-for-keg-water-bottle-and-service-industry-handling/products/water-bottle-sack-truck-for-6-bottles',
    # 'https://handle-it.com/collections/sack-trucks-for-keg-water-bottle-and-service-industry-handling/products/aluminium-sack-trucks-bottled-water-trolley',
    # 'https://handle-it.com/collections/sack-trucks-for-keg-water-bottle-and-service-industry-handling/products/aluminium-sack-trucks-bottled-water-trolley-5-bottle',
    # 'https://handle-it.com/collections/sack-trucks-for-keg-water-bottle-and-service-industry-handling/products/power-assisted-stair-climbing-sack-truck',
    # 'https://handle-it.com/collections/sack-trucks-for-keg-water-bottle-and-service-industry-handling/products/keg-skate-dolly',
    # 'https://handle-it.com/collections/sack-trucks-and-trolleys-for-gas-bottles/products/oxygen-bottle-trolleys',
    # 'https://handle-it.com/collections/sack-trucks-and-trolleys-for-gas-bottles/products/gas-bottle-sack-truck',
    # 'https://handle-it.com/collections/sack-trucks-and-trolleys-for-gas-bottles/products/multi-fuel-delivery-sack-truck',
    # 'https://handle-it.com/collections/sack-trucks-and-trolleys-for-gas-bottles/products/heavy-duty-gas-bottle-sack-truck',
    # 'https://handle-it.com/collections/sack-trucks-and-trolleys-for-gas-bottles/products/gas-cylinder-trolley-for-47kg-propane-or-lpg',
    # 'https://handle-it.com/collections/sack-trucks-and-trolleys-for-gas-bottles/products/three-wheeled-lpg-gas-cylinder-trolley',
    # 'https://handle-it.com/collections/sack-trucks-and-trolleys-for-gas-bottles/products/oxygen-and-gas-moving-sack-truck',
    # 'https://handle-it.com/collections/sack-trucks-and-trolleys-for-gas-bottles/products/gas-bottle-trolley',
    # 'https://handle-it.com/collections/sack-trucks-and-trolleys-for-gas-bottles/products/gas-cylinder-trolley',
    # 'https://handle-it.com/collections/sack-trucks-and-trolleys-for-gas-bottles/products/gas-bottle-sack-barrow',
    # 'https://handle-it.com/collections/sack-trucks-and-trolleys-for-gas-bottles/products/hospital-gas-bottle-trolley',
    # 'https://handle-it.com/collections/sack-trucks-and-trolleys-for-gas-bottles/products/twin-cylinder-gas-bottle-trolley',
    # 'https://handle-it.com/collections/sack-trucks-and-trolleys-for-gas-bottles/products/gas-bottle-storage-rack',
    # 'https://handle-it.com/collections/sack-trucks-and-trolleys-for-gas-bottles/products/gas-bottle-storage-cages',
    # 'https://handle-it.com/collections/sack-trucks-and-trolleys-for-gas-bottles/products/oxygen-cylinder-trolley',
    # 'https://handle-it.com/collections/sack-trucks-and-trolleys-for-gas-bottles/products/facilities-bulk-cylinder-or-gas-bottle-trailer',
    # 'https://handle-it.com/collections/sack-trucks-trolleys-and-carts-for-handling-drums-and-barrels/products/oil-drum-trolley',
    # 'https://handle-it.com/collections/rough-terrain-sack-trucks/products/sack-truck-and-barrow-for-rough-terrain',
    # 'https://handle-it.com/collections/magliner-trucks/products/aluminium-sack-trucks-traditional-sack-barrow',
    # 'https://handle-it.com/collections/magliner-trucks/products/aluminium-sack-trucks-traditional-sack-truck-with-curved-back',
    # 'https://handle-it.com/collections/magliner-trucks/products/magliner-aluminium-sack-truck-with-stair-skids',
    # 'https://handle-it.com/collections/magliner-trucks/products/aluminium-sack-trucks-basic-sack-truck',
    # 'https://handle-it.com/collections/magliner-trucks/products/magliner-aluminium-keg-sack-truck',
    # 'https://handle-it.com/collections/magliner-trucks/products/aluminium-sack-trucks-food-services-sack-truck',
    # 'https://handle-it.com/collections/magliner-trucks/products/aluminium-sack-trucks-folding-sack-truck',
    # 'https://handle-it.com/collections/magliner-trucks/products/aluminium-sack-trucks-bottled-water-trolley',
    # 'https://handle-it.com/collections/magliner-trucks/products/aluminium-sack-trucks-bottled-water-trolley-5-bottle',
    # 'https://handle-it.com/collections/magliner-trucks/products/aluminium-sack-trucks-gemini-junior',
    # 'https://handle-it.com/collections/magliner-trucks/products/aluminium-sack-trucks-gemini-junior-senior',
    # 'https://handle-it.com/collections/magliner-trucks/products/aluminium-sack-trucks-gemini-xl',
    # 'https://handle-it.com/collections/magliner-trucks/products/magliner-aluminium-sack-trucks-basic-sack-truck',
    # 'https://handle-it.com/collections/magliner-accessories/products/c5-stair-skid',
    # 'https://handle-it.com/collections/magliner-frames/products/aluminium-sack-trucks-no-4-plastic-braced-frame',
    # 'https://handle-it.com/collections/magliner-handles/products/aluminium-sack-trucks-no-11-u-loop-handle',
    # 'https://handle-it.com/collections/magliner-plates/products/aluminium-sack-trucks-cast-magnesium-a-plate',
    # 'https://handle-it.com/collections/magliner-wheels/products/10-inch-sack-truck-pneumatic-wheels',
    # 'https://handle-it.com/collections/mobile-workbench-and-table-trolleys/products/table-trolley',
    # 'https://handle-it.com/collections/mobile-workbench-and-table-trolleys/products/shelf-trolley-with-two-tiers',
    # 'https://handle-it.com/collections/mobile-workbench-and-table-trolleys/products/heavy-duty-table-trolley',
    # 'https://handle-it.com/collections/mobile-workbench-and-table-trolleys/products/heavy-duty-table-trolley-steel-shelves',
    # 'https://handle-it.com/collections/mobile-workbench-and-table-trolleys/products/service-trolley-with-2-or-3-tiers',
    # 'https://handle-it.com/collections/mobile-workbench-and-table-trolleys/products/service-trolley',
    # 'https://handle-it.com/collections/mobile-workbench-and-table-trolleys/products/storage-trolley-small',
    # 'https://handle-it.com/collections/mobile-workbench-and-table-trolleys/products/industrial-table-trolley',
    # 'https://handle-it.com/collections/mobile-workbench-and-table-trolleys/products/reception-filing-trolley',
    # 'https://handle-it.com/collections/mobile-workbench-and-table-trolleys/products/collapsible-folding-table-or-shelf-trolley',
    # 'https://handle-it.com/collections/mobile-workbench-and-table-trolleys/products/adjustable-height-table-trolley',
    # 'https://handle-it.com/collections/mobile-workbench-and-table-trolleys/products/two-or-three-shelf-trolley-with-pneumatic-castors',
    # 'https://handle-it.com/collections/mobile-workbench-and-table-trolleys/products/powered-2-tier-trolley',
    # 'https://handle-it.com/collections/mobile-workbench-and-table-trolleys/products/powered-trolley-with-3-shelves',
    # 'https://handle-it.com/collections/mobile-workbenches/products/mobile-workbench',
    # 'https://handle-it.com/collections/shelf-trolleys-and-storage-trolleys/products/distribution-trolley',
    # 'https://handle-it.com/collections/box-and-tote-pan-trolleys/products/stacking-mail-room-box-trolley',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/medical-dressing-trolley',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/hospital-trolley-with-aluminium-shelves',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/hospital-parcel-drop-box',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/secure-medical-records-trolley',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/patient-records-trolley',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/hospital-storage-trolley',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/medical-box-trolley',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/clinical-storage-trolley',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/medicine-cabinet-trolley',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/drug-and-medicine-trolleys',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/2-3-tier-hospital-service-trolley',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/hospital-oxygen-cylinder-trolley',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/motorised-secure-records-trolley',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/powered-service-trolley',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/powered-security-trolley-with-panic-alarm-system',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/powered-2-tier-trolley',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/library_and_book_trolley',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/trolley-for-moving-a4-size-files',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/stainless-steel-trolley-with-2-or-3-shelves',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/collapsible-folding-table-or-shelf-trolley',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/powered-trolley-with-3-shelves',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/powered-full-security-storage-trolley',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/power-assisted-locking-cage-trolley',
    # 'https://handle-it.com/collections/hospital-shelf-trolleys-and-security-cages/products/electric-security-cage-trolley',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/hospital-linen-trolley',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/platform-truck-for-hospitals-with-4-plastic-sides',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/iv-drip-infusion-stand',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/medical-iv-drip-stand',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/stainless-steel-iv-drip-stand',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/drip-stand-with-oxygen-rack',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/stacking-hospital-mail-room-box-trolley',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/hospital-oxygen-cylinder-trolley',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/oxygen-bottle-trolleys',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/gavanized-heavy-duty-platform-trucks-hi-36-gfbt',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/facilities-stainless-steel-platform-trolley',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/double-sided-trolley-for-hospitals',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/hospital-trolley-with-aluminium-shelves',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/patient-records-trolley',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/medicine-cabinet-trolley',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/secure-medical-records-trolley',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/heavy-duty-turntable-trolley',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/industrial-turntable-trolley',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/facilities-bulk-cylinder-or-gas-bottle-trailer',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/galvanised-turntable-trolley',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/trolley-ratchet-strap',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/powered-service-trolley',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/electric-powered-flatbed-trolley',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/powered-platform-truck-with-removable-sides-hi-pow-range',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/powered-2-tier-trolley',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/motorised-secure-records-trolley',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/powered-security-trolley-with-panic-alarm-system',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/electric-turntable-trailer',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/powered-turntable-trolley-with-mesh-sides',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/turntable-trolley-with-steel-sides',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/turntable-trailer',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/1-ton-electric-powered-turntable-trolley',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/powered-trolley-with-3-shelves',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/powered-turntable-truck-with-steel-sides',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/powered-full-security-storage-trolley',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/power-assisted-locking-cage-trolley',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/electric-security-cage-trolley',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/turntable-trailer-with-400mm-sides-500kg-capacity',
    # 'https://handle-it.com/collections/hospital-facilities-trolleys/products/copy-of-turntable-truck-with-400m-sides-1000kg-capacity',
    # 'https://handle-it.com/collections/hospital-medical-record-trolleys-and-security-cages/products/hospital-storage-trolley',
    # 'https://handle-it.com/collections/hospital-medical-record-trolleys-and-security-cages/products/medical-box-trolley',
    # 'https://handle-it.com/collections/hospital-medical-record-trolleys-and-security-cages/products/clinical-storage-trolley',
    # 'https://handle-it.com/collections/hospital-medical-record-trolleys-and-security-cages/products/patient-records-trolley',
    # 'https://handle-it.com/collections/hospital-medical-record-trolleys-and-security-cages/products/medicine-cabinet-trolley',
    # 'https://handle-it.com/collections/hospital-medical-record-trolleys-and-security-cages/products/trolley-for-moving-a4-size-files',
    # 'https://handle-it.com/collections/hospital-medical-record-trolleys-and-security-cages/products/secure-medical-records-trolley',
    # 'https://handle-it.com/collections/hospital-medical-record-trolleys-and-security-cages/products/hospital-parcel-drop-box',
    # 'https://handle-it.com/collections/hospital-medical-record-trolleys-and-security-cages/products/motorised-secure-records-trolley',
    # 'https://handle-it.com/collections/hospital-medical-record-trolleys-and-security-cages/products/powered-security-trolley-with-panic-alarm-system',
    # 'https://handle-it.com/collections/hospital-medical-record-trolleys-and-security-cages/products/powered-full-security-storage-trolley',
    # 'https://handle-it.com/collections/hospital-medical-record-trolleys-and-security-cages/products/power-assisted-locking-cage-trolley',
    # 'https://handle-it.com/collections/hospital-medical-record-trolleys-and-security-cages/products/electric-security-cage-trolley',
    # 'https://handle-it.com/collections/hospital-mail-and-post-room-trolleys/products/stacking-hospital-mail-room-box-trolley',
    # 'https://handle-it.com/collections/hospital-mail-and-post-room-trolleys/products/large-mailroom-trolleys',
    'https://handle-it.com/collections/hospital-mail-and-post-room-trolleys/products/mail-room-trolley',
    'https://handle-it.com/collections/hospital-mail-and-post-room-trolleys/products/small-mail-room-trolleys',
    'https://handle-it.com/collections/hospital-mail-and-post-room-trolleys/products/suspended-mail-bag-trolleys',
    'https://handle-it.com/collections/hospital-mail-and-post-room-trolleys/products/mail-room-shelf-trolley',
    'https://handle-it.com/collections/hospital-mail-and-post-room-trolleys/products/mail-distribution-trolley',
    'https://handle-it.com/collections/hospital-mail-and-post-room-trolleys/products/hospital-trolley-with-aluminium-shelves',
    'https://handle-it.com/collections/hospital-mail-and-post-room-trolleys/products/secure-medical-records-trolley',
    'https://handle-it.com/collections/hospital-mail-and-post-room-trolleys/products/hospital-parcel-drop-box',
    'https://handle-it.com/collections/hospital-mail-and-post-room-trolleys/products/electric-powered-flatbed-trolley',
    'https://handle-it.com/collections/hospital-mail-and-post-room-trolleys/products/powered-platform-truck-with-removable-sides-hi-pow-range',
    'https://handle-it.com/collections/hospital-mail-and-post-room-trolleys/products/motorised-secure-records-trolley',
    'https://handle-it.com/collections/hospital-mail-and-post-room-trolleys/products/medicine-cabinet-trolley',
    'https://handle-it.com/collections/hospital-mail-and-post-room-trolleys/products/patient-records-trolley',
    'https://handle-it.com/collections/hospital-mail-and-post-room-trolleys/products/powered-full-security-storage-trolley',
    'https://handle-it.com/collections/hospital-mail-and-post-room-trolleys/products/power-assisted-locking-cage-trolley',
    'https://handle-it.com/collections/hospital-mail-and-post-room-trolleys/products/electric-security-cage-trolley',
    'https://handle-it.com/collections/hospital-gas-and-oxygen-bottle-handling-and-storage/products/gas-bottle-sack-truck',
    'https://handle-it.com/collections/hospital-gas-and-oxygen-bottle-handling-and-storage/products/hospital-oxygen-cylinder-trolley',
    'https://handle-it.com/collections/hospital-gas-and-oxygen-bottle-handling-and-storage/products/oxygen-bottle-trolleys',
    'https://handle-it.com/collections/hospital-gas-and-oxygen-bottle-handling-and-storage/products/iv-drip-infusion-stand',
    'https://handle-it.com/collections/hospital-gas-and-oxygen-bottle-handling-and-storage/products/drip-stand-with-oxygen-rack',
    'https://handle-it.com/collections/hospital-gas-and-oxygen-bottle-handling-and-storage/products/medical-gas-cylinder-trolley',
    'https://handle-it.com/collections/hospital-gas-and-oxygen-bottle-handling-and-storage/products/hospital-gas-bottle-trolley',
    'https://handle-it.com/collections/hospital-gas-and-oxygen-bottle-handling-and-storage/products/oxygen-and-gas-moving-sack-truck',
    'https://handle-it.com/collections/hospital-gas-and-oxygen-bottle-handling-and-storage/products/facilities-bulk-cylinder-or-gas-bottle-trailer',
    'https://handle-it.com/collections/hospital-gas-and-oxygen-bottle-handling-and-storage/products/medical-gas-bottle-storage-rack',
    'https://handle-it.com/collections/hospital-gas-and-oxygen-bottle-handling-and-storage/products/medical-gas-bottle-storage-cage',
    'https://handle-it.com/collections/hospital-gas-and-oxygen-bottle-handling-and-storage/products/medical-iv-drip-stand',
    'https://handle-it.com/collections/hospital-gas-and-oxygen-bottle-handling-and-storage/products/stainless-steel-iv-drip-stand',
    'https://handle-it.com/collections/retrieval-steps/products/2-tread-sucker-steps-with-platform',
    'https://handle-it.com/collections/drop-pads-for-kegs/products/drop-mat-600mm-x-600mm',
    'https://handle-it.com/collections/pallet-trucks/products/heavy-duty-pallet-truck',
    'https://handle-it.com/collections/pallet-trucks/products/very-heavy-duty-pallet-truck',
    'https://handle-it.com/collections/pallet-trucks/products/low-profile-pallet-truck',
    'https://handle-it.com/collections/pallet-trucks/products/extra-low-profile-pallet-truck',
    'https://handle-it.com/collections/pallet-trucks/products/short-pallet-truck',
    'https://handle-it.com/collections/pallet-trucks/products/short-and-narrow-pallet-truck',
    'https://handle-it.com/collections/pallet-trucks/products/extra-long-pallet-truck',
    'https://handle-it.com/collections/pallet-trucks/products/standard-weighing-pallet-truck',
    'https://handle-it.com/collections/pallet-trucks/products/semi-stainless-steel-pallet-truck',
    'https://handle-it.com/collections/pallet-trucks/products/stainless-steel-pallet-truck',
    'https://handle-it.com/collections/pallet-trucks/products/galvanised-pallet-truck',
    'https://handle-it.com/collections/gkn-and-euro-pallet-trucks/products/standard-weighing-pallet-truck',
    'https://handle-it.com/collections/heavy-duty-pallet-trucks/products/heavy-duty-pallet-truck',
    'https://handle-it.com/collections/pallet-trucks-for-wet-applcations/products/galvanised-pallet-truck',
    'https://handle-it.com/collections/low-profile-pallet-trucks/products/extra-low-profile-pallet-truck',
    'https://handle-it.com/collections/extra-long-or-extra-short/products/extra-long-pallet-truck',
    'https://handle-it.com/collections/sucker-steps/products/2-tread-sucker-steps-with-platform',
    'https://handle-it.com/collections/mobile-steps/products/picking-trolleys-with-steps',
    'https://handle-it.com/collections/mobile-steps/products/5-tread-mobile-steps',
    'https://handle-it.com/collections/mobile-steps/products/6-tread-mobile-safety-steps-with-lever-brake',
    'https://handle-it.com/collections/mobile-steps/products/7-tread-mobile-safety-steps-with-lever-brake',
    'https://handle-it.com/collections/mobile-steps/products/8-tread-mobile-safety-steps-with-lever-brake',
    'https://handle-it.com/collections/mobile-steps/products/9-tread-mobile-safety-steps-with-lever-brake',
    'https://handle-it.com/collections/mobile-steps/products/10-tread-mobile-safety-steps-with-lever-brake',
    'https://handle-it.com/collections/mobile-steps/products/11-tread-mobile-safety-steps-with-lever-brake',
    'https://handle-it.com/collections/mobile-steps/products/12-tread-mobile-safety-steps-with-lever-brake',
    'https://handle-it.com/collections/mobile-steps/products/13-tread-mobile-safety-steps-with-lever-brake',
    'https://handle-it.com/collections/mobile-steps/products/14-tread-mobile-safety-steps-with-lever-brake',
    'https://handle-it.com/collections/mobile-steps/products/15-tread-mobile-safety-steps-with-lever-brake',
    'https://handle-it.com/collections/mobile-safety-steps-ladders/products/go-anywhere-mobile-safety-step-ladders',
    'https://handle-it.com/collections/safety-step-platforms/products/mobile-steps-3-tread-with-retracting-castors',

]


def save_pdf(url):
    driver = webdriver.Chrome()
    driver.maximize_window()
    driver.get(url)
    time.sleep(2)
    title = driver.find_element(By.XPATH, "//h1[@class='product-single__title header-flavour']").text.replace('|', "_").replace('/', '')
    titles = title + "-"
    print("Title...", titles)
    time.sleep(2)
    s = driver.find_element(By.XPATH, "//*[@id='specification']/div[2]")
    driver.execute_script("arguments[0].scrollIntoView();", s)

    gui.hotkey('tab')
    gui.hotkey('up')
    gui.hotkey('enter')
    time.sleep(2)
    gui.hotkey('tab')
    for i in range(0, 4):
        gui.hotkey('tab')
    gui.press('down')
    gui.press("enter")
    time.sleep(2)
    for i in range(0, 5):
        gui.hotkey('tab')
    gui.press("enter")
    time.sleep(2)
    gui.press('backspace')
    time.sleep(2)
    gui.typewrite(titles)
    time.sleep(3)
    gui.press("enter")
    time.sleep(1)
    print('Download Successfully')
    driver.quit()


def main():
    i = 0
    for url in mylist:
        i += 1
        save_pdf(url)
        print('Product-url...', i, url)


main()
